feature_name: Filestore XCTX
feature_description: |
  These properties configure access to file storages located on other OX App Suite contexts.
properties:
    - key: com.openexchange.file.storage.xctx.retryAfterErrorInterval
      description: |
        The time interval, in seconds, after which access to an error afflicted account should be retried.
      defaultValue:  3600
      version: 7.10.5
      reloadable: true
      configcascadeAware: true
      related: 
      file: filestorage.properties
      packageName: open-xchange-subscribe
      tags: ["Federated Sharing", "XCTX"]
    - key: com.openexchange.capability.filestorage_xctx
      description: |
        Allows the user to integrate a share link from a different OX App Suite installation as filestorage.
      defaultValue:  false
      version: 7.10.5
      reloadable: true
      configcascadeAware: true
      related: 
      file: filestorage.properties
      packageName: open-xchange-subscribe
      tags: ["Federated Sharing", "XCTX"]
    - key: com.openexchange.file.storage.xctx.maxAccounts
      description: |
        Defines the maximum number of allowed accounts for a user within the xctx provider. A value of 0 disables the limit. 
      defaultValue:  20
      version: 7.10.5
      reloadable: true
      configcascadeAware: true
      related: 
      file: filestorage.properties
      packageName: open-xchange-subscribe
      tags: ["Federated Sharing", "XCTX"]
    - key: com.openexchange.file.storage.xctx.autoRemoveUnknownShares
      description: |
        Enables or disables the automatic removal of accounts in the <i>cross-context</i> file storage provider that refer to a no longer 
        existing guest user in the remote context. 
      defaultValue: true
      version: 7.10.5
      reloadable: true
      configcascadeAware: true
      related:
      file: filestorage.properties
      packageName: open-xchange-subscribe
      tags: ["Federated Sharing", "XCTX"]
