define("io.ox/calendar/edit/view-main",["io.ox/calendar/edit/binding-util","io.ox/calendar/util","io.ox/core/extensions","io.ox/core/date","io.ox/calendar/edit/view-participants","io.ox/calendar/edit/view-addparticipants","io.ox/calendar/edit/collection-participants","dot!io.ox/calendar/edit/common.html","gettext!io.ox/calendar/edit/main"],function(a,b,c,d,e,f,g,h,i){var j,k,l,m=[{value:0,format:"minutes"},{value:15,format:"minutes"},{value:30,format:"minutes"},{value:45,format:"minutes"},{value:60
,format:"hours"},{value:120,format:"hours"},{value:240,format:"hours"},{value:360,format:"hours"},{value:420,format:"hours"},{value:720,format:"hours"},{value:1440,format:"days"},{value:2880,format:"days"},{value:4320,format:"days"},{value:5760,format:"days"},{value:7200,format:"days"},{value:8640,format:"days"},{value:10080,format:"weeks"},{value:20160,format:"weeks"},{value:30240,format:"weeks"},{value:40320,format:"weeks"}];return"use strict",_.each(m,function(a){var b;switch(a.format){case"minutes"
:a.label=i.format(i.ngettext("%1$d Minute","%1$d Minutes",a.value),i.noI18n(a.value));break;case"hours":b=Math.floor(a.value/60),a.label=i.format(i.ngettext("%1$d Hour","%1$d Hours",b),i.noI18n(b));break;case"days":b=Math.floor(a.value/60/24),a.label=i.format(i.ngettext("%1$d Day","%1$d Days",b),i.noI18n(b));break;case"weeks":b=Math.floor(a.value/60/24/7),a.label=i.format(i.ngettext("%1$d Week","%1$d Weeks",b),i.noI18n(b))}}),j={SUBJECT:i("Subject"),LOCATION:i("Location"),STARTS_ON:i("Starts on")
,ENDS_ON:i("Ends on"),ALL_DAY:i("All day"),CHANGE_TIMEZONE:i("Change timezone"),DESCRIPTION:i("Description"),REMINDER:i("Reminder"),NO_REMINDER:i("no reminder"),DISPLAY_AS:i("Display as"),RESERVED:i("reserved"),TEMPORARY:i("Temporary"),ABSENT:i("absent"),FREE:i("free"),TYPE:i("Type"),PARTICIPANTS:i("Participants"),PRIVATE:i("Private"),NOTIFY_ALL:i("Notify all")},$.fn.datepicker.dates.en={days:d.locale.days,daysShort:d.locale.daysShort,daysMin:d.locale.daysStandalone,months:d.locale.months,monthsShort
:d.locale.monthsShort},k=$.fn.datepicker.dates,$.fn.datepicker.DPGlobal.formatDate=function(a,b){var c;if(!a)return null;if(a.constructor.toString().indexOf("Date")===-1)return a;return c=new d.Local(a.getTime()),c.format(b)},$.fn.datepicker.DPGlobal.parseDate=function(a,b){var c,e=d.Local.parse(a,b);if(e!==null)return c=new Date(e.local),c;else return a},$.fn.datepicker.DPGlobal.parseFormat=function(a){return a},l=Backbone.View.extend({RECURRENCE_NONE:0,tagName:"div",className:"io-ox-calendar-edit container"
,subviews:{},events:{"click .save":"onSave"},initialize:function(){var c=this;c.subviews={},c._modelBinder=new Backbone.ModelBinder,c.guid=_.uniqueId("io_ox_calendar_edit_");var d=function(a,c,d,e){if(a==="ModelToView"){var f=b.getRecurrenceString(e.attributes);return f?": "+f:""}else return e.get(d)};c.bindings={start_date:[{selector:".startsat-date",converter:a.convertDate},{selector:".startsat-time",converter:a.convertTime}],end_date:[{selector:".endsat-date",converter:a.convertDate},{selector
:".endsat-time",converter:a.convertTime}]},c.model.on("change:start_date",_.bind(c.onStartDateChange,c)),c.model.on("change:end_date",_.bind(c.onEndDateChange,c)),Backbone.Validation.bind(this,{forceUpdate:!0,selector:"data-property"})},render:function(){var a=this;j.SAVE_BUTTON_LABEL=a.model.has("id")?i("Save"):i("Create"),a.$el.empty().append(h.render("io.ox/calendar/edit/section",{strings:j,reminderList:m,uid:a.guid}));var b=Backbone.ModelBinder.createDefaultBindings(this.el,"data-property"),k=
_.extend(b,a.bindings);c.point("io.ox/calendar/edit/bindings/common").invoke("modify",a,{bindings:k}),a._modelBinder.bind(a.model,a.el,k),a.$(".startsat-date").datepicker({format:d.DATE}),a.$(".endsat-date").datepicker({format:d.DATE});var l=new g(a.model.get("participants"));return a.subviews.participants=new e({collection:l,el:$(a.el).find(".participants")}),a.subviews.participants.render(),l.on("remove",_.bind(a.onRemoveParticipant,a)),a.subviews.addparticipants=new f({el:$(a.el).find(".add-participants"
)}),a.subviews.addparticipants.render(),a.subviews.addparticipants.on("select",_.bind(a.onAddParticipant,a)),a},onStartDateChange:function(){var a=this,b=a.model.previous("start_date"),c=a.model.get("start_date"),d=a.model.get("end_date"),e=d-b,f=c+e;!a.model.hasChanged("end_date")&&_.isNumber(f)&&a.model.set("end_date",f)},onEndDateChange:function(){var a=this,b=a.model.get("start_date"),c=a.model.previous("end_date"),d=a.model.get("end_date"),e,f;b>d&&(e=c-b,f=d-e,_.isNumber(f)&&a.model.set("start_date"
,f))},onSave:function(){var a=this;a.trigger("save")},onAddParticipant:function(a){var b=this.model.get("participants"),c=!0;console.log("adding participants",arguments),this.subviews.participants.collection.add(a),c=!_(b).any(function(b){return b.id===a.id&&b.type===a.type}),c&&b.push({id:a.id,type:a.type}),this.model.set("participants",b),console.log("participants in model",this.model)},onRemoveParticipant:function(a,b){var c=this.model.get("participants");c=_(c).filter(function(b){if(b.id===a.
get("id")&&b.type===a.get("type"))return!1;return!0}),this.model.set("participants",c)}}),l})