
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.taskmgmt.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T19:02:36.705+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "OXTaskMgmtService",
                      portName = "OXTaskMgmtServiceHttpEndpoint",
                      targetNamespace = "http://soap.admin.openexchange.com",
                      wsdlLocation = "null",
                      endpointInterface = "com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType")
                      
public class OXTaskMgmtServicePortTypeImpl4 implements OXTaskMgmtServicePortType {

    private static final Logger LOG = Logger.getLogger(OXTaskMgmtServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType#getTaskResults(com.openexchange.admin.soap.taskmgmt.dataobjects.Context  ctx ,)com.openexchange.admin.soap.taskmgmt.dataobjects.Credentials  cred ,)java.lang.Integer  id )*
     */
    public java.lang.Object getTaskResults(com.openexchange.admin.soap.taskmgmt.dataobjects.Context ctx,com.openexchange.admin.soap.taskmgmt.dataobjects.Credentials cred,java.lang.Integer id) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , RemoteException_Exception , ExecutionException_Exception , InterruptedException_Exception    { 
        LOG.info("Executing operation getTaskResults");
        System.out.println(ctx);
        System.out.println(cred);
        System.out.println(id);
        try {
            java.lang.Object _return = new java.lang.Object();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new ExecutionException_Exception("ExecutionException...");
        //throw new InterruptedException_Exception("InterruptedException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType#flush(com.openexchange.admin.soap.taskmgmt.soap.Flush  parameters )*
     */
    public void flush(Flush parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , TaskManagerException_Exception , RemoteException_Exception    { 
        LOG.info("Executing operation flush");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new TaskManagerException_Exception("TaskManagerException...");
        //throw new RemoteException_Exception("RemoteException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType#getJobList(com.openexchange.admin.soap.taskmgmt.dataobjects.Context  ctx ,)com.openexchange.admin.soap.taskmgmt.dataobjects.Credentials  cred )*
     */
    public java.lang.String getJobList(com.openexchange.admin.soap.taskmgmt.dataobjects.Context ctx,com.openexchange.admin.soap.taskmgmt.dataobjects.Credentials cred) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , RemoteException_Exception    { 
        LOG.info("Executing operation getJobList");
        System.out.println(ctx);
        System.out.println(cred);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new RemoteException_Exception("RemoteException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType#deleteJob(com.openexchange.admin.soap.taskmgmt.soap.DeleteJob  parameters )*
     */
    public void deleteJob(DeleteJob parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , TaskManagerException_Exception , RemoteException_Exception    { 
        LOG.info("Executing operation deleteJob");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new TaskManagerException_Exception("TaskManagerException...");
        //throw new RemoteException_Exception("RemoteException...");
    }

}
