package com.openexchange.admin.soap.taskmgmt.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T19:02:36.761+02:00
 * Generated source version: 2.6.0
 *
 */
@WebServiceClient(name = "OXTaskMgmtService",
                  // wsdlLocation = "null",
                  targetNamespace = "http://soap.admin.openexchange.com")
public class OXTaskMgmtService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtService");
    public final static QName OXTaskMgmtServiceHttpsEndpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpsEndpoint");
    public final static QName OXTaskMgmtServiceHttpSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpSoap12Endpoint");
    public final static QName OXTaskMgmtServiceHttpsSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpsSoap11Endpoint");
    public final static QName OXTaskMgmtServiceHttpsSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpsSoap12Endpoint");
    public final static QName OXTaskMgmtServiceHttpEndpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpEndpoint");
    public final static QName OXTaskMgmtServiceHttpSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXTaskMgmtServiceHttpSoap11Endpoint");
    static {
        WSDL_LOCATION = null;
    }

    public OXTaskMgmtService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OXTaskMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OXTaskMgmtService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsEndpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsEndpoint() {
        return super.getPort(OXTaskMgmtServiceHttpsEndpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsEndpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpsEndpoint, OXTaskMgmtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpSoap12Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpSoap12Endpoint() {
        return super.getPort(OXTaskMgmtServiceHttpSoap12Endpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpSoap12Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpSoap12Endpoint, OXTaskMgmtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsSoap11Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsSoap11Endpoint() {
        return super.getPort(OXTaskMgmtServiceHttpsSoap11Endpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsSoap11Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpsSoap11Endpoint, OXTaskMgmtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsSoap12Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsSoap12Endpoint() {
        return super.getPort(OXTaskMgmtServiceHttpsSoap12Endpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpsSoap12Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpsSoap12Endpoint, OXTaskMgmtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpEndpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpEndpoint() {
        return super.getPort(OXTaskMgmtServiceHttpEndpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpEndpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpEndpoint, OXTaskMgmtServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpSoap11Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpSoap11Endpoint() {
        return super.getPort(OXTaskMgmtServiceHttpSoap11Endpoint, OXTaskMgmtServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXTaskMgmtServicePortType
     */
    @WebEndpoint(name = "OXTaskMgmtServiceHttpSoap11Endpoint")
    public OXTaskMgmtServicePortType getOXTaskMgmtServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXTaskMgmtServiceHttpSoap11Endpoint, OXTaskMgmtServicePortType.class, features);
    }

}
