
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.taskmgmt.soap;

import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicReference;
import com.openexchange.admin.rmi.OXTaskMgmtInterface;
import com.openexchange.admin.rmi.exceptions.InvalidCredentialsException;
import com.openexchange.admin.rmi.exceptions.InvalidDataException;
import com.openexchange.admin.rmi.exceptions.StorageException;
import com.openexchange.admin.rmi.exceptions.TaskManagerException;
import com.openexchange.admin.soap.taskmgmt.dataobjects.Context;
import com.openexchange.admin.soap.taskmgmt.dataobjects.Credentials;
import com.openexchange.admin.soap.taskmgmt.dataobjects.Database;
import com.openexchange.admin.soap.taskmgmt.dataobjects.Entry;
import com.openexchange.admin.soap.taskmgmt.dataobjects.SOAPMapEntry;
import com.openexchange.admin.soap.taskmgmt.dataobjects.SOAPStringMap;
import com.openexchange.admin.soap.taskmgmt.dataobjects.SOAPStringMapMap;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T19:02:36.628+02:00
 * Generated source version: 2.6.0
 *
 */

@javax.jws.WebService(
                      serviceName = "OXTaskMgmtService",
                      portName = "OXTaskMgmtServiceHttpsEndpoint",
                      targetNamespace = "http://soap.admin.openexchange.com",
                      // wsdlLocation = "null",
                      endpointInterface = "com.openexchange.admin.soap.taskmgmt.soap.OXTaskMgmtServicePortType")

public class OXTaskMgmtServicePortTypeImpl implements OXTaskMgmtServicePortType {

    public static final AtomicReference<OXTaskMgmtInterface> RMI_REFERENCE = new AtomicReference<OXTaskMgmtInterface>();

    private static OXTaskMgmtInterface getTaskMgmtInterface() throws RemoteException_Exception {
        final OXTaskMgmtInterface taskMgmtInterface = RMI_REFERENCE.get();
        if (null == taskMgmtInterface) {
            throw new RemoteException_Exception("Missing "+OXTaskMgmtInterface.class.getName() + " instance.");
        }
        return taskMgmtInterface;
    }

    @Override
    public java.lang.Object getTaskResults(final Context ctx,final Credentials cred,final java.lang.Integer id) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , RemoteException_Exception , ExecutionException_Exception , InterruptedException_Exception    {
        final OXTaskMgmtInterface taskMgmtInterface = getTaskMgmtInterface();
        try {
            return taskMgmtInterface.getTaskResults(soap2Context(ctx), soap2Credentials(cred), id.intValue());
        } catch (final RemoteException e) {
            com.openexchange.admin.soap.taskmgmt.soap.RemoteException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.RemoteException();
            com.openexchange.admin.soap.taskmgmt.rmi.RemoteException value = new com.openexchange.admin.soap.taskmgmt.rmi.RemoteException();
            value.setMessage(e.getMessage());
            faultDetail.setRemoteException(value);
            throw new RemoteException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidCredentialsException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException();
            faultDetail.setInvalidCredentialsException(value);
            throw new InvalidCredentialsException_Exception(e.getMessage(), faultDetail, e);
        } catch (final StorageException e) {
            com.openexchange.admin.soap.taskmgmt.soap.StorageException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.StorageException();
            com.openexchange.admin.soap.taskmgmt.exceptions.StorageException value = new com.openexchange.admin.soap.taskmgmt.exceptions.StorageException();
            faultDetail.setStorageException(value);
            throw new StorageException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidDataException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException();
            faultDetail.setInvalidDataException(value);
            throw new InvalidDataException_Exception(e.getMessage(), faultDetail, e);
        } catch (final java.lang.InterruptedException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InterruptedException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InterruptedException();
            throw new InterruptedException_Exception(e.getMessage(), faultDetail, e);
        } catch (final ExecutionException e) {
            com.openexchange.admin.soap.taskmgmt.soap.ExecutionException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.ExecutionException();
            com.openexchange.admin.soap.taskmgmt.concurrent.ExecutionException value = new com.openexchange.admin.soap.taskmgmt.concurrent.ExecutionException();
            faultDetail.setExecutionException(value);
            throw new ExecutionException_Exception(e.getMessage(), faultDetail, e);
        }
    }

    @Override
    public void flush(final Flush parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , TaskManagerException_Exception , RemoteException_Exception    {
        final OXTaskMgmtInterface taskMgmtInterface = getTaskMgmtInterface();
        try {
            taskMgmtInterface.flush(soap2Context(parameters.ctx), soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            com.openexchange.admin.soap.taskmgmt.soap.RemoteException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.RemoteException();
            com.openexchange.admin.soap.taskmgmt.rmi.RemoteException value = new com.openexchange.admin.soap.taskmgmt.rmi.RemoteException();
            value.setMessage(e.getMessage());
            faultDetail.setRemoteException(value);
            throw new RemoteException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidCredentialsException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException();
            faultDetail.setInvalidCredentialsException(value);
            throw new InvalidCredentialsException_Exception(e.getMessage(), faultDetail, e);
        } catch (final StorageException e) {
            com.openexchange.admin.soap.taskmgmt.soap.StorageException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.StorageException();
            com.openexchange.admin.soap.taskmgmt.exceptions.StorageException value = new com.openexchange.admin.soap.taskmgmt.exceptions.StorageException();
            faultDetail.setStorageException(value);
            throw new StorageException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidDataException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException();
            faultDetail.setInvalidDataException(value);
            throw new InvalidDataException_Exception(e.getMessage(), faultDetail, e);
        } catch (TaskManagerException e) {
            com.openexchange.admin.soap.taskmgmt.soap.TaskManagerException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.TaskManagerException();
            com.openexchange.admin.soap.taskmgmt.exceptions.TaskManagerException value = new com.openexchange.admin.soap.taskmgmt.exceptions.TaskManagerException();
            faultDetail.setTaskManagerException(value);
            throw new TaskManagerException_Exception(e.getMessage(), faultDetail, e);
        }
    }

    @Override
    public java.lang.String getJobList(final Context ctx,final Credentials cred) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , RemoteException_Exception    {
        final OXTaskMgmtInterface taskMgmtInterface = getTaskMgmtInterface();
        try {
            return taskMgmtInterface.getJobList(soap2Context(ctx), soap2Credentials(cred));
        } catch (final RemoteException e) {
            com.openexchange.admin.soap.taskmgmt.soap.RemoteException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.RemoteException();
            com.openexchange.admin.soap.taskmgmt.rmi.RemoteException value = new com.openexchange.admin.soap.taskmgmt.rmi.RemoteException();
            value.setMessage(e.getMessage());
            faultDetail.setRemoteException(value);
            throw new RemoteException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidCredentialsException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException();
            faultDetail.setInvalidCredentialsException(value);
            throw new InvalidCredentialsException_Exception(e.getMessage(), faultDetail, e);
        } catch (final StorageException e) {
            com.openexchange.admin.soap.taskmgmt.soap.StorageException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.StorageException();
            com.openexchange.admin.soap.taskmgmt.exceptions.StorageException value = new com.openexchange.admin.soap.taskmgmt.exceptions.StorageException();
            faultDetail.setStorageException(value);
            throw new StorageException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidDataException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException();
            faultDetail.setInvalidDataException(value);
            throw new InvalidDataException_Exception(e.getMessage(), faultDetail, e);
        }
    }

    @Override
    public void deleteJob(final DeleteJob parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , TaskManagerException_Exception , RemoteException_Exception    {
        final OXTaskMgmtInterface taskMgmtInterface = getTaskMgmtInterface();
        try {
            taskMgmtInterface.deleteJob(soap2Context(parameters.ctx), soap2Credentials(parameters.auth), parameters.i.intValue());
        } catch (final RemoteException e) {
            com.openexchange.admin.soap.taskmgmt.soap.RemoteException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.RemoteException();
            com.openexchange.admin.soap.taskmgmt.rmi.RemoteException value = new com.openexchange.admin.soap.taskmgmt.rmi.RemoteException();
            value.setMessage(e.getMessage());
            faultDetail.setRemoteException(value);
            throw new RemoteException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidCredentialsException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidCredentialsException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidCredentialsException();
            faultDetail.setInvalidCredentialsException(value);
            throw new InvalidCredentialsException_Exception(e.getMessage(), faultDetail, e);
        } catch (final StorageException e) {
            com.openexchange.admin.soap.taskmgmt.soap.StorageException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.StorageException();
            com.openexchange.admin.soap.taskmgmt.exceptions.StorageException value = new com.openexchange.admin.soap.taskmgmt.exceptions.StorageException();
            faultDetail.setStorageException(value);
            throw new StorageException_Exception(e.getMessage(), faultDetail, e);
        } catch (final InvalidDataException e) {
            com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.InvalidDataException();
            com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException value = new com.openexchange.admin.soap.taskmgmt.exceptions.InvalidDataException();
            faultDetail.setInvalidDataException(value);
            throw new InvalidDataException_Exception(e.getMessage(), faultDetail, e);
        } catch (TaskManagerException e) {
            com.openexchange.admin.soap.taskmgmt.soap.TaskManagerException faultDetail = new com.openexchange.admin.soap.taskmgmt.soap.TaskManagerException();
            com.openexchange.admin.soap.taskmgmt.exceptions.TaskManagerException value = new com.openexchange.admin.soap.taskmgmt.exceptions.TaskManagerException();
            faultDetail.setTaskManagerException(value);
            throw new TaskManagerException_Exception(e.getMessage(), faultDetail, e);
        }
    }

    private static com.openexchange.admin.rmi.dataobjects.Credentials soap2Credentials(final Credentials soapCredentials) {
        if (null == soapCredentials) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Credentials credentials = new com.openexchange.admin.rmi.dataobjects.Credentials();
        final String login = soapCredentials.getLogin();
        if (null != login) {
            credentials.setLogin(login);
        }
        final String password = soapCredentials.getPassword();
        if (null != password) {
            credentials.setPassword(password);
        }
        return credentials;
    }

    private static com.openexchange.admin.rmi.dataobjects.Context soap2Context(final Context soapContext) {
        if (null == soapContext) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Context ret = new com.openexchange.admin.rmi.dataobjects.Context();

        Long lng = soapContext.getAverageSize();
        if (null != lng) {
            ret.setAverage_size(lng);
        }

        final Boolean enabled = soapContext.isEnabled();
        if (null != enabled) {
            ret.setEnabled(enabled);
        }

        final String s = soapContext.getFilestoreName();
        if (null != s) {
            ret.setFilestore_name(s);
        }

        Integer itg = soapContext.getFilestoreId();
        if (null != itg) {
            ret.setFilestoreId(itg);
        }

        itg = soapContext.getId();
        ret.setId(itg);

        if (null != soapContext.getLoginMappings()) {
            for (String loginMapping : soapContext.getLoginMappings()) {
                if (null != loginMapping) {
                    ret.addLoginMapping(loginMapping);
                }
            }
        }

        lng = soapContext.getMaxQuota();
        if (null != lng) {
            ret.setMaxQuota(lng);
        }

        final String name = soapContext.getName();
        if (null != name) {
            ret.setName(name);
        }

        final Long usedQuota = soapContext.getUsedQuota();
        if (null != usedQuota) {
            ret.setUsedQuota(usedQuota);
        }

        final Database readDatabase = soapContext.getReadDatabase();
        if (null != readDatabase) {
            ret.setReadDatabase(soap2Database(readDatabase));
        }

        final Database writeDatabase = soapContext.getWriteDatabase();
        if (null != writeDatabase) {
            ret.setWriteDatabase(soap2Database(writeDatabase));
        }

        final SOAPStringMapMap userAttributes = soapContext.getUserAttributes();
        if (null != userAttributes) {
            ret.setUserAttributes(soap2MapMap(userAttributes));
        }
        return ret;
    }

    private static com.openexchange.admin.rmi.dataobjects.Database soap2Database(final Database soapDatabase) {
        if (null == soapDatabase) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Database ret = new com.openexchange.admin.rmi.dataobjects.Database();

        Integer itg = soapDatabase.getClusterWeight();
        if (itg != null) {
            ret.setClusterWeight(itg);
        }

        itg = soapDatabase.getCurrentUnits();
        if (itg != null) {
            ret.setCurrentUnits(itg);
        }

        String tmp = soapDatabase.getDriver();
        if (tmp != null) {
            ret.setDriver(tmp);
        }

        itg = soapDatabase.getId();
        if (itg != null) {
            ret.setId(itg);
        }

        tmp = soapDatabase.getLogin();
        if (tmp != null) {
            ret.setLogin(tmp);
        }

        Boolean bool = soapDatabase.isMaster();
        if (bool != null) {
            ret.setMaster(bool);
        }

        itg = soapDatabase.getMasterId();
        if (itg != null) {
            ret.setMasterId(itg);
        }

        itg = soapDatabase.getMaxUnits();
        if (itg != null) {
            ret.setMaxUnits(itg);
        }

        tmp = soapDatabase.getName();
        if (tmp != null) {
            ret.setName(tmp);
        }

        tmp = soapDatabase.getPassword();
        if (tmp != null) {
            ret.setPassword(tmp);
        }

        itg = soapDatabase.getPoolHardLimit();
        if (itg != null) {
            ret.setPoolHardLimit(itg);
        }

        itg = soapDatabase.getPoolInitial();
        if (itg != null) {
            ret.setPoolInitial(itg);
        }

        itg = soapDatabase.getPoolMax();
        if (itg != null) {
            ret.setPoolMax(itg);
        }

        itg = soapDatabase.getReadId();
        if (itg != null) {
            ret.setRead_id(itg);
        }

        tmp = soapDatabase.getScheme();
        if (tmp != null) {
            ret.setScheme(tmp);
        }

        tmp = soapDatabase.getUrl();
        if (tmp != null) {
            ret.setUrl(tmp);
        }
        return ret;
    }

    private static Map<String, Map<String, String>> soap2MapMap(final SOAPStringMapMap soapStringMapMap) {
        if (null == soapStringMapMap) {
            return null;
        }
        final java.util.List<SOAPMapEntry> entries = soapStringMapMap.getEntries();
        final Map<String, Map<String, String>> map = new HashMap<String, Map<String,String>>(entries.size());
        for (final SOAPMapEntry soapMapEntry : entries) {
            if (null != soapMapEntry) {
                map.put(soapMapEntry.getKey(), soap2Map(soapMapEntry.getValue()));
            }
        }
        return map;
    }

    private static Map<String, String> soap2Map(final SOAPStringMap soapStringMap) {
        if (null == soapStringMap) {
            return null;
        }
        final java.util.List<Entry> entries = soapStringMap.getEntries();
        final Map<String, String> map = new HashMap<String, String>(entries.size());
        for (final Entry entry : entries) {
            if (null != entry) {
                map.put(entry.getKey(), entry.getValue());
            }
        }
        return map;
    }

}
