
package com.openexchange.admin.soap.taskmgmt.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T19:02:36.754+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXTaskMgmtServicePortType_OXTaskMgmtServiceHttpsSoap12Endpoint_Server{

    protected OXTaskMgmtServicePortType_OXTaskMgmtServiceHttpsSoap12Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXTaskMgmtServicePortTypeImpl();
        String address = "https://ox6-dev.open-xchange.com/servlet/axis2/services/OXTaskMgmtService.OXTaskMgmtServiceHttpsSoap12Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXTaskMgmtServicePortType_OXTaskMgmtServiceHttpsSoap12Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
