define("io.ox/contacts/view-detail",["io.ox/core/extensions","gettext!io.ox/contacts/contacts","io.ox/contacts/util","io.ox/contacts/api","io.ox/contacts/actions"],function(a,b,c,d){var e=function(){return _(arguments).select(function(a,b){return b>0&&!!a}).join(arguments[0]||"")};"use strict";function f(a,b,c,d){var e,f;if(b)return e=$("<td>").addClass("value"),f=$("<tr>").append($("<td>").addClass("io-ox-label").text(a)).append(e),_.isFunction(d)?d(e):(typeof d=="string"&&e.addClass(d),e.text(b
)),f.appendTo(c),1;else return 0}function g(a,b,c,d){var e=$("<td>").addClass("value"),f=$("<tr>").append($("<td>").addClass("io-ox-label").text(a),e),g=$("<span>").addClass("blue").text(b);return e.append(g," ",c),f.appendTo(d),1}function h(a){var b;a.preventDefault(),b={to:[[a.data.display_name,a.data.email]]},require(["io.ox/mail/write/main"],function(a){a.getApp().launch().done(function(){this.compose(b)})})}function i(a,b,c){return f(a,b,this,function(a){a.addClass("blue").append($("<a>",{href
:"mailto: "+b}).addClass("blue").text(b).on("click",{email:b,display_name:c.display_name},h))})}function j(a,b,c){return f(a,b,c,function(a){a.addClass("blue").append($("<a>",{href:"callto: "+b}).addClass("blue").text(b))})}function k(a,b,c,d,g,h){return f(a,!0,h,function(a){var f=$("<a>",{href:"http://www.google.de/maps?q="+encodeURIComponent(e(", ",b,e(" ",c,d))),target:"_blank"}).addClass("nolink");b&&(f.append($("<span>").text(b)),d&&f.append($("<br>"))),c&&f.append($("<span>").text(c+" ")),d&&
f.append($("<span>").text(d)),g&&(f.append($("<br>")),f.append($("<span>").text(g))),f.append($("<br><small class='blue'>(Google Maps&trade;)</small>")),a.append(f)})}return a.point("io.ox/contacts/detail").extend({index:100,id:"contact-details",draw:function(b){var c=$("<tr>").appendTo(this);a.point("io.ox/contacts/detail/head").invoke("draw",c,b)}}),a.point("io.ox/contacts/detail/head").extend({index:100,id:"contact-picture",draw:function(a){this.append($("<td>").css({verticalAlign:"top",paddingBottom
:"0"}).append(d.getPicture(a).addClass("picture"))).append($("<td>").css({verticalAlign:"top"}).append($("<div>").addClass("name clear-title user-select-text").text(c.getFullName(a))).append($("<div>").addClass("job clear-title user-select-text").text(a.mark_as_distributionlist?b("Distribution list"):a.company||a.position||a.profession?e(", ",a.company,a.position,a.profession)+" ":c.getMail(a)+" ")))}}),a.point("io.ox/contacts/detail").extend({index:150,id:"inline-actions",draw:function(b){var c=
$("<td>",{colspan:"2"});a.point("io.ox/contacts/detail/actions").invoke("draw",c,b),this.append($("<tr>").append(c))}}),a.point("io.ox/contacts/detail").extend({index:160,id:"address",draw:function(b){a.point("io.ox/contacts/detail/address").invoke("draw",this,b)}}),a.point("io.ox/contacts/detail").extend({index:200,id:"phones",draw:function(b){a.point("io.ox/contacts/detail/phones").invoke("draw",this,b)}}),a.point("io.ox/contacts/detail").extend({index:200,id:"mails",draw:function(b){a.point("io.ox/contacts/detail/mails"
).invoke("draw",this,b)}}),a.point("io.ox/contacts/detail").extend({index:200,id:"birthday",draw:function(b){a.point("io.ox/contacts/detail/birthday").invoke("draw",this,b)}}),a.point("io.ox/contacts/detail").extend({index:200,id:"qr",draw:function(b){a.point("io.ox/contacts/detail/qr").invoke("draw",this,b)}}),a.point("io.ox/contacts/detail/address").extend({index:100,id:"contact-address",draw:function(a){var c;f(b("Department"),a.department,this),f(b("Position"),a.position,this),f(b("Profession"
),a.profession,this),c=0;if(a.street_business||a.city_business)c+=k(b("Work"),a.street_business,a.postal_code_business,a.city_business,null,this);if(a.street_home||a.city_home)c+=k(b("Home"),a.street_home,a.postal_code_home,a.city_home,null,this);c>0&&f(""," ",this)}}),a.point("io.ox/contacts/detail/phones").extend({index:100,id:"contact-phone",draw:function(a){var c=0;c+=j(b("Phone (business)"),a.telephone_business1,this),c+=j(b("Phone (business)"),a.telephone_business2,this),c+=j(b("Phone (private)"
),a.telephone_home1,this),c+=j(b("Phone (private)"),a.telephone_home2,this),c+=j(b("Mobile"),a.cellular_telephone1,this),c+=j(b("Mobile"),a.cellular_telephone2,this),c>0&&f(""," ",this)}}),a.point("io.ox/contacts/detail/mails").extend({index:100,id:"contact-mails",draw:function(a){var c,d,e,h,j,k;a.mark_as_distributionlist===!0?(c=0,d=_.copy(a.distribution_list||[],!0),e=d.length,h=this,e===0&&g(b("Members"),b("This list has no members yet")," ",h),_.each(d,function(a,c){c===0?g(b("Members"),a.display_name
,a.mail,h):g("",a.display_name,a.mail,h)})):(j={},k=0,k+=i.call(this,b("Email"),a.email1,a),j[a.email1]=!0,j[a.email2]!==!0&&(k+=i.call(this,b("Email"),a.email2,a),j[a.email2]=!0),j[a.email3]!==!0&&(k+=i.call(this,b("Email"),a.email3,a)),k>0&&f(""," ",this))}}),a.point("io.ox/contacts/detail/birthday").extend({index:100,id:"contact-birthdays",draw:function(a){var c=0,d=new Date(a.birthday);a.birthday!==null&&!isNaN(d.getDate())&&(c+=f(b("Birthday"),d.getDate()+"."+(d.getMonth()+1)+"."+d.getFullYear
(),this))}}),a.point("io.ox/contacts/detail/qr").extend({index:100,id:"qr",draw:function(a){var b=0;Modernizr.canvas&&!a.mark_as_distributionlist&&(b>0&&(f(" "," ",this),b=0),f(" ",!0,this,function(b){b.append($('<i class="icon-qrcode">'),$.txt(" "),$("<a>",{href:"#"}).text("Show QR code").on("click",function(c){c.preventDefault(),b.empty().busy(),require(["io.ox/contacts/view-qrcode"],function(c){var d=c.getVCard(a);b.idle().qrcode(d),d=b=c=null})}))}))}}),{draw:function(b){var c;return b?(c=$("<table>"
,{border:0,cellpadding:0,cellspacing:0}).addClass("contact-detail view user-select-text").attr("data-obj-id",b.folder_id+"."+b.id),a.point("io.ox/contacts/detail").invoke("draw",c,b)):c=$(),c}}})