
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.group;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-31T14:44:23.379+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "OXGroupService",
                      portName = "OXGroupServiceHttpsEndpoint",
                      targetNamespace = "http://soap.admin.openexchange.com",
                      wsdlLocation = "null",
                      endpointInterface = "com.openexchange.admin.soap.group.OXGroupServicePortType")
                      
public class OXGroupServicePortTypeImpl4 implements OXGroupServicePortType {

    private static final Logger LOG = Logger.getLogger(OXGroupServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#change(com.openexchange.admin.soap.group.Change  parameters )*
     */
    public void change(Change parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation change");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#removeMember(com.openexchange.admin.soap.group.RemoveMember  parameters )*
     */
    public void removeMember(RemoveMember parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation removeMember");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#listAll(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> listAll(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation listAll");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#getDefaultGroup(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public com.openexchange.admin.soap.dataobjects.xsd.Group getDefaultGroup(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getDefaultGroup");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.dataobjects.xsd.Group _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#getMembers(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.soap.dataobjects.xsd.Group  grp ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> getMembers(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.soap.dataobjects.xsd.Group grp,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getMembers");
        System.out.println(ctx);
        System.out.println(grp);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#listGroupsForUser(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.soap.dataobjects.xsd.User  usr ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> listGroupsForUser(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.soap.dataobjects.xsd.User usr,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation listGroupsForUser");
        System.out.println(ctx);
        System.out.println(usr);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#delete(com.openexchange.admin.soap.group.Delete  parameters )*
     */
    public void delete(Delete parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation delete");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#deleteMultiple(com.openexchange.admin.soap.group.DeleteMultiple  parameters )*
     */
    public void deleteMultiple(DeleteMultiple parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation deleteMultiple");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#addMember(com.openexchange.admin.soap.group.AddMember  parameters )*
     */
    public void addMember(AddMember parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation addMember");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#getMultipleData(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group>  grps ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> getMultipleData(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> grps,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getMultipleData");
        System.out.println(ctx);
        System.out.println(grps);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#create(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.soap.dataobjects.xsd.Group  grp ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public com.openexchange.admin.soap.dataobjects.xsd.Group create(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.soap.dataobjects.xsd.Group grp,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation create");
        System.out.println(ctx);
        System.out.println(grp);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.dataobjects.xsd.Group _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#list(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)java.lang.String  pattern ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> list(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,java.lang.String pattern,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation list");
        System.out.println(ctx);
        System.out.println(pattern);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.dataobjects.xsd.Group> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.group.OXGroupServicePortType#getData(com.openexchange.admin.soap.dataobjects.xsd.Context  ctx ,)com.openexchange.admin.soap.dataobjects.xsd.Group  grp ,)com.openexchange.admin.rmi.dataobjects.xsd.Credentials  auth )*
     */
    public com.openexchange.admin.soap.dataobjects.xsd.Group getData(com.openexchange.admin.soap.dataobjects.xsd.Context ctx,com.openexchange.admin.soap.dataobjects.xsd.Group grp,com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchGroupException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getData");
        System.out.println(ctx);
        System.out.println(grp);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.dataobjects.xsd.Group _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchGroupException_Exception("NoSuchGroupException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

}
