
package com.openexchange.admin.soap.group;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-31T14:44:23.427+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXGroupServicePortType_OXGroupServiceHttpSoap11Endpoint_Server{

    protected OXGroupServicePortType_OXGroupServiceHttpSoap11Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXGroupServicePortTypeImpl5();
        String address = "http://ox6-dev.open-xchange.com/servlet/axis2/services/OXGroupService.OXGroupServiceHttpSoap11Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXGroupServicePortType_OXGroupServiceHttpSoap11Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
