#!/bin/bash

OXFUNCTIONS=/opt/open-xchange/etc/oxfunctions.sh
OXCONFIG=/opt/open-xchange/etc/groupware/ox-scriptconf.sh
OXPREFIX=/opt/open-xchange
OXBUNDLES=$OXPREFIX/bundles


test -f $OXFUNCTIONS || {
	echo "missing common shell functions file"
	exit 1
}

. $OXFUNCTIONS

test -f $OXCONFIG && . $OXCONFIG

warn() {
    echo -e "\e[1m$1\e[0m"
}

test -f $OXCONFIG && . $OXCONFIG

ox_set_JAVA_BIN

test -z "$JAVA_XTRAOPTS" && JAVA_XTRAOPTS="-Xms20M -Xmx280M"

JAVA_OPTS="${JAVA_OXCMD_OPTS} \
-Djava.awt.headless=true \
-Dopenexchange.propdir=$PROPERTIESDIR \
-Djava.util.logging.config.file=$LOGGINGPROPERTIES"

CLASSPATH="-classpath $OXBUNDLES/com.openexchange.server.jar:\
$OXBUNDLES/com.openexchange.global.jar:\
$OXBUNDLES/com.openexchange.subscribe.crawler.jar:\
$OXBUNDLES/org.apache.commons.cli_1.2.0.v201105210650.jar:\
$OXBUNDLES/org.apache.commons.logging_1.1.1.v201101211721.jar"

pushd $OXPREFIX

umask 066
exec $JAVA_BIN $JAVA_OPTS $CLASSPATH com.openexchange.subscribe.crawler.commandline.CrawlerUpdateCLT $@
