<?xml version="1.0"?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:reseller="http://4psa.com/Reseller/2.5.1" xmlns:client="http://4psa.com/Client/2.5.1" xmlns:extension="http://4psa.com/Extension/2.5.1" xmlns:channel="http://4psa.com/Channel/2.5.1" xmlns:pbx="http://4psa.com/PBX/2.5.1" xmlns:billing="http://4psa.com/Billing/2.5.1" xmlns:report="http://4psa.com/Report/2.5.1" xmlns:account="http://4psa.com/Account/2.5.1" xmlns:globalop="http://4psa.com/GlobalOp/2.5.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="VoIpNowService" targetNamespace="http://4psa.com/VoIpNowService/2.5.1">
	<documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">This is the VoIpNow services contact.</documentation>
	<import namespace="http://4psa.com/Reseller/2.5.1" location="Reseller/Reseller.wsdl"/>
	<import namespace="http://4psa.com/Client/2.5.1" location="Client/Client.wsdl"/>
	<import namespace="http://4psa.com/Channel/2.5.1" location="Channel/Channel.wsdl"/>
	<import namespace="http://4psa.com/PBX/2.5.1" location="PBX/PBX.wsdl"/>
	<import namespace="http://4psa.com/Billing/2.5.1" location="Billing/Billing.wsdl"/>
	<import namespace="http://4psa.com/Report/2.5.1" location="Report/Report.wsdl"/>
	<import namespace="http://4psa.com/Extension/2.5.1" location="Extension/Extension.wsdl"/>
	<import namespace="http://4psa.com/Account/2.5.1" location="Account/Account.wsdl"/>
	<import namespace="http://4psa.com/GlobalOp/2.5.1" location="GlobalOp/GlobalOp.wsdl"/>
	<types/>
</definitions>
