DROP TABLE IF EXISTS publications;
DROP TABLE IF EXISTS publication_sites;

CREATE TABLE publication_sites (
id INT4 UNSIGNED NOT NULL AUTO_INCREMENT, 
cid INT4 UNSIGNED NOT NULL, 
user INT4 UNSIGNED NOT NULL, 
name VARCHAR(255) NOT NULL, 
tag_expression VARCHAR(255) NOT NULL, 
PRIMARY KEY (id), 
FOREIGN KEY(cid, user) REFERENCES user(cid, id)) 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;