#!/usr/bin/perl
package Listgroup;
use strict;
use Data::Dumper;
use base qw(BasicCommandlineOptions);


#Use the SOAP::Lite Perl module
#use SOAP::Lite +trace => 'debug';
use SOAP::Lite;

my $test = new Listgroup();
$test->doRequest();

sub new {
	my ($inPkg) = @_;
	my $self = BasicCommandlineOptions->new();
	
	bless $self, $inPkg;
    return $self;
}

sub doRequest {
   	my $inSelf = shift;
    my $soap = SOAP::Lite->ns( $inSelf->{'serviceNs'} )->proxy( $inSelf->{'basisUrl'}."OXGroupService" );
    
    my $pattern = SOAP::Data->value("*");
    
    my $som_entry = 
      $soap->list($inSelf->{'Context'},$pattern,$inSelf->{'creds'});
    
    if ( $som_entry->fault() ) {
        $inSelf->fault_output($som_entry);
	exit(1);
    } else {
        my $fields = [ "id", "name", "displayname", "members" ]; 
        
        my @results = $som_entry->paramsall;
        #print @results[0];
        
        my @data = $inSelf->SUPER::fetch_results($fields, \@results);
        
        $inSelf->reformmembers(\@data);
        
        $inSelf->doCSVOutput($fields, \@data);
    }

}

sub reformmembers {
    my $inSelf = shift;
    my $data = shift;
    
    for my $row (@$data) {
      my $value = @$row[-1];
      if( ref($value) eq "ARRAY" ) {
	@$row[-1] = join(", ", @$value) if defined $value;
      } else {
	@$row[-1] = $value;
      }
    }
}

exit;

