@Library('pipeline-library') _

def myLabel = "dockerbuild-${UUID.randomUUID().toString()}"
def image

pipeline {
  agent {
    kubernetes {
      label myLabel
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: jagregory/pandoc:latest
    command:
    - cat
    tty: true
"""
    }
  }
  stages {
    stage('Run Pandoc Docker') {
      steps {
        container('docker') {
          sh 'cd documentation-clt; ./createmanpages.sh'
        }
      }
    }
    stage('Archive manpages.gz') {
      steps {
        archiveArtifacts artifacts: 'documentation-clt/output/manpages/*.gz'
      }
    }
  }
}
