define("io.ox/core/test/cacheObjectCache",["io.ox/core/extensions","io.ox/core/cache"],function(a,b){var c=5e3,d="testkey",e="ABC";"use strict";function f(){var a=function(){return a.value};return a.value=!1,a.yep=function(){a.value=!0},a}a.point("test/suite").extend({id:"core-cache-objectcache",index:100,test:function(a){a.describe("Caching with ObjectCache",function(){var d=new b.ObjectCache("TEST_ObjectCache"),e=(new Date).getTime(),g=e-1e3,h=e+1e3,i="A.ABC",k="Simple",l={folder_id:"A",id:"ABC"
,TEST:"1"},m={folder_id:"A",id:"ABC",TEST:"2"},n={folder_id:"A",id:"ABC",TEST:"3"},o={folder_id:"A",id:"ABD",TEST:"1"},p={folder_id:"A",id:"ABE",TEST:"1"},q={folder_id:"A",id:"ABF",TEST:"1"};a.it("clearing cache",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.clear().done(function(c){b.yep(),a.expect(c).not.toBeDefined()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("getting not existing key",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get("notexistent"
).done(function(c){b.yep(),a.expect(c).toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("adding data ",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.add(l,e).done(function(c){b.yep(),a.expect(c).toEqual(i)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("adding old data ",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.add(m,g).done(function(c){b.yep(),a.expect(c).toEqual(i)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined
()})}),a.it("getting data to test for old data replacement",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get(i).done(function(c){b.yep(),a.expect(c).toEqual(l)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("adding new data ",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.add(n,h).done(function(c){b.yep(),a.expect(c).toEqual(i)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("getting data to test for new data replacement",function(
){var b=new f;a.waitsFor(b,"Could not get key",c),d.get(i).done(function(c){b.yep(),a.expect(c).toEqual(n)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("adding array of new data ",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.add([l,o,p,q],e).done(function(c){b.yep(),a.expect(c).toEqual(["A.ABC","A.ABD","A.ABE","A.ABF"])}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for key existence",function(){var b=new f;a.waitsFor(b,"Could not get key"
,c),d.get(i).done(function(c){b.yep(),a.expect(c).not.toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for key existence on nonexisting key",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get("fdfsgagsdg").done(function(c){b.yep(),a.expect(c).toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for array of key existence",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get(["A.ABC","A.ABD"]).done(function(
c){b.yep(),a.expect(c).not.toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for object existence",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get(l).done(function(c){b.yep(),a.expect(c).not.toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for array of object existence",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get([l,o]).done(function(c){b.yep(),a.expect(c).not.toBeNull()}).fail(function(
c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for array of mixed object/key existence",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get([l,"A.ABE"]).done(function(c){b.yep(),a.expect(c).not.toBeNull()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking for array of mixed object/key existence with nonexistent key",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.get([l,"A.ABX"]).done(function(c){b.yep(),a.expect(c).toBeNull()}).fail
(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking cachesize before removing",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.size().done(function(c){b.yep(),a.expect(c).toEqual(4)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("removing by single key",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.remove(i).done(function(){b.yep(),a.expect(!0).toBeTruthy()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking cachesize after removing"
,function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.size().done(function(c){b.yep(),a.expect(c).toEqual(3)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("removing by object",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.remove(o).done(function(){b.yep(),a.expect(!0).toBeTruthy()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking cachesize after removing",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.size().done(function(
c){b.yep(),a.expect(c).toEqual(2)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("removing by array of keys",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.remove(["A.ABE","A.ABF"]).done(function(){b.yep(),a.expect(!0).toBeTruthy()}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})}),a.it("checking cachesize after removing",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.size().done(function(c){b.yep(),a.expect(c).toEqual(0)}).fail(function(c)
{b.yep(),a.expect(c).not.toBeDefined()})}),a.it("merging objects",function(){var b=new f;a.waitsFor(b,"Could not get key",c),d.add(l).pipe(function(){return d.merge(m).pipe(function(){return d.get(l)})}).done(function(c){b.yep(),a.expect(c).toEqual(m)}).fail(function(c){b.yep(),a.expect(c).not.toBeDefined()})})})}})})