
package com.openexchange.admin.soap.util;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-31T13:47:54.544+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXUtilServicePortType_OXUtilServiceHttpEndpoint_Server{

    protected OXUtilServicePortType_OXUtilServiceHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXUtilServicePortTypeImpl();
        String address = "http://ox6-dev.open-xchange.com/servlet/axis2/services/OXUtilService.OXUtilServiceHttpEndpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXUtilServicePortType_OXUtilServiceHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
