#! /bin/bash

DDIR=$1 || DDIR="/opt/open-xchange/sbin"
pushd $DDIR
for method in create delete change list; do
    for module in user group resource; do
	linkname="${method}${module}"
	rm -f $linkname
	ln -sf cmdmuxer $linkname
    done
done
