define("io.ox/contacts/edit/view-form",["io.ox/core/extensions","gettext!io.ox/contacts/contacts","io.ox/contacts/util","io.ox/contacts/api","io.ox/core/tk/view","io.ox/core/tk/model"],function(a,b,c,d,e){var f={sections:{personal:["title","first_name","last_name","display_name","second_name","suffix","nickname","birthday","marital_status","number_of_children","spouse_name","anniversary","url"],messaging:["email1","email2","email3","instant_messenger1","instant_messenger2"],phone:["cellular_telephone1"
,"cellular_telephone2","telephone_business1","telephone_business2","telephone_home1","telephone_home2","telephone_company","telephone_other","fax_business","fax_home","fax_other","telephone_car","telephone_isdn","telephone_pager","telephone_primary","telephone_radio","telephone_telex","telephone_ttytdd","telephone_ip","telephone_assistant","telephone_callback"],home_address:["street_home","postal_code_home","city_home","state_home","country_home"],business_address:["street_business","postal_code_business"
,"city_business","state_business","country_business"],other_address:["street_other","postal_code_other","city_other","state_other","country_other"],job:["profession","position","department","company","room_number","employee_type","number_of_employees","sales_volume","tax_id","commercial_register","branches","business_category","info","manager_name","assistant_name"],userfields:["userfield01","userfield02","userfield03","userfield04","userfield05","userfield06","userfield07","userfield08","userfield09"
,"userfield10","userfield11","userfield12","userfield13","userfield14","userfield15","userfield16","userfield17","userfield18","userfield19","userfield20"],comment:["note"]},rare:["nickname","marital_status","number_of_children","spouse_name","marital_status","number_of_children","spouse_name","url","anniversary","telephone_company","fax_home","fax_other","telephone_car","telephone_isdn","telephone_pager","telephone_primary","telephone_radio","telephone_telex","telephone_ttytdd","telephone_assistant"
,"telephone_callback","telephone_ip","number_of_employees","sales_volume","tax_id","commercial_register","branches","business_category","info","manager_name","assistant_name","employee_type","userfield04","userfield05","userfield06","userfield07","userfield08","userfield09","userfield10","userfield11","userfield12","userfield13","userfield14","userfield15","userfield16","userfield17","userfield18","userfield19","userfield20"],alwaysVisible:["first_name","last_name","display_name","email1","cellular_telephone1"
],i18n:{personal:b("Personal information"),messaging:b("Messaging"),phone:b("Phone & fax numbers"),home_address:b("Home address"),business_address:b("Business address"),other_address:b("Other address"),job:b("Job description"),comment:b("Comment"),userfields:b("User fields")}},g="input, textarea",h=b("Show more"),i=b("Show less"),j=function(){return $(this).val()!==""},k=function(){return $(this).val()===""},l=function(a){return a.find(".always-visible").length||a.find(g).filter(j).length},m=function(
a){return a.find(g).filter(k).length>0},n=function(a){a.preventDefault();var b=$(this).closest(".section");l(b)?(b.removeClass("show-section"),b.hasClass("show-less")?b.addClass("show-more").removeClass("show-less").find(g).filter(k).parents(".section-group").not(".always-visible").addClass("hidden"):b.addClass("show-less").removeClass("show-more").find(".hidden").removeClass("hidden").end().find(g).first().focus()):b.hasClass("show-section")?b.addClass("show-less").removeClass("show-section").find
(".section-group").removeClass("hidden"):b.addClass("show-section").removeClass("show-less").find(".section-group").addClass("hidden")},o=function(b){return function(c){var d=c.view.createSection(),e=c.view.createSectionTitle({text:f.i18n[b]}),g=c.view.createSectionContent();this.append(d.append(e,g)),d.prepend($("<div>").addClass("add-section").append($("<i>").addClass("icon-plus-sign"),$.txt(" "),$("<a>",{href:"#"}).addClass("toggle").text(f.i18n[b]))),d.prepend($("<a>",{href:"#"}).addClass("toggle show-more"
).text(h),$("<a>",{href:"#"}).addClass("toggle show-less").text(i)),d.on("click",".sectiontitle, .toggle",{pointName:b},n),/^(.*_address)$/.test(b)?(c.pointName="contact_"+b,a.point("io.ox/contacts/edit/form/address").invoke("draw",g,c)):a.point("io.ox/contacts/edit/form/"+b).invoke("draw",g,c),l(d)?m(d)?d.addClass("show-more"):d.addClass("show-less"):d.addClass("show-section")}},p=function(a){return function(b){var c=_.uniqueId("c"),d=b.view,e=d.getModel(),g=e.schema.getFieldType(a),h=e.schema.getFieldLabel
(a),i,j,k=_(f.alwaysVisible).indexOf(a)>-1,l=e.isEmpty(a),m=_(f.rare).indexOf(a)>-1,n=$("<div>").addClass("io-ox-label");switch(g){case"text":j="createTextArea";break;case"pastDate":j="createDateField";break;default:j="createTextField"}i=d[j]({id:"auto",property:a,classes:"input-large"}),this.append(d.createSectionGroup().append(n.append(d.createLabel({"for":"last",text:h})),i).addClass(k?"always-visible":undefined).addClass(!k&&l?"hidden":undefined).addClass(m?"rare-field":undefined))}},q=function(
a){var b="street,postal_code/city,state,country".split(","),c="_"+a.pointName.split("_")[1],d=this,e=a.view,f=e.getModel();_.each(b,function(b,e){var f=b.split(/\//);if(f.length===1){b=b+c;var g=p(b);g.apply(d,[a])}else{var h=a.view.createSectionGroup(),i=[],j=[],k=!0;d.append(h),_.each(f,function(b,d){var e=_.uniqueId("c"),f=a.view.getModel().schema.getFieldLabel(b+c);i.push(a.view.createLabel({"for":e,text:f})),j.push(a.view.createTextField({id:e,property:b+c,classes:"input-large"})),k=a.view.getModel
().get(b+c)?!1:!0});var l=$("<div>").addClass("inlinelabel");_.each(i,function(a){l.append(a)}),h.append(l),_.each(j,function(a,b){h.append(a.addClass("inline "+"nr"+b))}),k&&h.addClass("hidden")}})},r=function(){$(this).closest(".window-body").find('input[type="file"]').trigger("click")},s=function(a){var b=a.target.files,c=new FileReader,d=a.data.view;c.onload=function(a){d.node.find(".picture").css("background-image","url("+a.target.result+")")},c.readAsDataURL(b[0]),d.getModel().dirty=!0},t=function(
a){var e=a.view,f=e.getModel().get();e.createSection({}).addClass("formheader").append(d.getPicture(f).addClass("picture").on("click",r),$("<span>").addClass("text name clear-title user-select-text").attr("data-property","display_name").text(c.getDisplayName(f)||" "),$("<span>").addClass("text job clear-title user-select-text").attr("data-property","jobdescription_calculated").text(c.getJob(f)||" "),$("<a>").attr("data-action","save").addClass("btn btn-primary").text(b("Save")).on("click",{model:
e.getModel()},function(a){a.data.model.save()}),e.createPicUpload().find("input").on("change",{view:e},s).end(),e.createSectionDelimiter({})).appendTo(this)},u=function(b){return function(c,d){a.point("io.ox/contacts/edit/form/"+b).extend({id:c,index:100+100*d,draw:p(c)})}},v=function(){var b=0;return function(c,d){a.point("io.ox/contacts/edit/form").extend({id:d,draw:o(d),index:200+100*b++}),_.each(c,u(d))}}(),w=function(){a.point("io.ox/contacts/edit/form").extend({index:100,id:"header",draw:t}
),_.each(f.sections,v),a.point("io.ox/contacts/edit/form/address").extend({id:"address",draw:q})},x=function(a){var b=this.get(),d="",e=a.data.node;b.first_name&&b.last_name?d=b.last_name+", "+b.first_name:d=b.last_name||b.first_name,d&&e.find('input[data-property="display_name"]').val(d).trigger("change"),e.find('span[data-property="display_name"]').text(c.getFullName(b)||" ")},y=function(a){var b=c.getJob(this.get()),d=a.data.node;d.find('span[data-property="jobdescription_calculated"]').text(b||" "
)},z=e.extend({draw:function(){var b=this.getModel();return b&&(b.on("change:title change:first_name change:last_name",{node:this.node},x).on("change:company change:position",{node:this.node},y),this.node.addClass("contact-detail edit").attr("data-property",b.get("folder_id")+"."+b.get("id")),a.point("io.ox/contacts/edit/form").invoke("draw",this.node,{view:this}),this.node.append($("<div>",{id:"myGrowl"}).addClass("jGrowl").css({position:"absolute",right:"-275px",top:"-10px"})),b.on("error:invalid"
,function(a,b){$("#myGrowl").jGrowl(a.message,{header:"Make an educated guess!",sticky:!0})})),this}});return"use strict",w(),z})