
package com.openexchange.admin.exceptions;

public class Classes {
	public static final int COM_OPENEXCHANGE_ADMIN_USEREXCEPTIONFACTORY = 0;	
	public static final int COM_OPENEXCHANGE_ADMIN_DATASOURCE_OXUSER = 1;
	public static final int COM_OPENEXCHANGE_ADMIN_TOOLS_ADMINDAEMONTOOLS = 2;
	public static final int COM_OPENEXCHANGE_ADMIN_DATASOURCE_OXCONTEXT = 3;
	public static final int COM_OPENEXCHANGE_ADMIN_CONTEXTEXCEPTIONFACTORY = 4;
	public static final int COM_OPENEXCHANGE_ADMIN_DATASOURCE_OXGROUP = 5;
	public static final int COM_OPENEXCHANGE_ADMIN_GROUPEXCEPTIONFACTORY = 6;
	public static final int COM_OPENEXCHANGE_ADMIN_DATASOURCE_OXRESOURCE = 7;
	public static final int COM_OPENEXCHANGE_ADMIN_RESOURCEEXCEPTIONFACTORY = 8;
	public static final int COM_OPENEXCHANGE_ADMIN_DATASOURCE_OXUTIL = 9;
	public static final int COM_OPENEXCHANGE_ADMIN_UTILEXCEPTIONFACTORY = 10;
}
