{
 "title": "MySQL",
 "tags": [
  "MySQL",
  "MariaDB"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   { "name": "job", "label": "Job", "query": "label_values(mysql_up,job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "MySQL Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "mysql_version_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "**Current QPS**",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "MySQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[$interval]) or mysql_global_status_threads_connected{instance=~\"$instance\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "mysql_global_status_max_used_connections{instance=~\"$instance\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "expr": "mysql_global_variables_max_connections{instance=~\"$instance\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "graph",
   "description": "**MySQL Active Threads**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "expr": "max_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  { "title": "Command & Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=~\"$instance\"}[$interval])>0) or irate(mysql_global_status_commands_total{instance=~\"$instance\"}[$interval])>0",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Top Command Counters Hourly",
   "type": "graph",
   "description": "**Top Command Counters**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(mysql_global_status_commands_total{instance=~\"$instance\"}[1h])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "graph",
   "description": "**MySQL Handlers**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$instance\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=~\"$instance\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "graph",
   "description": "**MySQL Transaction Handlers**",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$instance\", handler=~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or irate(mysql_global_status_handlers_total{instance=~\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{instance=~\"$instance\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=~\"$instance\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=~\"$instance\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=~\"$instance\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{instance=~\"$instance\"}",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=~\"$instance\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{instance=~\"$instance\"}",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=~\"$instance\"}",
     "legendFormat": "Adaptive Hash Index Size"
    }
   ]
  },
  { "title": "Table Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "**MySQL Questions**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_questions{instance=~\"$instance\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "MySQL Thread Cache",
   "type": "graph",
   "description": "**MySQL Thread Cache**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_thread_cache_size{instance=~\"$instance\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "expr": "mysql_global_status_threads_cached{instance=~\"$instance\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "expr": "rate(mysql_global_status_threads_created{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_threads_created{instance=~\"$instance\"}[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  { "title": "Temporary Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "MySQL Temporary Objects",
   "type": "graph",
   "description": "**MySQL Temporary Objects**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_created_tmp_tables{instance=~\"$instance\"}[5m])",
     "legendFormat": "Created Tmp Tables"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_created_tmp_disk_tables{instance=~\"$instance\"}[5m])",
     "legendFormat": "Created Tmp Disk Tables"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_files{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_created_tmp_files{instance=~\"$instance\"}[5m])",
     "legendFormat": "Created Tmp Files"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "graph",
   "description": "**MySQL Select Types**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_select_full_join{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_select_full_join{instance=~\"$instance\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "expr": "rate(mysql_global_status_select_full_range_join{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_select_full_range_join{instance=~\"$instance\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "expr": "rate(mysql_global_status_select_range{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_select_range{instance=~\"$instance\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "expr": "rate(mysql_global_status_select_range_check{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_select_range_check{instance=~\"$instance\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "expr": "rate(mysql_global_status_select_scan{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_select_scan{instance=~\"$instance\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "MySQL Query Cache Memory",
   "type": "graph",
   "description": "**MySQL Query Cache Memory**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_qcache_free_memory{instance=~\"$instance\"}",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{instance=~\"$instance\"}",
     "legendFormat": "Query Cache Size"
    }
   ]
  },
  {
   "title": "MySQL Query Cache Activity",
   "type": "graph",
   "description": "**MySQL Query Cache Activity**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_qcache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_qcache_hits{instance=~\"$instance\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_qcache_inserts{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_qcache_inserts{instance=~\"$instance\"}[5m])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(mysql_global_status_qcache_not_cached{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_qcache_not_cached{instance=~\"$instance\"}[5m])",
     "legendFormat": "Not Cached"
    },
    {
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_qcache_lowmem_prunes{instance=~\"$instance\"}[5m])",
     "legendFormat": "Prunes"
    },
    {
     "expr": "rate(mysql_global_status_qcache_queries_in_cache{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_qcache_queries_in_cache{instance=~\"$instance\"}[5m])",
     "legendFormat": "Queries in Cache"
    }
   ]
  },
  { "title": "Table Openings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "MySQL Table Open Cache Status",
   "type": "graph",
   "description": "**MySQL Table Open Cache Status**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_tables{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=~\"$instance\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=~\"$instance\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "graph",
   "description": "**MySQL Open Tables**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{instance=~\"$instance\"}",
     "legendFormat": "Open Tables"
    },
    {
     "expr": "mysql_global_variables_table_open_cache{instance=~\"$instance\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "description": "**MySQL Network Traffic**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=~\"$instance\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{instance=~\"$instance\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=~\"$instance\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "description": "**MySQL Network Usage Hourly**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(mysql_global_status_bytes_received{instance=~\"$instance\"}[1h])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(mysql_global_status_bytes_sent{instance=~\"$instance\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}