{
 "title": "Operating System",
 "tags": [ "OS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info,job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$instance\"}) or sum(time() - node_boot_time{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"}) or sum(node_memory_MemTotal{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$instance\", mode=\"system\"}) or count(node_cpu{instance=~\"$instance\", mode=\"system\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[30m])) or avg(irate(node_cpu{instance=~\"$instance\",mode=\"iowait\"}[30m]))) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[30m])) * 100) OR\n100 - (avg(irate(node_cpu{instance=~\"$instance\",mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"} / (node_memory_MemTotal_bytes{instance=~\"$instance\"})))* 100 OR\n(1 - (node_memory_MemAvailable{instance=~\"$instance\"} / (node_memory_MemTotal{instance=~\"$instance\"})))* 100"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$instance\"} / node_memory_SwapTotal_bytes{instance=~\"$instance\"})) * 100 OR\n(1 - (node_memory_SwapFree{instance=~\"$instance\"} / node_memory_SwapTotal{instance=~\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, 100 - ((node_filesystem_avail_bytes{instance=~\"$instance\",fstype=~\"ext[2-4]|[x|z]fs\"} * 100) / node_filesystem_size_bytes {instance=~\"$instance\",fstype=~\"ext[2-4]|[x|z]fs\"})) OR topk(1, 100 - ((node_filesystem_avail{instance=~\"$instance\",fstype=~\"ext[2-4]|[x|z]fs\"} * 100) / node_filesystem_size {instance=~\"$instance\",fstype=~\"ext[2-4]|[x|z]fs\"}))"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Load",
   "type": "graph",
   "description": "The load average.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "shortterm (1m)"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "midterm (5m)"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "longterm (15m)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Average time cpus spent in each mode.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[30m])) OR avg(irate(node_cpu{instance=~\"$instance\",mode=\"system\"}[30m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[30m])) OR avg(irate(node_cpu{instance=~\"$instance\",mode=\"user\"}[30m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[30m])) OR avg(irate(node_cpu{instance=~\"$instance\",mode=\"iowait\"}[30m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "1-avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[30m])) OR 1-avg(irate(node_cpu{instance=~\"$instance\",mode=\"idle\"}[30m]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "description": "Number of processes blocked *(waiting for I/O to complete)* and in runnable state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "Running"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} OR node_memory_MemTotal{instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"} OR node_memory_MemTotal{instance=~\"$instance\"} - node_memory_MemAvailable{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"} OR node_memory_MemAvailable{instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Forks",
   "type": "graph",
   "description": "Number of forks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_forks_total{instance=~\"$instance\"}[$interval]) OR irate(node_forks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "description": "Number of context switches.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[$interval]) OR irate(node_context_switches{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "File descriptor information.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*\"}[30m])*8 OR irate(node_network_receive_bytes{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*\"}[30m])*8",
     "legendFormat": "{{device}}_Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*\"}[30m])*8 OR irate(node_network_transmit_bytes{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*\"}[30m])*8",
     "legendFormat": "{{device}}_Transmit"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$instance\"}[30m]) OR irate(node_disk_reads_completed{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$instance\"}[30m]) OR irate(node_disk_writes_completed{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Writes"
    }
   ]
  },
  {
   "title": "Disk R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance\"}[30m]) OR irate(node_disk_bytes_read{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance\"}[30m]) OR irate(node_disk_bytes_written{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Written"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$instance\"}[30m]) OR\n      irate(node_disk_read_time_ms{instance=~\"$instance\"}[30m]) / irate(node_disk_reads_completed{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$instance\"}[30m]) OR\n      irate(node_disk_write_time_ms{instance=~\"$instance\"}[30m]) / irate(node_disk_writes_completed{instance=~\"$instance\"}[30m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  }
 ]
}