package com._4psa.client._2_5_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.498+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://4psa.com/Client/2.5.1", name = "ClientInterface")
@XmlSeeAlso({com._4psa.clientdata_xsd._2_5.ObjectFactory.class, com._4psa.headerdata_xsd._2_5.ObjectFactory.class, com._4psa.billingmessages_xsd._2_5.ObjectFactory.class, com._4psa.clientmessages_xsd._2_5.ObjectFactory.class, com._4psa.billingmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.reportdata_xsd._2_5.ObjectFactory.class, com._4psa.extensionmessages_xsd._2_5.ObjectFactory.class, com._4psa.channeldata_xsd._2_5.ObjectFactory.class, com._4psa.pbxmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.accountmessages_xsd._2_5.ObjectFactory.class, com._4psa.resellermessages_xsd._2_5.ObjectFactory.class, com._4psa.common_xsd._2_5.ObjectFactory.class, com._4psa.billingdata_xsd._2_5.ObjectFactory.class, com._4psa.clientmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.extensionmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.pbxdata_xsd._2_5.ObjectFactory.class, com._4psa.reportmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.channelmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.pbxmessages_xsd._2_5.ObjectFactory.class, com._4psa.globalopmessages_xsd._2_5.ObjectFactory.class, com._4psa.reportmessages_xsd._2_5.ObjectFactory.class, com._4psa.extensiondata_xsd._2_5.ObjectFactory.class, com._4psa.resellermessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.resellerdata_xsd._2_5.ObjectFactory.class, com._4psa.channelmessages_xsd._2_5.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientInterface {

    @WebResult(name = "GetClientsResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetClients", action = "http://4psa.com/Client/2.5.1:getClientsIn")
    public com._4psa.clientmessagesinfo_xsd._2_5.GetClientResponseType getClients(
        @WebParam(partName = "messagePart", name = "GetClientsRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.GetClientsRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetClientPLResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetClientPL", action = "http://4psa.com/Client/2.5.1:getClientPLIn")
    public com._4psa.clientmessagesinfo_xsd._2_5.GetClientPLResponseType getClientPL(
        @WebParam(partName = "messagePart", name = "GetClientPLRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.GetClientPLRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "DelClientResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "DelClient", action = "http://4psa.com/Client/2.5.1:delClientIn")
    public com._4psa.common_xsd._2_5.DelObject delClient(
        @WebParam(partName = "messagePart", name = "DelClientRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.DelClientRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "EditClientResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "EditClient", action = "http://4psa.com/Client/2.5.1:editClientIn")
    public com._4psa.clientmessages_xsd._2_5.EditClientResponse editClient(
        @WebParam(partName = "messagePart", name = "EditClientRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.EditClientRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetClientDetailsResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetClientDetails", action = "http://4psa.com/Client/2.5.1:getClientDetailsIn")
    public com._4psa.clientmessages_xsd._2_5.GetClientDetailsResponse getClientDetails(
        @WebParam(partName = "messagePart", name = "GetClientDetailsRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.GetClientDetailsRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "SetClientCpAccessResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "SetClientCpAccess", action = "http://4psa.com/Client/2.5.1:setClientCpAccessIn")
    public com._4psa.common_xsd._2_5.UpdateObject setClientCpAccess(
        @WebParam(partName = "messagePart", name = "SetClientCpAccessRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.SetClientCpAccessRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "SetClientPLResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "SetClientPL", action = "http://4psa.com/Client/2.5.1:setClientPLIn")
    public com._4psa.common_xsd._2_5.UpdateObject setClientPL(
        @WebParam(partName = "messagePart", name = "SetClientPLRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.SetClientPLRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "SetClientStatusResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "SetClientStatus", action = "http://4psa.com/Client/2.5.1:setClientStatusIn")
    public com._4psa.common_xsd._2_5.UpdateObject setClientStatus(
        @WebParam(partName = "messagePart", name = "SetClientStatusRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.SetClientStatusRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "MoveClientsResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "MoveClients", action = "http://4psa.com/Client/2.5.1:moveClientsIn")
    public com._4psa.clientmessagesinfo_xsd._2_5.MoveClientsResponseType moveClients(
        @WebParam(partName = "messagePart", name = "MoveClientsRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.MoveClientsRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "AddClientResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "AddClient", action = "http://4psa.com/Client/2.5.1:addClientIn")
    public com._4psa.clientmessages_xsd._2_5.AddClientResponse addClient(
        @WebParam(partName = "messagePart", name = "AddClientRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.AddClientRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "UpdateClientPLResponse", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "UpdateClientPL", action = "http://4psa.com/Client/2.5.1:updateClientPLIn")
    public com._4psa.common_xsd._2_5.UpdateObject updateClientPL(
        @WebParam(partName = "messagePart", name = "UpdateClientPLRequest", targetNamespace = "http://4psa.com/ClientMessages.xsd/2.5.1")
        com._4psa.clientmessages_xsd._2_5.UpdateClientPLRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );
}
