
package com._4psa.client._2_5_1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.271+02:00
 * Generated source version: 2.4.0
 *
 */
public final class ClientInterface_ClientPort_Client {

    private static final QName SERVICE_NAME = new QName("http://4psa.com/Client/2.5.1", "ClientPort");

    private ClientInterface_ClientPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ClientPort.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ClientPort ss = new ClientPort(wsdlURL, SERVICE_NAME);
        ClientInterface port = ss.getClientPort();

        {
        System.out.println("Invoking getClients...");
        com._4psa.clientmessages_xsd._2_5.GetClientsRequest _getClients_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getClients_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getClients_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessagesinfo_xsd._2_5.GetClientResponseType _getClients__return = port.getClients(_getClients_messagePart, _getClients_headerPart, _getClients_headerPart1);
        System.out.println("getClients.result=" + _getClients__return);

        System.out.println("getClients._getClients_headerPart1=" + _getClients_headerPart1.value);

        }
        {
        System.out.println("Invoking getClientPL...");
        com._4psa.clientmessages_xsd._2_5.GetClientPLRequest _getClientPL_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getClientPL_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getClientPL_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessagesinfo_xsd._2_5.GetClientPLResponseType _getClientPL__return = port.getClientPL(_getClientPL_messagePart, _getClientPL_headerPart, _getClientPL_headerPart1);
        System.out.println("getClientPL.result=" + _getClientPL__return);

        System.out.println("getClientPL._getClientPL_headerPart1=" + _getClientPL_headerPart1.value);

        }
        {
        System.out.println("Invoking delClient...");
        com._4psa.clientmessages_xsd._2_5.DelClientRequest _delClient_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delClient_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delClient_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delClient__return = port.delClient(_delClient_messagePart, _delClient_headerPart, _delClient_headerPart1);
        System.out.println("delClient.result=" + _delClient__return);

        System.out.println("delClient._delClient_headerPart1=" + _delClient_headerPart1.value);

        }
        {
        System.out.println("Invoking editClient...");
        com._4psa.clientmessages_xsd._2_5.EditClientRequest _editClient_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _editClient_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _editClient_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessages_xsd._2_5.EditClientResponse _editClient__return = port.editClient(_editClient_messagePart, _editClient_headerPart, _editClient_headerPart1);
        System.out.println("editClient.result=" + _editClient__return);

        System.out.println("editClient._editClient_headerPart1=" + _editClient_headerPart1.value);

        }
        {
        System.out.println("Invoking getClientDetails...");
        com._4psa.clientmessages_xsd._2_5.GetClientDetailsRequest _getClientDetails_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getClientDetails_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getClientDetails_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessages_xsd._2_5.GetClientDetailsResponse _getClientDetails__return = port.getClientDetails(_getClientDetails_messagePart, _getClientDetails_headerPart, _getClientDetails_headerPart1);
        System.out.println("getClientDetails.result=" + _getClientDetails__return);

        System.out.println("getClientDetails._getClientDetails_headerPart1=" + _getClientDetails_headerPart1.value);

        }
        {
        System.out.println("Invoking setClientCpAccess...");
        com._4psa.clientmessages_xsd._2_5.SetClientCpAccessRequest _setClientCpAccess_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _setClientCpAccess_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _setClientCpAccess_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _setClientCpAccess__return = port.setClientCpAccess(_setClientCpAccess_messagePart, _setClientCpAccess_headerPart, _setClientCpAccess_headerPart1);
        System.out.println("setClientCpAccess.result=" + _setClientCpAccess__return);

        System.out.println("setClientCpAccess._setClientCpAccess_headerPart1=" + _setClientCpAccess_headerPart1.value);

        }
        {
        System.out.println("Invoking setClientPL...");
        com._4psa.clientmessages_xsd._2_5.SetClientPLRequest _setClientPL_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _setClientPL_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _setClientPL_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _setClientPL__return = port.setClientPL(_setClientPL_messagePart, _setClientPL_headerPart, _setClientPL_headerPart1);
        System.out.println("setClientPL.result=" + _setClientPL__return);

        System.out.println("setClientPL._setClientPL_headerPart1=" + _setClientPL_headerPart1.value);

        }
        {
        System.out.println("Invoking setClientStatus...");
        com._4psa.clientmessages_xsd._2_5.SetClientStatusRequest _setClientStatus_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _setClientStatus_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _setClientStatus_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _setClientStatus__return = port.setClientStatus(_setClientStatus_messagePart, _setClientStatus_headerPart, _setClientStatus_headerPart1);
        System.out.println("setClientStatus.result=" + _setClientStatus__return);

        System.out.println("setClientStatus._setClientStatus_headerPart1=" + _setClientStatus_headerPart1.value);

        }
        {
        System.out.println("Invoking moveClients...");
        com._4psa.clientmessages_xsd._2_5.MoveClientsRequest _moveClients_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _moveClients_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _moveClients_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessagesinfo_xsd._2_5.MoveClientsResponseType _moveClients__return = port.moveClients(_moveClients_messagePart, _moveClients_headerPart, _moveClients_headerPart1);
        System.out.println("moveClients.result=" + _moveClients__return);

        System.out.println("moveClients._moveClients_headerPart1=" + _moveClients_headerPart1.value);

        }
        {
        System.out.println("Invoking addClient...");
        com._4psa.clientmessages_xsd._2_5.AddClientRequest _addClient_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _addClient_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _addClient_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.clientmessages_xsd._2_5.AddClientResponse _addClient__return = port.addClient(_addClient_messagePart, _addClient_headerPart, _addClient_headerPart1);
        System.out.println("addClient.result=" + _addClient__return);

        System.out.println("addClient._addClient_headerPart1=" + _addClient_headerPart1.value);

        }
        {
        System.out.println("Invoking updateClientPL...");
        com._4psa.clientmessages_xsd._2_5.UpdateClientPLRequest _updateClientPL_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _updateClientPL_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _updateClientPL_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _updateClientPL__return = port.updateClientPL(_updateClientPL_messagePart, _updateClientPL_headerPart, _updateClientPL_headerPart1);
        System.out.println("updateClientPL.result=" + _updateClientPL__return);

        System.out.println("updateClientPL._updateClientPL_headerPart1=" + _updateClientPL_headerPart1.value);

        }

        System.exit(0);
    }

}
