define("io.ox/calendar/util",["io.ox/core/date","gettext!io.ox/calendar/calendar"],function(a,b){var c,d,e=a.locale.daysStandalone,f=a.locale.days,g=a.locale.months,h=[b("last"),"",b("first"),b("second"),b("third"),b("fourth"),b("last")],i=[b("Reserved"),b("Temporary"),b("Absent"),b("Free")],j="reserved temporary absent free".split(" "),k=["",'<i class="icon-ok">','<i class="icon-remove">','<i class="icon-question-sign">'],l=["","accepted","declined","tentative"],m=6e4,n=60*m,o=24*n,p=7*o,q=1,r=2
,s=4,t=8,u=16,v=32,w=64,x=a.locale.weekStart;return"use strict",$.when.apply($,_.map(["America/Los_Angeles","America/New_York","America/Sao_Paulo","Europe/London","Europe/Berlin","Europe/Moscow","Asia/Kolkata","Asia/Shanghai","Australia/Sydney"],a.getTimeZone)).done(function(){c=Array.prototype.slice.call(arguments)}),d={MINUTE:m,HOUR:n,DAY:o,WEEK:p,getFirstWeekDay:function(){return x},getDayNames:function(){return e.slice(x).concat(e.slice(0,x))},getDaysInMonth:function(a,b){return(new Date(a,b+1
,0)).getDate()},isToday:function(b){return Math.floor(b/o)===Math.floor(a.Local.localTime((new Date).getTime())/o)},floor:function(a,b){a=a||0,b=b||n;if(typeof b=="number")return Math.floor(a/b)*b;else if(b==="week"){var c=new Date(a),d=c.getDay(),e=c.getTime()-d*o;return this.floor(e,o)}},getTime:function(a){var b=new Date(a);return _.pad(b.getUTCHours(),2)+":"+_.pad(b.getUTCMinutes(),2)},getDate:function(a){var b=a!==undefined?new Date(a):new Date;return e[b.getUTCDay()]+", "+_.pad(b.getUTCDate
(),2)+"."+_.pad(b.getUTCMonth()+1,2)+"."+b.getUTCFullYear()},getSmartDate:function(a){var b=a!==undefined?new Date(a):new Date,c=new Date,d=this.floor(c.getTime(),"week"),e=0,h=0;b.setUTCHours(0,0,0,0),c.setUTCHours(0,0,0,0),e=b-c,h=b-d;if(e<0){if(e>=-1*o)return"Yesterday";else if(h>-7*o)return"Last Week"}else if(e<o)return"Today";else if(e<2*o)return"Tomorrow";else if(h<7*o)return f[b.getUTCDay()];else if(h>=7*o&&h<14*o)return"Next week";return g[b.getUTCMonth()]+" "+b.getUTCFullYear()},getDateInterval
:function(a){var b=(a.end_date-a.start_date)/o>>0;if(a.full_time&&b>1)return this.getDate(a.start_date)+" – "+this.getDate(a.end_date-1);else return this.getDate(a.start_date)},getTimeInterval:function(c,e){var f,g,h;e=e||a.Local;if(c.full_time)return f=(c.end_date-c.start_date)/o>>0,f<=1?b("Whole day"):b.format(b.ngettext("%d day","%d days",f),f);else return g=e.localTime(a.Local.utc(c.start_date)),h=e.localTime(a.Local.utc(c.end_date)),d.getTime(g)+" – "+d.getTime(h)},addTimezoneLabel:function(
b,e){var f=a.Local.getTTInfoLocal(e.start_date);b.append($.txt(d.getTimeInterval(e)+" "),$("<span>").addClass("label").text(f.abbr).popover({title:d.getTimeInterval(e)+" "+f.abbr,content:g,animation:!1,placement:function(a,b){var c=$(b).offset(),d=$("body").width()/2;return c.left>d?"left":"right"}}));function g(){var a=$("<div>");return _(c).each(function(b){a.append($("<div>").addClass("clear").append($("<span>").text(b.displayName.replace(/^.*?\//,"")),$("<b>").append($("<span>").addClass("label label-info"
).text(b.getTTInfoLocal(e.start_date).abbr)),$("<i>").text(d.getTimeInterval(e,b))))}),'<div class="timezones">'+a.html()+"</div>"}return b},getShownAsClass:function(a){return j[(a.shown_as||1)-1]},getShownAs:function(a){return i[(a.shown_as||1)-1]},getConfirmationSymbol:function(a){return k[a||0]},getConfirmationClass:function(a){return l[a||0]},isRecurring:function(a){return!!a.recurrence_type},getRecurrenceString:function(a){function c(a){return h[a+1]}function d(a){var c=[];switch(a){case 62:
c.push(b("Work Day"));break;case 65:c.push(b("Weekend Day"));break;case 127:c.push(b("Day"));break;default:a%r/q>=1&&c.push(b("Sunday")),a%s/r>=1&&c.push(b("Monday")),a%t/s>=1&&c.push(b("Tuesday")),a%u/t>=1&&c.push(b("Wednesday")),a%v/u>=1&&c.push(b("Thursday")),a%w/v>=1&&c.push(b("Friday")),a/w>=1&&c.push(b("Saturday"))}return c.join(", ")}function e(a){return g[a]}var f="",i=_.printf,j=a.interval,k=a.days||null,l=a.month,m=a.day_in_month;switch(a.recurrence_type){case 1:f=i(b("Each %s Day"),j);
break;case 2:f=j===1?i(b("Weekly on %s"),d(k)):i(b("Each %s weeks on %s"),j,d(k));break;case 3:k===null?f=j===1?i(b("On %s. day every month"),m):i(b("On %s. day every %s. month"),m,j):f=j===1?i(b("On %s %s every month"),c(m),d(k)):i(b("On %s %s each %s. months"),c(m),d(k),j);break;case 4:k===null?f=i(b("Each %s. %s"),m,e(l)):f=i(b("On %s %s in %s"),c(m),d(k),e(l))}return f},getNote:function(a){return $.trim(a.note||"").replace(/\n{3,}/g,"\n\n").replace(/</g,"&lt;").replace(/(https?\:\/\/\S+)/g,'<a href="$1" target="_blank">$1</a>'
)},getConfirmations:function(a){var b={};return _(a.users).each(function(a){b[String(a.id)]={status:a.confirmation||0,comment:a.confirmmessage||""}}),_(a.confirmations).each(function(a){b[a.mail]={status:a.status||0,comment:a.confirmmessage||""}}),b},getMonthScaffold:function(a){var b=new Date(a||_.now()),c=b.getUTCFullYear(),e=b.getUTCMonth(),f=b.getUTCDay(),g=Date.UTC(c,e,1),h=(7+(new Date(g)).getDay()-d.getFirstWeekDay())%7,i=d.getDaysInMonth(c,e)+h,j=0,k=[],l=g-o*h,m,n;for(;j<i||j%7!==0;j+=1,
l+=o)j%7===0&&(m=[],k.push(m)),b=new Date(l),m.push(n={year:b.getUTCFullYear(),month:b.getUTCMonth(),date:b.getUTCDate(),day:b.getUTCDay(),timestamp:l,isToday:d.isToday(l),col:j%7,row:k.length-1}),n.isWeekend=n.day===0||n.day===6,n.isOut=n.year!==c||n.month!==e;return k}},d})