define("io.ox/calendar/view-detail",["io.ox/core/extensions","io.ox/calendar/util","io.ox/core/api/user","io.ox/core/api/group","io.ox/core/api/resource","io.ox/core/api/folder","io.ox/core/extPatterns/links","gettext!io.ox/calendar/calendar","less!io.ox/calendar/style.css"],function(a,b,c,d,e,f){var g=function(b){b.preventDefault(),a.point("io.ox/core/person:action").each(function(a){_.call(a.action,b.data,b)})};"use strict",a.point("io.ox/calendar/detail").extend({index:100,id:"date",draw:function(
b){var c=$("<div>").addClass("date").appendTo(this);a.point("io.ox/calendar/detail/date").invoke("draw",c,b)}}),a.point("io.ox/calendar/detail/date").extend({index:100,id:"time",draw:function(a){this.append(b.addTimezoneLabel($("<div>").addClass("interval"),a))}}),a.point("io.ox/calendar/detail/date").extend({index:200,id:"date",draw:function(a){var c=b.getRecurrenceString(a);this.append($("<div>").addClass("day").text(b.getDateInterval(a)+(c!==""?" – "+c:"")))}}),a.point("io.ox/calendar/detail")
.extend({index:350,id:"inline-actions",draw:function(b){a.point("io.ox/calendar/detail/actions").invoke("draw",this,b)}}),a.point("io.ox/calendar/detail").extend({index:200,id:"title",draw:function(a){this.append($("<div>").addClass("title clear-title").text(a.title||""))}}),a.point("io.ox/calendar/detail").extend({index:300,id:"location",draw:function(a){this.append($("<div>").addClass("location").text(a.location||" "))}}),a.point("io.ox/calendar/detail").extend({index:400,id:"note",draw:function(
a){a.note&&this.append($("<div>").addClass("note").html(b.getNote(a)))}});function h(a,c){var d,e,f,h,i=a.mail||a.id,j=c[i]||{status:0,comment:""},k=b.getConfirmationSymbol(j.status),l=b.getConfirmationClass(j.status),m=c[i]||a.folder_id,n=m?"person":"",o=String(a.mail).toLowerCase();return a.type===5?(h=String(a.display_name).toLowerCase(),h===o?e=d=o:(e=a.display_name?a.display_name+" <"+o+">":o,d=a.display_name||o)):e=d=a.display_name||String(a.mail).toLowerCase(),f=$("<div>").addClass("participant"
).append($('<a href="#">').addClass(n+" "+l).text(e)).append($("<span>").addClass("status "+l).html(" "+k)).on("click",{display_name:d,email1:o,internal_userid:a.internal_userid},g),j.comment!==""&&f.append($("<span>").addClass("comment").text(j.comment)),f}return a.point("io.ox/calendar/detail").extend({index:500,id:"participants",draw:function(a){var f,g,i,j,k,l=a.participants,m=l.length,n=m>1?$("<div>").addClass("participants"):$(),o={};m>1&&(o=b.getConfirmations(a),n.busy(),f=_(l).chain().select
(function(a){return a.type===1}).map(function(a){return a.id}).value(),g=_(l).chain().select(function(a){return a.type===2}).map(function(a){return{id:a.id}}).value(),i=_(l).chain().select(function(a){return a.type===3}).map(function(a){return{id:a.id}}).value(),j=_(l).chain().select(function(a){return a.type===5}).sortBy(function(a){return a.mail}).value(),n.append($("<div>").addClass("io-ox-label").text("Participants")),k=$("<div>").addClass("participant-list").appendTo(n),$.when(c.getList(f),d
.getList(g),e.getList(i)).done(function(a,b,d){_(a).chain().sortBy(function(a){return a.display_name}).each(function(a){k.append(h(a,o))}),_(j).each(function(a){k.append(h(a,o))}),_(b).chain().sortBy(function(a){return a.display_name}).each(function(a){var b,d=_(a.members).difference(f);d.length&&(n.append($("<div>").addClass("group").text(a.display_name+":")).append(b=$("<div>").addClass("participant-list")),c.getList(d).done(function(a){_(a).chain().sortBy(function(a){return a.display_name}).each
(function(a){b.append(h(a,o))})}))}),d.length&&(n.append($("<div>").addClass("io-ox-label").text("Resources")).append(k=$("<div>").addClass("participant-list")),_(d).chain().sortBy(function(a){return a.display_name}).each(function(a){k.append(h(a,o))}))}).always(function(){n.idle().append($("<div>").addClass("participants-clear"))})),this.append(n)}}),a.point("io.ox/calendar/detail").extend({index:600,id:"details",draw:function(b){var c=$("<div>").addClass("details").append($("<div>").addClass("io-ox-label"
).text("Details")).appendTo(this);a.point("io.ox/calendar/detail/details").invoke("draw",c,b)}}),a.point("io.ox/calendar/detail/details").extend({index:100,id:"shownAs",draw:function(a){this.append($("<span>").addClass("detail-label").text("Show as"+": ")).append($("<span>").addClass("detail shown_as "+b.getShownAsClass(a)).text(" ")).append($("<span>").addClass("detail").text(" "+b.getShownAs(a))).append($("<br>"))}}),a.point("io.ox/calendar/detail/details").extend({index:200,id:"folder",draw:function(
a){this.append($("<span>").addClass("detail-label").text("Folder"+": "),$("<span>").addClass("detail").append(f.getTextNode(a.folder_id)),$("<br>"))}}),a.point("io.ox/calendar/detail/details").extend({index:200,id:"created",draw:function(a){this.append($("<span>").addClass("detail-label").text("Created"+": ")).append($("<span>").addClass("detail").append($("<span>").text(b.getDate(a.creation_date))).append($("<span>").text(" – ")).append($("<span>").append(c.getTextNode(a.created_by)))).append($("<br>"
))}}),a.point("io.ox/calendar/detail/details").extend({index:200,id:"modified",draw:function(a){this.append($("<span>").addClass("detail-label").text("Modified"+": ")).append($("<span>").addClass("detail").append($("<span>").text(b.getDate(a.last_modified))).append($("<span>").text(" – ")).append($("<span>").append(c.getTextNode(a.modified_by)))).append($("<br>"))}}),{draw:function(b){var c;return b?(c=$("<div>").addClass("calendar-detail"),a.point("io.ox/calendar/detail").invoke("draw",c,b)):c=$
(),c}}})