#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;
use JMX::Jmx4Perl;
use JMX::Jmx4Perl::Request;   # Type constants are exported here

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    if (-e "/opt/open-xchange/bundles/com.openexchange.ajp.jar") {
        print "yes\n";
        exit 0;
    } else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
	print "graph_title AJPv13Server\n";
	print "graph_args --base 1000 -l 0\n";
	print "graph_category Open Xchange\n";
	print "graph_vlabel Number\n";
	print "a.label NumActive\n";
	print "a.draw AREA\n";
	print "b.label NumIdle\n";
	print "b.draw STACK\n";
	print "c.label PoolSize\n";
	print "c.draw LINE1\n";
	exit 0
}
									

### Settings and connection Testing

my $jmx = new JMX::Jmx4Perl(url => $ENV{oxJolokiaUrl},
user => $ENV{oxJolokiaUser},
password => $ENV{oxJolokiaPassword});

### Test if a connection can be made
my $request = new JMX::Jmx4Perl::Request({type => AGENT_VERSION});
my $response = $jmx->request($request);
if ($response->is_error()){
	my $status = $response->status();
	if ($status == 404) {
		die "Link to servlet might be wrong";
	}
	elsif ($status == 401) {
		die "Credentials to login might be wrong";
	}
	else {
		die "Something went wrong ",$status;
	}
}

###

$request = new JMX::Jmx4Perl::Request(READ,
	"com.openexchange.monitoring:name=AJPv13ServerThreadsMonitor",
	"NumActive");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "a.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(READ,
	"com.openexchange.monitoring:name=AJPv13ServerThreadsMonitor",
	"NumIdle");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "b.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(READ,
	"com.openexchange.monitoring:name=AJPv13ServerThreadsMonitor",
	"PoolSize");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "c.value ",$response->value(),"\n";
}
