#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;

use LWP;
use JSON;

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
	print "yes\n";
	exit 0;
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Cassandra Ignores\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel Number\n";
    print "ignores.label Ignores\n";
    print "ignores.draw LINE1\n";
    print "ignoresOnClientTimeout.label Ignores On Client Timeout\n";
    print "ignoresOnClientTimeout.draw LINE1\n";
    print "ignoresOnConnectionError.label Ignores On Connection Error\n";
    print "ignoresOnConnectionError.draw LINE1\n";
    print "ignoresOnOtherErrors.label Ignores On Other Errors\n";
    print "ignoresOnOtherErrors.draw LINE1\n";
    print "ignoresOnReadTimeout.label Ignores On Read Timeout\n";
    print "ignoresOnReadTimeout.draw LINE1\n";
    print "ignoresOnWriteTimeout.label Ignores On Write Timeout\n";
    print "ignoresOnWriteTimeout.draw LINE1\n";
    print "ignoresOnUnavailable.label Ignores On Unavailable\n";
    print "ignoresOnUnavailable.draw LINE1\n";
    exit 0
}

my $url = $ENV{oxJolokiaUrl};
my $username = $ENV{oxJolokiaUser};
my $password = $ENV{oxJolokiaPassword};

callUrl("ignores","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/Ignores");
callUrl("ignoresOnClientTimeout","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnClientTimeout");
callUrl("ignoresOnConnectionError","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnConnectionError");
callUrl("ignoresOnOtherErrors","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnOtherErrors");
callUrl("ignoresOnReadTimeout","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnReadTimeout");
callUrl("ignoresOnUnavailable","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnUnavailable");
callUrl("ignoresOnWriteTimeout","/read/com.openexchange.nosql.cassandra:name=Cassandra%20Cluster%20Monitoring%20Bean/IgnoresOnWriteTimeout");

sub callUrl {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			print "$_[0].value ";
			print $json->{value},"\n";
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}
	}
}