#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;
use JMX::Jmx4Perl;
use JMX::Jmx4Perl::Request;   # Type constants are exported here

###
# Infos about HTTP keepalive:
#   hits count:    Requests that get handled via a "keep-alive" enabled connection.
#   live count:    The number of live keep-alive connections.
#   refuses count: the number of times keep-alive mode was refused.
#   timeouts cout: Connections that weren't closed to signal completion according to HTTP1.0/1.1 but simply timed out. 
###

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    print "yes\n";
    exit 0;
}

if ( $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title OSGi EventAdmin\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel number of events\n";
    print "graph_period minute\n";
    print "enqueued.label enqueued events\n";
    print "avg.label events per minute\n";
    print "avg.draw AREA\n";
    exit 0
}

### Settings and connection Testing

my $jmx = new JMX::Jmx4Perl(url => $ENV{oxJolokiaUrl},
user => $ENV{oxJolokiaUser},
password => $ENV{oxJolokiaPassword});

### Test if a connection can be made
my $request = new JMX::Jmx4Perl::Request({type => AGENT_VERSION});
my $response = $jmx->request($request);
if ($response->is_error()){
    my $status = $response->status();
    if ($status == 404) {
        die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
    }
    elsif ($status == 401) {
        die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
    }
    else {
        die "Something went wrong ",$status;
    }
}

###

$request = new JMX::Jmx4Perl::Request(READ,
    "org.apache.felix.eventadmin.monitoring:type=EventAdminMBean",
    "EventsPerMinute");
$response = $jmx->request($request);
if ($response->is_ok()){
    print "avg.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(READ,
    "org.apache.felix.eventadmin.monitoring:type=EventAdminMBean",
    "EnqueuedEvents");
$response = $jmx->request($request);
if ($response->is_ok()){
    print "enqueued.value ",$response->value(),"\n";
}