#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;

use LWP;
use JSON;


if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    if (-e "/opt/open-xchange/bundles/com.openexchange.http.grizzly/com.openexchange.http.grizzly.jar") {
        print "yes\n";
        exit 0;
    } else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title Grizzly HttpCodecFilter\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel Number\n";
    
    print "total-bytes-written.label total-bytes-written\n";
    print "total-bytes-written.draw LINE1\n";
    print "total-bytes-written.type DERIVE\n";
    print "total-bytes-written.min 0\n";
    
    print "total-bytes-received.label total-bytes-received\n";
    print "total-bytes-received.draw LINE1\n";
    print "total-bytes-received.type DERIVE\n";
    print "total-bytes-received.min 0\n";
    
    print "http-codec-error-count.label http-codec-error-count\n";
    print "http-codec-error-count.draw LINE1\n";
    print "http-codec-error-count.type DERIVE\n";
    print "http-codec-error-count.min 0\n";
    
    exit 0
}

my $url = $ENV{oxJolokiaUrl};
my $username = $ENV{oxJolokiaUser};
my $password = $ENV{oxJolokiaPassword};

callUrl("total-bytes-written","/read/org.glassfish.grizzly:name=HttpCodecFilter,pp=!/gmbal-root!/HttpServer[HttpServer]!/NetworkListener[NetworkListener[http-listener]],type=HttpCodecFilter/total-bytes-written");
callUrl("total-bytes-received","/read/org.glassfish.grizzly:name=HttpCodecFilter,pp=!/gmbal-root!/HttpServer[HttpServer]!/NetworkListener[NetworkListener[http-listener]],type=HttpCodecFilter/total-bytes-received");
callUrl("http-codec-error-count","/read/org.glassfish.grizzly:name=HttpCodecFilter,pp=!/gmbal-root!/HttpServer[HttpServer]!/NetworkListener[NetworkListener[http-listener]],type=HttpCodecFilter/http-codec-error-count");

sub callUrl {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			print "$_[0].value ";
			print $json->{value},"\n";
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}
	}
}