#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;
use JMX::Jmx4Perl;
use JMX::Jmx4Perl::Request;   # Type constants are exported here

if ( $ARGV[0] and $ARGV[0] eq "autoconf") {
    if (-e "/opt/open-xchange/bundles/com.openexchange.service.indexing.impl.jar") {
        print "yes\n";
        exit 0;
    } else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title Indexing Jobs\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel number of jobs\n";
    print "a.label all stored jobs\n";
    print "b.label locally stored jobs\n";
    print "c.label currently running jobs\n";
    exit 0
}

### Settings and connection Testing

my $jmx = new JMX::Jmx4Perl(url => $ENV{oxJolokiaUrl},
user => $ENV{oxJolokiaUser},
password => $ENV{oxJolokiaPassword});

### test if a connection can be made
my $request = new JMX::Jmx4Perl::Request({type => AGENT_VERSION});
my $response = $jmx->request($request);
if ($response->is_error()){
	my $status = $response->status();
	if ($status == 404) {
		die "Link to servlet might be wrong";
	}
	elsif ($status == 401) {
		die "Credentials to login might be wrong";
	}
	else {
		die "Something went wrong ",$status;
	}
}

###

$request = new JMX::Jmx4Perl::Request(EXEC,
	"com.openexchange.service.indexing:type=indexingServiceMonitoring",
	"countStoredJobInfos");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "a.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(EXEC,
	"com.openexchange.service.indexing:type=indexingServiceMonitoring",
	"countLocalTriggers");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "b.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(EXEC,
	"com.openexchange.service.indexing:type=indexingServiceMonitoring",
	"countRunningJobs");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "c.value ",$response->value(),"\n";
}
