#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;

use LWP;
use JSON;

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
	print "yes\n";
	exit 0;
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
	print "graph_title Java Heap\n";
	print "graph_args --base 1024 -l 0\n";
	print "graph_category Open Xchange\n";
	print "graph_vlabel \n";
	print "a.label Old Gen\n";
	print "a.draw AREA\n";
	print "b.label Survivor\n";
	print "b.draw STACK\n";
	print "c.label Eden Space\n";
	print "c.draw STACK\n";
	print "d.label Java heap\n";
	print "d.draw AREA\n";
	exit 0
}

my $url = $ENV{oxJolokiaUrl};
my $username = $ENV{oxJolokiaUser};
my $password = $ENV{oxJolokiaPassword};

callUrlForUsageUsed("a","/read/java.lang:*,name=*Old Gen*,type=MemoryPool/Usage");
callUrlForUsageUsed("b","/read/java.lang:*,name=*Survivor*,type=MemoryPool/Usage");
callUrlForUsageUsed("c","/read/java.lang:*,name=*Eden*,type=MemoryPool/Usage");
callUrl("d","/read/java.lang:name=Java heap,type=MemoryPool/Usage/used");

sub callUrl {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url"."$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			print "$_[0]".".value ";
			print $json->{value},"\n";
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}

		print STDERR $response->status_line, "\n";
	}
}

sub callUrlForUsageUsed {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url"."$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			foreach my $val (values $json->{value}){
				print "$_[0]".".value ";
				print $val->{Usage}{used},"\n";
			}
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}

		print STDERR $response->status_line, "\n";
	}
}