#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;
use JMX::Jmx4Perl;
use JMX::Jmx4Perl::Request;   # Type constants are exported here

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
	print "yes\n";
	exit 0;
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
	print "graph_title Java non Heap\n";
	print "graph_args --base 1024 -l 0\n";
	print "graph_category Open Xchange\n";
	print "graph_vlabel bytes\n";
	print "a.label Code Cache\n";
	print "a.draw AREA\n";
	print "b.label Perm Gen\n";
	print "b.draw STACK\n";
	exit 0
}
									
### Settings and connection Testing

my $jmx = new JMX::Jmx4Perl(url => $ENV{oxJolokiaUrl},
user => $ENV{oxJolokiaUser},
password => $ENV{oxJolokiaPassword});

### test if a connection can be made
my $request = new JMX::Jmx4Perl::Request({type => AGENT_VERSION});
my $response = $jmx->request($request);
if ($response->is_error()){
	my $status = $response->status();
	if ($status == 404) {
		die "Link to servlet might be wrong";
	}
	elsif ($status == 401) {
		die "Credentials to login might be wrong";
	}
	else {
		die "Something went wrong ",$status;
	}
}

###

$request = new JMX::Jmx4Perl::Request(READ,
	"java.lang:name=Code Cache,type=MemoryPool",
	"Usage",
	"used");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "a.value ",$response->value(),"\n";
}

$request = new JMX::Jmx4Perl::Request(READ,
	"java.lang:name=CMS Perm Gen,type=MemoryPool",
	"Usage",
	"used");
$response = $jmx->request($request);
if ($response->is_ok()){
	print "b.value ",$response->value(),"\n";
}
