#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;

use LWP;
use JSON;

###
# Infos about Push Notification Service:
#   avg:      The number of submitted notifications per minute.
#   enqueued: The number of notifications that are currently submitted, but not yet processed
#   total:    Derivation of total notifications
###

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    if (-e "/opt/open-xchange/bundles/com.openexchange.pns.impl.jar") {
        print "yes\n";
        exit 0;
    }
    else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Push Notification Service\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel number of notifications\n";
    print "graph_period minute\n";
    
    print "enqueued.label enqueued notifications\n";
    
    print "avg.label notifications per minute\n";
    print "avg.draw AREA\n";

    print "total.label Push Notifications\n";
    print "total.draw LINE1\n";
    print "total.type DERIVE\n";
    print "total.min 0\n";

    exit 0
}

my $url = $ENV{oxJolokiaUrl};
my $username = $ENV{oxJolokiaUser};
my $password = $ENV{oxJolokiaPassword};

callUrl("avg","/read/com.openexchange.pns:name=PushNotificationMBean/NotificationsPerMinute");
callUrl("enqueued","/read/com.openexchange.pns:name=PushNotificationMBean/EnqueuedNotifications");
callUrl("total","/read/com.openexchange.pns:name=PushNotificationMBean/TotalNumberOfSubmittedNotifications");

sub callUrl {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			print "$_[0].value ";
			print $json->{value},"\n";
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}
	}
}