#!/usr/bin/perl
#%# family=auto
#%# capabilities=autoconf

use strict;

use LWP;
use JSON;

###
# Infos about Web Sockets:
#   count:                The number of open Web Sockets on target node.
#   buffered-messages:    The number of buffered messages that are supposed to be transmitted to remote cluster members. 
###

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    if (-e "/opt/open-xchange/bundles/com.openexchange.websockets.grizzly.jar") {
        print "yes\n";
        exit 0;
    }
    else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config") {
    print "graph_title Web Socket\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel Number\n";
    
    print "count.label count\n";
    print "count.draw LINE1\n";
    print "count.type GAUGE\n";
    print "count.min 0\n";
    
    print "buffered-message.label buffered-message\n";
    print "buffered-message.draw LINE1\n";
    print "buffered-message.type GAUGE\n";
    print "buffered-message.min 0\n";

    exit 0
}

my $url = $ENV{oxJolokiaUrl};
my $username = $ENV{oxJolokiaUser};
my $password = $ENV{oxJolokiaPassword};

callUrl("count","/read/com.openexchange.websockets:name=WebSocketMBean/NumberOfWebSockets");
callUrl("buffered-message","/read/com.openexchange.websockets:name=WebSocketMBean/NumberOfBufferedMessages");

sub callUrl {
	my $ua = LWP::UserAgent->new();
	my $req = HTTP::Request->new(GET => "$url$_[1]");
	$req->authorization_basic($username,$password);
	
	$req->header('Accept', => 'text/html');
	
	my $response = $ua->request($req);
	
	if ($response->is_success) {
		my $json = decode_json($response->decoded_content);
		if (defined $json->{value}){
			print "$_[0].value ";
			print $json->{value},"\n";
		}
	}
	else {
		my $status = $response->status_line;
		if ($status == 404) {
			die "Link to servlet might not be set correctly, this can be done by altering /etc/munin/plugin-conf.d/ox and setting the correct path to your jolokia servlet";
		}
		elsif ($status == 401) {
			die "Credentials to login might be not set correctly. The credentials are set inside /opt/open-xchange/etc/jolokia.properties on the OX, for munin, those need to be altered at /etc/munin/plugin-conf.d/ox";
		}
		else {
			die "Something went wrong:\n",$status;
		}
	}
}
