#! /usr/bin/php
<?php

include("ox-soap.php");

try {
	
	srand(microtime()*1000000);
	$random_id = rand(1, 99999);
	
	
	$res = new Resource();
	$res->name =  "ox_tests_resource_".$random_id;	
	$res->displayname = "OX Test Resource ".$random_id;	
	$res->email = "ox_tests_resource_".$random_id."@example.org";
	$res->description = "Test Resource Descrption by SOAP and PHP";
	$res->available = true;
	
	$result = getResourceClient($SOAPHOST)->create(getContextObject($CONTEXT_ID),$res, getCredentialsObject($CONTEXT_ADMIN,$CONTEXT_ADMIN_PASS));
	
	if (!is_soap_fault($result)) {
		$res->id = $result->id;
		$res->displayname = $res->displayname."_changed";
		$res->description = $res->description."_changed";
		$result = getResourceClient($SOAPHOST)->change(getContextObject($CONTEXT_ID),$res, getCredentialsObject($CONTEXT_ADMIN,$CONTEXT_ADMIN_PASS));
	}
	
} catch (SoapFault $fault) {
	handleSoapFault($fault);
} catch (Exception $e) {
	handleExcepion($e);
}
?>
