#! /bin/bash

DDIR=$1 || DDIR="/opt/open-xchange/sbin"

contextlist=$(<contextcltlist)
userlist=$(<usercltlist)
pushd $DDIR
for linkname in $contextlist; do
	if [ "$linkname" != "createcontext" ]; then
	    rm -f $linkname
	    ln -sf createcontext $linkname
	fi
done
for linkname in $userlist; do
	if [ "$linkname" != "createuser" ]; then
	    rm -f $linkname
	    ln -sf createuser $linkname
	fi
done
