#! /bin/bash

DDIR=$1 || DDIR="/opt/open-xchange/sbin"

COMMANDS="changequotacontext \
createcontext \
deletecontext \
disablecontext \
disableallcontexts \
enablecontext \
enableallcontexts \
movedatabasecontext \
movefilestorecontext \
searchcontext \
addreason \
editfilestore \
listdatabase \
listfilestore \
listreason \
listserver \
registerdatabase \
registerfilestore \
registerserver \
removereason \
unregisterdatabase \
unregisterfilestore \
unregisterserver \
updatedatabase"
pushd $DDIR
for linkname in $COMMANDS; do
    ln -sf cmdmuxer-plugin-hosting $linkname
done
for method in create delete change list; do
    for module in user group resource; do
	linkname="${method}${module}"
	rm -f $linkname
	ln -sf cmdmuxer $linkname
    done
done
