/*
 *
 *    OPEN-XCHANGE legal information
 *
 *    All intellectual property rights in the Software are protected by
 *    international copyright laws.
 *
 *
 *    In some countries OX, OX Open-Xchange, open xchange and OXtender
 *    as well as the corresponding Logos OX Open-Xchange and OX are registered
 *    trademarks of the OX Software GmbH group of companies.
 *    The use of the Logos is not covered by the GNU General Public License.
 *    Instead, you are allowed to use these Logos according to the terms and
 *    conditions of the Creative Commons License, Version 2.5, Attribution,
 *    Non-commercial, ShareAlike, and the interpretation of the term
 *    Non-commercial applicable to the aforementioned license is published
 *    on the web site http://www.open-xchange.com/EN/legal/index.html.
 *
 *    Please make sure that third-party modules and libraries are used
 *    according to their respective licenses.
 *
 *    Any modifications to this package must retain all copyright notices
 *    of the original copyright holder(s) for the original code used.
 *
 *    After any such modifications, the original and derivative code shall remain
 *    under the copyright of the copyright holder(s) and/or original author(s)per
 *    the Attribution and Assignment Agreement that can be located at
 *    http://www.open-xchange.com/EN/developer/. The contributing author shall be
 *    given Attribution for the derivative code and a license granting use.
 *
 *     Copyright (C) 2016-2020 OX Software GmbH
 *     Mail: info@open-xchange.com
 *
 *
 *     This program is free software; you can redistribute it and/or modify it
 *     under the terms of the GNU General Public License, Version 2 as published
 *     by the Free Software Foundation.
 *
 *     This program is distributed in the hope that it will be useful, but
 *     WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *     or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *     for more details.
 *
 *     You should have received a copy of the GNU General Public License along
 *     with this program; if not, write to the Free Software Foundation, Inc., 59
 *     Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */

package com.openexchange.grizzly;

import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpMethod;
import org.apache.commons.httpclient.methods.GetMethod;
import org.junit.Test;
import com.openexchange.ajax.simple.AbstractSimpleClientTest;
import com.openexchange.ajax.simple.SimpleOXClient;


/**
 * {@link MaxHttpHeaderSizeTest} - Check that we can add a header of around 10kB to our simple get request. This will fail unless Apache and
 * Grizzly are configured to allow enourmous header sizes, see grizzly.properties for more infos.
 *
 * @author <a href="mailto:marc.arens@open-xchange.com">Marc Arens</a>
 * @since v7.8.0
 */
public class MaxHttpHeaderSizeTest extends AbstractSimpleClientTest {

    private String bigValue="TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAA"
        + "AAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAA"
        + "AAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAA"
        + "AAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAA"
        + "AAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw";

    @Test
    public void test() throws Exception {
        SimpleOXClient oxClient = createClient();
        HttpClient httpClient = oxClient.getClient();
        Header bigHeader= new Header("bigheader", bigValue);
        HttpMethod getPing = new GetMethod("/servlet/Ping");
        getPing.addRequestHeader(bigHeader);
        int status = httpClient.executeMethod(getPing);
        assertEquals(200, status);
    }

}
