/*
 * @copyright Copyright (c) OX Software GmbH, Germany <info@open-xchange.com>
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with OX App Suite.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
 *
 * Any use of the work other than as authorized under this license or copyright law is prohibited.
 *
 */

package com.openexchange.grizzly;

import static org.junit.Assert.assertEquals;
import org.apache.commons.httpclient.Header;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpMethod;
import org.apache.commons.httpclient.methods.GetMethod;
import org.junit.Test;
import com.openexchange.ajax.simple.AbstractSimpleClientTest;
import com.openexchange.ajax.simple.SimpleOXClient;

/**
 * {@link MaxHttpHeaderSizeTest} - Check that we can add a header of around 10kB to our simple get request. This will fail unless Apache and
 * Grizzly are configured to allow enourmous header sizes, see grizzly.properties for more infos.
 *
 * @author <a href="mailto:marc.arens@open-xchange.com">Marc Arens</a>
 * @since v7.8.0
 */
public class MaxHttpHeaderSizeTest extends AbstractSimpleClientTest {

    private String bigValue="TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAA"
        + "AAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAA"
        + "AAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAA"
        + "AAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAA"
        + "AAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTl"
        + "RMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4g"
        + "AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAA"
        + "AGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNT"
        + "UAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAA"
        + "AAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEd"
        + "AAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAA"
        + "AAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw==AAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw"
        + "TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II"
        + "4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAA"
        + "AAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTV"
        + "NTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAA"
        + "AAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAb"
        + "EdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAAB"
        + "AAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAA"
        + "AAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAA"
        + "DwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4"
        + "II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAA"
        + "AAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRM"
        + "TVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAA"
        + "AAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAG"
        + "AbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUA"
        + "ABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAA"
        + "AAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAA"
        + "AADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADwTlRMTVNTUAABAAAA"
        + "l4II4gAAAAAAAAAAAAAAAAAAAAAGAbEdAAAADw";

    @Test
    public void test() throws Exception {
        SimpleOXClient oxClient = createClient();
        HttpClient httpClient = oxClient.getClient();
        Header bigHeader = new Header("bigheader", bigValue);
        HttpMethod getPing = new GetMethod("/servlet/Ping");
        getPing.addRequestHeader(bigHeader);
        int status = httpClient.executeMethod(getPing);
        assertEquals(200, status);
    }

}
