define("io.ox/dev/testing/jasmine",function(){var a,b,c,d,e,f,g,h,i,j,k,l={},m=!0,n={};return m&&(l.jasmine=n),n.unimplementedMethod_=function(){throw new Error("unimplemented method")},n.undef=n.___undefined___,n.VERBOSE=!1,n.DEFAULT_UPDATE_INTERVAL=250,n.DEFAULT_TIMEOUT_INTERVAL=5e3,n.getGlobal=function(){function a(){return this}return a()},n.bindOriginal_=function(a,b){var c=a[b];if(c.apply)return function(){return c.apply(a,arguments)};else return n.getGlobal()[b]},n.setTimeout=n.bindOriginal_
(n.getGlobal(),"setTimeout"),n.clearTimeout=n.bindOriginal_(n.getGlobal(),"clearTimeout"),n.setInterval=n.bindOriginal_(n.getGlobal(),"setInterval"),n.clearInterval=n.bindOriginal_(n.getGlobal(),"clearInterval"),n.MessageResult=function(a){this.type="log",this.values=a,this.trace=new Error},n.MessageResult.prototype.toString=function(){var a,b="";for(a=0;a<this.values.length;a++)a>0&&(b+=" "),n.isString_(this.values[a])?b+=this.values[a]:b+=n.pp(this.values[a]);return b},n.ExpectationResult=function(
a){var b;this.type="expect",this.matcherName=a.matcherName,this.passed_=a.passed,this.expected=a.expected,this.actual=a.actual,this.message=this.passed_?"Passed.":a.message,b=a.trace||new Error(this.message),this.trace=this.passed_?"":b},n.ExpectationResult.prototype.toString=function(){return this.message},n.ExpectationResult.prototype.passed=function(){return this.passed_},n.getEnv=function(){var a=n.currentEnv_=n.currentEnv_||new n.Env;return a},n.isArray_=function(a){return n.isA_("Array",a)}
,n.isString_=function(a){return n.isA_("String",a)},n.isNumber_=function(a){return n.isA_("Number",a)},n.isA_=function(a,b){return Object.prototype.toString.apply(b)==="[object "+a+"]"},n.pp=function(a){var b=new n.StringPrettyPrinter;return b.format(a),b.string},n.isDomNode=function(a){return a.nodeType>0},n.any=function(a){return new n.Matchers.Any(a)},n.Spy=function(a){this.identity=a||"unknown",this.isSpy=!0,this.plan=function(){},this.mostRecentCall={},this.argsForCall=[],this.calls=[]},n.Spy
.prototype.andCallThrough=function(){return this.plan=this.originalValue,this},n.Spy.prototype.andReturn=function(a){return this.plan=function(){return a},this},n.Spy.prototype.andThrow=function(a){return this.plan=function(){throw a},this},n.Spy.prototype.andCallFake=function(a){return this.plan=a,this},n.Spy.prototype.reset=function(){this.wasCalled=!1,this.callCount=0,this.argsForCall=[],this.calls=[],this.mostRecentCall={}},n.createSpy=function(a){var b,c=function(){c.wasCalled=!0,c.callCount++
;var a=n.util.argsToArray(arguments);return c.mostRecentCall.object=this,c.mostRecentCall.args=a,c.argsForCall.push(a),c.calls.push({object:this,args:a}),c.plan.apply(this,arguments)},d=new n.Spy(a);for(b in d)c[b]=d[b];return c.reset(),c},n.isSpy=function(a){return a&&a.isSpy},n.createSpyObj=function(a,b){var c,d;if(!n.isArray_(b)||b.length===0)throw new Error("createSpyObj requires a non-empty array of method names to create spies for");c={};for(d=0;d<b.length;d++)c[b[d]]=n.createSpy(a+"."+b[d]
);return c},n.log=function(){var a=n.getEnv().currentSpec;a.log.apply(a,arguments)},a=function(a,b){return n.getEnv().currentSpec.spyOn(a,b)},m&&(l.spyOn=a),b=function(a,b){return n.getEnv().it(a,b)},m&&(l.it=b),c=function(a,b){return n.getEnv().xit(a,b)},m&&(l.xit=c),d=function(a){return n.getEnv().currentSpec.expect(a)},m&&(l.expect=d),e=function(a){n.getEnv().currentSpec.runs(a)},m&&(l.runs=e),f=function(a){n.getEnv().currentSpec.waits(a)},m&&(l.waits=f),g=function(a,b,c){n.getEnv().currentSpec
.waitsFor.apply(n.getEnv().currentSpec,arguments)},m&&(l.waitsFor=g),h=function(a){n.getEnv().beforeEach(a)},m&&(l.beforeEach=h),i=function(a){n.getEnv().afterEach(a)},m&&(l.afterEach=i),j=function(a,b){return n.getEnv().describe(a,b)},m&&(l.describe=j),k=function(a,b){return n.getEnv().xdescribe(a,b)},m&&(l.xdescribe=k),n.XmlHttpRequest=typeof XMLHttpRequest=="undefined"?function(){var a;function b(a){try{return a()}catch(b){}return null}a=b(function(){return new ActiveXObject("Msxml2.XMLHTTP.6.0"
)})||b(function(){return new ActiveXObject("Msxml2.XMLHTTP.3.0")})||b(function(){return new ActiveXObject("Msxml2.XMLHTTP")})||b(function(){return new ActiveXObject("Microsoft.XMLHTTP")});if(!a)throw new Error("This browser does not support XMLHttpRequest.");return a}:XMLHttpRequest,n.util={},n.util.inherit=function(a,b){var c=function(){};c.prototype=b.prototype,a.prototype=new c},n.util.formatException=function(a){var b,c,d;return a.line?b=a.line:a.lineNumber&&(b=a.lineNumber),a.sourceURL?c=a.sourceURL
:a.fileName&&(c=a.fileName),d=a.name&&a.message?a.name+": "+a.message:a.toString(),c&&b&&(d+=" in "+c+" (line "+b+")"),d},n.util.htmlEscape=function(a){if(!a)return a;return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},n.util.argsToArray=function(a){var b,c=[];for(b=0;b<a.length;b++)c.push(a[b]);return c},n.util.extend=function(a,b){var c;for(c in b)a[c]=b[c];return a},n.Env=function(){this.currentSpec=null,this.currentSuite=null,this.currentRunner_=new n.Runner(this),this.reporter=new 
n.MultiReporter,this.updateInterval=n.DEFAULT_UPDATE_INTERVAL,this.defaultTimeoutInterval=n.DEFAULT_TIMEOUT_INTERVAL,this.lastUpdate=0,this.specFilter=function(){return!0},this.nextSpecId_=0,this.nextSuiteId_=0,this.equalityTesters_=[],this.matchersClass=function(){n.Matchers.apply(this,arguments)},n.util.inherit(this.matchersClass,n.Matchers),n.Matchers.wrapInto_(n.Matchers.prototype,this.matchersClass)},n.Env.prototype.setTimeout=n.setTimeout,n.Env.prototype.clearTimeout=n.clearTimeout,n.Env.prototype
.setInterval=n.setInterval,n.Env.prototype.clearInterval=n.clearInterval,n.Env.prototype.version=function(){if(n.version_)return n.version_;else throw new Error("Version not set")},n.Env.prototype.versionString=function(){var a,b;if(!n.version_)return"version unknown";return a=this.version(),b=a.major+"."+a.minor+"."+a.build,a.release_candidate&&(b+=".rc"+a.release_candidate),b+=" revision "+a.revision,b},n.Env.prototype.nextSpecId=function(){return this.nextSpecId_++},n.Env.prototype.nextSuiteId=
function(){return this.nextSuiteId_++},n.Env.prototype.addReporter=function(a){this.reporter.addReporter(a)},n.Env.prototype.execute=function(){this.currentRunner_.execute()},n.Env.prototype.describe=function(a,b){var c,d=new n.Suite(this,a,b,this.currentSuite),e=this.currentSuite;e?e.add(d):this.currentRunner_.add(d),this.currentSuite=d,c=null;try{b.call(d)}catch(f){c=f}return c&&this.it("encountered a declaration exception",function(){throw c}),this.currentSuite=e,d},n.Env.prototype.beforeEach=
function(a){this.currentSuite?this.currentSuite.beforeEach(a):this.currentRunner_.beforeEach(a)},n.Env.prototype.currentRunner=function(){return this.currentRunner_},n.Env.prototype.afterEach=function(a){this.currentSuite?this.currentSuite.afterEach(a):this.currentRunner_.afterEach(a)},n.Env.prototype.xdescribe=function(){return{execute:function(){}}},n.Env.prototype.it=function(a,b){var c=new n.Spec(this,this.currentSuite,a);return this.currentSuite.add(c),this.currentSpec=c,b&&c.runs(b),c},n.Env
.prototype.xit=function(){return{id:this.nextSpecId(),runs:function(){}}},n.Env.prototype.compareObjects_=function(a,b,c,d){var e,f;if(a.__Jasmine_been_here_before__===b&&b.__Jasmine_been_here_before__===a)return!0;a.__Jasmine_been_here_before__=b,b.__Jasmine_been_here_before__=a,e=function(a,b){return a!==null&&a[b]!==n.undef};for(f in b)!e(a,f)&&e(b,f)&&c.push("expected has key '"+f+"', but missing from actual.");for(f in a)!e(b,f)&&e(a,f)&&c.push("expected missing key '"+f+"', but present in actual."
);for(f in b){if(f==="__Jasmine_been_here_before__")continue;this.equals_(a[f],b[f],c,d)||d.push("'"+f+"' was '"+(b[f]?n.util.htmlEscape(b[f].toString()):b[f])+"' in expected, but was '"+(a[f]?n.util.htmlEscape(a[f].toString()):a[f])+"' in actual.")}return n.isArray_(a)&&n.isArray_(b)&&a.length!==b.length&&d.push("arrays were not the same length"),delete a.__Jasmine_been_here_before__,delete b.__Jasmine_been_here_before__,c.length===0&&d.length===0},n.Env.prototype.equals_=function(a,b,c,d){var e
,f,g;c=c||[],d=d||[];for(e=0;e<this.equalityTesters_.length;e++){f=this.equalityTesters_[e],g=f(a,b,this,c,d);if(g!==n.undef)return g}if(a===b)return!0;if(a===n.undef||a===null||b===n.undef||b===null)return a===n.undef&&b===n.undef;if(n.isDomNode(a)&&n.isDomNode(b))return a===b;if(a instanceof Date&&b instanceof Date)return a.getTime()===b.getTime();if(a instanceof n.Matchers.Any)return a.matches(b);if(b instanceof n.Matchers.Any)return b.matches(a);if(n.isString_(a)&&n.isString_(b))return a===b;
if(n.isNumber_(a)&&n.isNumber_(b))return a===b;if(typeof a=="object"&&typeof b=="object")return this.compareObjects_(a,b,c,d);return a===b},n.Env.prototype.contains_=function(a,b){var c;if(n.isArray_(a)){for(c=0;c<a.length;c++)if(this.equals_(a[c],b))return!0;return!1}return a.indexOf(b)>=0},n.Env.prototype.addEqualityTester=function(a){this.equalityTesters_.push(a)},n.Reporter=function(){},n.Reporter.prototype.reportRunnerStarting=function(){},n.Reporter.prototype.reportRunnerResults=function(){
},n.Reporter.prototype.reportSuiteResults=function(){},n.Reporter.prototype.reportSpecStarting=function(){},n.Reporter.prototype.reportSpecResults=function(){},n.Reporter.prototype.log=function(){},n.Block=function(a,b,c){this.env=a,this.func=b,this.spec=c},n.Block.prototype.execute=function(a){try{this.func.apply(this.spec)}catch(b){this.spec.fail(b)}a()},n.JsApiReporter=function(){this.started=!1,this.finished=!1,this.suites_=[],this.results_={}},n.JsApiReporter.prototype.reportRunnerStarting=function(
a){var b,c,d;this.started=!0,b=a.topLevelSuites();for(c=0;c<b.length;c++)d=b[c],this.suites_.push(this.summarize_(d))},n.JsApiReporter.prototype.suites=function(){return this.suites_},n.JsApiReporter.prototype.summarize_=function(a){var b,c,d=a instanceof n.Suite,e={id:a.id,name:a.description,type:d?"suite":"spec",children:[]};if(d){b=a.children();for(c=0;c<b.length;c++)e.children.push(this.summarize_(b[c]))}return e},n.JsApiReporter.prototype.results=function(){return this.results_},n.JsApiReporter
.prototype.resultsForSpec=function(a){return this.results_[a]},n.JsApiReporter.prototype.reportRunnerResults=function(){this.finished=!0},n.JsApiReporter.prototype.reportSuiteResults=function(){},n.JsApiReporter.prototype.reportSpecResults=function(a){this.results_[a.id]={messages:a.results().getItems(),result:a.results().failedCount>0?"failed":"passed"}},n.JsApiReporter.prototype.log=function(){},n.JsApiReporter.prototype.resultsForSpecs=function(a){var b,c,d={};for(b=0;b<a.length;b++)c=a[b],d[c
]=this.summarizeResult_(this.results_[c]);return d},n.JsApiReporter.prototype.summarizeResult_=function(a){var b,c,d=[],e=a.messages.length;for(b=0;b<e;b++)c=a.messages[b],d.push({text:c.type==="log"?c.toString():n.undef,passed:c.passed?c.passed():!0,type:c.type,message:c.message,trace:{stack:c.passed&&!c.passed()?c.trace.stack:n.undef}});return{result:a.result,messages:d}},n.Matchers=function(a,b,c,d){this.env=a,this.actual=b,this.spec=c,this.isNot=d||!1,this.reportWasCalled_=!1},n.Matchers.pp=function(
){throw new Error("jasmine.Matchers.pp() is no longer supported, please use jasmine.pp() instead!")},n.Matchers.prototype.report=function(){throw new Error("As of jasmine 0.11, custom matchers must be implemented differently -- please see jasmine docs")},n.Matchers.wrapInto_=function(a,b){var c,d;for(c in a){if(c==="report")continue;d=a[c],b.prototype[c]=n.Matchers.matcherFn_(c,d)}},n.Matchers.matcherFn_=function(a,b){return function(){var c,d,e,f,g=n.util.argsToArray(arguments),h=b.apply(this,arguments
);this.isNot&&(h=!h);if(this.reportWasCalled_)return h;if(!h)if(this.message)c=this.message.apply(this,arguments),n.isArray_(c)&&(c=c[this.isNot?1:0]);else{d=a.replace(/[A-Z]/g,function(a){return" "+a.toLowerCase()}),c="Expected "+n.pp(this.actual)+(this.isNot?" not ":" ")+d;if(g.length>0)for(e=0;e<g.length;e++)e>0&&(c+=","),c+=" "+n.pp(g[e]);c+="."}return f=new n.ExpectationResult({matcherName:a,passed:h,expected:g.length>1?g:g[0],actual:this.actual,message:c}),this.spec.addMatcherResult(f),n.undef
}},n.Matchers.prototype.toBe=function(a){return this.actual===a},n.Matchers.prototype.toNotBe=function(a){return this.actual!==a},n.Matchers.prototype.toEqual=function(a){return this.env.equals_(this.actual,a)},n.Matchers.prototype.toNotEqual=function(a){return!this.env.equals_(this.actual,a)},n.Matchers.prototype.toMatch=function(a){return(new RegExp(a)).test(this.actual)},n.Matchers.prototype.toNotMatch=function(a){return!(new RegExp(a)).test(this.actual)},n.Matchers.prototype.toBeDefined=function(
){return this.actual!==n.undef},n.Matchers.prototype.toBeUndefined=function(){return this.actual===n.undef},n.Matchers.prototype.toBeNull=function(){return this.actual===null},n.Matchers.prototype.toBeTruthy=function(){return!!this.actual},n.Matchers.prototype.toBeFalsy=function(){return!this.actual},n.Matchers.prototype.toHaveBeenCalled=function(){if(arguments.length>0)throw new Error("toHaveBeenCalled does not take arguments, use toHaveBeenCalledWith");if(!n.isSpy(this.actual))throw new Error("Expected a spy, but got "+
n.pp(this.actual)+".");return this.message=function(){return["Expected spy "+this.actual.identity+" to have been called.","Expected spy "+this.actual.identity+" not to have been called."]},this.actual.wasCalled},n.Matchers.prototype.wasCalled=n.Matchers.prototype.toHaveBeenCalled,n.Matchers.prototype.wasNotCalled=function(){if(arguments.length>0)throw new Error("wasNotCalled does not take arguments");if(!n.isSpy(this.actual))throw new Error("Expected a spy, but got "+n.pp(this.actual)+".");return this
.message=function(){return["Expected spy "+this.actual.identity+" to not have been called.","Expected spy "+this.actual.identity+" to have been called."]},!this.actual.wasCalled},n.Matchers.prototype.toHaveBeenCalledWith=function(){var a=n.util.argsToArray(arguments);if(!n.isSpy(this.actual))throw new Error("Expected a spy, but got "+n.pp(this.actual)+".");return this.message=function(){if(this.actual.callCount===0)return["Expected spy "+this.actual.identity+" to have been called with "+n.pp(a)+" but it was never called."
,"Expected spy "+this.actual.identity+" not to have been called with "+n.pp(a)+" but it was."];else return["Expected spy "+this.actual.identity+" to have been called with "+n.pp(a)+" but was called with "+n.pp(this.actual.argsForCall),"Expected spy "+this.actual.identity+" not to have been called with "+n.pp(a)+" but was called with "+n.pp(this.actual.argsForCall)]},this.env.contains_(this.actual.argsForCall,a)},n.Matchers.prototype.wasCalledWith=n.Matchers.prototype.toHaveBeenCalledWith,n.Matchers
.prototype.wasNotCalledWith=function(){var a=n.util.argsToArray(arguments);if(!n.isSpy(this.actual))throw new Error("Expected a spy, but got "+n.pp(this.actual)+".");return this.message=function(){return["Expected spy not to have been called with "+n.pp(a)+" but it was","Expected spy to have been called with "+n.pp(a)+" but it was"]},!this.env.contains_(this.actual.argsForCall,a)},n.Matchers.prototype.toContain=function(a){return this.env.contains_(this.actual,a)},n.Matchers.prototype.toNotContain=
function(a){return!this.env.contains_(this.actual,a)},n.Matchers.prototype.toBeLessThan=function(a){return this.actual<a},n.Matchers.prototype.toBeGreaterThan=function(a){return this.actual>a},n.Matchers.prototype.toBeCloseTo=function(a,b){var c,d;return b!==0&&(b=b||2),c=Math.pow(10,b),d=Math.round(this.actual*c),a=Math.round(a*c),a===d},n.Matchers.prototype.toThrow=function(a){var b,c,d=!1;if(typeof this.actual!="function")throw new Error("Actual is not a function");try{this.actual()}catch(e){b=
e}return b&&(d=a===n.undef||this.env.equals_(b.message||b,a.message||a)),c=this.isNot?"not ":"",this.message=function(){if(b&&(a===n.undef||!this.env.equals_(b.message||b,a.message||a)))return["Expected function "+c+"to throw",a?a.message||a:"an exception",", but it threw",b.message||b].join(" ");else return"Expected function to throw an exception."},d},n.Matchers.Any=function(a){this.expectedClass=a},n.Matchers.Any.prototype.matches=function(a){if(this.expectedClass===String)return typeof a=="string"||
a instanceof String;if(this.expectedClass===Number)return typeof a=="number"||a instanceof Number;if(this.expectedClass===Function)return typeof a=="function"||a instanceof Function;if(this.expectedClass===Object)return typeof a=="object";return a instanceof this.expectedClass},n.Matchers.Any.prototype.toString=function(){return"<jasmine.any("+this.expectedClass+")>"},n.MultiReporter=function(){this.subReporters_=[]},n.util.inherit(n.MultiReporter,n.Reporter),n.MultiReporter.prototype.addReporter=
function(a){this.subReporters_.push(a)},function(){var a,b,c=["reportRunnerStarting","reportRunnerResults","reportSuiteResults","reportSpecStarting","reportSpecResults","log"],d=function(a){return function(){for(var b=0;b<this.subReporters_.length;b++){var c=this.subReporters_[b];c[a]&&c[a].apply(c,arguments)}}};for(a=0;a<c.length;a++)b=c[a],n.MultiReporter.prototype[b]=d(b)}(),n.NestedResults=function(){this.totalCount=0,this.passedCount=0,this.failedCount=0,this.skipped=!1,this.items_=[]},n.NestedResults
.prototype.rollupCounts=function(a){this.totalCount+=a.totalCount,this.passedCount+=a.passedCount,this.failedCount+=a.failedCount},n.NestedResults.prototype.log=function(a){this.items_.push(new n.MessageResult(a))},n.NestedResults.prototype.getItems=function(){return this.items_},n.NestedResults.prototype.addResult=function(a){a.type!=="log"&&(a.items_?this.rollupCounts(a):(this.totalCount++,a.passed()?this.passedCount++:this.failedCount++)),this.items_.push(a)},n.NestedResults.prototype.passed=function(
){return this.passedCount===this.totalCount},n.PrettyPrinter=function(){this.ppNestLevel_=0},n.PrettyPrinter.prototype.format=function(a){if(this.ppNestLevel_>40)throw new Error("jasmine.PrettyPrinter: format() nested too deeply!");this.ppNestLevel_++;try{a===n.undef?this.emitScalar("undefined"):a===null?this.emitScalar("null"):a===n.getGlobal()?this.emitScalar("<global>"):a instanceof n.Matchers.Any?this.emitScalar(a.toString()):typeof a=="string"?this.emitString(a):n.isSpy(a)?this.emitScalar("spy on "+
a.identity):a instanceof RegExp?this.emitScalar(a.toString()):typeof a=="function"?this.emitScalar("Function"):typeof a.nodeType=="number"?this.emitScalar("HTMLNode"):a instanceof Date?this.emitScalar("Date("+a+")"):a.__Jasmine_been_here_before__?this.emitScalar("<circular reference: "+(n.isArray_(a)?"Array":"Object")+">"):n.isArray_(a)||typeof a=="object"?(a.__Jasmine_been_here_before__=!0,n.isArray_(a)?this.emitArray(a):this.emitObject(a),delete a.__Jasmine_been_here_before__):this.emitScalar(a
.toString())}finally{this.ppNestLevel_--}},n.PrettyPrinter.prototype.iterateObject=function(a,b){var c;for(c in a){if(c==="__Jasmine_been_here_before__")continue;b(c,a.__lookupGetter__?a.__lookupGetter__(c)!==n.undef&&a.__lookupGetter__(c)!==null:!1)}},n.PrettyPrinter.prototype.emitArray=n.unimplementedMethod_,n.PrettyPrinter.prototype.emitObject=n.unimplementedMethod_,n.PrettyPrinter.prototype.emitScalar=n.unimplementedMethod_,n.PrettyPrinter.prototype.emitString=n.unimplementedMethod_,n.StringPrettyPrinter=
function(){n.PrettyPrinter.call(this),this.string=""},n.util.inherit(n.StringPrettyPrinter,n.PrettyPrinter),n.StringPrettyPrinter.prototype.emitScalar=function(a){this.append(a)},n.StringPrettyPrinter.prototype.emitString=function(a){this.append("'"+a+"'")},n.StringPrettyPrinter.prototype.emitArray=function(a){var b;this.append("[ ");for(b=0;b<a.length;b++)b>0&&this.append(", "),this.format(a[b]);this.append(" ]")},n.StringPrettyPrinter.prototype.emitObject=function(a){var b,c=this;this.append("{ "
),b=!0,this.iterateObject(a,function(d,e){b?b=!1:c.append(", "),c.append(d),c.append(" : "),e?c.append("<getter>"):c.format(a[d])}),this.append(" }")},n.StringPrettyPrinter.prototype.append=function(a){this.string+=a},n.Queue=function(a){this.env=a,this.blocks=[],this.running=!1,this.index=0,this.offset=0,this.abort=!1},n.Queue.prototype.addBefore=function(a){this.blocks.unshift(a)},n.Queue.prototype.add=function(a){this.blocks.push(a)},n.Queue.prototype.insertNext=function(a){this.blocks.splice(
this.index+this.offset+1,0,a),this.offset++},n.Queue.prototype.start=function(a){this.running=!0,this.onComplete=a,this.next_()},n.Queue.prototype.isRunning=function(){return this.running},n.Queue.LOOP_DONT_RECURSE=!0,n.Queue.prototype.next_=function(){var a=this,b=!0,c=!0,d=!1,e=function(){if(n.Queue.LOOP_DONT_RECURSE&&c){d=!0;return}a.blocks[a.index].abort&&(a.abort=!0),a.offset=0,a.index++;var e=(new Date).getTime();a.env.updateInterval&&e-a.env.lastUpdate>a.env.updateInterval?(a.env.lastUpdate=
e,a.env.setTimeout(function(){a.next_()},0)):n.Queue.LOOP_DONT_RECURSE&&d?b=!0:a.next_()};while(b)b=!1,c=!0,d=!1,a.index<a.blocks.length&&!this.abort?(a.blocks[a.index].execute(e),c=!1,d&&e()):(a.running=!1,a.onComplete&&a.onComplete())},n.Queue.prototype.results=function(){var a,b=new n.NestedResults;for(a=0;a<this.blocks.length;a++)this.blocks[a].results&&b.addResult(this.blocks[a].results());return b},n.Runner=function(a){var b=this;b.env=a,b.queue=new n.Queue(a),b.before_=[],b.after_=[],b.suites_=
[]},n.Runner.prototype.execute=function(){var a=this;a.env.reporter.reportRunnerStarting&&a.env.reporter.reportRunnerStarting(this),a.queue.start(function(){a.finishCallback()})},n.Runner.prototype.beforeEach=function(a){a.typeName="beforeEach",this.before_.splice(0,0,a)},n.Runner.prototype.afterEach=function(a){a.typeName="afterEach",this.after_.splice(0,0,a)},n.Runner.prototype.finishCallback=function(){this.env.reporter.reportRunnerResults(this)},n.Runner.prototype.addSuite=function(a){this.suites_
.push(a)},n.Runner.prototype.add=function(a){a instanceof n.Suite&&this.addSuite(a),this.queue.add(a)},n.Runner.prototype.specs=function(){var a,b=this.suites(),c=[];for(a=0;a<b.length;a++)c=c.concat(b[a].specs());return c},n.Runner.prototype.suites=function(){return this.suites_},n.Runner.prototype.topLevelSuites=function(){var a,b=[];for(a=0;a<this.suites_.length;a++)this.suites_[a].parentSuite||b.push(this.suites_[a]);return b},n.Runner.prototype.results=function(){return this.queue.results()}
,n.Spec=function(a,b,c){var d;if(!a)throw new Error("jasmine.Env() required");if(!b)throw new Error("jasmine.Suite() required");d=this,d.id=a.nextSpecId?a.nextSpecId():null,d.env=a,d.suite=b,d.description=c,d.queue=new n.Queue(a),d.afterCallbacks=[],d.spies_=[],d.results_=new n.NestedResults,d.results_.description=c,d.matchersClass=null},n.Spec.prototype.getFullName=function(){return this.suite.getFullName()+" "+this.description+"."},n.Spec.prototype.results=function(){return this.results_},n.Spec
.prototype.log=function(){return this.results_.log(arguments)},n.Spec.prototype.runs=function(a){var b=new n.Block(this.env,a,this);return this.addToQueue(b),this},n.Spec.prototype.addToQueue=function(a){this.queue.isRunning()?this.queue.insertNext(a):this.queue.add(a)},n.Spec.prototype.addMatcherResult=function(a){this.results_.addResult(a)},n.Spec.prototype.expect=function(a){var b=new(this.getMatchersClass_())(this.env,a,this);return b.not=new(this.getMatchersClass_())(this.env,a,this,!0),b},n
.Spec.prototype.waits=function(a){var b=new n.WaitsBlock(this.env,a,this);return this.addToQueue(b),this},n.Spec.prototype.waitsFor=function(){var a,b,c,d=null,e=null,f=null;for(a=0;a<arguments.length;a++){b=arguments[a];switch(typeof b){case"function":d=b;break;case"string":e=b;break;case"number":f=b}}return c=new n.WaitsForBlock(this.env,f,d,e,this),this.addToQueue(c),this},n.Spec.prototype.fail=function(a){var b=new n.ExpectationResult({passed:!1,message:a?n.util.formatException(a):"Exception"
,trace:{stack:a.stack}});this.results_.addResult(b)},n.Spec.prototype.getMatchersClass_=function(){return this.matchersClass||this.env.matchersClass},n.Spec.prototype.addMatchers=function(a){var b=this.getMatchersClass_(),c=function(){b.apply(this,arguments)};n.util.inherit(c,b),n.Matchers.wrapInto_(a,c),this.matchersClass=c},n.Spec.prototype.finishCallback=function(){this.env.reporter.reportSpecResults(this)},n.Spec.prototype.finish=function(a){this.removeAllSpies(),this.finishCallback(),a&&a()}
,n.Spec.prototype.after=function(a){this.queue.isRunning()?this.queue.add(new n.Block(this.env,a,this)):this.afterCallbacks.unshift(a)},n.Spec.prototype.execute=function(a){var b=this;if(!b.env.specFilter(b)){b.results_.skipped=!0,b.finish(a);return}this.env.reporter.reportSpecStarting(this),b.env.currentSpec=b,b.addBeforesAndAftersToQueue(),b.queue.start(function(){b.finish(a)})},n.Spec.prototype.addBeforesAndAftersToQueue=function(){var a,b,c=this.env.currentRunner();for(b=this.suite;b;b=b.parentSuite
)for(a=0;a<b.before_.length;a++)this.queue.addBefore(new n.Block(this.env,b.before_[a],this));for(a=0;a<c.before_.length;a++)this.queue.addBefore(new n.Block(this.env,c.before_[a],this));for(a=0;a<this.afterCallbacks.length;a++)this.queue.add(new n.Block(this.env,this.afterCallbacks[a],this));for(b=this.suite;b;b=b.parentSuite)for(a=0;a<b.after_.length;a++)this.queue.add(new n.Block(this.env,b.after_[a],this));for(a=0;a<c.after_.length;a++)this.queue.add(new n.Block(this.env,c.after_[a],this))},n
.Spec.prototype.explodes=function(){throw"explodes function should not have been called"},n.Spec.prototype.spyOn=function(a,b,c){var d;if(a===n.undef)throw"spyOn could not find an object to spy upon for "+b+"()";if(!c&&a[b]===n.undef)throw b+"() method does not exist";if(!c&&a[b]&&a[b].isSpy)throw new Error(b+" has already been spied upon");return d=n.createSpy(b),this.spies_.push(d),d.baseObj=a,d.methodName=b,d.originalValue=a[b],a[b]=d,d},n.Spec.prototype.removeAllSpies=function(){var a,b;for(a=0
;a<this.spies_.length;a++)b=this.spies_[a],b.baseObj[b.methodName]=b.originalValue;this.spies_=[]},n.Suite=function(a,b,c,d){var e=this;e.id=a.nextSuiteId?a.nextSuiteId():null,e.description=b,e.queue=new n.Queue(a),e.parentSuite=d,e.env=a,e.before_=[],e.after_=[],e.children_=[],e.suites_=[],e.specs_=[]},n.Suite.prototype.getFullName=function(){var a,b=this.description;for(a=this.parentSuite;a;a=a.parentSuite)b=a.description+" "+b;return b},n.Suite.prototype.finish=function(a){this.env.reporter.reportSuiteResults
(this),this.finished=!0,typeof a=="function"&&a()},n.Suite.prototype.beforeEach=function(a){a.typeName="beforeEach",this.before_.unshift(a)},n.Suite.prototype.afterEach=function(a){a.typeName="afterEach",this.after_.unshift(a)},n.Suite.prototype.results=function(){return this.queue.results()},n.Suite.prototype.add=function(a){this.children_.push(a),a instanceof n.Suite?(this.suites_.push(a),this.env.currentRunner().addSuite(a)):this.specs_.push(a),this.queue.add(a)},n.Suite.prototype.specs=function(
){return this.specs_},n.Suite.prototype.suites=function(){return this.suites_},n.Suite.prototype.children=function(){return this.children_},n.Suite.prototype.execute=function(a){var b=this;this.queue.start(function(){b.finish(a)})},n.WaitsBlock=function(a,b,c){this.timeout=b,n.Block.call(this,a,null,c)},n.util.inherit(n.WaitsBlock,n.Block),n.WaitsBlock.prototype.execute=function(a){n.VERBOSE&&this.env.reporter.log(">> Jasmine waiting for "+this.timeout+" ms..."),this.env.setTimeout(function(){a()
},this.timeout)},n.WaitsForBlock=function(a,b,c,d,e){this.timeout=b||a.defaultTimeoutInterval,this.latchFunction=c,this.message=d,this.totalTimeSpentWaitingForLatch=0,n.Block.call(this,a,null,e)},n.util.inherit(n.WaitsForBlock,n.Block),n.WaitsForBlock.TIMEOUT_INCREMENT=10,n.WaitsForBlock.prototype.execute=function(a){var b,c,d;n.VERBOSE&&this.env.reporter.log(">> Jasmine waiting for "+(this.message||"something to happen"));try{b=this.latchFunction.apply(this.spec)}catch(e){this.spec.fail(e),a();return}
b?a():this.totalTimeSpentWaitingForLatch>=this.timeout?(c="timed out after "+this.timeout+" msec waiting for "+(this.message||"something to happen"),this.spec.fail({name:"timeout",message:c}),this.abort=!0,a()):(this.totalTimeSpentWaitingForLatch+=n.WaitsForBlock.TIMEOUT_INCREMENT,d=this,this.env.setTimeout(function(){d.execute(a)},n.WaitsForBlock.TIMEOUT_INCREMENT))},n.FakeTimer=function(){var a;this.reset(),a=this,a.setTimeout=function(b,c){return a.timeoutsMade++,a.schedulefunction(a.timeoutsMade
,b,c,!1),a.timeoutsMade},a.setInterval=function(b,c){return a.timeoutsMade++,a.schedulefunction(a.timeoutsMade,b,c,!0),a.timeoutsMade},a.clearTimeout=function(b){a.scheduledFunctions[b]=n.undef},a.clearInterval=function(b){a.scheduledFunctions[b]=n.undef}},n.FakeTimer.prototype.reset=function(){this.timeoutsMade=0,this.scheduledFunctions={},this.nowMillis=0},n.FakeTimer.prototype.tick=function(a){var b=this.nowMillis,c=b+a;this.runFunctionsWithinRange(b,c),this.nowMillis=c},n.FakeTimer.prototype.
runFunctionsWithinRange=function(a,b){var c,d,e,f,g=[];for(d in this.scheduledFunctions)c=this.scheduledFunctions[d],c!==n.undef&&c.runAtMillis>=a&&c.runAtMillis<=b&&(g.push(c),this.scheduledFunctions[d]=n.undef);if(g.length>0){g.sort(function(a,b){return a.runAtMillis-b.runAtMillis});for(e=0;e<g.length;++e)try{f=g[e],this.nowMillis=f.runAtMillis,f.funcToCall(),f.recurring&&this.schedulefunction(f.timeoutKey,f.funcToCall,f.millis,!0)}catch(h){}this.runFunctionsWithinRange(a,b)}},n.FakeTimer.prototype
.scheduleFunction=function(a,b,c,d){this.scheduledFunctions[a]={runAtMillis:this.nowMillis+c,funcToCall:b,recurring:d,timeoutKey:a,millis:c}},n.Clock={defaultFakeTimer:new n.FakeTimer,reset:function(){n.Clock.assertInstalled(),n.Clock.defaultFakeTimer.reset()},tick:function(a){n.Clock.assertInstalled(),n.Clock.defaultFakeTimer.tick(a)},runFunctionsWithinRange:function(a,b){n.Clock.defaultFakeTimer.runFunctionsWithinRange(a,b)},scheduleFunction:function(a,b,c,d){n.Clock.defaultFakeTimer.schedulefunction
(a,b,c,d)},useMock:function(){var a;n.Clock.isInstalled()||(a=n.getEnv().currentSpec,a.after(n.Clock.uninstallMock),n.Clock.installMock())},installMock:function(){n.Clock.installed=n.Clock.defaultFakeTimer},uninstallMock:function(){n.Clock.assertInstalled(),n.Clock.installed=n.Clock.real},real:{setTimeout:n.getGlobal().setTimeout,clearTimeout:n.getGlobal().clearTimeout,setInterval:n.getGlobal().setInterval,clearInterval:n.getGlobal().clearInterval},assertInstalled:function(){if(!n.Clock.isInstalled
())throw new Error("Mock clock is not installed, use jasmine.Clock.useMock()")},isInstalled:function(){return n.Clock.installed===n.Clock.defaultFakeTimer},installed:null},n.Clock.installed=n.Clock.real,n.getGlobal().setTimeout=function(a,b){if(n.Clock.installed.setTimeout.apply)return n.Clock.installed.setTimeout.apply(this,arguments);else return n.Clock.installed.setTimeout(a,b)},n.getGlobal().setInterval=function(a,b){if(n.Clock.installed.setInterval.apply)return n.Clock.installed.setInterval.
apply(this,arguments);else return n.Clock.installed.setInterval(a,b)},n.getGlobal().clearTimeout=function(a){if(n.Clock.installed.clearTimeout.apply)return n.Clock.installed.clearTimeout.apply(this,arguments);else return n.Clock.installed.clearTimeout(a)},n.getGlobal().clearInterval=function(a){if(n.Clock.installed.clearTimeout.apply)return n.Clock.installed.clearInterval.apply(this,arguments);else return n.Clock.installed.clearInterval(a)},n.version_={major:1,minor:1,build:0,revision:1315677058}
,l})