package com._4psa.billing._2_5_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.515+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://4psa.com/Billing/2.5.1", name = "BillingInterface")
@XmlSeeAlso({com._4psa.clientdata_xsd._2_5.ObjectFactory.class, com._4psa.headerdata_xsd._2_5.ObjectFactory.class, com._4psa.billingmessages_xsd._2_5.ObjectFactory.class, com._4psa.clientmessages_xsd._2_5.ObjectFactory.class, com._4psa.billingmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.reportdata_xsd._2_5.ObjectFactory.class, com._4psa.extensionmessages_xsd._2_5.ObjectFactory.class, com._4psa.channeldata_xsd._2_5.ObjectFactory.class, com._4psa.pbxmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.accountmessages_xsd._2_5.ObjectFactory.class, com._4psa.resellermessages_xsd._2_5.ObjectFactory.class, com._4psa.common_xsd._2_5.ObjectFactory.class, com._4psa.billingdata_xsd._2_5.ObjectFactory.class, com._4psa.clientmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.extensionmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.pbxdata_xsd._2_5.ObjectFactory.class, com._4psa.reportmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.channelmessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.pbxmessages_xsd._2_5.ObjectFactory.class, com._4psa.globalopmessages_xsd._2_5.ObjectFactory.class, com._4psa.reportmessages_xsd._2_5.ObjectFactory.class, com._4psa.extensiondata_xsd._2_5.ObjectFactory.class, com._4psa.resellermessagesinfo_xsd._2_5.ObjectFactory.class, com._4psa.resellerdata_xsd._2_5.ObjectFactory.class, com._4psa.channelmessages_xsd._2_5.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BillingInterface {

    @WebResult(name = "GetRechargesResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetRecharges", action = "http://4psa.com/Billing/2.5.1:getRechargesIn")
    public com._4psa.billingmessages_xsd._2_5.GetRechargesResponse getRecharges(
        @WebParam(partName = "messagePart", name = "GetRechargesRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.GetRechargesRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "AddChargingPackageResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "AddChargingPackage", action = "http://4psa.com/Billing/2.5.1:addChargingPackageIn")
    public com._4psa.common_xsd._2_5.UpdateObject addChargingPackage(
        @WebParam(partName = "messagePart", name = "AddChargingPackageRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.AddChargingPackageRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "DelDestinationExceptionResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "DelDestinationException", action = "http://4psa.com/Billing/2.5.1:delDestinationExceptionIn")
    public com._4psa.common_xsd._2_5.DelObject delDestinationException(
        @WebParam(partName = "messagePart", name = "DelDestinationExceptionRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.DelDestinationExceptionRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetChargingPackagesResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetChargingPackages", action = "http://4psa.com/Billing/2.5.1:getChargingPackagesIn")
    public com._4psa.billingdata_xsd._2_5.ChargingPackageList getChargingPackages(
        @WebParam(partName = "messagePart", name = "GetChargingPackagesRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.GetChargingPackagesRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetDestinationExceptionsResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetDestinationExceptions", action = "http://4psa.com/Billing/2.5.1:getDestinationExceptionsIn")
    public com._4psa.billingdata_xsd._2_5.DestinationExceptionList getDestinationExceptions(
        @WebParam(partName = "messagePart", name = "GetDestinationExceptionsRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.GetDestinationExceptionsRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "DelChargingPackageResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "DelChargingPackage", action = "http://4psa.com/Billing/2.5.1:delChargingPackageIn")
    public com._4psa.common_xsd._2_5.DelObject delChargingPackage(
        @WebParam(partName = "messagePart", name = "DelChargingPackageRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.DelChargingPackageRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "DelMonthlyLimitResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "DelMonthlyLimit", action = "http://4psa.com/Billing/2.5.1:delMonthlyLimitIn")
    public com._4psa.common_xsd._2_5.DelObject delMonthlyLimit(
        @WebParam(partName = "messagePart", name = "DelMonthlyLimitRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.DelMonthlyLimitRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "RechargeResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "Recharge", action = "http://4psa.com/Billing/2.5.1:rechargeIn")
    public com._4psa.common_xsd._2_5.UpdateObject recharge(
        @WebParam(partName = "messagePart", name = "RechargeRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.RechargeRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetChargingPlansResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetChargingPlans", action = "http://4psa.com/Billing/2.5.1:getChargingPlansIn")
    public com._4psa.billingmessagesinfo_xsd._2_5.GetChargingPlanResponseType getChargingPlans(
        @WebParam(partName = "messagePart", name = "GetChargingPlansRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.GetChargingPlansRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "GetChargingPlanDetailsResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "GetChargingPlanDetails", action = "http://4psa.com/Billing/2.5.1:getChargingPlanDetailsIn")
    public com._4psa.billingmessagesinfo_xsd._2_5.GetChargingPlanDetailsResponseType getChargingPlanDetails(
        @WebParam(partName = "messagePart", name = "GetChargingPlanDetailsRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.GetChargingPlanDetailsRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "EditDestinationExceptionResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "EditDestinationException", action = "http://4psa.com/Billing/2.5.1:editDestinationExceptionIn")
    public com._4psa.common_xsd._2_5.UpdateObject editDestinationException(
        @WebParam(partName = "messagePart", name = "EditDestinationExceptionRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.EditDestinationExceptionRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "EditChargingPackageResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "EditChargingPackage", action = "http://4psa.com/Billing/2.5.1:editChargingPackageIn")
    public com._4psa.common_xsd._2_5.UpdateObject editChargingPackage(
        @WebParam(partName = "messagePart", name = "EditChargingPackageRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.EditChargingPackageRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "AddChargingPlanResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "AddChargingPlan", action = "http://4psa.com/Billing/2.5.1:addChargingPlanIn")
    public com._4psa.billingmessages_xsd._2_5.AddChargingPlanResponse addChargingPlan(
        @WebParam(partName = "messagePart", name = "AddChargingPlanRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.AddChargingPlanRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "AddDestinationExceptionResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "AddDestinationException", action = "http://4psa.com/Billing/2.5.1:addDestinationExceptionIn")
    public com._4psa.common_xsd._2_5.UpdateObject addDestinationException(
        @WebParam(partName = "messagePart", name = "AddDestinationExceptionRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.AddDestinationExceptionRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "DelChargingPlanResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "DelChargingPlan", action = "http://4psa.com/Billing/2.5.1:delChargingPlanIn")
    public com._4psa.common_xsd._2_5.DelObject delChargingPlan(
        @WebParam(partName = "messagePart", name = "DelChargingPlanRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.DelChargingPlanRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );

    @WebResult(name = "EditChargingPlanResponse", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1", partName = "messagePart")
    @WebMethod(operationName = "EditChargingPlan", action = "http://4psa.com/Billing/2.5.1:editChargingPlanIn")
    public com._4psa.billingmessages_xsd._2_5.EditChargingPlanResponse editChargingPlan(
        @WebParam(partName = "messagePart", name = "EditChargingPlanRequest", targetNamespace = "http://4psa.com/BillingMessages.xsd/2.5.1")
        com._4psa.billingmessages_xsd._2_5.EditChargingPlanRequest messagePart,
        @WebParam(partName = "headerPart", name = "userCredentials", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        com._4psa.headerdata_xsd._2_5.UserCredentials headerPart,
        @WebParam(partName = "headerPart", mode = WebParam.Mode.OUT, name = "serverInfo", targetNamespace = "http://4psa.com/HeaderData.xsd/2.5.1", header = true)
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> headerPart1
    );
}
