
package com._4psa.billing._2_5_1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.320+02:00
 * Generated source version: 2.4.0
 *
 */
public final class BillingInterface_BillingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://4psa.com/Billing/2.5.1", "BillingPort");

    private BillingInterface_BillingPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BillingPort.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BillingPort ss = new BillingPort(wsdlURL, SERVICE_NAME);
        BillingInterface port = ss.getBillingPort();

        {
        System.out.println("Invoking getRecharges...");
        com._4psa.billingmessages_xsd._2_5.GetRechargesRequest _getRecharges_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getRecharges_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getRecharges_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingmessages_xsd._2_5.GetRechargesResponse _getRecharges__return = port.getRecharges(_getRecharges_messagePart, _getRecharges_headerPart, _getRecharges_headerPart1);
        System.out.println("getRecharges.result=" + _getRecharges__return);

        System.out.println("getRecharges._getRecharges_headerPart1=" + _getRecharges_headerPart1.value);

        }
        {
        System.out.println("Invoking addChargingPackage...");
        com._4psa.billingmessages_xsd._2_5.AddChargingPackageRequest _addChargingPackage_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _addChargingPackage_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _addChargingPackage_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _addChargingPackage__return = port.addChargingPackage(_addChargingPackage_messagePart, _addChargingPackage_headerPart, _addChargingPackage_headerPart1);
        System.out.println("addChargingPackage.result=" + _addChargingPackage__return);

        System.out.println("addChargingPackage._addChargingPackage_headerPart1=" + _addChargingPackage_headerPart1.value);

        }
        {
        System.out.println("Invoking delDestinationException...");
        com._4psa.billingmessages_xsd._2_5.DelDestinationExceptionRequest _delDestinationException_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delDestinationException_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delDestinationException_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delDestinationException__return = port.delDestinationException(_delDestinationException_messagePart, _delDestinationException_headerPart, _delDestinationException_headerPart1);
        System.out.println("delDestinationException.result=" + _delDestinationException__return);

        System.out.println("delDestinationException._delDestinationException_headerPart1=" + _delDestinationException_headerPart1.value);

        }
        {
        System.out.println("Invoking getChargingPackages...");
        com._4psa.billingmessages_xsd._2_5.GetChargingPackagesRequest _getChargingPackages_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getChargingPackages_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getChargingPackages_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingdata_xsd._2_5.ChargingPackageList _getChargingPackages__return = port.getChargingPackages(_getChargingPackages_messagePart, _getChargingPackages_headerPart, _getChargingPackages_headerPart1);
        System.out.println("getChargingPackages.result=" + _getChargingPackages__return);

        System.out.println("getChargingPackages._getChargingPackages_headerPart1=" + _getChargingPackages_headerPart1.value);

        }
        {
        System.out.println("Invoking getDestinationExceptions...");
        com._4psa.billingmessages_xsd._2_5.GetDestinationExceptionsRequest _getDestinationExceptions_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getDestinationExceptions_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getDestinationExceptions_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingdata_xsd._2_5.DestinationExceptionList _getDestinationExceptions__return = port.getDestinationExceptions(_getDestinationExceptions_messagePart, _getDestinationExceptions_headerPart, _getDestinationExceptions_headerPart1);
        System.out.println("getDestinationExceptions.result=" + _getDestinationExceptions__return);

        System.out.println("getDestinationExceptions._getDestinationExceptions_headerPart1=" + _getDestinationExceptions_headerPart1.value);

        }
        {
        System.out.println("Invoking delChargingPackage...");
        com._4psa.billingmessages_xsd._2_5.DelChargingPackageRequest _delChargingPackage_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delChargingPackage_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delChargingPackage_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delChargingPackage__return = port.delChargingPackage(_delChargingPackage_messagePart, _delChargingPackage_headerPart, _delChargingPackage_headerPart1);
        System.out.println("delChargingPackage.result=" + _delChargingPackage__return);

        System.out.println("delChargingPackage._delChargingPackage_headerPart1=" + _delChargingPackage_headerPart1.value);

        }
        {
        System.out.println("Invoking delMonthlyLimit...");
        com._4psa.billingmessages_xsd._2_5.DelMonthlyLimitRequest _delMonthlyLimit_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delMonthlyLimit_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delMonthlyLimit_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delMonthlyLimit__return = port.delMonthlyLimit(_delMonthlyLimit_messagePart, _delMonthlyLimit_headerPart, _delMonthlyLimit_headerPart1);
        System.out.println("delMonthlyLimit.result=" + _delMonthlyLimit__return);

        System.out.println("delMonthlyLimit._delMonthlyLimit_headerPart1=" + _delMonthlyLimit_headerPart1.value);

        }
        {
        System.out.println("Invoking recharge...");
        com._4psa.billingmessages_xsd._2_5.RechargeRequest _recharge_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _recharge_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _recharge_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _recharge__return = port.recharge(_recharge_messagePart, _recharge_headerPart, _recharge_headerPart1);
        System.out.println("recharge.result=" + _recharge__return);

        System.out.println("recharge._recharge_headerPart1=" + _recharge_headerPart1.value);

        }
        {
        System.out.println("Invoking getChargingPlans...");
        com._4psa.billingmessages_xsd._2_5.GetChargingPlansRequest _getChargingPlans_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getChargingPlans_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getChargingPlans_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingmessagesinfo_xsd._2_5.GetChargingPlanResponseType _getChargingPlans__return = port.getChargingPlans(_getChargingPlans_messagePart, _getChargingPlans_headerPart, _getChargingPlans_headerPart1);
        System.out.println("getChargingPlans.result=" + _getChargingPlans__return);

        System.out.println("getChargingPlans._getChargingPlans_headerPart1=" + _getChargingPlans_headerPart1.value);

        }
        {
        System.out.println("Invoking getChargingPlanDetails...");
        com._4psa.billingmessages_xsd._2_5.GetChargingPlanDetailsRequest _getChargingPlanDetails_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _getChargingPlanDetails_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _getChargingPlanDetails_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingmessagesinfo_xsd._2_5.GetChargingPlanDetailsResponseType _getChargingPlanDetails__return = port.getChargingPlanDetails(_getChargingPlanDetails_messagePart, _getChargingPlanDetails_headerPart, _getChargingPlanDetails_headerPart1);
        System.out.println("getChargingPlanDetails.result=" + _getChargingPlanDetails__return);

        System.out.println("getChargingPlanDetails._getChargingPlanDetails_headerPart1=" + _getChargingPlanDetails_headerPart1.value);

        }
        {
        System.out.println("Invoking editDestinationException...");
        com._4psa.billingmessages_xsd._2_5.EditDestinationExceptionRequest _editDestinationException_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _editDestinationException_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _editDestinationException_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _editDestinationException__return = port.editDestinationException(_editDestinationException_messagePart, _editDestinationException_headerPart, _editDestinationException_headerPart1);
        System.out.println("editDestinationException.result=" + _editDestinationException__return);

        System.out.println("editDestinationException._editDestinationException_headerPart1=" + _editDestinationException_headerPart1.value);

        }
        {
        System.out.println("Invoking editChargingPackage...");
        com._4psa.billingmessages_xsd._2_5.EditChargingPackageRequest _editChargingPackage_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _editChargingPackage_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _editChargingPackage_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _editChargingPackage__return = port.editChargingPackage(_editChargingPackage_messagePart, _editChargingPackage_headerPart, _editChargingPackage_headerPart1);
        System.out.println("editChargingPackage.result=" + _editChargingPackage__return);

        System.out.println("editChargingPackage._editChargingPackage_headerPart1=" + _editChargingPackage_headerPart1.value);

        }
        {
        System.out.println("Invoking addChargingPlan...");
        com._4psa.billingmessages_xsd._2_5.AddChargingPlanRequest _addChargingPlan_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _addChargingPlan_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _addChargingPlan_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingmessages_xsd._2_5.AddChargingPlanResponse _addChargingPlan__return = port.addChargingPlan(_addChargingPlan_messagePart, _addChargingPlan_headerPart, _addChargingPlan_headerPart1);
        System.out.println("addChargingPlan.result=" + _addChargingPlan__return);

        System.out.println("addChargingPlan._addChargingPlan_headerPart1=" + _addChargingPlan_headerPart1.value);

        }
        {
        System.out.println("Invoking addDestinationException...");
        com._4psa.billingmessages_xsd._2_5.AddDestinationExceptionRequest _addDestinationException_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _addDestinationException_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _addDestinationException_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _addDestinationException__return = port.addDestinationException(_addDestinationException_messagePart, _addDestinationException_headerPart, _addDestinationException_headerPart1);
        System.out.println("addDestinationException.result=" + _addDestinationException__return);

        System.out.println("addDestinationException._addDestinationException_headerPart1=" + _addDestinationException_headerPart1.value);

        }
        {
        System.out.println("Invoking delChargingPlan...");
        com._4psa.billingmessages_xsd._2_5.DelChargingPlanRequest _delChargingPlan_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delChargingPlan_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delChargingPlan_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delChargingPlan__return = port.delChargingPlan(_delChargingPlan_messagePart, _delChargingPlan_headerPart, _delChargingPlan_headerPart1);
        System.out.println("delChargingPlan.result=" + _delChargingPlan__return);

        System.out.println("delChargingPlan._delChargingPlan_headerPart1=" + _delChargingPlan_headerPart1.value);

        }
        {
        System.out.println("Invoking editChargingPlan...");
        com._4psa.billingmessages_xsd._2_5.EditChargingPlanRequest _editChargingPlan_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _editChargingPlan_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _editChargingPlan_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.billingmessages_xsd._2_5.EditChargingPlanResponse _editChargingPlan__return = port.editChargingPlan(_editChargingPlan_messagePart, _editChargingPlan_headerPart, _editChargingPlan_headerPart1);
        System.out.println("editChargingPlan.result=" + _editChargingPlan__return);

        System.out.println("editChargingPlan._editChargingPlan_headerPart1=" + _editChargingPlan_headerPart1.value);

        }

        System.exit(0);
    }

}
