
package com._4psa.account._2_5_1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.310+02:00
 * Generated source version: 2.4.0
 * 
 */
public final class AccountInterface_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://4psa.com/Account/2.5.1", "AccountPort");

    private AccountInterface_AccountPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AccountPort.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AccountPort ss = new AccountPort(wsdlURL, SERVICE_NAME);
        AccountInterface port = ss.getAccountPort();  
        
        {
        System.out.println("Invoking setAccountStatus...");
        com._4psa.accountmessages_xsd._2_5.SetAccountStatusRequest _setAccountStatus_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _setAccountStatus_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _setAccountStatus_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.UpdateObject _setAccountStatus__return = port.setAccountStatus(_setAccountStatus_messagePart, _setAccountStatus_headerPart, _setAccountStatus_headerPart1);
        System.out.println("setAccountStatus.result=" + _setAccountStatus__return);

        System.out.println("setAccountStatus._setAccountStatus_headerPart1=" + _setAccountStatus_headerPart1.value);

        }
        {
        System.out.println("Invoking linkAccount...");
        com._4psa.accountmessages_xsd._2_5.LinkAccountRequest _linkAccount_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _linkAccount_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _linkAccount_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.accountmessages_xsd._2_5.LinkAccountResponse _linkAccount__return = port.linkAccount(_linkAccount_messagePart, _linkAccount_headerPart, _linkAccount_headerPart1);
        System.out.println("linkAccount.result=" + _linkAccount__return);

        System.out.println("linkAccount._linkAccount_headerPart1=" + _linkAccount_headerPart1.value);

        }
        {
        System.out.println("Invoking delAccount...");
        com._4psa.accountmessages_xsd._2_5.DelAccountRequest _delAccount_messagePart = null;
        com._4psa.headerdata_xsd._2_5.UserCredentials _delAccount_headerPart = null;
        javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo> _delAccount_headerPart1 = new javax.xml.ws.Holder<com._4psa.headerdata_xsd._2_5.ServerInfo>();
        com._4psa.common_xsd._2_5.DelObject _delAccount__return = port.delAccount(_delAccount_messagePart, _delAccount_headerPart, _delAccount_headerPart1);
        System.out.println("delAccount.result=" + _delAccount__return);

        System.out.println("delAccount._delAccount_headerPart1=" + _delAccount_headerPart1.value);

        }

        System.exit(0);
    }

}
