define("io.ox/core/tk/dialogs",["io.ox/core/event","io.ox/core/bootstrap/basics"],function(a){var b=$("<div>").hide().addClass("abs io-ox-dialog-underlay"),c=$("<div>").hide().addClass("io-ox-dialog-popup").append($("<div>").addClass("modal-header"),$("<div>").addClass("modal-body"),$("<div>").addClass("modal-footer")),d=function(d){var e={underlay:b.clone().appendTo("body"),popup:c.clone().appendTo("body")},f=$.Deferred(),g,h=this,i={},j=_.extend({underlayAction:null,defaultAction:null,easyOut:!1
,center:!0,async:!1,top:"50%"},d),k=function(){$(document).off("keydown",g),e.popup.empty().remove(),e.underlay.remove();for(var a in h)delete h[a];h.close=h.idle=$.noop,e.header=e.body=e.footer=null,e=f=h=i=j=null},l=function(){e.footer.find("button").attr("disabled","disabled"),e.body.find("input").attr("disabled","disabled")},m=function(){e.footer.find("button").removeAttr("disabled"),e.body.find("input").removeAttr("disabled")},n=function(a){var b=a.data?a.data.action:a,c=j.async&&b!=="cancel"
;c&&l(),h.trigger("action "+b,i),c||(f.resolve(b,i),k())};_(["header","body","footer"]).each(function(a){e[a]=e.popup.find(".modal-"+a)}),a.extend(this),this.data=function(a){return i=a!==undefined?a:{},this},this.header=function(){return e.header.append.apply(e.header,arguments),this},this.getHeader=function(){return e.header},this.getPopup=function(){return e.popup},this.getContentNode=this.getBody=function(){return e.body},this.getContentControls=this.getFooter=function(){return e.footer},this
.text=function(a){var b=e.body;return b.find(".plain-text").remove(),b.append($("<h4>").addClass("plain-text").text(a||"")),this},this.append=function(a){return e.body.append(a),this};var o=function(a,b,c,d){d=d||{};var e={label:b,data:{action:a},click:n,dataaction:c,purelink:d.purelink,inverse:d.inverse};d.type&&(e[d.type]=!0);var f=$.button(e);return f.addClass(d.classes)};this.addButton=function(a,b,c,d){var f=o(a,b,c,d);return e.footer.append(f),this},this.addDangerButton=function(a,b,c,d){var f=
o(a,b,c,d);return f.addClass("btn-danger"),e.footer.prepend(f),this},this.addPrimaryButton=function(a,b,c,d){var f=o(a,b,c,d);return f.addClass("btn-primary"),e.footer.prepend(f),this},this.addAlternativeButton=function(a,b,c,d){var f=o(a,b,c,d);return f.css({"float":"left",marginLeft:0}),e.footer.prepend(f),this},g=function(a){a.which===27&&n("cancel")},this.close=function(){!j||j.async?k():n("cancel")},this.idle=function(){m()},this.show=function(a){e.header.children().length===0&&e.header.remove
();var b={width:parseInt(j.width||e.popup.width(),10),height:parseInt(j.height||e.popup.height(),10)};_(["width","height"]).each(function(a){var c=j[$.camelCase("max-"+a)];j[c]&&b[a]>j[c]&&(b[a]=j[c]);var d=$(document)[a]()-100;b[a]&&b[a]>d&&(b[a]=d)}),j.center?e.popup.css({width:b.width+"px",top:"50%",marginTop:0-((b.height+60)/2>>0)+"px"}):e.popup.css({width:b.width+"px",top:j.top||"0px"}),e.underlay.show(),e.popup.show();var c=e.popup.find(".btn-primary").first().focus();return c.length||e.popup
.find(".btn").not(".btn-danger").first().focus(),j.easyOut&&$(document).on("keydown",g),a&&a.call(e.popup),this.trigger("show"),f},e.underlay.click(function(){j.underlayAction?n(j.underlayAction):j.easyOut&&n("cancel")}),e.popup.click(function(){j.defaultAction&&n(j.defaultAction)}),this.setUnderlayAction=function(a){return j.underlayAction=a,this},this.setDefaultAction=function(a){return j.defaultAction=a,this}},e=function(a){a=a||{},a.top="50px",a.center=!1,d.call(this,a)},f=function(a){var b,c
,d,e,f,g,h,i=null,j=$("<div>").addClass("io-ox-sidepopup-pane default-content-padding abs"),k=$("<span>").addClass("io-ox-sidepopup-close close").html("&times"),l=$("<div>").addClass("io-ox-sidepopup abs").append(k,j),m=$("<div>").addClass("io-ox-sidepopup-arrow").append($("<div>").addClass("border")).append($("<div>").addClass("triangle")),n=this;j=j.scrollable(),this.nodes={},this.lastTrigger=null,b=function(a){a.preventDefault()},c=function(a){return a.isDefaultPrevented()},f=function(a){a.which===27&&
e(a)},g=function(a){e(a)},h=function(a){c(a)||(b(a),e(a))},e=function(a){$(document).off("keydown",f),n.nodes.closest.off("scroll",g),n.nodes.click.off("click",h),n.lastTrigger=null,i=setTimeout(function(){m.detach(),j.empty(),l.detach()},100)},k.on("click",function(a){return j.trigger("click"),e(a),!1}),l.on("click",b),d=function(a,c){var d=$(this),k,o;n.nodes={closest:d.parents(".io-ox-sidepopup-pane, .window-content"),click:d.parents(".io-ox-sidepopup-pane, .window-body"),target:d.parents(".window-body"
)},o=n.nodes.closest.prop("sidepopup")||null,n.lastTrigger=o?o.lastTrigger:null,k=(d.parents(".io-ox-sidepopup, .window-content").css("zIndex")||1)+2;if(n.lastTrigger===this)e(a);else{o&&o.close(),n.lastTrigger=this,n.nodes.closest.prop("sidepopup",n),b(a),clearTimeout(i),n.nodes.click.on("click",h),n.nodes.closest.on("scroll",g),$(document).on("keydown",f);var p=$(document).width(),q,r=d.parents(".io-ox-sidepopup").first(),s=r.length===0;q=s&&d.offset().left>p/2||r.hasClass("right")?"left":"right"
,l.add(m).removeClass("left right").addClass(q).css("zIndex",k),m.css("zIndex",k+1),n.nodes.target.append(l.css("visibility","hidden")),(c||$.noop).call(this,j.empty(),a);var t=d.outerHeight(!0)/2>>0,u=d.offset().top+t-n.nodes.target.offset().top;m.css("top",u),l.css("visibility",""),n.nodes.target.append(m)}},this.delegate=function(a,b,c){return $(a).on("click",b,function(a){d.call(this,a,c)}),this},this.show=function(a,b){return d.call(a.target,a,b),this},this.close=function(a){e(a)}},g=$("<div>"
).addClass("abs io-ox-dialog-pane").append($("<div>").addClass("content")).append($("<div>").addClass("form-actions")),h=function(){var a=this,b={pane:g.clone().hide().appendTo("body"),relativeTo:null};b.content=b.pane.find(".content"),b.controls=b.pane.find(".form-actions"),this.visible=!1;var c=$.Deferred(),d=function(){a.visible=!1,b.pane.fadeOut()},e=function(a){c.resolve(a.data),d()};this.text=function(a){return b.content.text(a||""),this},this.append=function(a){return b.content.append(a),this
},this.addButton=function(a,c){return b.controls.append($.button({label:c,data:a,click:e})),this},this.relativeTo=function(a){return b.relativeTo=$(a),this},this.toggle=function(){this.visible?e("toggeled"):this.show()},this.show=function(){this.visible=!0;var a,d,e,f,g,h,i;h=$(window).height(),i=$(window).width();var j=b.pane.css("opacity");return b.pane.css("opacity","0.001"),b.pane.show(),f=b.controls.outerHeight(!0)+b.content.outerHeight(!0)+2,g=b.content.find(".block").outerWidth(!0)+20,b.pane
.hide(),b.pane.css("opacity",j),b.relativeTo?(a=b.relativeTo.offset(),a.top<h/2?d=a.top+b.relativeTo.outerHeight()+3:(d=a.top-f-10,d<0&&(d=0)),a.left<i/2?e=a.left:e=a.left+b.relativeTo.outerWidth()-g,b.pane.css({height:f+"px",width:g+"px",top:d+"px",left:e+"px"})):b.pane.css({height:f+"px",width:g+"px",marginTop:0-(f/2>>0)+"px"}),b.pane.fadeIn(),c}};return"use strict",{ModalDialog:d,CreateDialog:e,SlidingPane:h,SidePopup:f}})