define("io.ox/core/tk/folderviews",["io.ox/core/tk/selection","io.ox/core/api/folder","io.ox/core/api/account","io.ox/core/api/user","io.ox/core/extensions","io.ox/core/event","io.ox/core/config","io.ox/settings/accounts/email/settings"],function(a,b,c,d,e,f,g,h){var i,j=ox.base+"/apps/themes/default/icons/",k=j+"folder-default.png",l="url("+j+"folder-open.png)",m="url("+j+"folder-close.png)",n=$("<div>").addClass("folder selectable").css("paddingLeft","13px"),o=$("<div>").addClass("subfolders").
hide(),p={},q=function(){return!0};"use strict";function r(a,c,d,f){var g,h=b.get({folder:c}),i={},j=null,k=!1,s=this,t={},u=_.isFunction(a.options.filter)?a.options.filter:q,v=function(){return a.root===s&&a.options.skipRoot},w=function(){return t.subfolders||t.subscr_subflds},x=function(){return g===undefined&&(g=t.id==="default0/INBOX"||a.options.type==="infostore"&&(t.id==="9"||t.id==="10")||a.options.type==="contacts"&&t.id==="2"),w()&&(v()||g)},y=function(a,b){return s.loadChildren(a).pipe(
function(a){return $.when.apply(null,_(a).invoke(b,i.sub.busy().show()))})},z=function(){return y(!1,"paint")},A=function(){return y(!0,"repaint")},B=function(){var a=w()?x()?m:l:"none";i.arrow.css("backgroundImage",a)},C=function(a){if(a.type!=="dblclick"&&$(this).hasClass("selectable"))return;a.preventDefault(),w()&&(g?(g=!1,i.sub.hide(),B()):(g=!0,i.sub.show(),B(),j===null&&z()))};this.id=c,this.getChildren=function(){return j},this.reload=function(){h=b.get({folder:c})},this.loadChildren=function(
d){var e,g={};if(j===null||d===!0)return j!==null&&d===!0&&_(j).each(function(a){g[a.id]=a.detach()}),e=p[c]===undefined&&b.needsRefresh(c),b.getSubFolders({folder:c}).done(function(a){e&&_.defer(function(){b.getSubFolders({folder:c,cache:!1}).done(function(b){_.isEqual(a,b)||(s.reload(),_(j).invoke("reload"),s.repaint()),p[c]=!1})})}).pipe(function(b){return j=_.chain(b).filter(function(a){return(a.module!=="system"||a.subfolders)&&u(a)}).map(function(b){var c;if(d&&g[b.id]!==undefined)return c=
g[b.id],delete g[b.id],c;else return new r(a,b.id,i.sub,v()?f:f+1)}).value(),_(g).each(function(a){a.destroy()}),g=null,j});else return $.Deferred().resolve(j)},this.detach=function(){return i.folder.detach(),i.sub.detach(),this},this.destroy=function(){_(i).each(function(a){a.remove()}),_(j).each(function(a){a.destroy()}),h=j=i=a=s=d=t=null},this.repaint=function(){if(k)return d.append(i.folder,i.sub),h.pipe(function(b){t=b,s.customize(),i.folder.hasClass("selectable")&&a.selection.addToIndex(t)
,B();if(x())return A();else return i.sub.empty().hide(),$.when()}).done(function(){d.idle()});else return this.paint()},this.paint=function(){return i.folder=n.clone().on("dblclick click",C),f>0&&i.folder.css("paddingLeft",13+f*22+"px"),i.sub=o.clone(),v()&&i.folder.hide(),d.append(i.folder,i.sub),h.pipe(function(b){var c;return t=b,i.arrow=$("<div>").addClass("folder-arrow").on("click",C),i.icon=$("<img>",{src:"",alt:""}).addClass("folder-icon"),i.label=$("<span>").addClass("folder-label"),i.counter=
$("<span>").addClass("folder-counter"),c=x()?z():$.when(),B(),i.folder.append(i.arrow,i.icon,i.counter,i.label),s.customize(),i.folder.attr("data-obj-id",t.id),i.folder.hasClass("selectable")&&a.selection.addToIndex(t),c}).done(function(){d.idle(),k=!0})},this.customize=function(){e.point("io.ox/foldertree/folder").invoke("customize",i.folder,t,a.options)}}function s(b,c){var d;this.options=_.extend({id:"default",rootFolderId:"1",skipRoot:!0,type:null},c),this.internal={destroy:$.noop},d=this,$(b
).addClass("io-ox-foldertree").append(this.container=$("<div>")),a.extend(this,b).setMultiple(!1).setSerializer(function(a){return String(a.id)}),f.extend(this),this.paint=function(){var a=this.paint;return a.running===null&&(this.trigger("beforepaint"),this.selection.clearIndex(),a.running=this.internal.paint.call(this)||$.when(),a.running.always(function(){d.selection.update(),d.trigger("paint"),a.running=null})),a.running||$.when()},this.paint.running=null,this.repaint=function(){var a=this.paint
;return a.running===null&&(this.trigger("beforerepaint"),this.selection.clearIndex(),a.running=(this.internal.repaint||this.internal.paint).call(this)||$.when(),a.running.always(function(){d.selection.update(),d.trigger("repaint"),a.running=null})),a.running||$.when()},this.busy=function(){return this.container.parent().busy().children().hide(),this.trigger("busy"),this},this.idle=function(){return this.container.parent().idle().children().show(),this.trigger("idle"),this},this.destroy=function()
{this.events.destroy(),this.selection.destroy(),this.internal.destroy(),b.empty(),b=this.container=this.selection=this.internal=null}}function t(a,b){b=$.extend({filter:function(a){return a.module===b.type||b.type==="mail"&&/^default\d+(\W|$)/i.test(a.id)}},b),s.call(this,a,b),this.root=new r(this,this.options.rootFolderId,this.container,0),this.internal.paint=function(){return this.root.paint()},this.internal.repaint=function(){return this.root.repaint()}}function u(a){a.preventDefault(),require
(["io.ox/core/tk/dialogs"],function(c){(new c.ModalDialog({width:400,easyOut:!0})).header($("<h4>").text("Add new folder")).append($("<input>",{placeholder:"Folder name",value:""}).addClass("nice-input")).addButton("cancel","Cancel").addPrimaryButton("add","Add folder").show(function(){this.find("input").focus()}).done(function(c){c==="add"&&(a.data.tree.busy(),b.create({folder:a.data.folder,data:{module:"mail",title:"New folder "+_.now()}}).done(function(b){a.data.tree.idle().repaint().done(function(
){a.data.tree.selection.set(String(b)),a.data=null})}))})})}function v(a,b){t.call(this,a,b),$(a).append(this.links=$("<div>").addClass("foldertree-links")),this.on("paint",function(){e.point("io.ox/application-foldertree/links").invoke("draw",this.links,{rootFolderId:this.options.rootFolderId,tree:this})})}e.point("io.ox/foldertree/folder").extend({index:100,id:"default",customize:function(a,d){var e,f,h,i,l=this.find(".folder-icon"),m=this.find(".folder-label"),n=this.find(".folder-counter");(function(
){var b,d,f,h,i={};a.module==="mail"?(d=function(){switch(a.id){case i.inbox_fullname:e=j+"inbox.png";break;case i.trash_fullname:e=j+"trash.png";break;case i.sent_fullname:e=j+"outbox.png";break;case i.drafts_fullname:e=j+"draft.png";break;case i.spam_fullname:e=j+"spam.png";break;case i.confirmed_ham_fullname:e=j+"ham.png";break;case i.confirmed_spam_fullname:e=j+"spam.png";break;default:e=k}l.attr("src",e)},b=/^default(\d*)\b/.exec(a.id),$.isArray(b)&&(b=b[1],b==="0"?(h=g.get("mail.folder"),h&&
(i.inbox_fullname=h.inbox,i.trash_fullname=h.trash,i.sent_fullname=h.sent,i.drafts_fullname=h.drafts,i.spam_fullname=h.spam,d())):(f="default"+b,c.get(b).done(function(a){a?i=a:i={inbox_fullname:f+"/INBOX",trash_fullname:f+"/Trash",sent_fullname:f+"/Sent",drafts_fullname:f+"/Drafts",spam_fullname:f+"/Spam"},i.inbox_fullname===undefined&&(i.inbox_fullname=f+"/INBOX"),d()})))):a.id==="6"?e=j+"user.png":e=k})(),f=!d.type||d.type===a.module,h=b.can("read",a),i=f&&h,i||(this.removeClass("selectable"),
a.folder_id==="10"&&this.css("opacity",.6)),l.attr("src",e),m.text(a.title+""),d.type==="mail"&&a.unread?(m.css("fontWeight","bold"),n.text(a.unread||"").show()):(m.css("fontWeight",""),n.hide())}}),e.point("io.ox/application-foldertree/links").extend({index:100,id:"create-folder",draw:function(a){this.append($("<div>").append($("<a>",{href:"#"}).addClass("action-link").text("Add new folder ...").on("click",{folder:a.rootFolderId,tree:a.tree},u)))}}),e.point("io.ox/application-foldertree/links").
extend({index:100,id:"create-mailaccount",draw:function(){this.append($("<div>").append($("<a>",{href:"#"}).addClass("action-link").text("Add mail account ...").on("click",h.mailAutoconfigDialog)))}}),i={"private":"Private","public":"Public ",shared:"Shared"};function w(a,c){var f;s.call(this,a,c),f=this;function g(a){var g=n.clone().append($("<img>",{src:"",alt:""}).addClass("folder-icon"),$("<span>").addClass("folder-label")).attr("data-obj-id",a.id);return b.is("shared",a)&&g.append($("<div>")
.addClass("shared-by").append(d.getLink(a.created_by,a["com.openexchange.folderstorage.displayName"]))),f.selection.addToIndex(a),e.point("io.ox/foldertree/folder").invoke("customize",g,a,c),g}function h(){b.getVisible({type:c.type}).done(function(a){var b,c,d=function(a,b){_(b).each(function(b){a.append(g(b))})};for(b in i)a[b]&&(f.container.append(c=$("<div>").addClass("section").append($("<div>").addClass("section-title").text(i[b]))),d(c,a[b]))})}this.internal.paint=function(){h()},this.internal
.repaint=function(){this.container.empty(),h()}}return{FolderList:w,FolderTree:t,ApplicationFolderTree:v}})