define("io.ox/core/tk/forms",["io.ox/core/date"],function(a){var b,c,d=function(){var a=$(this);a.trigger("update.model",{property:a.attr("data-property"),value:a.prop("checked")})},e=function(a,b){$(this).prop("checked",!!b)},f=function(){var a=$(this);a.trigger("update.model",{property:a.attr("data-property"),value:a.val()})},g=function(a,b){$(this).val(b)},h=function(){var a=$(this),b=/((\d{2})|(\d))\.((\d{2})|(\d))\.((\d{4})|(\d{2}))/;if(a.val()!==""&&b.test(a.val())){var c=a.val().split(".")
,d=Date.UTC(c[2],--c[1],c[0]);a.trigger("update.model",{property:a.attr("data-property"),value:d})}else a.trigger("update.model",{property:a.attr("data-property"),value:a.val()})},i=function(b,c){_.isNumber(c)&&(c=(new a.Local(a.Local.utc(c))).format(a.DATE)),$(this).val(c)},j=f,k=function(a,b){var c=$(this);c.prop("checked",c.attr("value")===b)},l=f,m=g,n=function(a,b){$(this).text(b)},o=function(a){var b=$(this).addClass("invalid-value").css({backgroundColor:"#fee",borderColor:"#a00"}).focus();
setTimeout(function(){b.removeClass("invalid-value").css({backgroundColor:"",borderColor:""}),b=null},5e3)},p=function(a,b){this.options=a||{},this.options.id=this.options.id,this.node=null,this.options.fieldtype=b};return"use strict",p.prototype.create=function(a,b){var d=this.options,e=c.connectLabelToField(d.id),f=$(a).attr({"data-property":d.property,name:d.name,id:e,value:d.value}).on("change",b).addClass(d.classes);this.node=f},p.prototype.applyModel=function(a){var b=this.options,c=b.model
,d=b.initialValue;(c||d)!==undefined&&this.node.on("invalid",o).on("update.view",a).triggerHandler("update.view",c!==undefined?c.get(b.property):d)},p.prototype.wrapLabel=function(){var a,b,c=this.options;c.label!==!1&&(a=$("<label>").addClass(c.fieldtype),b=$.txt(c.label||""),this.node=a.append(b,this.node))},b="",c={createCheckbox:function(a){var b=new p(a,"checkbox");return b.create('<input type="checkbox">',d),b.applyModel(e),b.wrapLabel(),b.node},createSelectbox:function(a){var b=new p(a,"select"
);return b.create("<select>",f),b.node.append(_(a.items).inject(function(a,b,c){return a.add($("<option>").attr("value",c).text(b))},$())),b.applyModel(g),b.wrapLabel(),b.node},createRadioButton:function(a){var b=new p(a,"radio");return b.create('<input type="radio">',j),b.applyModel(k),b.wrapLabel(),b.node},createTextField:function(a){var b=new p(a,"text");return b.create('<input type="text">',l),b.applyModel(m),b.wrapLabel(),b.node},createTextArea:function(a){var b=new p(a,"text");return b.create
("<textarea>",l),b.applyModel(m),b.wrapLabel(),b.node},createDateField:function(a){var b=new p(a,"date");return b.create('<input type="date">',h),b.applyModel(i),b.wrapLabel(),b.node},createPasswordField:function(a){var b=new p(a,"text");return b.create('<input type="password">',l),b.applyModel(m),b.wrapLabel(),b.node},createFileField:function(a){var b=new p(a,"file");return b.create('<input type="file">',l),b.node.attr({accept:a.accept}),b.applyModel(m),b.wrapLabel(),b.node},createLabeledTextField
:function(a){return c.createLabel(a).css({width:"100%",display:"inline-block"}).append(c.createText({text:a.label})).append(c.createTextField({property:a.property,value:a.value,model:a.model,span:a.span}).css({width:a.width+"px",display:"inline-block"}))},createLabeledPasswordField:function(a){var b=c.createLabel(a).css({width:"100%",display:"inline-block"});return b.append(c.createText({text:a.label})),b.append(c.createPasswordField({property:a.property,value:a.value,model:a.model,validator:a.validator
}).css({width:a.width+"px",display:"inline-block"})),b},createLabel:function(a){var b,d=c.connectLabelToField(a["for"]);return a.text=a.text||"",b=$("<label>"),b.attr("for",d),b.text(a.text),b},createText:function(a){var b=$("<span>").addClass("text").addClass(a.classes).text(a.text||"");return a.model&&a.property&&b.attr("data-property",a.property).on("update.view",n).triggerHandler("update.view",a.model.get(a.property)),b},createInfoText:function(a){var b=$("<div>").addClass("informational-text"
);return a.html?b.html(a.html):b.text(a.text),b},createSectionDelimiter:function(){return $("<div>").addClass("settings sectiondelimiter")},createApplicationTitle:function(a){return $("<div>").addClass("clear-title").text(a.text)},createSettingsHead:function(a){return $("<div>").append(c.createApplicationTitle({text:a.title})).append(c.createSectionDelimiter())},createSection:function(a){return $("<div>").addClass("section")},createSectionTitle:function(a){return $("<legend>").addClass("sectiontitle"
).text(a.text)},createSectionContent:function(a){return $("<div>").addClass("sectioncontent")},createSectionGroup:function(a){return $("<div>").addClass("section-group")},createSectionHorizontalWrapper:function(){return $("<div>").addClass("form-horizontal")},createControlGroup:function(){return $("<div>").addClass("control-group")},createInlineControlGroup:function(){return $("<div>").addClass("control-group form-inline")},createControlGroupLabel:function(a){if(a){var b=c.connectLabelToField(a["for"
]);return $("<label>",{"for":b}).text(a.text).addClass("control-label")}else return $("<label>")},createControlsWrapper:function(){return $("<div>").addClass("controls")},createPicUpload:function(a){var b=_.extend({target:"picture-upload",name:"picture-upload-file"},a);return b.target+="-"+_.now(),$("<form>",{"accept-charset":"UTF-8",enctype:"multipart/form-data",method:"POST",target:b.target}).append(c.createFileField({wrap:!1,accept:"image/*","data-property":b.name,name:b.name})).append($("<iframe>"
,{name:b.target,src:"blank.html"}).hide())},getLastLabelId:function(){return b},connectLabelToField:function(a){var d;if(a==="auto")return d=b=_.uniqueId("label_"),d;else if(a==="last")return c.getLastLabelId();else return a},createListBox:function(a){var b=$("<div>").addClass("listbox");return b.append(c.createListSpacer()),_.each(a.model.get(a.dataid),function(a,d){console.log(d+":"+a.dataid),b.append(c.createListItem({dataid:a.dataid,html:a.html}))}),b.append(c.createListSpacer()),b},createListItem
:function(a){a.classStr=a.classStr||"deletable-item";var b=$("<div>");return b.addClass(a.classStr),b.attr("data-item-id",a.dataid),b.append($("<a>").html("&times;").addClass("close")),b.append($("<div>").html(a.html)),b.on("click",function(){console.log("click"),b.parent().find('div[selected="selected"]').attr("selected",null),b.attr("selected","selected")}),b},createListSpacer:function(){return $("<div>").addClass("spacer").css({height:"0px"})},createButton:function(a){return $("<button>").addClass
(a.btnclass).text(a.label)}},c})