define.async("io.ox/core/tk/html-editor",[],function(){"use strict";function a(){var a=$(this),b=a.attr("style"),c=$("<p>");b&&c.attr("style",b),a.replaceWith(c.append(a.contents()))}function b(a,b){b.content=b.content.replace(/<!--(.*?)-->/g,"").replace(/ data-[^=]+="[^"]*"/g,"").replace(/&nbsp;/ig," ").replace(/([^>\s])<a/ig,"$1 <a").replace(/<\/\s?a>([^<\s,\.:;])/ig,"</a> $1").replace(/([^=])"([\w\- ]+)"/g,"$1“$2”").replace(/(\w\s)-(\s\w)/g,"$1–$2")}function c(a,b){var c,d=$(b),e=b.tagName,f=d
.children();d.removeAttr("id title alt rel");if(/^(BR|HR|IMG)$/.test(e))return a;d.attr("align")&&d.css("textAlign",d.attr("align")).removeAttr("align"),d.contents().each(function(){b.nodeType===3&&(b.nodeValue=b.nodeValue.replace(/:$/,": "))});if(f.length===0){c=$.trim(d.text());if(c==="")if(e==="TD")d.text(" ");else return d.remove(),!1;else{if(/^(SPAN|SMALL|PRE)$/.test(e)&&!d.attr("class")&&!d.attr("style"))return d.replaceWith($.txt(d.text())),!1;/^".+"$/.test(c)&&d.text(c.replace(/^"/,"“").replace
(/"$/,"”"))}}else if(e==="DIV"&&!d.attr("class")&&!d.attr("style"))return f.eq(0).unwrap(),!1;return a}function d(){$(this).children().first().unwrap()}function e(){var a,b=$(this);b.attr("href")?(b.removeAttr("title target"),/^\[\d+\]$/.test(b.text())&&/^#/.test(b.attr("href"))&&(a=(b.text()+"").match(/^\[(\d+)\]$/),b.replaceWith($("<sup>").text(a[1]).add($.txt(" "))))):b.replaceWith(b.contents())}function f(){var a=$(this);a.replaceWith($("<em>").text(a.text()))}function g(){var a=$(this);a.removeAttr
("width").attr({border:"0",cellSpacing:"0",cellPadding:"0"}).css({lineHeight:"1em",margin:"0.5em auto 0.5em auto"}),a.find("th").css({fontWeight:"bold",textAlign:"center",borderBottom:"1px solid #555",padding:"0.4em 1em 0.4em 1em"}),a.find("td").css({borderBottom:"1px solid #aaa",padding:"0.4em 1em 0.4em 1em"}),a.find("tr").first().find("td, th").css({borderTop:"1px solid #555"}),a.find("tr").last().find("td, th").css({borderBottom:"1px solid #555"})}function h(){var a=$(this),b=a.contents();b.length===1&&
b.get(0).tagName==="BR"&&a.remove()}function i(b,i){var j,k=$(i.node);k.find("iframe, object, applet, input, textarea, button, select, "+"canvas, script, noscript, audio, video, img").remove(),k.find("sup").css("lineHeight","0"),k.find("article, header, footer, section, form").each(d),k.find("a").each(e),k.find("code").each(f);do j=_(k.find("*")).inject(c,!0);while(!j);k.find("table").each(g),k.eq(0).children("div").each(a),k.find("p").each(h)}function j(a){var b=a.commonAncestorContainer||a.parentElement
(),c=$(b).parents("blockquote").last(),d=c.length>0;return d}function k(a){var b,c,d=a.selection.getRng(),e=a.getBody(),f=e.createTextRange(),g=e.createTextRange();f.setEndPoint("EndToStart",d),f=f.htmlText,g.setEndPoint("StartToEnd",d),g=g.htmlText.replace(/^(\s*<[^>]+>\s*)<BR\s*\/?>(.*)$/im,"$1$2"),b="#cursor~mark^";while(f.indexOf(b)>=0||g.indexOf(b)>=0)b+=String.fromCharCode(64+Math.random()*63);c="<p>"+b+"</p>",e.innerHTML=f+c+g,d.findText(b),d.select(),d.pasteHTML(""),d.collapse(!0)}function l
(a){var b,c,d,e,f,g,h,i=a.selection.getRng();i.collapsed||(a.execCommand("Delete",!1,null),i=a.selection.getRng()),b=i.commonAncestorContainer,c=null,d=function(a){var b;if(a)if(a.hasChildNodes())for(b=0;b<a.childNodes.length;b++)if(a.childNodes[b].nodeType===1){d(a.childNodes[b]);return}else a.childNodes[b].nodeType===3&&(a.childNodes[b].nodeValue=a.childNodes[b].nodeValue.replace("​",""));else a.nodeName==="BR"&&(c=a)};while(b&&b.nodeName!=="BODY")i.setEndAfter(b),e=b.parentNode,f=i.extractContents
(),d(f.firstChild),$(f).text().length>0&&e.insertBefore(f,b.nextSibling),b=e;if(c)try{c.parentNode.removeChild(c)}catch(j){}g=a.getDoc().createElement("span"),g.innerHTML="&nbsp;",h=a.getDoc().createElement("p"),h.appendChild(g),i.insertNode(h),a.selection.select(g),a.execCommand("Delete",!1,null)}function m(a,b){var c=a.selection.getRng();j(c)&&(c.startContainer?l(a):k(a),a.dom.events.cancel(b))}function n(a){var c,d,e,f,g,h,j,k,l,n=$.Deferred();(a=$(a)).tinymce({script_url:ox.base+"/apps/moxiecode/tiny_mce/tiny_mce.js"
,plugins:"paste",theme:"advanced",skin:"ox",init_instance_callback:function(){c=a.tinymce(),$(c.getWin()).on("focus",function(){$("#"+c.id+"_tbl").addClass("focused")}).on("blur",function(){$("#"+c.id+"_tbl").removeClass("focused")}),n.resolve()},theme_advanced_buttons1:"bold,italic,underline,strikethrough,|,"+"bullist,numlist,indent,outdent,|,"+"justifyleft,justifycenter,justifyright,|,"+"forecolor,backcolor,|,formatselect,|,"+"undo,redo,",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_toolbar_location
:"top",theme_advanced_toolbar_align:"left",theme_advanced_blockformats:"h1,h2,h3,h4,p,blockquote",theme_advanced_more_colors:!1,theme_advanced_text_colors:"000000,555555,AAAAAA,0088CC,AA0000",theme_advanced_background_colors:"FFFFFF,FFFF00,00FFFF,00FF00,00FFFF,FFBE33",theme_advanced_default_foreground_color:"#000000",theme_advanced_default_background_color:"#FFFFFF",entity_encoding:"raw",verify_html:!1,paste_auto_cleanup_on_paste:!0,paste_remove_styles:!0,paste_remove_styles_if_webkit:!0,paste_strip_class_attributes
:"all",paste_block_drop:!1,paste_preprocess:b,paste_postprocess:i,setup:function(a){a.onKeyDown.add(function(a,b){if((b.keyCode||b.which)===13)try{m(a,b)}catch(b){console.error("Ooops! setup.onKeyDown()",b)}})}}),d=_.debounce(function(){var b=a.parent(),c=b.width(),d=b.height(),e=d-b.find("td.mceToolbar").outerHeight()-2;b.find("table.mceLayout").css({width:c+"px",height:d+"px"}),b.find("iframe").css("height",e+"px")},100),e=function(a){return String(a||"").replace(/^[^\S\n]+/,"").replace(/^\n{3,}/
,"").replace(/\s+$/)},f=function(a){return $.trim((a+"").replace(/[\r\n]+/g,""))},g=function(a){return"> "+$.trim(a).replace(/\n/g,"\n> ")},h=function(a){c.setContent(a+"")},j=function(){h("")},k=function(a){return String(a||"").replace(/\r/g,"").replace(new RegExp("\\n","g"),"<br>")},l=function(){return f(c.getContent()).replace(/<(\w+)[ ]?\/>/g,"<$1>").replace(/(<p>(<br>)?<\/p>)+$/,"")},this.done=function(a){return n.done(a),n},this.focus=function(){c.focus()},this.ln2br=k,this.clear=j,this.getContent=
l,this.getPlainText=function(){var a;return _.browser.IE&&$("p",c.getBody()).append("<br>"),$(":header",c.getBody()).append("<br>"),a="",$(c.getBody()).children().each(function(){var b="";c.selection.select(this,!0),b=c.selection.getContent({format:"text"});switch(this.tagName){case"BLOCKQUOTE":a+=g(b)+"\n\n";break;case"P":case"H1":case"H2":case"H3":case"H4":a+=b+"\n\n";break;default:a+=b+"\n"}}),a},this.setContent=h,this.setPlainText=function(a){var b,c,d="",f=!1,g="";a=e(a),a.substr(0,2)==="\n\n"&&
(d+="<p></p>",a=a.substr(2)),_(a.split("\n").concat("")).each(function(a){a=$.trim(a),a===""||f&&a.substr(0,1)!==">"?(b=f?"<blockquote><p>":"<p>",c=f?"</blockquote></p>":"</p>",d+=g!==""?b+g.replace(/<br>$/,"")+c:"",g="",f=!1):a.substr(0,1)===">"?(g+=a.substr(2).replace(/</g,"&lt;").replace(/>/g,"&gt;")+"<br>",f=!0):g+=a.replace(/</g,"&lt;").replace(/>/g,"&gt;")+"<br>"}),h(d)},this.paste=function(a){c.execCommand("mceInsertClipboardContent",!1,{content:a})},this.scrollTop=function(a){var b=$(c.getDoc
());if(a===undefined)return b.scrollTop();else a==="top"?b.scrollTop(0):a==="bottom"&&b.scrollTop(b.get(0).body.scrollHeight)},this.appendContent=function(a){var b=this.getContent();a=/^<p/i.test(a)?a:"<p>"+k(a)+"</p>",this.setContent(b+a)},this.replaceParagraph=function(a,b){var c,d,e=this.getContent();a=/^<p/i.test(a)?a:"<p>"+k(a)+"</p>";if((c=e.indexOf(a))>-1)return d=this.scrollTop(),this.setContent(e.substr(0,c)+(b||"")+e.substr(c+a.length)),this.scrollTop(d),!0;else return!1},this.removeContent=
function(a){this.replaceContent(a,"")},this.removeBySelector=function(a){$(a,c.getDoc()).remove()},this.replaceContent=function(a,b){var d,e=c.getWin(),f=!1;function g(){c.selection.setContent(b||"")}c.selection.select(c.getBody(),!0),c.selection.collapse(!0);if(_.browser.IE){c.focus(),d=c.getDoc().selection.createRange();while(d.findText(a,1,0))d.scrollIntoView(),d.select(),g(),f=!0}else while(e.find(a,0,0,!1,!1,!1,!1))g(),f=!0;return window.lala=e,f},this.getMode=function(){return"html"},this.tinymce=
function(){return a.tinymce?a.tinymce():{}},this.handleShow=function(){a.parents(".window-content").find(".editor-print-margin").hide(),a.removeAttr("disabled").idle().next().show(),a.hide(),d(),$(window).on("resize",d)},this.handleHide=function(){$(window).off("resize",d)},this.destroy=function(){this.handleHide(),c&&$(c.getWin()).off("focus blur"),a.tinymce()&&a.tinymce().remove(),a=a.tinymce=n=c=null}}return $.getScript(ox.base+"/apps/moxiecode/tiny_mce/jquery.tinymce.js").pipe(function(){return n
})})