define("io.ox/core/tk/model",["io.ox/core/event"],function(a){var b,c,d=function(a,b){this.properties=_.isArray(a)?a:[a],this.message=b},e=/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,f={string:function(){return!0},text:function(){return!0},number:function(a,b,c){var e=/^\d+$/;return e.test(b)||new d(a,_.printf("%s must be a number",c.i18n||a))},array:function(a,b,c){return _.isArray(b)||new d(a,_.printf("%s must be an array",c.i18n||a))},"boolean":function(a,b,c){return _.isBoolean
(b)||new d(a,_.printf("%s must be bool",c.i18n||a))},date:function(){return!0},pastDate:function(a,b,c){if(_.isString(b))return new d(a,_.printf("%s is not a valide date",c.i18n||a));return _.now()>b||new d(a,_.printf("%s must be in the past",c.i18n||a))},email:function(a,b,c){return e.test(b)||new d(a,_.printf("%s must be a valid email address",c.i18n||a))},url:function(){return!0}},g=function(a,b){if(a===""&&b===undefined)return!0;else return _.isEqual(a,b)},h=function(a){this._definitions=a||{
}};return"use strict",h.prototype={formats:f,get:function(a){return this._definitions[a]||{}},getDefaults:function(){var a={};return _(this._definitions).each(function(b,c){b.defaultValue!==undefined&&(a[c]=b.defaultValue)}),a},getMandatories:function(){var a=[];return _(this._definitions).each(function(b,c){b.mandatory&&a.push(c)}),a},isMandatory:function(a){return!!this.get(a).mandatory},getFieldType:function(a){return this.get(a).format},getFieldLabel:function(a){return this.get(a).label},isTrimmed
:function(a){return this.get(a).trim!==!1},validate:function(a,b){var c=this.get(a),e=c.format||"string",f=b===""||b===null,g=c.mandatory!==!0;if(f)return g||new d(a,_.printf("%s is mandatory",c.i18n||a));if(_.isFunction(this.formats[e]))return this.formats[e](a,b,c);console.error("Unknown format used in model schema",e)},check:function(){return $.when()}},c=function(a){_(this._computed).each(function(b,d){if(_(b.deps).indexOf(a)>-1){var e=this._memoize[d],f=this.get(d);_.isEqual(e,f)||(this.trigger
("change:"+d,d,f),c.call(this,d))}},this)},b=function(b){b=b||{},this._data={},this._previous={},this._defaults=this.schema.getDefaults(),this._memoize={},this.cid=_.uniqueId("c"),a.extend(this),this.initialize(b.data||b||{})},b.addComputed=function(a,b,c){return c||(c=b,b=[]),a&&_.isFunction(c)&&(this.prototype._computed[a]={deps:b,callback:c}),this},b.prototype={_computed:{},idAttribute:"id",schema:new h,initialize:function(a){this._previous=_.copy(a||{},!0),this._data=_.extend({},this._defaults
,_.copy(a||{},!0)),this.idAttribute in this._data&&(this.id=this._data[this.idAttribute]),_(this._computed).each(function(a,b){this.get(b)},this)},isEmpty:function(a){var b=this._data[a];return b===""||b===undefined||b===null},has:function(a){return a in this._data},get:function(a){var b,c,d;if(a===undefined)return _.copy(this._data,!0);else if(this._computed[a]===undefined)return _.copy(this._data[a],!0);else return b=this._computed[a],c=_(b.deps).map(this.get,this),d=b.callback.apply(this,c),this
._memoize[a]=d},set:function(a,b){var d;if(a===undefined)return;_.isString(b)&&this.schema.isTrimmed(a)&&(b=$.trim(b));if(g(b,this._data[a]))return;d=this.schema.validate(a,b),this._data[a]=b,d!==!0&&this.trigger("error:invalid",d),this.trigger("change:"+a+" change",a,b),c.call(this,a)},isDirty:function(){var a,b,c,d=this._previous,e=this._defaults;for(a in this._data){b=this._data[a],c=!g(b,d[a])&&!_.isEqual(b,e[a]);if(c)return!0}return!1},getChanges:function(){var a={},b=this._previous;return _
(this._data).each(function(c,d){g(c,b[d])||(a[d]=_.copy(c,!0))}),a},toString:function(){return JSON.stringify(this._data)},toJSON:function(){return this.toString()},setData:function(a){console.warn("DEPRECATED: setData - use initialize()"),this.init(a)},getData:function(){return console.warn("DEPRECATED: getData - use get()"),_.copy(this._data,!0)},_validate:function(){return!0},getDefinition:function(a){return console.warn("DEPRECATED: getDefinition -> schema.get()"),this.schema.get(a)},validate
:function(a,b){return console.warn("DEPRECATED: validate -> schema.validate()"),this.schema.validate(a,b)},check:function(a,b){return console.warn("DEPRECATED: check -> schema.check()"),this.schema.check(a,b)},isMandatory:function(a){return console.warn("DEPRECATED: isMandatory"),this.schema.isMandatory(a)},isTrimmed:function(a){return console.warn("DEPRECATED: isTrimmed"),this.schema.isTrimmed(a)},save:function(){var a=function(a,b,c){var d=this.schema.validate(c,b);if(d!==!0)return this.trigger
("error:invalid",d),!1;else return a},b=function(){var a=$.Deferred().notify(),b=this;return this.trigger("save:progress"),(this.store(this.get(),this.getChanges())||$.when()).done(function(){"trigger"in b&&(b.initialize(b._data),b.trigger.apply(b,["save:beforedone"].concat($.makeArray(arguments))),b.trigger.apply(b,["save:done"].concat($.makeArray(arguments)))),a.resolve.apply(a,arguments)}).fail(function(){"trigger"in b&&(b.trigger.apply(b,["save:beforefail"].concat($.makeArray(arguments))),b.trigger
.apply(b,["save:fail"].concat($.makeArray(arguments)))),a.reject.apply(a,arguments)}),a},c=function(a){return this.trigger("error:inconsistent",a),a};return function(){var e;_(this.schema.getMandatories()).each(function(a){a in this._data||(this._data[a]="")},this);if(!_(this._data).inject(a,!0,this))return $.Deferred().reject();return e=this.schema.check(this._data,d),_.isFunction((e||{}).promise)||(e=typeof e=="object"?$.Deferred().reject(e):$.when()),e.pipe(_.bind(b,this),_.bind(c,this))}}(),store
:function(){},destroy:function(){this.events.destroy(),this._data=null,this._previous=null,this._defaults=null,this._memoize=null}},_.makeExtendable(b),b.Schema=h,b})