define("io.ox/core/tk/selection",["io.ox/core/event"],function(a){var b=function(b){this.classFocus="focussed",this.classSelected="selected",a.extend(this);var c=this,d=!0,e=!1,f={},g=!0,h=[],i={},j={},k=j,l=j,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C=-1,D,E;u=function(a){return e||d&&a&&a.metaKey},v=function(a){return a&&a.shiftKey&&d},E=function(){var a=0,b;for(b in f){a++;if(a>1)return!0}return!1},m=function(){var a=c.get();c.trigger("change",a),a.length===0&&c.trigger("empty")},n=function(a,b){v(b)?(
c.selectRange(l,a),k=a):(t(a),k=l=a),m()},y=function(a){if(g&&h.length){var b=h[0];p(),n(b,a),c.trigger("select:first",b)}},z=function(a){if(g){var b=w(k)-1,d;b>=0&&(d=h[b],p(),n(d,a),c.trigger("select:previous",d))}},A=function(a){if(g&&h.length){var b=h.length-1,d=h[b];p(),n(d,a),c.trigger("select:last",d)}},B=function(a){if(g){var b=w(k)+1,d;b<h.length&&(d=h[b],p(),n(d,a),c.trigger("select:next",d))}},D=function(a){c.trigger("keyboard",a,a.which);switch(a.which){case 38:return a.metaKey?y(a):z
(a),!1;case 40:return a.metaKey?A(a):B(a),!1}},o=function(a){var b,d;if(!a.isDefaultPrevented()){b=$(this).attr("data-obj-id"),d=g?h[w(b)]:b;if(d!==undefined)if(!u(a)){if(!q(d)||E()||c.serialize(d)!==c.serialize(k))p(),n(d,a)}else n(d,a)}},w=function(a){return g?i[c.serialize(a)]:-1},x=function(a){return b.find('.selectable[data-obj-id="'+c.serialize(a)+'"]')},q=function(a){return f[c.serialize(a)]!==undefined},r=function(a){if(a){var d=c.serialize(a);f[d]=a,x(d).addClass(c.classSelected).find("input.reflect-selection"
).attr("checked","checked").end().intoViewport(b),k=a,C=w(a),l===j&&(l=a),c.trigger("select",d)}},s=function(a){var b=c.serialize(a);delete f[b],x(b).find("input.reflect-selection").removeAttr("checked").end().removeClass(c.classSelected),c.trigger("deselect",b)},t=function(a){q(a)?s(a):r(a)},p=function(){var a="";for(a in f)s(a)},this.serialize=function(a){return typeof a=="object"?a.folder_id!==undefined?a.folder_id+"."+a.id:a.id:a},this.setSerializer=function(a){this.serialize=function(b){return typeof 
b=="object"?a(b):b}},this.init=function(a){var b=this.get();p(),h=a.slice(),i={},k=l=j;var d=0,e=a.length,f,g=!1,n=C;for(;d<e;d++)i[c.serialize(a[d])]=d;for(d=0,e=b.length;d<e;d++)f=c.serialize(b[d]),i[f]!==undefined&&(r(b[d]),g=!0);return a.length>0&&(C=-1),!g&&n>=0&&r(h[n]),_.isEqual(b,c.get())||m(),this},this.insertAt=function(a,b){var d=a.length,e=_(a).reduce(function(a,b){return a||c.serialize(b)in i},!1);e||(h.splice.apply(h,[b,0].concat(a)),_(i).each(function(a,c){a>=b&&(i[c]+=d)}),_(a).each
(function(a,d){i[c.serialize(a)]=b+d}))},this.remove=function(a){_(a).each(function(a){var b=c.serialize(a),d=i[b];d!==undefined&&h.splice(d,1,null)}),h=_(h).compact(),i={},_(h).each(function(a,b){i[c.serialize(a)]=b})},this.update=function(){var a=b.find(".selectable"),d=0,e=a.length,f=null;for(;d<e;d++)f=$(a[d]),q(f.attr("data-obj-id"))?f.find("input.reflect-selection").attr("checked","checked").end().addClass(c.classSelected):f.find("input.reflect-selection").removeAttr("checked");return this}
,this.clearIndex=function(){return h=[],i={},this},this.addToIndex=function(a){var b=this.serialize(a);return i[b]===undefined&&(i[b]=h.length,h.push(a)),this},this.hasIndex=function(a){return g=!!a,this},this.setMultiple=function(a){return d=!!a,this},this.setEditable=function(a){return e=!!a,k=l=j,C=-1,this},this.get=function(){var a=[],b="";for(b in f)a.push(f[b]);return a},this.unfold=this.get,this.clear=function(a){return p(),a!==!0&&(c.trigger("clear"),m()),this},this.select=function(a){return r
(a),m(),this},this.set=function(a,b){return p(),_(_.isArray(a)?a:[a]).each(function(a){var b;typeof a=="string"&&g&&(b=h[w(a)])!==undefined?r(b):r(a)}),b!==!0&&m(),this},this.equals=function(a){return _.isEqual(a,this.get())},this.selectRange=function(a,b){if(g){a=w(a),b=w(b);if(a>b){var c=a;a=b,b=c}for(;a<=b;a++)r(h[a]);m()}return this},this.selectFirst=function(){return y(),this},this.selectSmart=function(){return this.get().length===0&&this.selectFirst(),this},this.selectNext=B,this.isSelected=
function(a){return q(a)},this.getIndex=function(a){return w(a)},this.keyboard=function(a){return $(document)[a?"on":"off"]("keydown",D),this},this.retrigger=function(a){if(a){var b=this.get();this.clear(),this.set(b)}else m()},this.retriggerUnlessEmpty=function(){this.get().length&&m()},this.destroy=function(){this.clear(),this.keyboard(!1),this.events.destroy(),b.off("click contextmenu"),f=h=i=k=null},b.on("click contextmenu",".selectable",o)};return"use strict",b.extend=function(a,c){return a.selection=new 
b(c)},b})