define("io.ox/core/api/folder",["io.ox/core/http","io.ox/core/cache","io.ox/core/config","io.ox/core/api/account","io.ox/core/event"],function(a,b,c,d,e){var f=new b.SimpleCache("folder",!0),g=new b.SimpleCache("subfolder",!0),h=new b.SimpleCache("visible-folder",!0),i=function(a,b){return a>>b&(b>=28?1:127)},j=function(b,c){c=c||{};var d=c.storage||f,e=function(){return a.GET({module:"folders",params:{action:"get",id:b,tree:"1"}}).done(function(a,b){d.add(a.id,a)}).fail(function(a){console.error
("folder.get",b,a)})};return c.cache===!1?e():d.get(b,e)},k={get:function(a){var b=_.extend({folder:"1",event:!1,cache:!0,storage:null},a||{}),c={};if(_.isArray(b.folder))return $.when.apply(null,_(b.folder).map(function(a){var d=$.Deferred();return a!==undefined?j(a,b).done(function(b){c[String(a)]=b}).always(function(){d.resolve()}):d.resolve(),d})).pipe(function(){return c});else return j(b.folder,b)},getSubFolders:function(b){var c=_.extend({folder:"1",all:!1,event:!1,cache:!0,storage:null},b||
{}),d=c.storage||g,e=function(){return a.GET({module:"folders",params:{action:"list",parent:c.folder,tree:"1",all:c.all?"1":"0"},appendColumns:!0}).done(function(a,b){d.add(c.folder,a),_(a).each(function(a){f.add(a.id,a)})}).fail(function(a){console.error("folder.getSubFolders",c.folder,a)})};return c.cache===!1?e():d.get(c.folder,e)},getPath:function(a){var b=_.extend({folder:"1",event:!1,cache:!0,storage:null},a||{}),c=b.storage||f,d=$.Deferred(),e=[],g=function(a){c.get(a).done(function(a){a!==
null})};return g(b.folder)},getVisible:function(b){var d=_.extend({type:"mail",cache:!0},b||{}),e=function(){return a.GET({module:"folders",appendColumns:!0,params:{tree:"1",action:"allVisible",content_type:d.type}}).pipe(function(b,e){var g,h,i={},j=String(c.get("folder."+d.type,0)),l=function(b){return a.makeObject(b,"folders")},m=function(a){return k.can("read",a)},n=function(a){return f.add(a,e),a},o=function(a,b){return a.id===j?-1:a.title.toLowerCase()>b.title.toLowerCase()?+1:-1};for(g in 
b)h=_.chain(b[g]).map(l).filter(m).map(n).value(),h.length>0&&(g!=="shared"&&h.sort(o),i[g]=h);return i}).done(function(a){h.add(d.type,a)})};return d.cache===!1?e():h.get(d.type,e)},create:function(b){var d=$.extend({folder:"1",tree:"1",event:!0},b||{});return d.data=$.extend({module:"mail",title:"New Folder",subscribed:1},d.data||{}),k.get({folder:d.folder}).pipe(function(b){return b.type===5?d.data.permissions=[{group:!1,bits:403710016,entity:c.get("identifier")}]:d.data.permissions=b.permissions
,a.PUT({module:"folders",params:{action:"new",folder_id:d.folder,tree:"1"},data:d.data,appendColumns:!1}).pipe(function(a){return k.getSubFolders({folder:d.folder,cache:!1}).pipe(function(){return a})})})},derive:{bits:function(a,b){return i(_.firstOf(a.own_rights,a,0),b||0)}},is:function(a,b){var e,f=0,g,h;if(_.isArray(b))return _(b).reduce(function(b,c){return b&&k.is(a,c)},!0);else if(a.search(/\|/)>-1){var i=a.split(/\|/);for(g=i.length,e=!1;f<g;f++)if(this.is(i[f],b)){e=!0;break}return e}else switch(
a){case"private":return b.type===1;case"public":return b.type===2;case"shared":return b.type===3;case"system":return b.type===5;case"mail":return b.module==="mail";case"messaging":return b.module==="messaging";case"calendar":return b.module==="calendar";case"contacts":return b.module==="contacts";case"tasks":return b.module==="tasks";case"infostore":return b.module==="infostore";case"account":return b.module==="system"&&/^default(\d+)?/.test(String(b.id));case"unifiedmail":return h=b?b.id!==undefined?
b.id:b:"",d.isUnified(h);case"external":return/^default[1-9]/.test(String(b.id))&&!this.is("unifiedmail",b);case"defaultfolder":var j=c.get("mail.folder");for(h in j)if(j[h]===b.id)return!0;return!1;case"published":if(b["com.openexchange.publish.publicationFlag"])return!0;if(b.permissions.length<=1)return!1;return b.type===1||b.type===7||b.module==="infostore"&&b.created_by===c.get("identifier")}},can:function(a,b){if(_.isArray(b))return _(b).reduce(function(b,c){return b&&k.can(a,c)},!0);var c=!0
,d=b.own_rights,e=b.standard_folder||this.is("system",b),f=i(d,28)===1,g=b.module==="mail";switch(a){case"read":return i(d,7)>0;case"write":return i(d,0)>=2;case"rename":return!f||e?c=!1:i(d,30)===1?c=!0:g?c=!this.is("defaultfolder",b):c=!0,c;case"create":return f||this.derive("permissions",b).bit>=4;case"delete":return f&&!e&&!this.is("defaultfolder",b);case"import":return(d&127)>=2&&this.is("calendar|contacts|tasks",b);case"export":return!this.is("shared",b)&&this.is("contacts|calendar",b);case"empty"
:return d>>21&127&&this.is("mail",b);case"changepermissions":return f;case"viewproperties":return!g&&!this.is("account",b)&&b.capabilities&1;case"subscribe":return g&&Boolean(b.capabilities&Math.pow(2,4));default:return!1}},folderCache:f,subFolderCache:g,needsRefresh:function(a){return g.get(a).pipe(function(a){return a!==null})},getTextNode:function(a){var b=document.createTextNode("");return j(a).done(function(a){b.nodeValue=a.title||a.id}).always(function(){_.defer(function(){b=null})}),b}},l=
function(a,b){a=_.isArray(a)?a:[a];var c=$.when.apply($,_(a).map(function(a){var c=_.isString(a)?a:a.folder_id;return f.get(c).pipe(function(a){if(a)return a.unread=Math.max(0,a.unread+b),f.add(c,a);else return $.when()})}));return _.chain(a).pluck("folder_id").uniq().each(function(a){k.trigger("change:"+a)}),c};return"use strict",k.setUnread=function(a,b){return f.get(a).pipe(function(c){if(c)return c.unread=Math.max(0,b),f.add(a,c).done(function(){k.trigger("change:"+a)});else return $.when()})
},k.decUnread=function(a){return l(a,-1)},k.incUnread=function(a){return l(a,+1)},e.extend(k),k})