
/*
 *
 */

package com._4psa.reseller._2_5_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-14T17:30:42.630+02:00
 * Generated source version: 2.4.0
 *
 */


@WebServiceClient(name = "ResellerPort",
                  wsdlLocation = "null",
                  targetNamespace = "http://4psa.com/Reseller/2.5.1")
public class ResellerPort extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://4psa.com/Reseller/2.5.1", "ResellerPort");
    public final static QName ResellerPort = new QName("http://4psa.com/Reseller/2.5.1", "ResellerPort");
    static {
        WSDL_LOCATION = null;
    }

    public ResellerPort(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResellerPort(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResellerPort() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns ResellerInterface
     */
    @WebEndpoint(name = "ResellerPort")
    public ResellerInterface getResellerPort() {
        return super.getPort(ResellerPort, ResellerInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResellerInterface
     */
    @WebEndpoint(name = "ResellerPort")
    public ResellerInterface getResellerPort(WebServiceFeature... features) {
        return super.getPort(ResellerPort, ResellerInterface.class, features);
    }

}
