#! /bin/bash

DDIR=$1 || DDIR="/opt/open-xchange/sbin"

COMMANDS="changecontext \
deletecontext \
disablecontext \
disableallcontexts \
enablecontext \
enableallcontexts \
movedatabasecontext \
movefilestorecontext \
listcontexts \
changefilestore \
listdatabases \
listfilestores \
listservers \
registerdatabase \
registerfilestore \
registerserver \
unregisterdatabase \
unregisterfilestore \
unregisterserver \
changedatabase"
pushd $DDIR
for linkname in $COMMANDS; do
    ln -sf createcontext $linkname
done
for method in create delete change list; do
    for module in user group resource; do
	linkname="${method}${module}"
	if [ "$linkname" != "createuser" ]; then
	    rm -f $linkname
	    ln -sf createuser $linkname
	fi
    done
done
