/*
 *
 *    OPEN-XCHANGE legal information
 *
 *    All intellectual property rights in the Software are protected by
 *    international copyright laws.
 *
 *
 *    In some countries OX, OX Open-Xchange, open xchange and OXtender
 *    as well as the corresponding Logos OX Open-Xchange and OX are registered
 *    trademarks of the Open-Xchange, Inc. group of companies.
 *    The use of the Logos is not covered by the GNU General Public License.
 *    Instead, you are allowed to use these Logos according to the terms and
 *    conditions of the Creative Commons License, Version 2.5, Attribution,
 *    Non-commercial, ShareAlike, and the interpretation of the term
 *    Non-commercial applicable to the aforementioned license is published
 *    on the web site http://www.open-xchange.com/EN/legal/index.html.
 *
 *    Please make sure that third-party modules and libraries are used
 *    according to their respective licenses.
 *
 *    Any modifications to this package must retain all copyright notices
 *    of the original copyright holder(s) for the original code used.
 *
 *    After any such modifications, the original and derivative code shall remain
 *    under the copyright of the copyright holder(s) and/or original author(s)per
 *    the Attribution and Assignment Agreement that can be located at
 *    http://www.open-xchange.com/EN/developer/. The contributing author shall be
 *    given Attribution for the derivative code and a license granting use.
 *
 *     Copyright (C) 2004-2011 Open-Xchange, Inc.
 *     Mail: info@open-xchange.com
 *
 *
 *     This program is free software; you can redistribute it and/or modify it
 *     under the terms of the GNU General Public License, Version 2 as published
 *     by the Free Software Foundation.
 *
 *     This program is distributed in the hope that it will be useful, but
 *     WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *     or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 *     for more details.
 *
 *     You should have received a copy of the GNU General Public License along
 *     with this program; if not, write to the Free Software Foundation, Inc., 59
 *     Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */

package com.openexchange.groupware.notify;

import java.io.ByteArrayInputStream;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import com.openexchange.groupware.container.Appointment;
import com.openexchange.groupware.container.UserParticipant;
import com.openexchange.groupware.ldap.User;

/**
 * Notifications to external invitations are not sent even though it says otherwise
 *
 * @author <a href="mailto:tobias.friedrich@open-xchange.com">Tobias Friedrich</a>
 */
public class Bug20694Test extends ParticipantNotifyTest {

	public void testShouldNotifyOrganizerOnAcceptThunderbirdICal() throws Exception {
        verifyOrganizerNotified(THUNDERBIRD_ICS);
	}

	public void testShouldNotifyOrganizerOnAcceptOutlookICal() throws Exception {
        verifyOrganizerNotified(OUTLOOK_ICS);
	}

	private void verifyOrganizerNotified(final String ical) throws Exception {
		// create appointment from ical
        final Appointment appointment = super.convertFromICal(new ByteArrayInputStream(ical.getBytes()));
        final User currentUser = U(2000)[0];
        final UserParticipant userParticipant = new UserParticipant(currentUser.getId());
        userParticipant.setEmailAddress(currentUser.getMail());
        userParticipant.setDisplayName(currentUser.getDisplayName());
        appointment.setUsers(new UserParticipant[] { userParticipant });

        // user 2000 accepts
		NotificationPool.getInstance().clear();
        super.notify.appointmentAccepted(appointment, super.session);

        // verify notification message
        final List<Message> messages = super.notify.getMessages();
		assertNotNull("no messages sent", messages);
		assertEquals("invalid number of messages", 1, messages.size());
		assertNotNull("message has no recipients", messages.get(0));
		assertAddresses(messages, appointment.getOrganizer());
	}

	private static String getTomorrowForICal(int hour) {
		final Calendar calendar = Calendar.getInstance();
		calendar.setTime(new Date());
		calendar.add(Calendar.DAY_OF_YEAR, 1);
		calendar.set(Calendar.HOUR_OF_DAY, hour);
		calendar.set(Calendar.MINUTE, 0);
		calendar.set(Calendar.SECOND, 0);
		calendar.set(Calendar.MILLISECOND, 0);
		return com.openexchange.data.conversion.ical.Tools.formatForICal(calendar.getTime());
	}

	/**
	 * Example file as generated by Thunderbird 7, taken from bug report
	 */
	private static final String THUNDERBIRD_ICS =
			"BEGIN:VCALENDAR" + "\r\n" +
			"PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN" + "\r\n" +
			"VERSION:2.0" + "\r\n" +
			"METHOD:REQUEST" + "\r\n" +
			"BEGIN:VTIMEZONE" + "\r\n" +
			"TZID:Europe/Berlin" + "\r\n" +
			"X-LIC-LOCATION:Europe/Berlin" + "\r\n" +
			"BEGIN:DAYLIGHT" + "\r\n" +
			"TZOFFSETFROM:+0100" + "\r\n" +
			"TZOFFSETTO:+0200" + "\r\n" +
			"TZNAME:CEST" + "\r\n" +
			"DTSTART:19700329T020000" + "\r\n" +
			"RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3" + "\r\n" +
			"END:DAYLIGHT" + "\r\n" +
			"BEGIN:STANDARD" + "\r\n" +
			"TZOFFSETFROM:+0200" + "\r\n" +
			"TZOFFSETTO:+0100" + "\r\n" +
			"TZNAME:CET" + "\r\n" +
			"DTSTART:19701025T030000" + "\r\n" +
			"RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10" + "\r\n" +
			"END:STANDARD" + "\r\n" +
			"END:VTIMEZONE" + "\r\n" +
			"BEGIN:VEVENT" + "\r\n" +
			"CREATED:20111027T070339Z" + "\r\n" +
			"LAST-MODIFIED:20111027T070425Z" + "\r\n" +
			"DTSTAMP:20111027T070425Z" + "\r\n" +
			"UID:1ce6e8c3-ed7c-430b-9b46-c173269c64b1" + "\r\n" +
			"SUMMARY:check TB7" + "\r\n" +
			"ORGANIZER;RSVP=TRUE;CN=Harald;PARTSTAT=ACCEPTED;ROLE=CHAIR:mailto:harald@h" + "\r\n" +
			" alunke.invalid" + "\r\n" +
			"ATTENDEE;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mailto:oxpro" + "\r\n" +
			" -a02@qs-c4.invalid" + "\r\n" +
			"DTSTART;TZID=Europe/Berlin:" + getTomorrowForICal(12) + "\r\n" +
			"DTEND;TZID=Europe/Berlin:" + getTomorrowForICal(13) + "\r\n" +
//			"DTSTART;TZID=Europe/Berlin:20111127T120000" + "\r\n" +
//			"DTEND;TZID=Europe/Berlin:20111127T130000" + "\r\n" +
			"TRANSP:OPAQUE" + "\r\n" +
			"END:VEVENT" + "\r\n" +
			"END:VCALENDAR" + "\r\n"
	;

	/**
	 * Example file as generated by Outlook 2010, taken from bug report
	 */
	private static final String OUTLOOK_ICS =
			"BEGIN:VCALENDAR" + "\r\n" +
			"METHOD:REQUEST" + "\r\n" +
			"PRODID:Microsoft Exchange Server 2010" + "\r\n" +
			"VERSION:2.0" + "\r\n" +
			"BEGIN:VTIMEZONE" + "\r\n" +
			"TZID:W. Europe Standard Time" + "\r\n" +
			"BEGIN:STANDARD" + "\r\n" +
			"DTSTART:16010101T030000" + "\r\n" +
			"TZOFFSETFROM:+0200" + "\r\n" +
			"TZOFFSETTO:+0100" + "\r\n" +
			"RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10" + "\r\n" +
			"END:STANDARD" + "\r\n" +
			"BEGIN:DAYLIGHT" + "\r\n" +
			"DTSTART:16010101T020000" + "\r\n" +
			"TZOFFSETFROM:+0100" + "\r\n" +
			"TZOFFSETTO:+0200" + "\r\n" +
			"RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3" + "\r\n" +
			"END:DAYLIGHT" + "\r\n" +
			"END:VTIMEZONE" + "\r\n" +
			"BEGIN:VEVENT" + "\r\n" +
			"ORGANIZER;CN=\"Schaefer, Harald\":MAILTO:Schaefer@hallo.invalid" + "\r\n" +
			"ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=oxpro-a02@" + "\r\n" +
			" qs-c4.invalid:MAILTO:oxpro-a02@qs-c4.invalid" + "\r\n" +
			"DESCRIPTION;LANGUAGE=de-DE:\n\n" + "\r\n" +
			"SUMMARY;LANGUAGE=de-DE:check outlook2010" + "\r\n" +
			"DTSTART;TZID=W. Europe Standard Time:" + getTomorrowForICal(17) + "\r\n" +
			"DTEND;TZID=W. Europe Standard Time:" + getTomorrowForICal(20) + "\r\n" +
//			"DTSTART;TZID=W. Europe Standard Time:20111127T110000" + "\r\n" +
//			"DTEND;TZID=W. Europe Standard Time:20111127T120000" + "\r\n" +
			"UID:040000008200E00074C5B7101A82E00800000000A07236668494CC01000000000000000" + "\r\n" +
			" 010000000543BEA74A7E0AD478B5B057E4C07EC34" + "\r\n" +
			"CLASS:PUBLIC" + "\r\n" +
			"PRIORITY:5" + "\r\n" +
			"DTSTAMP:20111027T064245Z" + "\r\n" +
			"TRANSP:OPAQUE" + "\r\n" +
			"STATUS:CONFIRMED" + "\r\n" +
			"SEQUENCE:0" + "\r\n" +
			"LOCATION;LANGUAGE=de-DE:Moabit" + "\r\n" +
			"X-MICROSOFT-CDO-APPT-SEQUENCE:0" + "\r\n" +
			"X-MICROSOFT-CDO-OWNERAPPTID:-1050957861" + "\r\n" +
			"X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE" + "\r\n" +
			"X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY" + "\r\n" +
			"X-MICROSOFT-CDO-ALLDAYEVENT:FALSE" + "\r\n" +
			"X-MICROSOFT-CDO-IMPORTANCE:1" + "\r\n" +
			"X-MICROSOFT-DISALLOW-COUNTER:FALSE" + "\r\n" +
			"BEGIN:VALARM" + "\r\n" +
			"ACTION:DISPLAY" + "\r\n" +
			"DESCRIPTION:REMINDER" + "\r\n" +
			"END:VALARM" + "\r\n" +
			"END:VEVENT" + "\r\n" +
			"END:VCALENDAR"
		;
}
