
package com.openexchange.admin.soap.resource.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:56:00.633+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXResourceServicePortType_OXResourceServiceHttpsSoap11Endpoint_Server{

    protected OXResourceServicePortType_OXResourceServiceHttpsSoap11Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXResourceServicePortTypeImpl();
        String address = "https://ox6-dev.open-xchange.com/servlet/axis2/services/OXResourceService.OXResourceServiceHttpsSoap11Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXResourceServicePortType_OXResourceServiceHttpsSoap11Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
