#@(#) sequences.sql 


CREATE TABLE sequence_id (
    id bigint auto_increment,
    PRIMARY KEY (id)
);


SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS = 1;


DELIMITER //
CREATE PROCEDURE get_unique_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    INSERT INTO sequence_id VALUES ();
    SELECT last_insert_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_calendar_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_contact_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_infostore_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_folder_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_forum_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_pinboard_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_project_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_task_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_gui_setting_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_ical_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_attachment_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE get_webdav_id() NOT DETERMINISTIC MODIFIES SQL DATA
BEGIN
    CALL get_unique_id();
END //
DELIMITER ;


SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS = 0;
