#@(#) tasks.sql consistency
    
ALTER TABLE infostore
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY folder_id INT4 UNSIGNED NOT NULL,
    MODIFY version INT4 UNSIGNED NOT NULL,
    MODIFY locked_until BIGINT(64) UNSIGNED,
    MODIFY color_label INT4 UNSIGNED NOT NULL,
    MODIFY creating_date BIGINT(64) NOT NULL,
    MODIFY last_modified BIGINT(64) NOT NULL,
    MODIFY created_by INT4 UNSIGNED NOT NULL,
    MODIFY changed_by INT4 UNSIGNED,
    ENGINE=InnoDB;

ALTER TABLE infostore_document
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY infostore_id INT4 UNSIGNED NOT NULL,
    MODIFY version_number INT4 UNSIGNED NOT NULL,
    MODIFY creating_date BIGINT(64) NOT NULL,
    MODIFY last_modified BIGINT(64) NOT NULL,
    MODIFY created_by INT4 UNSIGNED NOT NULL,
    MODIFY changed_by INT4 UNSIGNED,
    MODIFY file_size INT4 UNSIGNED,
    MODIFY file_md5sum VARCHAR(32),
    ADD FOREIGN KEY (cid, infostore_id) REFERENCES infostore (cid, id),
    ENGINE=InnoDB;


ALTER TABLE del_infostore
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY folder_id INT4 UNSIGNED NOT NULL,
    MODIFY version INT4 UNSIGNED NOT NULL,
    MODIFY color_label INT4 UNSIGNED NOT NULL,
    MODIFY creating_date BIGINT(64) NOT NULL,
    MODIFY last_modified BIGINT(64) NOT NULL,
    MODIFY created_by INT4 UNSIGNED NOT NULL,
    MODIFY changed_by INT4 UNSIGNED,
    ENGINE=InnoDB;
    
ALTER TABLE del_infostore_document
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY infostore_id INT4 UNSIGNED NOT NULL,
    MODIFY version_number INT4 UNSIGNED NOT NULL,
    MODIFY creating_date BIGINT(64) NOT NULL,
    MODIFY last_modified BIGINT(64) NOT NULL,
    MODIFY created_by INT4 UNSIGNED NOT NULL,
    MODIFY changed_by INT4 UNSIGNED,
    MODIFY file_size INT4 UNSIGNED,
    MODIFY file_md5sum VARCHAR(32),
    ENGINE=InnoDB;
    
 ALTER TABLE infostore_property
     MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY name VARCHAR(128) NOT NULL,
    MODIFY namespace VARCHAR(128)NOT NULL,
    MODIFY value VARCHAR(255),
    MODIFY language VARCHAR(128),
    ENGINE=InnoDB;
    
ALTER TABLE infostore_lock
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY userid INT4 UNSIGNED NOT NULL,
    MODIFY timeout BIGINT(64) UNSIGNED NOT NULL,
    MODIFY type TINYINT UNSIGNED NOT NULL,
    MODIFY scope TINYINT UNSIGNED NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE lock_null
	MODIFY cid INT4 UNSIGNED NOT NULL,
	MODIFY id INT4 UNSIGNED NOT NULL,
	MODIFY url VARCHAR(255) NOT NULL,
	ENGINE=InnoDB;

ALTER TABLE lock_null_lock
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    ENGINE=InnoDB;
