#@(#) ldap2sql.sql consistency

ALTER TABLE groups
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    MODIFY gidNumber INT4 UNSIGNED DEFAULT 5000 NOT NULL,
	ENGINE=InnoDB;

ALTER TABLE del_groups
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE user
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY mail VARCHAR(256) NOT NULL,
    MODIFY mailEnabled boolean NOT NULL,
    MODIFY preferredLanguage VARCHAR(10) NOT NULL,
    MODIFY shadowLastChange INTEGER NOT NULL,
    MODIFY timeZone VARCHAR(128) NOT NULL,
    MODIFY contactId INT4 UNSIGNED NOT NULL,
	MODIFY passwordMech VARCHAR(32) DEFAULT '{CRYPT}' NOT NULL,
    MODIFY uidNumber INT4 UNSIGNED DEFAULT 5000 NOT NULL,
    MODIFY gidNumber INT4 UNSIGNED DEFAULT 5000 NOT NULL,
    MODIFY homeDirectory VARCHAR(128) DEFAULT '/tmp/foo' NOT NULL,
    MODIFY loginShell VARCHAR(128) DEFAULT '/bin/bash' NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE del_user
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY mail VARCHAR(256) NOT NULL,
    MODIFY mailEnabled boolean NOT NULL,
    MODIFY preferredLanguage VARCHAR(10) NOT NULL,
    MODIFY shadowLastChange INTEGER NOT NULL,
    MODIFY timeZone VARCHAR(128) NOT NULL,
    MODIFY contactId INT4 UNSIGNED NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE groups_member
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY member INT4 UNSIGNED NOT NULL,
    ADD FOREIGN KEY (cid, id) REFERENCES groups(cid, id),
    ADD FOREIGN KEY (cid, member) REFERENCES user(cid, id),
    ENGINE=InnoDB;

ALTER TABLE login2user
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY uid VARCHAR(128) NOT NULL,
    ADD FOREIGN KEY (cid, id) REFERENCES user(cid, id),
    ENGINE=InnoDB;

ALTER TABLE user_attribute
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY name VARCHAR(128) NOT NULL,
    MODIFY value VARCHAR(128) NOT NULL,
    ADD FOREIGN KEY (cid, id) REFERENCES user(cid, id),
    ENGINE=InnoDB;

ALTER TABLE resource_group
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY available boolean NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE del_resource_group
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY available boolean NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE resource
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY available boolean NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE del_resource
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY identifier VARCHAR(128) NOT NULL,
    MODIFY displayName VARCHAR(128) NOT NULL,
    MODIFY available boolean NOT NULL,
    MODIFY lastModified INT8 NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE resource_group_member
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY member INT4 UNSIGNED NOT NULL,
    ADD FOREIGN KEY (cid, id) REFERENCES resource_group(cid, id),
    ADD FOREIGN KEY (cid, member) REFERENCES resource(cid, id),
    ENGINE=InnoDB;

