
package com.openexchange.push.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.12
 * 2015-09-02T13:11:52.466+02:00
 * Generated source version: 2.7.12
 */

@WebFault(name = "PushSoapInterfaceException", targetNamespace = "http://soap.push.openexchange.com")
public class PushSoapInterfaceException_Exception extends java.lang.Exception {
    
    private com.openexchange.push.soap.PushSoapInterfaceException pushSoapInterfaceException;

    public PushSoapInterfaceException_Exception() {
        super();
    }
    
    public PushSoapInterfaceException_Exception(String message) {
        super(message);
    }
    
    public PushSoapInterfaceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PushSoapInterfaceException_Exception(String message, com.openexchange.push.soap.PushSoapInterfaceException pushSoapInterfaceException) {
        super(message);
        this.pushSoapInterfaceException = pushSoapInterfaceException;
    }

    public PushSoapInterfaceException_Exception(String message, com.openexchange.push.soap.PushSoapInterfaceException pushSoapInterfaceException, Throwable cause) {
        super(message, cause);
        this.pushSoapInterfaceException = pushSoapInterfaceException;
    }

    public com.openexchange.push.soap.PushSoapInterfaceException getFaultInfo() {
        return this.pushSoapInterfaceException;
    }
}
