
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.reseller.user.reseller.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T11:07:58.171+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "OXResellerUserService",
                      portName = "OXResellerUserServiceHttpEndpoint",
                      targetNamespace = "http://soap.reseller.admin.openexchange.com",
                      wsdlLocation = "null",
                      endpointInterface = "com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType")
                      
public class OXResellerUserServicePortTypeImpl4 implements OXResellerUserServicePortType {

    private static final Logger LOG = Logger.getLogger(OXResellerUserServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#change(com.openexchange.admin.soap.reseller.user.reseller.soap.Change  parameters )*
     */
    public void change(Change parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation change");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#delete(com.openexchange.admin.soap.reseller.user.reseller.soap.Delete  parameters )*
     */
    public void delete(Delete parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation delete");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#getContextAdmin(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.User getContextAdmin(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation getContextAdmin");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#list(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)java.lang.String  searchPattern ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> list(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,java.lang.String searchPattern,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation list");
        System.out.println(ctx);
        System.out.println(searchPattern);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#changeByModuleAccessName(com.openexchange.admin.soap.reseller.user.reseller.soap.ChangeByModuleAccessName  parameters )*
     */
    public void changeByModuleAccessName(ChangeByModuleAccessName parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation changeByModuleAccessName");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#createByModuleAccess(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  usrdata ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.UserModuleAccess  access ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.User createByModuleAccess(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User usrdata,com.openexchange.admin.soap.reseller.user.soap.dataobjects.UserModuleAccess access,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation createByModuleAccess");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(access);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#getModuleAccess(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  user ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.UserModuleAccess getModuleAccess(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User user,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation getModuleAccess");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.UserModuleAccess _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#create(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  usrdata ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.User create(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User usrdata,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation create");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#listAll(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> listAll(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation listAll");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#getMultipleData(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User>  users ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> getMultipleData(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> users,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation getMultipleData");
        System.out.println(ctx);
        System.out.println(users);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#getData(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  user ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.User getData(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User user,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation getData");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#deleteMultiple(com.openexchange.admin.soap.reseller.user.reseller.soap.DeleteMultiple  parameters )*
     */
    public void deleteMultiple(DeleteMultiple parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation deleteMultiple");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#exists(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  user ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.lang.Boolean exists(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User user,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation exists");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#listCaseInsensitive(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)java.lang.String  searchPattern ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> listCaseInsensitive(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,java.lang.String searchPattern,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation listCaseInsensitive");
        System.out.println(ctx);
        System.out.println(searchPattern);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.reseller.user.soap.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#getAccessCombinationName(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  user ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public java.lang.String getAccessCombinationName(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User user,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation getAccessCombinationName");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#changeByModuleAccess(com.openexchange.admin.soap.reseller.user.reseller.soap.ChangeByModuleAccess  parameters )*
     */
    public void changeByModuleAccess(ChangeByModuleAccess parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation changeByModuleAccess");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.reseller.user.reseller.soap.OXResellerUserServicePortType#createByModuleAccessName(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext  ctx ,)com.openexchange.admin.soap.reseller.user.soap.dataobjects.User  usrdata ,)java.lang.String  accessCombinationName ,)com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials  auth )*
     */
    public com.openexchange.admin.soap.reseller.user.soap.dataobjects.User createByModuleAccessName(com.openexchange.admin.soap.reseller.user.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.user.soap.dataobjects.User usrdata,java.lang.String accessCombinationName,com.openexchange.admin.soap.reseller.user.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    { 
        LOG.info("Executing operation createByModuleAccessName");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(accessCombinationName);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.reseller.user.soap.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new StorageException_Exception("StorageException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
    }

}
