
package com.openexchange.custom.parallels.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-11T15:32:34.649+02:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "InvalidCredentialsException", targetNamespace = "http://soap.parallels.custom.openexchange.com")
public class InvalidCredentialsException_Exception extends java.lang.Exception {
    
    private com.openexchange.custom.parallels.soap.InvalidCredentialsException invalidCredentialsException;

    public InvalidCredentialsException_Exception() {
        super();
    }
    
    public InvalidCredentialsException_Exception(String message) {
        super(message);
    }
    
    public InvalidCredentialsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCredentialsException_Exception(String message, com.openexchange.custom.parallels.soap.InvalidCredentialsException invalidCredentialsException) {
        super(message);
        this.invalidCredentialsException = invalidCredentialsException;
    }

    public InvalidCredentialsException_Exception(String message, com.openexchange.custom.parallels.soap.InvalidCredentialsException invalidCredentialsException, Throwable cause) {
        super(message, cause);
        this.invalidCredentialsException = invalidCredentialsException;
    }

    public com.openexchange.custom.parallels.soap.InvalidCredentialsException getFaultInfo() {
        return this.invalidCredentialsException;
    }
}
