#!/usr/bin/perl -w
#%# family=auto
#%# capabilities=autoconf

$showruntimestats="/opt/open-xchange/sbin/showruntimestats";
$showexec="$showruntimestats -j";

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
	if (-x $showexec) {
		print "yes\n";
		exit 0;
	}
	else {
		print "no\n";
		exit 0;
	}
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
	print "graph_title Cache objects\n";
	print "graph_args --base 1000 -l 0\n";
	print "graph_category Open Xchange\n";
	print "graph_vlabel Number of objects in caches\n";
	print "a.label Context\n";
	print "a.draw LINE1\n";
    print "b.label Filestore\n";
    print "b.draw LINE1\n";
    print "c.label DBPool\n";
    print "c.draw LINE1\n";
    print "d.label User\n";
    print "d.draw LINE1\n";
    print "e.label UserConfiguration\n";
    print "e.draw LINE1\n";
    print "f.label UserSettingMail\n";
    print "f.draw LINE1\n";
    print "g.label OXFolder\n";
    print "g.draw LINE1\n";
    print "h.label OXFolderQuery\n";
    print "h.draw LINE1\n";
    print "i.label IMAP Connection\n";
    print "i.draw LINE1\n";
    print "j.label Message\n";
    print "j.draw LINE1\n";
    print "k.label Mail Message\n";
    print "k.draw LINE1\n";
    print "l.label Mail Connection\n";
    print "l.draw LINE1\n";
    print "m.label Calendar\n";
    print "m.draw LINE1\n";
    print "n.label Session\n";
    print "n.draw LINE1\n";
	exit 0
}
									

open(SHOWRUNTIME,"$showexec |") || die "can not read monitoring output"; 

while (<SHOWRUNTIME>)
{
	if ( $_ =~ /Context /) {
		s/.*\=//; 
		$val=$_+0;
		print "a.value $val\n";
		next;
	}

	if ( $_ =~ /Filestore /) {
		s/.*\=//; 
		$val=$_+0;
		print "b.value $val\n";
		next;
	}
	
	if ( $_ =~ /OXDBPoolCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "c.value $val\n";
		next;
	}
	
	if ( $_ =~ /User /) {
		s/.*\=//; 
		$val=$_+0;
		print "d.value $val\n";
		next;
	}
	
	if ( $_ =~ /UserConfiguration /) {
		s/.*\=//; 
		$val=$_+0;
		print "e.value $val\n";
		next;
	}
	
	if ( $_ =~ /UserSettingMail /) {
		s/.*\=//; 
		$val=$_+0;
		print "f.value $val\n";
		next;
	}
	
	if ( $_ =~ /OXFolderCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "g.value $val\n";
		next;
	}
	
	if ( $_ =~ /OXFolderQueryCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "h.value $val\n";
		next;
	}
	
	if ( $_ =~ /OXIMAPConCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "i.value $val\n";
		next;
	}
	
	if ( $_ =~ /OXMessageCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "j.value $val\n";
		next;
	}
	
	if ( $_ =~ /MailMessageCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "k.value $val\n";
		next;
	}
	
	if ( $_ =~ /MailConnectionCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "l.value $val\n";
		next;
	}
	
	if ( $_ =~ /CalendarCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "m.value $val\n";
		next;
	}
	
	if ( $_ =~ /SessionCache /) {
		s/.*\=//; 
		$val=$_+0;
		print "n.value $val\n";
		next;
	}
}