#!/usr/bin/perl -w
#%# family=auto
#%# capabilities=autoconf

$showruntimestats="/opt/open-xchange/sbin/showruntimestats";
$showexec="$showruntimestats --generalstats";

if ( $ARGV[0] and $ARGV[0] eq "autoconf")
{
    if (-x $showruntimestats) {
        print "yes\n";
        exit 0;
    }
    else {
        print "no\n";
        exit 0;
    }
}

if ( $ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title Active Sessions\n";
    print "graph_args --base 1000 -l 0\n";
    print "graph_category Open Xchange\n";
    print "graph_vlabel Number\n";
    print "a.label Active Sessions\n";
    print "a.draw LINE1\n";
    exit 0
}

open(SHOWRUNTIME,"$showexec |") || die "can not read monitoring output";

while (<SHOWRUNTIME>)
{
    if ( $_ =~ /GeneralMonitor,NumberOfActiveSessions/) {
        s/.*\=//; 
        $val=$_+0;
        print "a.value $val\n";
        next;
    }
}

close (SHOWRUNTIME);
