
package com.openexchange.admin.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-30T17:24:19.761+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "InvalidDataException", targetNamespace = "http://soap.admin.openexchange.com")
public class InvalidDataException_Exception extends java.lang.Exception {
    
    private com.openexchange.admin.soap.InvalidDataException invalidDataException;

    public InvalidDataException_Exception() {
        super();
    }
    
    public InvalidDataException_Exception(String message) {
        super(message);
    }
    
    public InvalidDataException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDataException_Exception(String message, com.openexchange.admin.soap.InvalidDataException invalidDataException) {
        super(message);
        this.invalidDataException = invalidDataException;
    }

    public InvalidDataException_Exception(String message, com.openexchange.admin.soap.InvalidDataException invalidDataException, Throwable cause) {
        super(message, cause);
        this.invalidDataException = invalidDataException;
    }

    public com.openexchange.admin.soap.InvalidDataException getFaultInfo() {
        return this.invalidDataException;
    }
}
