
package com.openexchange.admin.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-30T17:24:19.788+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "NoSuchUserException", targetNamespace = "http://soap.admin.openexchange.com")
public class NoSuchUserException_Exception extends java.lang.Exception {
    
    private com.openexchange.admin.soap.NoSuchUserException noSuchUserException;

    public NoSuchUserException_Exception() {
        super();
    }
    
    public NoSuchUserException_Exception(String message) {
        super(message);
    }
    
    public NoSuchUserException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchUserException_Exception(String message, com.openexchange.admin.soap.NoSuchUserException noSuchUserException) {
        super(message);
        this.noSuchUserException = noSuchUserException;
    }

    public NoSuchUserException_Exception(String message, com.openexchange.admin.soap.NoSuchUserException noSuchUserException, Throwable cause) {
        super(message, cause);
        this.noSuchUserException = noSuchUserException;
    }

    public com.openexchange.admin.soap.NoSuchUserException getFaultInfo() {
        return this.noSuchUserException;
    }
}
