package com.openexchange.admin.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-30T17:24:19.801+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://soap.admin.openexchange.com", name = "OXUserServicePortType")
@XmlSeeAlso({com.openexchange.admin.rmi.exceptions.xsd.ObjectFactory.class, java.io.xsd.ObjectFactory.class, com.openexchange.admin.soap.dataobjects.xsd.ObjectFactory.class, java.rmi.xsd.ObjectFactory.class, com.openexchange.admin.rmi.dataobjects.xsd.ObjectFactory.class, ObjectFactory.class})
public interface OXUserServicePortType {

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:createByModuleAccess", output = "urn:createByModuleAccessResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:createByModuleAccessStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:createByModuleAccessInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:createByModuleAccessInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:createByModuleAccessNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:createByModuleAccessRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:createByModuleAccessDatabaseUpdateException")})
    @RequestWrapper(localName = "createByModuleAccess", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.CreateByModuleAccess")
    @WebMethod(action = "urn:createByModuleAccess")
    @ResponseWrapper(localName = "createByModuleAccessResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.CreateByModuleAccessResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.User createByModuleAccess(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "usrdata", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User usrdata,
        @WebParam(name = "access", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.UserModuleAccess access,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:change", output = "urn:changeResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:changeStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:changeInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:changeInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:changeNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:changeRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:changeNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:changeDatabaseUpdateException")})
    @WebMethod(action = "urn:change")
    public void change(
        @WebParam(partName = "parameters", name = "change", targetNamespace = "http://soap.admin.openexchange.com")
        Change parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:createByModuleAccessName", output = "urn:createByModuleAccessNameResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:createByModuleAccessNameStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:createByModuleAccessNameInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:createByModuleAccessNameInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:createByModuleAccessNameNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:createByModuleAccessNameRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:createByModuleAccessNameDatabaseUpdateException")})
    @RequestWrapper(localName = "createByModuleAccessName", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.CreateByModuleAccessName")
    @WebMethod(action = "urn:createByModuleAccessName")
    @ResponseWrapper(localName = "createByModuleAccessNameResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.CreateByModuleAccessNameResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.User createByModuleAccessName(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "usrdata", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User usrdata,
        @WebParam(name = "access_combination_name", targetNamespace = "http://soap.admin.openexchange.com")
        java.lang.String accessCombinationName,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:getModuleAccess", output = "urn:getModuleAccessResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:getModuleAccessStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:getModuleAccessInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:getModuleAccessInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:getModuleAccessNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:getModuleAccessRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:getModuleAccessNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:getModuleAccessDatabaseUpdateException")})
    @RequestWrapper(localName = "getModuleAccess", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetModuleAccess")
    @WebMethod(action = "urn:getModuleAccess")
    @ResponseWrapper(localName = "getModuleAccessResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetModuleAccessResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.UserModuleAccess getModuleAccess(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "user", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User user,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:listAll", output = "urn:listAllResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:listAllStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:listAllInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:listAllInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:listAllNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:listAllRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:listAllDatabaseUpdateException")})
    @RequestWrapper(localName = "listAll", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ListAll")
    @WebMethod(action = "urn:listAll")
    @ResponseWrapper(localName = "listAllResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ListAllResponse")
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> listAll(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:getContextAdmin", output = "urn:getContextAdminResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:getContextAdminStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:getContextAdminInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:getContextAdminInvalidDataException"), @FaultAction(className = DuplicateExtensionException_Exception.class, value = "urn:getContextAdminDuplicateExtensionException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:getContextAdminRemoteException")})
    @RequestWrapper(localName = "getContextAdmin", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetContextAdmin")
    @WebMethod(action = "urn:getContextAdmin")
    @ResponseWrapper(localName = "getContextAdminResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetContextAdminResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.User getContextAdmin(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, DuplicateExtensionException_Exception, RemoteException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:changeByModuleAccessName", output = "urn:changeByModuleAccessNameResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:changeByModuleAccessNameStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:changeByModuleAccessNameInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:changeByModuleAccessNameInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:changeByModuleAccessNameNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:changeByModuleAccessNameRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:changeByModuleAccessNameNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:changeByModuleAccessNameDatabaseUpdateException")})
    @WebMethod(action = "urn:changeByModuleAccessName")
    public void changeByModuleAccessName(
        @WebParam(partName = "parameters", name = "changeByModuleAccessName", targetNamespace = "http://soap.admin.openexchange.com")
        ChangeByModuleAccessName parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:delete", output = "urn:deleteResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:deleteStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:deleteInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:deleteInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:deleteNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:deleteRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:deleteNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:deleteDatabaseUpdateException")})
    @WebMethod(action = "urn:delete")
    public void delete(
        @WebParam(partName = "parameters", name = "delete", targetNamespace = "http://soap.admin.openexchange.com")
        Delete parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:deleteMultiple", output = "urn:deleteMultipleResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:deleteMultipleStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:deleteMultipleInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:deleteMultipleInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:deleteMultipleNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:deleteMultipleRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:deleteMultipleNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:deleteMultipleDatabaseUpdateException")})
    @WebMethod(action = "urn:deleteMultiple")
    public void deleteMultiple(
        @WebParam(partName = "parameters", name = "deleteMultiple", targetNamespace = "http://soap.admin.openexchange.com")
        DeleteMultiple parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:changeByModuleAccess", output = "urn:changeByModuleAccessResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:changeByModuleAccessStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:changeByModuleAccessInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:changeByModuleAccessInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:changeByModuleAccessNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:changeByModuleAccessRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:changeByModuleAccessNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:changeByModuleAccessDatabaseUpdateException")})
    @WebMethod(action = "urn:changeByModuleAccess")
    public void changeByModuleAccess(
        @WebParam(partName = "parameters", name = "changeByModuleAccess", targetNamespace = "http://soap.admin.openexchange.com")
        ChangeByModuleAccess parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:getMultipleData", output = "urn:getMultipleDataResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:getMultipleDataStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:getMultipleDataInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:getMultipleDataInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:getMultipleDataNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:getMultipleDataRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:getMultipleDataNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:getMultipleDataDatabaseUpdateException")})
    @RequestWrapper(localName = "getMultipleData", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetMultipleData")
    @WebMethod(action = "urn:getMultipleData")
    @ResponseWrapper(localName = "getMultipleDataResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetMultipleDataResponse")
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> getMultipleData(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "users", targetNamespace = "http://soap.admin.openexchange.com")
        java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> users,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:getAccessCombinationName", output = "urn:getAccessCombinationNameResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:getAccessCombinationNameStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:getAccessCombinationNameInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:getAccessCombinationNameInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:getAccessCombinationNameNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:getAccessCombinationNameRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:getAccessCombinationNameNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:getAccessCombinationNameDatabaseUpdateException")})
    @RequestWrapper(localName = "getAccessCombinationName", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetAccessCombinationName")
    @WebMethod(action = "urn:getAccessCombinationName")
    @ResponseWrapper(localName = "getAccessCombinationNameResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetAccessCombinationNameResponse")
    public java.lang.String getAccessCombinationName(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "user", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User user,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:create", output = "urn:createResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:createStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:createInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:createInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:createNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:createRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:createDatabaseUpdateException")})
    @RequestWrapper(localName = "create", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.Create")
    @WebMethod(action = "urn:create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.CreateResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.User create(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "usrdata", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User usrdata,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:list", output = "urn:listResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:listStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:listInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:listInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:listNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:listRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:listDatabaseUpdateException")})
    @RequestWrapper(localName = "list", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.List")
    @WebMethod(action = "urn:list")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ListResponse")
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> list(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "search_pattern", targetNamespace = "http://soap.admin.openexchange.com")
        java.lang.String searchPattern,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:listCaseInsensitive", output = "urn:listCaseInsensitiveResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:listCaseInsensitiveStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:listCaseInsensitiveInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:listCaseInsensitiveInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:listCaseInsensitiveNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:listCaseInsensitiveRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:listCaseInsensitiveDatabaseUpdateException")})
    @RequestWrapper(localName = "listCaseInsensitive", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ListCaseInsensitive")
    @WebMethod(action = "urn:listCaseInsensitive")
    @ResponseWrapper(localName = "listCaseInsensitiveResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ListCaseInsensitiveResponse")
    public java.util.List<com.openexchange.admin.soap.dataobjects.xsd.User> listCaseInsensitive(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "search_pattern", targetNamespace = "http://soap.admin.openexchange.com")
        java.lang.String searchPattern,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:changeModuleAccessGlobal", output = "urn:changeModuleAccessGlobalResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:changeModuleAccessGlobalStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:changeModuleAccessGlobalInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:changeModuleAccessGlobalInvalidDataException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:changeModuleAccessGlobalRemoteException")})
    @WebMethod(action = "urn:changeModuleAccessGlobal")
    public void changeModuleAccessGlobal(
        @WebParam(partName = "parameters", name = "changeModuleAccessGlobal", targetNamespace = "http://soap.admin.openexchange.com")
        ChangeModuleAccessGlobal parameters
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, RemoteException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:exists", output = "urn:existsResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:existsStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:existsInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:existsInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:existsNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:existsRemoteException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:existsDatabaseUpdateException")})
    @RequestWrapper(localName = "exists", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.Exists")
    @WebMethod(action = "urn:exists")
    @ResponseWrapper(localName = "existsResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.ExistsResponse")
    public java.lang.Boolean exists(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "user", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User user,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, DatabaseUpdateException_Exception;

    @WebResult(name = "return", targetNamespace = "http://soap.admin.openexchange.com")
    @Action(input = "urn:getData", output = "urn:getDataResponse", fault = {@FaultAction(className = StorageException_Exception.class, value = "urn:getDataStorageException"), @FaultAction(className = InvalidCredentialsException_Exception.class, value = "urn:getDataInvalidCredentialsException"), @FaultAction(className = InvalidDataException_Exception.class, value = "urn:getDataInvalidDataException"), @FaultAction(className = NoSuchContextException_Exception.class, value = "urn:getDataNoSuchContextException"), @FaultAction(className = RemoteException_Exception.class, value = "urn:getDataRemoteException"), @FaultAction(className = NoSuchUserException_Exception.class, value = "urn:getDataNoSuchUserException"), @FaultAction(className = DatabaseUpdateException_Exception.class, value = "urn:getDataDatabaseUpdateException")})
    @RequestWrapper(localName = "getData", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetData")
    @WebMethod(action = "urn:getData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://soap.admin.openexchange.com", className = "com.openexchange.admin.soap.GetDataResponse")
    public com.openexchange.admin.soap.dataobjects.xsd.User getData(
        @WebParam(name = "ctx", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.Context ctx,
        @WebParam(name = "user", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.soap.dataobjects.xsd.User user,
        @WebParam(name = "auth", targetNamespace = "http://soap.admin.openexchange.com")
        com.openexchange.admin.rmi.dataobjects.xsd.Credentials auth
    ) throws StorageException_Exception, InvalidCredentialsException_Exception, InvalidDataException_Exception, NoSuchContextException_Exception, RemoteException_Exception, NoSuchUserException_Exception, DatabaseUpdateException_Exception;
}
