
=head1 Axis2 integration into OX


This document describes how Axis2 is integrated into OX and how to
deploy SOAP services into the system.

=head2 Axis2

Apache Axis is an implementation of the SOAP ("Simple Object Access
Protocol") submission to W3C.

See http://ws.apache.org/axis2/ for more details.

=head2 OX Integration

Axis2 is basically a servlet that needs to be deployed into a servlet
container like tomcat. OX ships with an own servlet container and the
OX Axis2 bundle is integrated into this container. All you have to do
is to install the C<open-xchange-axis2> (C<com.openexchange.axis2>) bundle.

A successfull integration of that bundle looks like this in the
C</var/log/open-xchange/open-xchange.log.0> logfile:

C<INFO: New servlet "org.apache.axis2.transport.http.AxisServlet" successfully registered to "servlet/axis2/*">

=head2 Deploying own SOAP Services

The Axis2 bundle and its directories reside in
C</opt/open-xchange/bundles/com.openexchange.axis2/>.

To deploy an own service, simply put the C<.aar> file into the
directory C<services> within this directory and restart the
open-xchange server or wait some time until the Axis2 bundle did
recognize it automatically.

=cut
