define("io.ox/mail/write/view-main",["io.ox/core/extensions","io.ox/mail/util","io.ox/mail/actions","io.ox/core/tk/view","io.ox/core/tk/model","io.ox/contacts/api","io.ox/contacts/util","io.ox/mail/util","io.ox/preview/main","gettext!io.ox/mail/mail","io.ox/core/tk/autocomplete"],function(a,b,c,d,e,f,g,h,i,j){var k,l,m=330,n=d.extend({initialize:function(){this.signatures=[],this.sections={}},focusSection:function(a){this.sections[a].find("input[type!=hidden]").eq(0).focus()},addSection:function(
a,b,c,d){return this.sections[a+"Label"]=$("<div>").attr("data-section-label",a).addClass("io-ox-label").text(b+"").prepend(d?$("<a>",{href:"#",tabindex:"7"}).addClass("collapse").text(j("Hide")).on("click",$.preventDefault):$()),d?this.sections[a+"Label"].on("click",{id:a},$.proxy(t,this)):this.sections[a+"Label"].css("cursor","default"),this.sections[a]=$("<div>").addClass("section").attr("data-section",a),this.sidepanel.append(this.sections[a+"Label"],this.sections[a]),c===!1&&(this.sections[a+"Label"
].hide(),this.sections[a].hide()),this.sections[a]},showSection:function(a,b){this.sections[a+"Label"].show(),this.sections[a].show().trigger("show"),b!==!1&&this.focusSection(a),this.sections[a+"Link"].hide()},hideSection:function(a,b){this.sections[a+"Label"].add(this.sections[a]).hide(),$(b).trigger("hide"),this.sections[a+"Link"].show()},addLink:function(a,b){return(this.sections[a+"Link"]=$("<div>")).addClass("section-link").append($("<a>",{href:"#",tabindex:"5"}).attr("data-section-link",a)
.text(b+"").on("click",{id:a},$.proxy(u,this))).appendTo(this.sidepanel)},applyHighPriority:function(a){a?this.priorityOverlay.addClass("high"):this.priorityOverlay.removeClass("high")},addUpload:function(){var a,b=this;return Modernizr.file?a={type:"file",name:"upload",multiple:"multiple",tabindex:"2"}:a={type:"file",name:"upload",tabindex:"2"},$("<div>").addClass("section-item upload").append($.labelize($("<input>",a).on("change",function(a){k(a,b)}),"mail_attachment")).appendTo(b.sections.attachments
)},createField:function(a){var b=this,c=b.app.getWindowNode();return $("<div>").addClass("fieldset").append($("<label>",{"for":"writer_field_"+a}).addClass("wrapping-label").append($("<input>",{type:"text",tabindex:"2",id:"writer_field_"+a}).attr("data-type",a).addClass("discreet").autocomplete({source:function(b){return f.autocomplete(b).pipe(function(b){var d={};return c.find("input[name="+a+"]").map(function(){var a=h.parseRecipient($(this).val())[1];d[a]=!0}),_(b).filter(function(a){return d[
a.email]===undefined})})},stringify:function(a){return a.display_name?'"'+a.display_name+'" <'+a.email+">":a.email},draw:function(a,b){x.call(null,this,a,b)},click:function(c){w.call(b,a,$(this))},blur:function(c){w.call(b,a,$(this))}}).on("keyup",function(c){if(c.which===13)w.call(b,a,$(this));else{var d=$(this).val();/^to:?\s/i.test(d)?($(this).val(""),b.showSection("to")):/^cc:?\s/i.test(d)?($(this).val(""),b.showSection("cc")):/^bcc:?\s/i.test(d)&&($(this).val(""),b.showSection("bcc"))}})))},
createRecipientList:function(a){return(this.sections[a+"List"]=$("<div>")).addClass("recipient-list").hide()},addRecipients:function(a,b){_(b).each(function(b){var c=$("<div>");y(a,c,{display_name:b[0]?b[0].replace(/^('|")|('|")$/g,""):b[1],email:b[1],contact:{}}),this.sections[a+"List"].append(c)},this),b&&b.length&&this.sections[a+"List"].show().trigger("show")},render:function(){var b=this,c=b.app;this.main=$("<div>").addClass("rightside").css({left:m+"px"}),this.main.append($("<div>").addClass
("abs io-ox-mail-write-main").append($("<div>").addClass("io-ox-label").text(j("Subject"))).append($("<div>").css("position","relative").append($("<div>").addClass("subject-wrapper").append($.labelize(this.subject=$("<input>").attr({type:"text",name:"subject",tabindex:"3",autocomplete:"off"}).addClass("subject").val("").on("keydown",function(a){if(a.which===13||a.which===9&&!a.shiftKey)a.preventDefault(),c.getEditor().focus()}).on("keyup",function(){var a=$.trim($(this).val());c.getWindow().setTitle
(a),c.setTitle(a)}),"mail_subject"))).append(this.priorityOverlay=$("<div>").addClass("priority-overlay").attr("title","Priority").text("★★★").on("click",$.proxy(v,this))).append($("<div>").addClass("btn-group sendbutton-wrapper").append($("<a>",{href:"#",tabindex:"8"}).addClass("btn btn-primary").css("width","100px").text(j("Send")).on("click",function(b){b.preventDefault(),a.point("io.ox/mail/write/actions/send").invoke("action",null,c)}).button()).append($("<a>",{href:"#",tabindex:"9"}).attr("data-toggle"
,"dropdown").addClass("btn btn-primary dropdown-toggle").append($("<span>").addClass("caret")).button()).append($("<ul>").addClass("dropdown-menu dropdown-right").append($("<li>").append($("<a>",{href:"#"}).text(j("Save as draft")).on("click",function(b){b.preventDefault(),a.point("io.ox/mail/write/actions/draft").invoke("action",null,c)})))))).append($("<div>").addClass("abs editor-outer-container").append($("<div>").addClass("abs editor-background")).append($("<div>").addClass("abs editor-print-margin"
)).append($("<div>").addClass("abs editor-inner-container").css("overflow","hidden").append(this.textarea=$("<textarea>").attr({name:"content",tabindex:"4",disabled:"disabled"}).addClass("text-editor"))))).append($("<div>",{id:"myGrowl"}).addClass("jGrowl").css({position:"absolute",right:"0",top:"0"})),this.scrollpane=$("<div>").css({width:m-26+"px"}).addClass("leftside io-ox-mail-write-sidepanel"),this.sidepanel=this.scrollpane.scrollable(),this.addSection("to",j("To")).append(this.createRecipientList
("to")).append(this.createField("to")),this.addSection("cc",j("Copy to"),!1,!0).append(this.createRecipientList("cc")).append(this.createField("cc")),this.addLink("cc",j("Copy (CC) to ...")),this.addSection("bcc",j("Blind copy to"),!1,!0).append(this.createRecipientList("bcc")).append(this.createField("bcc")),this.addLink("bcc",j("Blind copy (BCC) to ...")),this.addSection("attachments",j("Attachments"),!1,!0),this.addUpload(),this.addLink("attachments",j("Attachments")),this.signatures.length&&(
this.addSection("signatures",j("Signatures"),!1,!0).append(_(this.signatures.concat(o)).inject(function(a,b,d){var e=(b.signature_text||"").replace(/\s\s+/g," ").replace(/(\W\W\W)\W+/g,"$1 ");return e=e.length>150?e.substr(0,150)+" ...":e,a.add($("<div>").addClass("section-item pointer").addClass(d>=this.signatures.length?"signature-remove":"").append($("<a>",{href:"#",tabindex:"5"}).on("click dragstart",$.preventDefault).text(b.signature_name)).append(e.length?$("<div>").addClass("signature-preview"
).text(" "+e):$()).on("click",{index:d},function(a){a.preventDefault(),c.setSignature(a)}))},$(),this)),this.addLink("signatures",j("Signatures"))),this.addSection("options",j("Options"),!1,!0).append($("<div>").addClass("section-item").css({paddingTop:"0.5em",paddingBottom:"0.5em"}).append($("<span>").addClass("group-label").text(j("Priority"))).append(B("priority","1",j("High"))).append(B("priority","3",j("Normal"),!0)).append(B("priority","5",j("Low"))).on("change","input",function(){var a=$(this
);a.val()==="1"&&a.prop("checked")?b.applyHighPriority(!0):b.applyHighPriority(!1)})).append($("<div>").addClass("section-item").css({paddingTop:"1em",paddingBottom:"1em"}).append(C("receipt",j("Delivery Receipt")))).append($("<div>").addClass("section-item").css({paddingTop:"1em",paddingBottom:"1em"}).append(C("vcard",j("Attach vCard")))),this.addLink("options",j("More ..."));var d=function(a){a.preventDefault(),c.setFormat(a.data.format).done(function(){c.getEditor().focus()})};Modernizr.touch||
this.addSection("format",j("Text format"),!0,!1).append($("<div>").addClass("change-format").append($("<a>",{href:"#"}).text(j("Text")).on("click",{format:"text"},d)).append($.txt("  –  ")).append($("<a>",{href:"#"}).text(j("HTML")).on("click",{format:"html"},d)))}}),o={signature_name:j("No signature")},p=function(a){if(a.message)return(new i.Preview({mimetype:"message/rfc822"})).supportsPreview();else return window.FileReader&&/^image\/(png|gif|jpe?g|bmp)$/i.test(a.type)},q=function(a){return $("<a>"
,{href:"#"}).text(j("Preview")).on("click",{file:a},function(a){a.preventDefault(),require(["io.ox/core/tk/dialogs"],function(b){(new b.SidePopup).show(a,function(b){var c,d,e=a.data.file,f=e.message;f?(c=new i.Preview({data:{nested_message:f},mimetype:"message/rfc822"},{width:b.parent().width(),height:"auto"}),c.supportsPreview()&&(c.appendTo(b),b.append($("<div>").text(" ")))):(d=new FileReader,d.onload=function(a){b.css({width:"100%",height:"100%"}).append($("<div>").css({width:"100%",height:"100%"
,backgroundImage:"url("+a.target.result+")",backgroundRepeat:"no-repeat",backgroundPosition:"center center",backgroundSize:"contain"})),d=d.onload=null},d.readAsDataURL(e))})})})},r=[j("B"),j("KB"),j("MB"),j("GB"),j("TB"),j("PB"),j("EB"),j("ZB"),j("YB")];"use strict";function s(a){var b=0,c=r.length;while(a>1024&&b<c)a=a/1024,b++;return j("%1$d %2$s",Math.round(a,1),r[b])}k=function(a,b){var c=$(a.currentTarget),d=c.prop("attachment")||c.prop("file")||c.prop("nested"),e=d?[d]:a.target.files;e.length&&
(_(e).each(function(a){var c=a.size||a.file_size;c=c!==undefined?s(c)+"  ":"",b.sections.attachments.append($("<div>").addClass("section-item file").append($('<div class="row-1">').text(a.filename||a.name||""),$('<div class="row-2">').append($("<span>").addClass("filesize").text(c),p(a)?q(a):$(),$.txt(" ")),$("<a>",{href:"#",tabindex:"6"}).addClass("remove").append($("<div>").addClass("icon").text("x")).on("click",function(a){a.preventDefault(),$(this).parent().prev().remove(),$(this).parent().remove
()})))}),$(a.target).closest(".section-item.upload").hide()),b.addUpload(k)};function t(a){var b=a.data.id;a.preventDefault(),this.hideSection(b,a.target)}function u(a){var b=a.data.id;a.preventDefault(),this.showSection(b,a.target)}function v(){var a=this.form.find("input[name=priority][value=1]"),b=this.form.find("input[name=priority][value=3]");a.prop("checked")?(a.prop("checked",!1),b.prop("checked",!0),this.applyHighPriority(!1)):(a.prop("checked",!0),b.prop("checked",!1),this.applyHighPriority
(!0))}function w(a,b){var c=h.parseRecipients(b.val());c.length?(this.addRecipients(a,c),b.val("").focus()):$.trim(b.val())!==""&&b.attr("disabled","disabled").css({border:"1px solid #a00",backgroundColor:"#fee"}).shake().done(function(){b.css({border:"",backgroundColor:""}).removeAttr("disabled").focus()})}function x(a,b,c){var d=$("<div>").addClass("contact-image"),e=g.getImage(b.contact),f=A(b.display_name,c),h=A(b.email,c);Modernizr.backgroundsize?d.css("backgroundImage","url("+e+")"):d.append
($("<img>",{src:e,alt:""}).css({width:"100%",height:"100%"})),a.addClass("io-ox-mail-write-contact").append(d,$("<div>").addClass("person-link ellipsis").html(f+" "),$("<div>").addClass("ellipsis").html(h))}function y(a,b,c){b.addClass("io-ox-mail-write-contact section-item").append(f.getPicture(c.email+"").addClass("contact-image"),$("<input>",{type:"hidden",name:a,value:z(c)}),$("<div>").append($("<a>",{href:"#"}).addClass("person-link").text(c.display_name+" ").on("click",{display_name:c.display_name
,email1:c.email},l)),$("<div>").text(String(c.email||"").toLowerCase()),$("<a>",{href:"#",tabindex:"6"}).addClass("remove").append($("<div>").addClass("icon").text("x")).on("click",{id:a},function(a){var b;a.preventDefault(),b=$(this).parents().find(".recipient-list"),$(this).parent().remove(),b.children().length===0&&b.hide()}))}function z(a){return a.display_name?'"'+a.display_name.replace(/"/g,'"')+'" <'+a.email+">":"<"+a.email+">"}l=function(b){b.preventDefault(b),a.point("io.ox/core/person:action"
).each(function(a){_.call(a.action,b.data,b)})};function A(a,b){return String(a).replace(/</g,"&lt;").replace(new RegExp(b,"i"),"<b>"+b+"</b>")}function B(a,b,c,d){var e=a+"_"+b+"_"+_.now(),f=$("<input>",{type:"radio",name:a,id:e,value:b,tabindex:"5"}),g=$("<label>",{"for":e}).text("  "+c+"     ");return d&&f.attr("checked","checked"),Modernizr.touch&&g.on("click",{id:e},function(){var a=$(this).prev();a.prop("selected",!a.prop("selected")).trigger("change")}),f.add(g)}function C(a,b,c){var d=a+"_"+
_.now(),e=$("<input>",{type:"checkbox",name:a,id:d,value:"1",tabindex:"5"}),f=$("<label>",{"for":d}).text("  "+b+"     ");return c&&e.attr("checked","checked"),Modernizr.touch&&f.on("click",{id:d},function(){var a=$(this).prev();a.prop("selected",!a.prop("selected")).trigger("change")}),e.add(f)}return n})