
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.reseller.group.reseller.soap;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import com.openexchange.admin.rmi.OXGroupInterface;
import com.openexchange.admin.rmi.exceptions.DatabaseUpdateException;
import com.openexchange.admin.rmi.exceptions.InvalidCredentialsException;
import com.openexchange.admin.rmi.exceptions.InvalidDataException;
import com.openexchange.admin.rmi.exceptions.NoSuchContextException;
import com.openexchange.admin.rmi.exceptions.NoSuchGroupException;
import com.openexchange.admin.rmi.exceptions.NoSuchUserException;
import com.openexchange.admin.rmi.exceptions.StorageException;
import com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.Context;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.Database;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.Entry;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.SOAPMapEntry;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.SOAPStringMap;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.SOAPStringMapMap;
import com.openexchange.admin.soap.reseller.group.soap.dataobjects.User;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T11:09:53.189+02:00
 * Generated source version: 2.6.0
 *
 */

@javax.jws.WebService(
                      serviceName = "OXResellerGroupService",
                      portName = "OXResellerGroupServiceHttpSoap12Endpoint",
                      targetNamespace = "http://soap.reseller.admin.openexchange.com",

                      endpointInterface = "com.openexchange.admin.soap.reseller.group.reseller.soap.OXResellerGroupServicePortType")

public class OXResellerGroupServicePortTypeImpl implements OXResellerGroupServicePortType {

    public static final AtomicReference<OXGroupInterface> RMI_REFERENCE = new AtomicReference<OXGroupInterface>();

    private static OXGroupInterface getGroupInterface() throws RemoteException_Exception {
        final OXGroupInterface groupInterface = RMI_REFERENCE.get();
        if (null == groupInterface) {
            throw new RemoteException_Exception("Missing "+OXGroupInterface.class.getName() + " instance.");
        }
        return groupInterface;
    }

    @Override
    public void change(Change parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            groupInterface.change(soap2Context(parameters.ctx), soap2Group(parameters.grp), soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final NoSuchUserException e) {
            throw new NoSuchUserException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public void removeMember(RemoveMember parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final List<User> list = parameters.members;
            if (null == list || list.isEmpty()) {
                throw new InvalidDataException_Exception("Missing members");
            }
            final com.openexchange.admin.rmi.dataobjects.User[] members = new com.openexchange.admin.rmi.dataobjects.User[list.size()];
            for (int i = 0; i < members.length; i++) {
                members[i] = soap2User(list.get(i));
            }
            groupInterface.removeMember(soap2Context(parameters.ctx), soap2Group(parameters.grp), members, soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final NoSuchUserException e) {
            throw new NoSuchUserException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public void delete(Delete parameters) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            groupInterface.delete(soap2Context(parameters.ctx), soap2Group(parameters.grp), soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group> list(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,java.lang.String pattern,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final com.openexchange.admin.rmi.dataobjects.Group[] groups = groupInterface.list(soap2Context(ctx), pattern, soap2Credentials(auth));
            if (null == groups) {
                return Collections.emptyList();
            }
            final int length = groups.length;
            final List<Group> list = new ArrayList<Group>(length);
            for (int i = 0; i < groups.length; i++) {
                list.add(group2Soap(groups[i]));
            }
            return list;
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.User> getMembers(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group grp,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final com.openexchange.admin.rmi.dataobjects.User[] members = groupInterface.getMembers(soap2Context(ctx), soap2Group(grp), soap2Credentials(auth));
            if (null == members) {
                return Collections.emptyList();
            }
            final int length = members.length;
            final List<User> list = new ArrayList<User>(length);
            for (int i = 0; i < members.length; i++) {
                list.add(user2Soap(members[i]));
            }
            return list;
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group getDefaultGroup(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            return group2Soap(groupInterface.getDefaultGroup(soap2Context(ctx), soap2Credentials(auth)));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public void addMember(AddMember parameters) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final List<User> list = parameters.members;
            if (null == list || list.isEmpty()) {
                throw new InvalidDataException_Exception("Missing members");
            }
            final com.openexchange.admin.rmi.dataobjects.User[] members = new com.openexchange.admin.rmi.dataobjects.User[list.size()];
            for (int i = 0; i < members.length; i++) {
                members[i] = soap2User(list.get(i));
            }
            groupInterface.addMember(soap2Context(parameters.ctx), soap2Group(parameters.grp), members, soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final NoSuchUserException e) {
            throw new NoSuchUserException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group create(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group grp,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            return group2Soap(groupInterface.create(soap2Context(ctx), soap2Group(grp), soap2Credentials(auth)));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchUserException e) {
            throw new NoSuchUserException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group> listAll(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final com.openexchange.admin.rmi.dataobjects.Group[] groups = groupInterface.listAll(soap2Context(ctx), soap2Credentials(auth));
            if (null == groups) {
                return Collections.emptyList();
            }
            final int length = groups.length;
            final List<Group> list = new ArrayList<Group>(length);
            for (int i = 0; i < groups.length; i++) {
                list.add(group2Soap(groups[i]));
            }
            return list;
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group> getMultipleData(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group> list,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final com.openexchange.admin.rmi.dataobjects.Group[] groups = new com.openexchange.admin.rmi.dataobjects.Group[list.size()];
            for (int i = 0; i < groups.length; i++) {
                groups[i] = soap2Group(list.get(i));
            }
            final com.openexchange.admin.rmi.dataobjects.Group[] retGroups = groupInterface.getData(soap2Context(ctx), groups, soap2Credentials(auth));
            if (null == retGroups) {
                return Collections.emptyList();
            }
            final int length = retGroups.length;
            final List<Group> ret = new ArrayList<Group>(length);
            for (int i = 0; i < retGroups.length; i++) {
                ret.add(group2Soap(retGroups[i]));
            }
            return ret;
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group getData(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group grp,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            return group2Soap(groupInterface.getData(soap2Context(ctx), soap2Group(grp), soap2Credentials(auth)));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public void deleteMultiple(DeleteMultiple parameters) throws DatabaseUpdateException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , NoSuchGroupException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final List<Group> grps = parameters.grps;
            final com.openexchange.admin.rmi.dataobjects.Group[] groups = new com.openexchange.admin.rmi.dataobjects.Group[grps.size()];
            for (int i = 0; i < groups.length; i++) {
                groups[i] = soap2Group(grps.get(i));
            }
            groupInterface.delete(soap2Context(parameters.ctx), groups, soap2Credentials(parameters.auth));
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchGroupException e) {
            throw new NoSuchGroupException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    @Override
    public java.util.List<com.openexchange.admin.soap.reseller.group.soap.dataobjects.Group> listGroupsForUser(com.openexchange.admin.soap.reseller.group.reseller.soap.dataobjects.ResellerContext ctx,com.openexchange.admin.soap.reseller.group.soap.dataobjects.User usr,com.openexchange.admin.soap.reseller.group.rmi.dataobjects.Credentials auth) throws DatabaseUpdateException_Exception , NoSuchUserException_Exception , InvalidCredentialsException_Exception , DuplicateExtensionException_Exception , NoSuchContextException_Exception , StorageException_Exception , RemoteException_Exception , InvalidDataException_Exception    {
        final OXGroupInterface groupInterface = getGroupInterface();
        try {
            final com.openexchange.admin.rmi.dataobjects.Group[] groups = groupInterface.listGroupsForUser(soap2Context(ctx), soap2User(usr), soap2Credentials(auth));
            if (null == groups) {
                return Collections.emptyList();
            }
            final int length = groups.length;
            final List<Group> list = new ArrayList<Group>(length);
            for (int i = 0; i < groups.length; i++) {
                list.add(group2Soap(groups[i]));
            }
            return list;
        } catch (final RemoteException e) {
            throw new RemoteException_Exception(e.getMessage(), e);
        } catch (final InvalidCredentialsException e) {
            throw new InvalidCredentialsException_Exception(e.getMessage(), e);
        } catch (final NoSuchContextException e) {
            throw new NoSuchContextException_Exception(e.getMessage(), e);
        } catch (final StorageException e) {
            throw new StorageException_Exception(e.getMessage(), e);
        } catch (final InvalidDataException e) {
            throw new InvalidDataException_Exception(e.getMessage(), e);
        } catch (final NoSuchUserException e) {
            throw new NoSuchUserException_Exception(e.getMessage(), e);
        } catch (final DatabaseUpdateException e) {
            throw new DatabaseUpdateException_Exception(e.getMessage(), e);
        }
    }

    private static com.openexchange.admin.rmi.dataobjects.Credentials soap2Credentials(final Credentials soapCredentials) {
        if (null == soapCredentials) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Credentials credentials = new com.openexchange.admin.rmi.dataobjects.Credentials();
        final String login = soapCredentials.getLogin();
        if (null != login) {
            credentials.setLogin(login);
        }
        final String password = soapCredentials.getPassword();
        if (null != password) {
            credentials.setPassword(password);
        }
        return credentials;
    }

    private static com.openexchange.admin.rmi.dataobjects.User soap2User(final User soapUser) {
        if (null == soapUser) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.User user = new com.openexchange.admin.rmi.dataobjects.User();
        final Boolean guiSpamFilterEnabled = soapUser.isGuiSpamFilterEnabled();
        if (null != guiSpamFilterEnabled) {
            user.setGui_spam_filter_enabled(guiSpamFilterEnabled);
        }

        if (null != soapUser.getAliases()) {
            for (String alias : soapUser.getAliases()) {
                if (null != alias) {
                    user.addAlias(alias);
                }
            }
        }

        final XMLGregorianCalendar anniversary = soapUser.getAnniversary();
        if (null != anniversary) {
            user.setAnniversary(anniversary.toGregorianCalendar().getTime());
        }

        final String assistantName = soapUser.getAssistantName();
        if (null != assistantName) {
            user.setAssistant_name(assistantName);
        }

        final XMLGregorianCalendar birthday = soapUser.getBirthday();
        if (null != birthday) {
            user.setBirthday(birthday.toGregorianCalendar().getTime());
        }

        String tmp = soapUser.getBranches();
        if (tmp != null) {
            user.setBranches(tmp);
        }

        tmp = soapUser.getBusinessCategory();
        if (tmp != null) {
            user.setBusiness_category(tmp);
        }

        tmp = soapUser.getCategories();
        if (tmp != null) {
            user.setCategories(tmp);
        }

        tmp = soapUser.getCellularTelephone1();
        if (tmp != null) {
            user.setCellular_telephone1(tmp);
        }

        tmp = soapUser.getCellularTelephone2();
        if (tmp != null) {
            user.setCellular_telephone2(tmp);
        }

        tmp = soapUser.getCityBusiness();
        if (tmp != null) {
            user.setCity_business(tmp);
        }

        tmp = soapUser.getCityHome();
        if (tmp != null) {
            user.setCity_home(tmp);
        }

        tmp = soapUser.getCityOther();
        if (tmp != null) {
            user.setCity_other(tmp);
        }

        tmp = soapUser.getCommercialRegister();
        if (tmp != null) {
            user.setCommercial_register(tmp);
        }

        tmp = soapUser.getCompany();
        if (tmp != null) {
            user.setCompany(tmp);
        }

        tmp = soapUser.getCountryBusiness();
        if (tmp != null) {
            user.setCountry_business(tmp);
        }

        tmp = soapUser.getCountryHome();
        if (tmp != null) {
            user.setCountry_home(tmp);
        }

        tmp = soapUser.getCountryOther();
        if (tmp != null) {
            user.setCountry_other(tmp);
        }

        tmp = soapUser.getDefaultSenderAddress();
        if (tmp != null) {
            user.setDefaultSenderAddress(tmp);
        }

        tmp = soapUser.getDepartment();
        if (tmp != null) {
            user.setDepartment(tmp);
        }

        tmp = soapUser.getDisplayName();
        if (tmp != null) {
            user.setDisplay_name(tmp);
        }

        tmp = soapUser.getEmail1();
        if (tmp != null) {
            user.setEmail1(tmp);
        }

        tmp = soapUser.getEmail2();
        if (tmp != null) {
            user.setEmail2(tmp);
        }

        tmp = soapUser.getEmail3();
        if (tmp != null) {
            user.setEmail3(tmp);
        }

        tmp = soapUser.getEmployeeType();
        if (tmp != null) {
            user.setEmployeeType(tmp);
        }

        tmp = soapUser.getFaxBusiness();
        if (tmp != null) {
            user.setFax_business(tmp);
        }

        tmp = soapUser.getFaxHome();
        if (tmp != null) {
            user.setFax_home(tmp);
        }

        tmp = soapUser.getFaxOther();
        if (tmp != null) {
            user.setFax_other(tmp);
        }

        Integer itg = soapUser.getFolderTree();
        if (itg != null) {
            user.setFolderTree(itg);
        }

        tmp = soapUser.getGivenName();
        if (tmp != null) {
            user.setGiven_name(tmp);
        }

        itg = soapUser.getId();
        if (itg != null) {
            user.setId(itg);
        }

        tmp = soapUser.getImapLogin();
        if (tmp != null) {
            user.setImapLogin(tmp);
        }

        tmp = soapUser.getImapServer();
        if (tmp != null) {
            user.setImapServer(tmp);
        }

        tmp = soapUser.getInfo();
        if (tmp != null) {
            user.setInfo(tmp);
        }

        tmp = soapUser.getInstantMessenger1();
        if (tmp != null) {
            user.setInstant_messenger1(tmp);
        }

        tmp = soapUser.getInstantMessenger2();
        if (tmp != null) {
            user.setInstant_messenger2(tmp);
        }

        tmp = soapUser.getLanguage();
        if (tmp != null) {
            user.setLanguage(tmp);
        }

        tmp = soapUser.getMailFolderConfirmedHamName();
        if (tmp != null) {
            user.setMail_folder_confirmed_ham_name(tmp);
        }

        tmp = soapUser.getMailFolderConfirmedSpamName();
        if (tmp != null) {
            user.setMail_folder_confirmed_spam_name(tmp);
        }

        tmp = soapUser.getMailFolderDraftsName();
        if (tmp != null) {
            user.setMail_folder_drafts_name(tmp);
        }

        tmp = soapUser.getMailFolderSentName();
        if (tmp != null) {
            user.setMail_folder_sent_name(tmp);
        }

        tmp = soapUser.getMailFolderSpamName();
        if (tmp != null) {
            user.setMail_folder_spam_name(tmp);
        }

        tmp = soapUser.getMailFolderTrashName();
        if (tmp != null) {
            user.setMail_folder_trash_name(tmp);
        }
        Boolean mailEnabled = soapUser.isMailenabled();
        if (null != mailEnabled) {
            user.setMailenabled(mailEnabled);
        }
        tmp = soapUser.getManagerName();
        if (tmp != null) {
            user.setManager_name(tmp);
        }

        tmp = soapUser.getMaritalStatus();
        if (tmp != null) {
            user.setMarital_status(tmp);
        }

        tmp = soapUser.getMiddleName();
        if (tmp != null) {
            user.setMiddle_name(tmp);
        }

        tmp = soapUser.getName();
        if (tmp != null) {
            user.setName(tmp);
        }

        tmp = soapUser.getNickname();
        if (tmp != null) {
            user.setNickname(tmp);
        }

        tmp = soapUser.getNote();
        if (tmp != null) {
            user.setNote(tmp);
        }

        tmp = soapUser.getNumberOfChildren();
        if (tmp != null) {
            user.setNumber_of_children(tmp);
        }

        tmp = soapUser.getNumberOfEmployee();
        if (tmp != null) {
            user.setNumber_of_employee(tmp);
        }

        tmp = soapUser.getPassword();
        if (tmp != null) {
            user.setPassword(tmp);
        }

        tmp = soapUser.getPasswordMech();
        if (tmp != null) {
            user.setPasswordMech(tmp);
        }

        tmp = soapUser.getPosition();
        if (tmp != null) {
            user.setPosition(tmp);
        }

        tmp = soapUser.getPostalCodeBusiness();
        if (tmp != null) {
            user.setPostal_code_business(tmp);
        }

        tmp = soapUser.getPostalCodeHome();
        if (tmp != null) {
            user.setPostal_code_home(tmp);
        }

        tmp = soapUser.getPostalCodeOther();
        if (tmp != null) {
            user.setPostal_code_other(tmp);
        }

        tmp = soapUser.getPrimaryEmail();
        if (tmp != null) {
            user.setPrimaryEmail(tmp);
        }

        tmp = soapUser.getProfession();
        if (tmp != null) {
            user.setProfession(tmp);
        }

        tmp = soapUser.getRoomNumber();
        if (tmp != null) {
            user.setRoom_number(tmp);
        }

        tmp = soapUser.getSalesVolume();
        if (tmp != null) {
            user.setSales_volume(tmp);
        }

        tmp = soapUser.getSmtpServer();
        if (tmp != null) {
            user.setSmtpServer(tmp);
        }

        tmp = soapUser.getSpouseName();
        if (tmp != null) {
            user.setSpouse_name(tmp);
        }

        tmp = soapUser.getStateBusiness();
        if (tmp != null) {
            user.setState_business(tmp);
        }

        tmp = soapUser.getStateHome();
        if (tmp != null) {
            user.setState_home(tmp);
        }

        tmp = soapUser.getStateOther();
        if (tmp != null) {
            user.setState_other(tmp);
        }

        tmp = soapUser.getStreetBusiness();
        if (tmp != null) {
            user.setStreet_business(tmp);
        }

        tmp = soapUser.getStreetHome();
        if (tmp != null) {
            user.setStreet_home(tmp);
        }

        tmp = soapUser.getStreetOther();
        if (tmp != null) {
            user.setStreet_other(tmp);
        }

        tmp = soapUser.getSuffix();
        if (tmp != null) {
            user.setSuffix(tmp);
        }

        tmp = soapUser.getSurName();
        if (tmp != null) {
            user.setSur_name(tmp);
        }

        tmp = soapUser.getTaxId();
        if (tmp != null) {
            user.setTax_id(tmp);
        }

        tmp = soapUser.getTelephoneAssistant();
        if (tmp != null) {
            user.setTelephone_assistant(tmp);
        }

        tmp = soapUser.getTelephoneBusiness1();
        if (tmp != null) {
            user.setTelephone_business1(tmp);
        }

        tmp = soapUser.getTelephoneBusiness2();
        if (tmp != null) {
            user.setTelephone_business2(tmp);
        }

        tmp = soapUser.getTelephoneCallback();
        if (tmp != null) {
            user.setTelephone_callback(tmp);
        }

        tmp = soapUser.getTelephoneCar();
        if (tmp != null) {
            user.setTelephone_car(tmp);
        }

        tmp = soapUser.getTelephoneCompany();
        if (tmp != null) {
            user.setTelephone_company(tmp);
        }

        tmp = soapUser.getTelephoneHome1();
        if (tmp != null) {
            user.setTelephone_home1(tmp);
        }

        tmp = soapUser.getTelephoneHome2();
        if (tmp != null) {
            user.setTelephone_home2(tmp);
        }

        tmp = soapUser.getTelephoneIp();
        if (tmp != null) {
            user.setTelephone_ip(tmp);
        }

        tmp = soapUser.getTelephoneIsdn();
        if (tmp != null) {
            user.setTelephone_isdn(tmp);
        }

        tmp = soapUser.getTelephoneOther();
        if (tmp != null) {
            user.setTelephone_other(tmp);
        }

        tmp = soapUser.getTelephonePager();
        if (tmp != null) {
            user.setTelephone_pager(tmp);
        }

        tmp = soapUser.getTelephonePrimary();
        if (tmp != null) {
            user.setTelephone_primary(tmp);
        }

        tmp = soapUser.getTelephoneRadio();
        if (tmp != null) {
            user.setTelephone_radio(tmp);
        }

        tmp = soapUser.getTelephoneTelex();
        if (tmp != null) {
            user.setTelephone_telex(tmp);
        }

        tmp = soapUser.getTelephoneTtytdd();
        if (tmp != null) {
            user.setTelephone_ttytdd(tmp);
        }

        tmp = soapUser.getTimezone();
        if (tmp != null) {
            user.setTimezone(tmp);
        }

        tmp = soapUser.getTitle();
        if (tmp != null) {
            user.setTitle(tmp);
        }

        itg = soapUser.getUploadFileSizeLimit();
        if (itg != null) {
            user.setUploadFileSizeLimit(itg);
        }

        itg = soapUser.getUploadFileSizeLimitPerFile();
        if (itg != null) {
            user.setUploadFileSizeLimitPerFile(itg);
        }

        tmp = soapUser.getUrl();
        if (tmp != null) {
            user.setUrl(tmp);
        }

        tmp = soapUser.getUserfield01();
        if (tmp != null) {
            user.setUserfield01(tmp);
        }

        tmp = soapUser.getUserfield02();
        if (tmp != null) {
            user.setUserfield02(tmp);
        }

        tmp = soapUser.getUserfield03();
        if (tmp != null) {
            user.setUserfield03(tmp);
        }

        tmp = soapUser.getUserfield04();
        if (tmp != null) {
            user.setUserfield04(tmp);
        }

        tmp = soapUser.getUserfield05();
        if (tmp != null) {
            user.setUserfield05(tmp);
        }

        tmp = soapUser.getUserfield06();
        if (tmp != null) {
            user.setUserfield06(tmp);
        }

        tmp = soapUser.getUserfield07();
        if (tmp != null) {
            user.setUserfield07(tmp);
        }

        tmp = soapUser.getUserfield08();
        if (tmp != null) {
            user.setUserfield08(tmp);
        }

        tmp = soapUser.getUserfield09();
        if (tmp != null) {
            user.setUserfield09(tmp);
        }

        tmp = soapUser.getUserfield10();
        if (tmp != null) {
            user.setUserfield10(tmp);
        }

        tmp = soapUser.getUserfield11();
        if (tmp != null) {
            user.setUserfield11(tmp);
        }

        tmp = soapUser.getUserfield12();
        if (tmp != null) {
            user.setUserfield12(tmp);
        }

        tmp = soapUser.getUserfield13();
        if (tmp != null) {
            user.setUserfield13(tmp);
        }

        tmp = soapUser.getUserfield14();
        if (tmp != null) {
            user.setUserfield14(tmp);
        }

        tmp = soapUser.getUserfield15();
        if (tmp != null) {
            user.setUserfield15(tmp);
        }

        tmp = soapUser.getUserfield16();
        if (tmp != null) {
            user.setUserfield16(tmp);
        }

        tmp = soapUser.getUserfield17();
        if (tmp != null) {
            user.setUserfield17(tmp);
        }

        tmp = soapUser.getUserfield18();
        if (tmp != null) {
            user.setUserfield18(tmp);
        }

        tmp = soapUser.getUserfield19();
        if (tmp != null) {
            user.setUserfield19(tmp);
        }

        tmp = soapUser.getUserfield20();
        if (tmp != null) {
            user.setUserfield20(tmp);
        }

        return user;
    }

    private static User user2Soap(final com.openexchange.admin.rmi.dataobjects.User user) {
        if (null == user) {
            return null;
        }
        final User soapUser = new User();
        soapUser.setGuiSpamFilterEnabled(user.getGui_spam_filter_enabled());
        soapUser.setAliases(user.getAliasesForSOAP());
        Date d = user.getAnniversary();
        if (null == d) {
            soapUser.setAnniversary(null);
        } else {
            try {
                final GregorianCalendar c = new GregorianCalendar();
                c.setTime(d);
                soapUser.setAnniversary(DatatypeFactory.newInstance().newXMLGregorianCalendar(c));
            } catch (final DatatypeConfigurationException e) {
                soapUser.setAnniversary(null);
            }
        }
        soapUser.setAssistantName(user.getAssistant_name());
        d = user.getBirthday();
        if (null == d) {
            soapUser.setBirthday(null);
        } else {
            try {
                final GregorianCalendar c = new GregorianCalendar();
                c.setTime(d);
                soapUser.setBirthday(DatatypeFactory.newInstance().newXMLGregorianCalendar(c));
            } catch (final DatatypeConfigurationException e) {
                soapUser.setBirthday(null);
            }
        }
        soapUser.setBranches(user.getBranches());
        soapUser.setBusinessCategory(user.getBusiness_category());
        soapUser.setCategories(user.getCategories());
        soapUser.setCellularTelephone1(user.getCellular_telephone1());
        soapUser.setCellularTelephone2(user.getCellular_telephone2());
        soapUser.setCityBusiness(user.getCity_business());
        soapUser.setCityHome(user.getCity_home());
        soapUser.setCityOther(user.getCity_other());
        soapUser.setCommercialRegister(user.getCommercial_register());
        soapUser.setCompany(user.getCompany());
        soapUser.setContextadmin(Boolean.valueOf(user.isContextadmin()));
        soapUser.setCountryBusiness(user.getCountry_business());
        soapUser.setCountryHome(user.getCountry_home());
        soapUser.setCountryOther(user.getCountry_other());
        soapUser.setDefaultSenderAddress(user.getDefaultSenderAddress());
        soapUser.setDefaultGroup(group2Soap(user.getDefault_group()));
        soapUser.setDepartment(user.getDepartment());
        soapUser.setDisplayName(user.getDisplay_name());
        soapUser.setEmail1(user.getEmail1());
        soapUser.setEmail2(user.getEmail2());
        soapUser.setEmail3(user.getEmail3());
        soapUser.setEmployeeType(user.getEmployeeType());
        soapUser.setFaxBusiness(user.getFax_business());
        soapUser.setFaxHome(user.getFax_home());
        soapUser.setFaxOther(user.getFax_other());
        soapUser.setFolderTree(user.getFolderTree());
        soapUser.setGivenName(user.getGiven_name());
        soapUser.setGuiPreferencesForSoap(map2Soap(user.getGuiPreferences()));
        soapUser.setId(user.getId());
        soapUser.setImapLogin(user.getImapLogin());
        soapUser.setImapServer(user.getImapServer());
        soapUser.setImapPort(user.getImapPort());
        soapUser.setImapServerString(user.getImapServerString());
        soapUser.setImapSchema(user.getImapSchema());
        soapUser.setInfo(user.getInfo());
        soapUser.setInstantMessenger1(user.getInstant_messenger1());
        soapUser.setInstantMessenger2(user.getInstant_messenger2());
        soapUser.setLanguage(user.getLanguage());
        soapUser.setMailFolderConfirmedHamName(user.getMail_folder_confirmed_ham_name());
        soapUser.setMailFolderConfirmedSpamName(user.getMail_folder_confirmed_spam_name());
        soapUser.setMailFolderDraftsName(user.getMail_folder_drafts_name());
        soapUser.setMailFolderSentName(user.getMail_folder_sent_name());
        soapUser.setMailFolderSpamName(user.getMail_folder_spam_name());
        soapUser.setMailFolderTrashName(user.getMail_folder_trash_name());
        soapUser.setMailenabled(user.getMailenabled());
        soapUser.setManagerName(user.getManager_name());
        soapUser.setMaritalStatus(user.getMarital_status());
        soapUser.setMiddleName(user.getMiddle_name());
        soapUser.setName(user.getName());
        soapUser.setNickname(user.getNickname());
        soapUser.setNote(user.getNote());
        soapUser.setNumberOfChildren(user.getNumber_of_children());
        soapUser.setNumberOfEmployee(user.getNumber_of_employee());
        soapUser.setPassword(user.getPassword());
        soapUser.setPasswordMech(user.getPasswordMech());
        soapUser.setPasswordExpired(user.getPassword_expired());
        soapUser.setPosition(user.getPosition());
        soapUser.setPostalCodeBusiness(user.getPostal_code_business());
        soapUser.setPostalCodeHome(user.getPostal_code_home());
        soapUser.setPostalCodeOther(user.getPostal_code_other());
        soapUser.setPrimaryEmail(user.getPrimaryEmail());
        soapUser.setProfession(user.getProfession());
        soapUser.setRoomNumber(user.getRoom_number());
        soapUser.setSalesVolume(user.getSales_volume());
        soapUser.setSmtpServer(user.getSmtpServer());
        soapUser.setSmtpPort(user.getSmtpPort());
        soapUser.setSmtpServerString(user.getSmtpServerString());
        soapUser.setSmtpSchema(user.getSmtpSchema());
        soapUser.setSpouseName(user.getSpouse_name());
        soapUser.setStateBusiness(user.getState_business());
        soapUser.setStateHome(user.getState_home());
        soapUser.setStateOther(user.getState_other());
        soapUser.setStreetBusiness(user.getStreet_business());
        soapUser.setStreetHome(user.getStreet_home());
        soapUser.setStreetOther(user.getStreet_other());
        soapUser.setSuffix(user.getSuffix());
        soapUser.setSurName(user.getSur_name());
        soapUser.setTaxId(user.getTax_id());
        soapUser.setTelephoneAssistant(user.getTelephone_assistant());
        soapUser.setTelephoneBusiness1(user.getTelephone_business1());
        soapUser.setTelephoneBusiness2(user.getTelephone_business2());
        soapUser.setTelephoneCallback(user.getTelephone_callback());
        soapUser.setTelephoneCar(user.getTelephone_car());
        soapUser.setTelephoneCompany(user.getTelephone_company());
        soapUser.setTelephoneHome1(user.getTelephone_home1());
        soapUser.setTelephoneHome2(user.getTelephone_home2());
        soapUser.setTelephoneIp(user.getTelephone_ip());
        soapUser.setTelephoneIsdn(user.getTelephone_isdn());
        soapUser.setTelephoneOther(user.getTelephone_other());
        soapUser.setTelephonePager(user.getTelephone_pager());
        soapUser.setTelephonePrimary(user.getTelephone_primary());
        soapUser.setTelephoneRadio(user.getTelephone_radio());
        soapUser.setTelephoneTelex(user.getTelephone_telex());
        soapUser.setTelephoneTtytdd(user.getTelephone_ttytdd());
        soapUser.setTimezone(user.getTimezone());
        soapUser.setTitle(user.getTitle());
        soapUser.setUploadFileSizeLimit(user.getUploadFileSizeLimit());
        soapUser.setUploadFileSizeLimitPerFile(user.getUploadFileSizeLimitPerFile());
        soapUser.setUrl(user.getUrl());
        soapUser.setUserAttributes(mapmap2Soap(user.getUserAttributes()));
        soapUser.setUserfield01(user.getUserfield01());
        soapUser.setUserfield02(user.getUserfield02());
        soapUser.setUserfield03(user.getUserfield03());
        soapUser.setUserfield04(user.getUserfield04());
        soapUser.setUserfield05(user.getUserfield05());
        soapUser.setUserfield06(user.getUserfield06());
        soapUser.setUserfield07(user.getUserfield07());
        soapUser.setUserfield08(user.getUserfield08());
        soapUser.setUserfield09(user.getUserfield09());
        soapUser.setUserfield10(user.getUserfield10());
        soapUser.setUserfield11(user.getUserfield11());
        soapUser.setUserfield12(user.getUserfield12());
        soapUser.setUserfield13(user.getUserfield13());
        soapUser.setUserfield14(user.getUserfield14());
        soapUser.setUserfield15(user.getUserfield15());
        soapUser.setUserfield16(user.getUserfield16());
        soapUser.setUserfield17(user.getUserfield17());
        soapUser.setUserfield18(user.getUserfield18());
        soapUser.setUserfield19(user.getUserfield19());
        soapUser.setUserfield20(user.getUserfield20());
        return soapUser;
    }

    private static com.openexchange.admin.rmi.dataobjects.Group soap2Group(final Group soapGroup) {
        if (null == soapGroup) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Group group = new com.openexchange.admin.rmi.dataobjects.Group();
        final String displayname = soapGroup.getDisplayname();
        if (null != displayname) {
            group.setDisplayname(displayname);
        }
        final Integer id = soapGroup.getId();
        if (null != id) {
            group.setId(id);
        }
        final List<Integer> members = soapGroup.getMembers();
        if (null != members) {
            group.setMembers(members.toArray(new Integer[0]));
        }
        final String name = soapGroup.getName();
        if (null != name) {
            group.setName(name);
        }
        return group;
    }

    private static Group group2Soap(final com.openexchange.admin.rmi.dataobjects.Group group) {
        if (null == group) {
            return null;
        }
        final Group soapGroup = new Group();
        soapGroup.setDisplayname(group.getDisplayname());
        soapGroup.setId(group.getId());
        {
            final Integer[] members = group.getMembers();
            soapGroup.setMembers(null == members ? null : Arrays.asList(members));
        }
        soapGroup.setName(group.getName());
        return soapGroup;
    }

    private static com.openexchange.admin.rmi.dataobjects.Context soap2Context(final Context soapContext) {
        if (null == soapContext) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Context ret = new com.openexchange.admin.rmi.dataobjects.Context();
        Long lng = soapContext.getAverageSize();
        if (null != lng) {
            ret.setAverage_size(lng);
        }

        final Boolean enabled = soapContext.isEnabled();
        if (null != enabled) {
            ret.setEnabled(enabled);
        }

        final String s = soapContext.getFilestoreName();
        if (null != s) {
            ret.setFilestore_name(s);
        }

        Integer itg = soapContext.getFilestoreId();
        if (null != itg) {
            ret.setFilestoreId(itg);
        }

        itg = soapContext.getId();
        ret.setId(itg);

        if (null != soapContext.getLoginMappings()) {
            for (String loginMapping : soapContext.getLoginMappings()) {
                if (null != loginMapping) {
                    ret.addLoginMapping(loginMapping);
                }
            }
        }

        lng = soapContext.getMaxQuota();
        if (null != lng) {
            ret.setMaxQuota(lng);
        }

        final String name = soapContext.getName();
        if (null != name) {
            ret.setName(name);
        }

        final Long usedQuota = soapContext.getUsedQuota();
        if (null != usedQuota) {
            ret.setUsedQuota(usedQuota);
        }

        final Database readDatabase = soapContext.getReadDatabase();
        if (null != readDatabase) {
            ret.setReadDatabase(soap2Database(readDatabase));
        }

        final Database writeDatabase = soapContext.getWriteDatabase();
        if (null != writeDatabase) {
            ret.setWriteDatabase(soap2Database(writeDatabase));
        }

        final SOAPStringMapMap userAttributes = soapContext.getUserAttributes();
        if (null != userAttributes) {
            ret.setUserAttributes(soap2MapMap(userAttributes));
        }

        return ret;
    }

    private static com.openexchange.admin.rmi.dataobjects.Database soap2Database(final Database soapDatabase) {
        if (null == soapDatabase) {
            return null;
        }
        final com.openexchange.admin.rmi.dataobjects.Database ret = new com.openexchange.admin.rmi.dataobjects.Database();
        Integer itg = soapDatabase.getClusterWeight();
        if (itg != null) {
            ret.setClusterWeight(itg);
        }

        itg = soapDatabase.getCurrentUnits();
        if (itg != null) {
            ret.setCurrentUnits(itg);
        }

        String tmp = soapDatabase.getDriver();
        if (tmp != null) {
            ret.setDriver(tmp);
        }

        itg = soapDatabase.getId();
        if (itg != null) {
            ret.setId(itg);
        }

        tmp = soapDatabase.getLogin();
        if (tmp != null) {
            ret.setLogin(tmp);
        }

        Boolean bool = soapDatabase.isMaster();
        if (bool != null) {
            ret.setMaster(bool);
        }

        itg = soapDatabase.getMasterId();
        if (itg != null) {
            ret.setMasterId(itg);
        }

        itg = soapDatabase.getMaxUnits();
        if (itg != null) {
            ret.setMaxUnits(itg);
        }

        tmp = soapDatabase.getName();
        if (tmp != null) {
            ret.setName(tmp);
        }

        tmp = soapDatabase.getPassword();
        if (tmp != null) {
            ret.setPassword(tmp);
        }

        itg = soapDatabase.getPoolHardLimit();
        if (itg != null) {
            ret.setPoolHardLimit(itg);
        }

        itg = soapDatabase.getPoolInitial();
        if (itg != null) {
            ret.setPoolInitial(itg);
        }

        itg = soapDatabase.getPoolMax();
        if (itg != null) {
            ret.setPoolMax(itg);
        }

        itg = soapDatabase.getReadId();
        if (itg != null) {
            ret.setRead_id(itg);
        }

        tmp = soapDatabase.getScheme();
        if (tmp != null) {
            ret.setScheme(tmp);
        }

        tmp = soapDatabase.getUrl();
        if (tmp != null) {
            ret.setUrl(tmp);
        }
        return ret;
    }

    private static Map<String, Map<String, String>> soap2MapMap(final SOAPStringMapMap soapStringMapMap) {
        if (null == soapStringMapMap) {
            return null;
        }
        final java.util.List<SOAPMapEntry> entries = soapStringMapMap.getEntries();
        final Map<String, Map<String, String>> map = new HashMap<String, Map<String,String>>(entries.size());
        for (final SOAPMapEntry soapMapEntry : entries) {
            map.put(soapMapEntry.getKey(), soap2Map(soapMapEntry.getValue()));
        }
        return map;
    }

    private static Map<String, String> soap2Map(final SOAPStringMap soapStringMap) {
        if (null == soapStringMap) {
            return null;
        }
        final java.util.List<Entry> entries = soapStringMap.getEntries();
        final Map<String, String> map = new HashMap<String, String>(entries.size());
        for (final Entry entry : entries) {
            map.put(entry.getKey(), entry.getValue());
        }
        return map;
    }

    private static SOAPStringMapMap mapmap2Soap(final Map<String, Map<String, String>> mapmap) {
        if (null == mapmap) {
            return null;
        }
        final SOAPStringMapMap soapMapMap = new SOAPStringMapMap();
        final java.util.List<SOAPMapEntry> entries = new ArrayList<SOAPMapEntry>(mapmap.size());
        for (final Map.Entry<String,Map<String,String>> mapmapEntry : mapmap.entrySet()) {
            final SOAPMapEntry mapEntry = new SOAPMapEntry();
            mapEntry.setKey(mapmapEntry.getKey());
            mapEntry.setValue(map2Soap(mapmapEntry.getValue()));
            entries.add(mapEntry);
        }
        soapMapMap.setEntries(entries);
        return soapMapMap;
    }

    private static SOAPStringMap map2Soap(final Map<String, String> map) {
        if (null == map) {
            return null;
        }
        final SOAPStringMap soapMap = new SOAPStringMap();
        final java.util.List<Entry> entries = new ArrayList<Entry>(map.size());
        for (final Map.Entry<String,String> mapEntry : map.entrySet()) {
            final Entry entry = new Entry();
            entry.setKey(mapEntry.getKey());
            entry.setValue(mapEntry.getValue());
            entries.add(entry);
        }
        soapMap.setEntries(entries);
        return soapMap;
    }

}
