DROP TABLE IF EXISTS subscriptions;

CREATE TABLE subscriptions (
id INT4 UNSIGNED NOT NULL AUTO_INCREMENT, 
cid INT4 UNSIGNED NOT NULL, 
user INT4 UNSIGNED NOT NULL, 
url VARCHAR(255) NOT NULL, 
folder_id INT4 UNSIGNED NOT NULL,
last_update INT4 UNSIGNED NOT NULL, 
PRIMARY KEY (id), 
FOREIGN KEY(cid, user) REFERENCES user(cid, id))
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;