define("io.ox/mail/actions",["io.ox/core/extensions","io.ox/core/extPatterns/links","io.ox/mail/api","io.ox/mail/util","gettext!io.ox/mail/mail","io.ox/core/config"],function(a,b,c,d,e,f){var g,h=f.get("modules.mail.defaultFolder.drafts"),i=b.Action;"use strict",new i("io.ox/mail/actions/reader",{id:"reader",action:function(a){a.toggleLamp()}}),new i("io.ox/mail/actions/compose",{id:"compose",action:function(){require(["io.ox/mail/write/main"],function(a){a.getApp().launch().done(function(){this.
compose()})})}}),new i("io.ox/mail/actions/delete",{id:"delete",requires:"toplevel some delete",multiple:function(a){c.remove(a)}}),new i("io.ox/mail/actions/reply-all",{id:"reply-all",requires:function(a){return a.collection.has("toplevel","one")&&d.hasOtherRecipients(a.context)&&a.context.folder_id!==h},action:function(a){require(["io.ox/mail/write/main"],function(b){b.getApp().launch().done(function(){this.replyall(a)})})}}),new i("io.ox/mail/actions/reply",{id:"reply",requires:function(a){return a
.collection.has("toplevel","one")&&a.context.folder_id!==h},action:function(a){require(["io.ox/mail/write/main"],function(b){b.getApp().launch().done(function(){this.reply(a)})})}}),new i("io.ox/mail/actions/forward",{id:"forward",requires:function(a){return a.collection.has("toplevel","some")},action:function(a){require(["io.ox/mail/write/main"],function(b){b.getApp().launch().done(function(){this.forward(a)})})}}),new i("io.ox/mail/actions/edit",{id:"edit",requires:function(a){return a.collection
.has("toplevel","one")&&a.context.folder_id===h},action:function(a){require(["io.ox/mail/write/main"],function(b){b.getApp().launch().done(function(){var b=this;this.compose(a).done(function(){b.setMsgRef(a.folder_id+"/"+a.id),b.markClean()})})})}}),new i("io.ox/mail/actions/source",{id:"source",requires:"toplevel one",action:function(a){var b,d=c.getSource(a);require(["io.ox/core/tk/dialogs"],function(c){(new c.ModalDialog({easyOut:!0,width:700})).addPrimaryButton("close",e("Close")).header($("<h3>"
).text(e("Mail source")+": "+(a.subject||""))).append(b=$("<textarea>",{rows:15,readonly:"readonly"}).css({width:"100%",boxSizing:"border-box",visibility:"hidden"}).addClass("input-xlarge").on("keydown",function(a){a.which!==27&&a.stopPropagation()})).show(function(){var a=this.busy();d.done(function(c){b.val(c||"").css({visibility:"",cursor:"default"}),b=d=null,a.idle()})})})}}),new i("io.ox/mail/actions/move",{id:"move",requires:"toplevel some",multiple:function(a){var b=this;require(["io.ox/core/tk/dialogs"
,"io.ox/core/tk/folderviews"],function(b,d){var f,g,h=(new b.ModalDialog({easyOut:!0})).header($("<h3>").text("Move")).addPrimaryButton("ok",e("OK")).addButton("cancel",e("Cancel"));h.getBody().css("maxHeight","250px"),f=_(a).first(),g=new d.FolderTree(h.getBody(),{type:"mail"}),g.paint(),h.show(function(){g.selection.set(f.folder_id||f.folder)}).done(function(b){var d;b==="ok"&&(d=g.selection.get(),d.length===1&&c.move(a,d[0].id)),g.destroy(),g=h=null})})}}),new i("io.ox/mail/actions/copy",{id:"copy"
,requires:"toplevel some",multiple:function(a){require(["io.ox/core/tk/dialogs","io.ox/core/tk/folderviews"],function(b,d){var f,g,h=(new b.ModalDialog({easyOut:!0})).header($("<h3>").text("Copy")).addPrimaryButton("ok",e("OK")).addButton("cancel",e("Cancel"));h.getBody().css("maxHeight","250px"),f=_(a).first(),g=new d.FolderTree(h.getBody(),{type:"mail"}),g.paint(),h.show(function(){g.selection.set({id:f.folder_id||f.folder})}).done(function(b){var d;b==="ok"&&(d=g.selection.get(),d.length===1&&
c.copy(a,d[0].id)),g.destroy(),g=h=null})})}}),new i("io.ox/mail/actions/markunread",{id:"markunread",requires:function(a){return c.getList(a.context).pipe(function(b){var d=a.collection.has("toplevel")&&_(b).reduce(function(a,b){return a&&b&&(b.flags&c.FLAGS.SEEN)===c.FLAGS.SEEN},!0);return d})},multiple:function(a){var b;c.markUnread(a),b=ox.ui.App.get("io.ox/mail")[0],b&&b.getGrid().selection.retrigger(!0)}}),new i("io.ox/mail/actions/markread",{id:"markread",requires:function(a){return c.getList
(a.context).pipe(function(b){var d=a.collection.has("toplevel")&&_(b).reduce(function(a,b){return a||b&&(b.flags&c.FLAGS.SEEN)===0},!1);return d})},multiple:function(a){var b;c.markRead(a),b=ox.ui.App.get("io.ox/mail")[0],b&&b.getGrid().selection.retrigger(!0)}}),new i("io.ox/mail/actions/preview-attachment",{id:"preview",requires:function(a){return require(["io.ox/preview/main"]).pipe(function(b){var c=_.getArray(a.context);return a.collection.has("some")&&_(c).reduce(function(a,c){return a||(new 
b.Preview({filename:c.filename,mimetype:c.content_type})).supportsPreview()},!1)})},multiple:function(a){var b=$.Event();b.target=this,require(["io.ox/core/tk/dialogs","io.ox/preview/main"],function(d,e){(new d.SidePopup).show(b,function(b){_(a).each(function(a){var d=new e.Preview({data:a,filename:a.filename,mimetype:a.content_type,dataURL:c.getUrl(a,"view")},{width:b.parent().width(),height:"auto"});d.supportsPreview()&&(b.append($("<h4>").addClass("mail-attachment-preview").text(a.filename)),d
.appendTo(b),b.append($("<div>").text(" ")))})})})}}),new i("io.ox/mail/actions/open-attachment",{id:"open",requires:"some",multiple:function(a){_(a).each(function(a){var b=c.getUrl(a,"view");window.open(b)})}}),new i("io.ox/mail/actions/download-attachment",{id:"download",requires:"some",multiple:function(a){var b;a.length===1?b=c.getUrl(_(a).first(),"download"):b=c.getUrl(a,"zip"),window.open(b)}}),new i("io.ox/mail/actions/save-attachment",{id:"save",requires:"some",multiple:function(a){c.saveAttachments
(a).done(function(a){console.log("Yep, saved!",a)})}}),a.point("io.ox/mail/links/toolbar").extend(new b.Link({index:100,id:"compose",label:e("Compose new mail"),ref:"io.ox/mail/actions/compose"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:100,prio:"hi",id:"reply-all",label:e("Reply All"),ref:"io.ox/mail/actions/reply-all"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:200,prio:"hi",id:"reply",label:e("Reply"),ref:"io.ox/mail/actions/reply"})),a.point("io.ox/mail/links/inline"
).extend(new b.Link({index:300,prio:"lo",id:"forward",label:e("Forward"),ref:"io.ox/mail/actions/forward"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:400,prio:"hi",id:"edit",label:e("Edit"),ref:"io.ox/mail/actions/edit"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:500,prio:"hi",id:"markunread",label:e("Mark Unread"),ref:"io.ox/mail/actions/markunread"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:501,prio:"hi",id:"markread",label:e("Mark read"
),ref:"io.ox/mail/actions/markread"})),g={NONE:e("None"),RED:e("Red"),BLUE:e("Blue"),GREEN:e("Green"),GREY:e("Grey"),BROWN:e("Brown"),AQUA:e("Aqua"),ORANGE:e("Orange"),PINK:e("Pink"),LIGHTBLUE:e("Lightblue"),YELLOW:e("Yellow")};function j(a){return c.update(a.data.data,{color_label:a.data.color,value:!0}).done(function(){var a=ox.ui.App.get("io.ox/mail")[0];a&&a.getGrid().selection.retrigger(!0)})}new i("io.ox/mail/actions/label",{id:"label",requires:"toplevel some",multiple:$.noop}),a.point("io.ox/mail/links/inline"
).extend(new b.Link({index:600,prio:"lo",id:"label",ref:"io.ox/mail/actions/label",draw:function(a){this.append($('<span class="dropdown" class="io-ox-inline-links" data-prio="lo">').append($('<a href="#" data-toggle="dropdown">').text(e("Label")).append($('<b class="caret">')).dropdown(),$('<ul class="dropdown-menu">').append(_(c.COLORS).reduce(function(b,c,d){return b.add($("<li>").append($("<a>").text(g[d]).on("click",{data:a,color:c},j).addClass(a.color_label===c?"active-label":undefined)))},
$()))))}})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:700,prio:"lo",id:"move",label:e("Move"),ref:"io.ox/mail/actions/move"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:800,prio:"lo",id:"copy",label:e("Copy"),ref:"io.ox/mail/actions/copy"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:900,prio:"lo",id:"source",label:e("View Source"),ref:"io.ox/mail/actions/source"})),a.point("io.ox/mail/links/inline").extend(new b.Link({index:1e3,prio:"hi",id:"delete"
,label:e("Delete"),ref:"io.ox/mail/actions/delete",special:"danger"})),a.point("io.ox/mail/attachment/links").extend(new b.Link({id:"preview",index:100,label:e("Preview"),ref:"io.ox/mail/actions/preview-attachment"})),a.point("io.ox/mail/attachment/links").extend(new b.Link({id:"open",index:200,label:e("Open in new tab"),ref:"io.ox/mail/actions/open-attachment"})),a.point("io.ox/mail/attachment/links").extend(new b.Link({id:"download",index:300,label:e("Download"),ref:"io.ox/mail/actions/download-attachment"
})),a.point("io.ox/mail/attachment/links").extend(new b.Link({id:"save",index:400,label:e("Save in file store"),ref:"io.ox/mail/actions/save-attachment"}))})