define("io.ox/mail/main",["io.ox/mail/util","io.ox/mail/api","io.ox/core/extensions","io.ox/core/commons","io.ox/core/config","io.ox/core/tk/vgrid","io.ox/mail/view-detail","io.ox/mail/view-grid-template","gettext!io.ox/mail/main","io.ox/mail/actions","less!io.ox/mail/style.css"],function(a,b,c,d,e,f,g,h,i){var j,k,l,m,n,o,p=e.get("modules.mail.defaultFolder.drafts"),q=function(a){a.preventDefault();var b=$(this).attr("data-option"),c=a.data.grid;/^(603|607|610|102)$/.test(b)?c.prop("sort",b).refresh
():/^(asc|desc)$/.test(b)?c.prop("order",b).refresh():b==="unread"&&c.prop("unread",!c.prop("unread"))},r=ox.ui.createApp({name:"io.ox/mail"}),s=330;return"use strict",r.setLauncher(function(){var a,c,e,p,t;j=ox.ui.createWindow({name:"io.ox/mail",title:i("Inbox"),titleWidth:s+27+"px",toolbar:!0,search:!0}),j.addClass("io-ox-mail-main"),r.setWindow(j),d.addFolderView(r,{width:s,type:"mail"}),l=$("<audio>",{src:ox.base+"/apps/io.ox/mail/images/ping.mp3"}).hide().prop("volume",.4).appendTo(j.nodes.main
),b.on("new-mail",function(){l.get(0).play()}),m=$("<div>").addClass("leftside border-right").css({width:s+"px"}).appendTo(j.nodes.main),o=$("<div>").css({left:s+1+"px"}).addClass("rightside mail-detail-pane").appendTo(j.nodes.main),n=o.scrollable(),k=new f(m),k.addTemplate(h.main),k.selection.unfold=function(){return _(this.get()).inject(function(a,c){return a.concat(b.getThread(c))},[])},k.prop("sort","610").prop("order","desc").prop("unread",!1),d.wireGridAndAPI(k,b,"getAllThreads","getThreads"
),d.wireGridAndSearch(k,j,b);function u(){var a,b=k.getToolbar().find(".grid-options"),c=b.find("ul"),d=k.prop();c.find("i").attr("class","icon-none"),c.find('[data-option="'+d.sort+'"], '+'[data-option="'+d.order+'"], '+'[data-option="'+(d.unread?"unread":"~unread")+'"]').find("i").attr("class","icon-ok"),b.find(".icon-envelope")[d.unread?"show":"hide"](),a=[1,.4][d.order==="desc"?"slice":"reverse"](),b.find(".icon-arrow-down").css("opacity",a[0]).end().find(".icon-arrow-up").css("opacity",a[1])
.end()}a='<li><a data-option="%s"><i/> %s</a></li>',k.getToolbar().prepend($("<div>").addClass("grid-options dropdown").css({display:"inline-block","float":"right"}).append($("<a>",{href:"#"}).attr("data-toggle","dropdown").append($('<i class="icon-envelope">').css("marginRight","0.5em").hide(),$('<i class="icon-arrow-down">'),$('<i class="icon-arrow-up">')).dropdown(),$("<ul>").addClass("dropdown-menu").css({top:"auto",bottom:"110%",right:0,left:"auto"}).append($(_.printf(a,610,i("Date"))),$(_.printf
(a,603,i("From"))),$(_.printf(a,102,i("Label"))),$(_.printf(a,607,i("Subject"))),$('<li class="divider">'),$(_.printf(a,"asc",i("Ascending"))),$(_.printf(a,"desc",i("Descending"))),$('<li class="divider">'),$(_.printf(a,"unread",i("Unread only")))).on("click","a",{grid:k},q))),k.on("change:prop:unread",function(a,b){b===!0?k.refresh().done(k.pause):k.resume().refresh()}),k.on("change:prop",u),u(),k.getToolbar().append($("<div>").addClass("grid-count").css({textAlign:"center",color:"#888"})),k.on("change:ids"
,function(a,b){var c=k.getToolbar().find(".grid-count").text("");setTimeout(function(){var a=_(b).reduce(function(a,b){return a+(b.thread?b.thread.length:1)},0);c.text(a+" "+i.ngettext("mail","mails",a))},10)}),k.setAllRequest(function(){var a=this.prop("sort"),c=this.prop("unread");return b[a==="610"?"getAllThreads":"getAll"]({folder:this.prop("folder"),sort:a,order:this.prop("order")},"auto").pipe(function(a){return c?_(a).filter(function(a){return(a.flags&32)===0}):a})}),j.nodes.title.on("click"
,".badge",function(a){a.preventDefault(),k.prop("unread",!k.prop("unread")).refresh()}),function(){function c(a,b,c){k.repaintLabels().done(function(){k.repaint(),a&&k.selection.insertAt(c==="desc"?a.slice(1):a.slice(0,-1),b+1)})}function d(d,e){var f,g;a[d+1]===undefined&&(f=b.getThread(e),g=b.getThreadOrder(e),f.length>1&&(a[d+1]=e,b.getList(f).done(function(a){c(a,d,g)})))}function e(d,e){var f,g;a[d+1]!==undefined&&(f=b.getThread(e),g=b.getThreadOrder(e),delete a[d+1],b.getList(f).done(function(
a){k.selection.remove(g==="desc"?a.slice(1):a.slice(0,-1)),c()}))}function f(b,c){a[b+1]===undefined?d(b,c):e(b,c)}var a={};k.addLabelTemplate(h.thread),k.requiresLabel=function(b){return a[b]!==undefined},k.getContainer().on("click",".thread-size",function(){var a=$(this).closest(".vgrid-cell"),b=parseInt(a.attr("data-index"),10),c=a.attr("data-obj-id");f(b,c)}),k.getContainer().on("click",".thread-summary-item",function(){var a=$(this).attr("data-obj-id");k.selection.set(a)}),k.selection.on("keyboard"
,function(a,b){var c,g,h,i=k.selection.get();i.length===1&&(c=k.selection.serialize(i[0]),g=k.selection.getIndex(c),h=b.which,h===39?d(g,c):h===37?e(g,c):h===13&&f(g,c))})}(),c=function(a){var c;n.busy(!0),k.getMode()==="all"?(c=b.getThread(a),b.get(c[0]).done(_.lfo(g.drawThread,n,c)).fail(_.lfo(p,a))):b.get(a).done(_.lfo(e)).fail(_.lfo(p,a))},e=function(a){n.idle().empty().append(g.draw(a).addClass("page"))},p=function(a){n.idle().empty().append($.fail(i("Oops, couldn't load that email."),function(
){c(a)}))},t=function(){var a=k.selection.get();a.length===1&&(n.css("height",""),c(a[0]))},b.on("delete",t),d.wireGridAndSelectionChange(k,"io.ox/mail",c,n),d.wireGridAndWindow(k,j),d.wireFirstRefresh(r,b),d.wireGridAndRefresh(k,b,j),r.on("folder:change folder:refresh",function(){r.folder.getData().done(function(a){var b,c=a.unread;(b=j.nodes.title.find(".badge")).length===0&&(b=$('<span class="badge badge-error">').appendTo(j.nodes.title)),c>0?b.text(c).show():b.hide()})}),k.setEmptyMessage(function(
a){return a==="search"?i('No mails found for "%s"',j.search.query):i("No mails in this folder")}),d.addFolderSupport(r,k,"mail").pipe(d.showWindow(j,k)).done(function(){_.url.hash("lamp")==="true"&&r.toggleLamp()})}),r.toggleLamp=function(){var a=!1,b=_.once(function(){var a=r.getWindow().nodes;a.outer.append($("<div>").addClass("spotlight-icon").css({backgroundImage:"url("+ox.base+"/apps/themes/default/glyphicons_064_lightbulb.png)"}).on("click",r.toggleLamp))});return function(){var c;b(),c=r.getWindow
().nodes,c.outer[a?"removeClass":"addClass"]("spotlight"),a=!a,_.url.hash("lamp",a?"true":null)}}(),{getApp:r.getInstance}})