define("io.ox/mail/settings",["io.ox/core/extensions","io.ox/settings/utils","io.ox/core/tk/dialogs","io.ox/core/tk/forms","io.ox/core/tk/view","settings!io.ox/mail"],function(a,b,c,d,e,f){var g,h={},i=function(){var a=[$()],b=0,c=$(),d=this,e=function(d,e){return function(){return a[b]=a[b][b===0?"add":"append"](c=d[e].apply(d,arguments)),this}};_(arguments).each(function(a){for(var b in a)_.isFunction(a[b])&&(d[b]=e(a,b))}),this.invoke=function(){var a=$.makeArray(arguments),b=a.shift();return c
[b].apply(c,a),this},this.add=function(){return b++,a.push(c),this},this.end=function(){return b>0&&(b--,a.pop()),this},this.get=function(){return a[0]},this.done=function(){try{return this.get()}catch(b){}finally{for(var e in this)delete this[e];a=c=d=null}}};return"use strict",window.settings=f,g={draw:function(a,c){var d=new e({model:f});return a.append(d.node),console.log(d),d.node.append(b.createSettingsHead(c)).append(b.createSection().append(b.createSectionTitle({text:"Common"}),b.createSectionContent
().append(b.createInfoText({html:"EVERYTHING IS JUST MENT TO BE AN EXAMPLE HERE::::: Melden Sie sich mit Ihrem OX-Konto in OX Chrome an, "+"um Ihre personalisierten Browserfunktionen online zu "+"speichern und über OX Chrome auf jedem Computer darauf "+"zuzugreifen. Sie werden dann auch automatisch in Ihren "+"Lieblingsdiensten von OX angemeldet. Weitere Informationen"+'mehr Infos unter <a href="http://www.open-xchange.com" target="_blank">www.open-xchange.com</a>'}),b.createSectionGroup().append
(d.createSelectbox({property:"mail-common-defaultview",label:"Default view:",items:{"V-split view 1":"option1","V-split view 2":"option2","V-split view 3":"option3"},currentValue:"option1",validator:h})).addClass("expertmode"),b.createSectionGroup().append(d.createSelectbox({property:"mail-common-spamfolderview",label:"Default view for Spam folder",items:{"V-split view 1":"option1","V-split view 2":"option2","V-split view 3":"option3"},validator:h})).addClass("expertmode"),b.createSectionDelimiter
(),b.createButton({label:"my button me"}),d.createCheckbox({property:"mail-common-selectfirst",label:"Automatically select first E-Mail?",validator:h}).addClass("expertmode"),d.createCheckbox({property:"mail-common-removepermanently",label:"Permanently remove deleted E-Mails?",validator:h}),d.createCheckbox({property:"mail-common-notifyreceipt",label:"Notify on delivery receipt?",validator:h}).addClass("expertmode"),d.createCheckbox({property:"mail-common-showsenderpic",label:"Show sender image?"
,validator:h}),d.createCheckbox({property:"mail-common-collectwhilesending",label:'Automatically collect contacts in the folder "Collected addresses" while sending?',validator:h}).addClass("expertmode"),d.createCheckbox({property:"mail-common-collectwhilereading",label:'Automatically collect contacts in the folder "Collected addresses" while reading?',validator:h}).addClass("expertmode"),b.createSectionDelimiter(),b.createButton({label:"click me"})),b.createSectionDelimiter())).append(b.createSection
().append(b.createSectionTitle({text:"Compose"})).append(b.createSectionContent().append(d.createCheckbox({property:"mail-common-selectfirst",label:"Insert the original E-Mail text to a reply",validator:h}).addClass("expertmode")).append(d.createCheckbox({property:"mail-common-removepermanently",label:"Append vcard",validator:h})).append(d.createCheckbox({property:"mail-common-notifyreceipt",label:"Enable auto completion of E-Mail addresses",validator:h}).addClass("expertmode")).append(b.createSectionGroup
().append(b.createInfoText({text:"Forward E-Mails as:"})).append(d.createRadioButton({property:"mail-compose-forwardas",label:"Inline",name:"mail-compose-forwardas",value:!0,validator:h})).append(d.createRadioButton({property:"mail-compose-forwardas",label:"Attachment",name:"mail-compose-forwardas",value:!1,validator:h})).addClass("expertmode")).append(b.createSectionGroup().append(b.createInfoText({text:'When "Reply all":'})).append(d.createRadioButton({property:"mail-compose-whenreplyall",label
:'Add sender and recipients to "To", Cc to "Cc"',name:"mail-compose-whenreplyall",value:"fields",validator:h})).append(d.createRadioButton({property:"mail-compose-whenreplyall",label:'Add sender to "To", recipients to "Cc"',name:"mail-compose-whenreplyall",value:"cc",validator:h})).addClass("expertmode")).append(b.createSectionGroup().append(b.createInfoText({text:"Format E-Mails as:"})).append(d.createRadioButton({property:"mail-compose-emailformat",label:"HTML",name:"mail-compose-emailformat",value
:"html",validator:h})).append(d.createRadioButton({property:"mail-compose-emailformat",label:"Plain text",name:"mail-compose-emailformat",value:"plain",validator:h})).append(d.createRadioButton({property:"mail-compose-emailformat",label:"HTML and Plain text",name:"mail-compose-emailformat",value:"both",validator:h}))).append(b.createSectionGroup().append(d.createSelectbox({property:"mail-testselect",label:"Editor feature set",items:{Enhanced:"enhanced",Default:"default"},validator:h})).addClass("expertmode"
)).append(b.createSectionGroup().append(d.createSelectbox({property:"mail-compose-font",label:"Default E-Mail font:",items:{Default:"default","Andale Mono":"andale_mono",Arial:"arial","Arial Black":"arial_black","Book Antiqua":"book_antiqua"},validator:h})).addClass("expertmode")).append(b.createSectionGroup().append(d.createSelectbox({property:"mail-compose-fontsize",label:"Default E-Mail font size:",items:{Default:"default","1 (8pt)":"8_pt","2 (10pt)":"10_pt"},validator:h})).addClass("expertmode"
)).append(b.createSectionGroup().append(d.createText({text:"Line wrap when sending text mails after: "})).append(d.createTextField({property:"mail-compose-linewarpafter",validator:h}).css({width:"30px",display:"inline-block"})).append(d.createText({text:" characters"})).addClass("expertmode")).append(b.createSectionGroup().append(d.createSelectbox({property:"mail-compose-defaultsender",label:"Default sender address:",items:{"mario@sourcegarden.de":"mario@sourcegarden.de","mario@sourcegarden.com":"mario@sourcegarden.com"
,"mario.scheliga@open-xchange.com":"mario.scheliga@open-xchange.com"},validator:h}))).append(b.createSectionGroup().append(d.createSelectbox({property:"mail-compose-savedraftsinterval",label:"Auto-save Email drafts?",items:{Disabled:"disabled","1 Minute":"1_minute","3 Minutes":"3_minutes","5 Minutes":"5_minutes","10 Minutes":"10_minutes"},validator:h})).addClass("expertmode")).append(b.createSectionDelimiter())).append(b.createSectionDelimiter())).append(b.createSection().append(b.createSectionTitle
({text:"Display"})).append(b.createSectionContent().append(d.createCheckbox({property:"mail-display-allowhtml",label:"Allow html formatted E-Mails",validator:h})).append(d.createCheckbox({property:"mail-display-blockimgs",label:"Block pre-loading of externally linked images",validator:h})).append(d.createCheckbox({property:"mail-display-emotionicons",label:"Display emoticons as graphics in text E-Mails",validator:h})).append(d.createCheckbox({property:"mail-display-colorquotes",label:"Color quoted lines"
,validator:h})).append(d.createCheckbox({property:"mail-display-namesinfields",label:"Show name instead of E-Mail address in To and Cc fields",validator:h}))).append(b.createSectionDelimiter())).append(b.createSection().addClass("expertmode").append(b.createSectionTitle({text:"Signatures"})).append(b.createSectionContent().append(d.createCheckbox({property:"mail-display-namesinfields",label:"Show name instead of E-Mail address in To and Cc fields",validator:h}))).append(b.createSectionDelimiter()
)).append(b.createSection().addClass("expertmode").append(b.createSectionTitle({text:"Filter"})).append(b.createSectionContent().append(d.createCheckbox({property:"mail-display-namesinfields",label:"Show name instead of E-Mail address in To and Cc fields",validator:h}))).append(b.createSectionDelimiter())).append(b.createSection().append(b.createSectionTitle({text:"Vacation Notice"})).append(b.createSectionContent().append(d.createCheckbox({property:"mail-display-namesinfields",label:"Show name instead of E-Mail address in To and Cc fields"
,validator:h}))).append(b.createSectionDelimiter())),a}},a.point("io.ox/mail/settings/detail").extend({index:200,id:"mailsettings",draw:function(a){return g.draw(this,a)},save:function(){f.save().done(function(){console.log("saved for email")})}}),{}})