define("io.ox/mail/view-detail",["io.ox/core/extensions","io.ox/core/extPatterns/links","io.ox/mail/util","io.ox/mail/api","io.ox/core/config","io.ox/core/http","io.ox/core/api/account","gettext!io.ox/mail/mail","io.ox/mail/actions"],function(a,b,c,d,e,f,g,h){var i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B;"use strict",window.iframeResize=function(a,b){_.defer(function(){var c=$(b.body).outerHeight(!0);$("#tmp-iframe-"+a).css("height",c+30+"px")}),Modernizr.touch&&$(b).on("touchmove",function(a){a.preventDefault
()})},i=function(a){var b=String(a||"").split(/<br\s?\/?>/i),c=!1,d=/^&gt;( |$)/i,e=0,f=b.length,g=[],h;for(a="";e<f;e++)h=b[e],d.test(h)?c?g.push(h.replace(d,"")):(c=!0,g=[h.replace(d,"")]):c?(g=$.trim(g.join("\n")).replace(/\n/g,"<br>"),a=a.replace(/<br>$/,"")+"<blockquote><p>"+g+"</p></blockquote>"+h,c=!1):a+=h+"<br>";return a},j=function(a){var b=i($.trim(a).replace(/\n|\r/g,"").replace(/^\s*(<br\/?>\s*)+/g,"").replace(/(<br\/?>\s*){3,}/g,"<br><br>").replace(/<\/blockquote>\s*(<br\/?>\s*)+<blockquote[^>]+>/g
,"<br><br>").replace(/(&quot;([^&]+)&quot;|"([^"]+)"|'([^']+)')(\s|<br>)+&lt;([^@]+@[^&]+)&gt;/g,'<a href="mailto:$6">$2$3</a>'));return b},k=function(a){var b=(a||"unknown").split(/;/);return b[0]},l=/^text\/html$/i,m=/^image\/(jpe?g|png|gif|bmp)$/i,n=/^(\s*)(http[^#]+#m=infostore&f=\d+)(\s*)$/i,o=/^(\s*)(http[^#]+#m=infostore&f=\d+&i=\d+)(\s*)$/i,p=/^(.*)(http:\/\/\S+)(\s.*)?$/i,q=/(<img[^>]+src=")\/ajax/g,r=function(a){a.preventDefault(),location.hash=a.data.hash,ox.launch("io.ox/files/main")}
,s=function(a){var b;return(b=a.match(/^https?:\/\/([^\/]+)/i))&&b.length&&_(ox.serverConfig.hosts).indexOf(b[1])},t=function(a,b){var c,d,e,f;return c=$("<a>",{href:"#"}).css({textDecoration:"none",fontFamily:"Arial"}).append($('<span class="label label-info">').text(b)),s(a)&&(d=a.match(/#m=infostore&f=(\d+)&i=(\d+)/i))&&d.length?(e=d[1],f=d[2],a="#app=io.ox/files&folder="+e+"&id="+e+"."+f,c.on("click",{hash:a},r)):c.attr("href",$.trim(a)),c},u=function(a){return $("<a>",{href:a}).text(a)},v=function(
a,b){setTimeout(function(){b.removeClass("unread"),a.unseen=!1,d.caches.get.add(a),b=a=null},2e3)},w=function(){var a=this.scrollHeight+"px";$(this).off("click.open").css("cursor","").on("dblclick.close",x).stop().animate({maxHeight:a,opacity:1},500)},x=function(){document.getSelection&&document.getSelection().collapse(this,0),$(this).off("dblclick.close").css("cursor","pointer").on("click.open",w).stop().animate({maxHeight:"3em",opacity:.5},500)},y=function(a){var b,c,d;a.preventDefault(),b=$(this
),c=b.attr("href").substr(7),d=b.text(),ox.launch("io.ox/mail/write/main").done(function(){this.compose({to:[[d,c]]})})},z={getContent:function(a){if(!a||!a.attachments)return $();var b=a.attachments,c="",e,f,g,i;e=k(b[0].content_type),f=l.test(e),c=$.trim(b[0].content),g=c.length>1024*512;if(c==="")return $("<div>").addClass("content").append($("<div>").addClass("infoblock backstripes").text(h("This email has no content")));return c=c.replace(q,"$1"+ox.apiRoot),i=document.createElement("DIV"),i.
className="content",i.innerHTML=c,i=$(i),f?g||(i.find("meta").remove(),i.find('div[style*="none none none solid"][style*="1.5pt"]').each(function(){$(this).replaceWith($("<blockquote>").append($(this).contents()))}).end().find("blockquote").find('[style*="white-space: "]').css("whiteSpace","").end().find("*").css("color","").end().end().find("img[width], img[height]").each(function(){var a=$(this),b=a.attr("width"),c=a.attr("height");a.removeAttr("width height"),b&&a.css({width:b+"px",maxWidth:b+"px"
}),c&&a.css("height",c+"px")}).end(),!("folder_id"in a)&&"filename"in a&&i.find('img[src^="cid:"]').each(function(){var b=$(this),c="<"+String(b.attr("src")||"").substr(4)+">",e,f=_.chain(a.attachments).filter(function(a){return a.cid===c}).first().value();f&&(e=d.getUrl(_.extend(f,{mail:a.parent}),"view"),b.attr("src",e))})):i.addClass("plain-text").html(j(c)),g||i.find("*").contents().each(function(){if(this.nodeType===3){var a=$(this),b=this.nodeValue,c=b.length,d;c>=60&&/\S{60}/.test(b)&&(this
.nodeValue=b.replace(/(\S{60})/g,"$1​")),(d=b.match(o))&&d.length?a.replaceWith($($.txt(d[1])).add(t(d[2],h("Document"))).add($.txt(d[3]))):(d=b.match(n))&&d.length?a.replaceWith($($.txt(d[1])).add(t(d[2],h("Folder"))).add($.txt(d[3]))):(d=b.match(p))&&d.length&&a.closest("a").length===0&&a.replaceWith($($.txt(d[1]||"")).add(u(d[2])).add($.txt(d[3])))}}),_(i.get(0).getElementsByTagName("BLOCKQUOTE")).each(function(a){a.removeAttribute("style"),a.removeAttribute("type")}),_(i.get(0).getElementsByTagName
("A")).each(function(a){$(a).attr("target","_blank").filter('[href^="mailto:"]').on("click",y)}),g||i.find("blockquote").not(i.find("blockquote blockquote")).css({maxHeight:"3em",overflow:"hidden",opacity:.5,cursor:"pointer"}).on("click.open",w).on("dblclick.close",x),i},drawScaffold:function(a,b){return $("<div>").addClass("mail-detail").busy().one("resolve",a,b)},draw:function(b){if(!b)return $("<div>");var d=$("<div>").addClass("mail-detail");return b.threadSize>1&&c.byMyself(b)&&!g.is("sent",
b.folder_id)&&d.addClass("by-myself"),c.isUnread(b)?d.addClass("unread"):b.unseen===!0&&v(b,d.addClass("unread")),a.point("io.ox/mail/detail").invoke("draw",d,b),d},autoResolveThreads:function(a){var b=$(this),c=b.parents();d.get(d.reduce(a.data)).done(function(c){c.threadKey=a.data.threadKey,c.threadPosition=a.data.threadPosition,c.threadSize=a.data.threadSize,b.replaceWith(z.draw(c))})},drawThread:function(){function b(a){var b=$(this),c=a.data.node,d=b.scrollTop(),e=d+c.parent().height();a.data
.nodes.each(function(){var a=$(this),b=a.position();b.top>d&&b.top<e&&a.trigger("resolve")})}function e(c,d,e,f,g,h){var i,j,k=document.createDocumentFragment(),l=c.closest(".scrollable").off("scroll"),m,n,f,o,p;d.length>1&&(n=$('<div class="mail-detail thread-inline-actions">'),a.point("io.ox/mail/thread").invoke("draw",n,d),n.children().first().prepend($('<span class="io-ox-label">').text("Entire thread")),k.appendChild(n.get(0)));for(i=0;j=d[i];i++)i>=f&&i<=g?(p=h.shift(),p.threadKey=j.threadKey
,p.threadPosition=j.threadPosition,p.threadSize=j.threadSize,k.appendChild(z.draw(p).get(0))):k.appendChild(z.drawScaffold(j,z.autoResolveThreads).get(0));c.idle().empty().get(0).appendChild(k),m=c.find(".mail-detail").not(".thread-inline-actions"),f=m.eq(e).position().top,l.scrollTop(d.length===1?0:f),l.on("scroll",{nodes:m,node:c},_.debounce(b,250)),m=k=c=l=d=p=h=null}return function(a,b,f){var g=_.lfo(e);d.getList(b).done(function(e){var f,h=e.length-1,i,j,k,l,m=[];for(f=i=h;f>=0;f--){i=f;if(c
.isUnread(e[f]))break}j=Math.ceil(a.parent().height()/300),l=Math.min(i+j,h),k=Math.max(0,i-(i+j-l));for(f=k;f<=l;f++)m.push(d.get(d.reduce(b[f])));$.when.apply($,m).done(function(){g(a,b,i,k,l,$.makeArray(arguments))})})}}()},a.point("io.ox/mail/detail").extend({index:100,id:"contact-picture",draw:function(a){var b;this.append(b=$("<div>").addClass("contact-picture").hide()),require(["io.ox/contacts/api"],function(c){c.getPictureURL(a.from[0][1]).done(function(c){c&&b.css("background-image","url("+
c+")").show(),/dummypicture\.png$/.test(c)&&b.addClass("default-picture"),c=b=a=null})})}}),a.point("io.ox/mail/detail").extend({index:110,id:"receiveddate",draw:function(a){var b=c.getDateTime(a.received_date||a.sent_date||0);this.append($("<div>").addClass("date list").text(b))}});function C(a){var b=ox.ui.App.get("io.ox/mail")[0],c=b.getWindow(),d=a.data.display_name||a.data.email1;c.nodes.search.val(d).focus(),c.search.query=d,c.trigger("search")}return a.point("io.ox/mail/detail").extend({index
:120,id:"fromlist",draw:function(a){this.append($("<div>").addClass("from list").append(c.serializeList(a.from,!0,function(a){ox.ui.App.get("io.ox/mail").length&&this.append($('<i class="icon-search">').on("click",a,C).css({marginLeft:"0.5em",opacity:.3,cursor:"pointer"}))})))}}),a.point("io.ox/mail/detail").extend({index:124,id:"thread-position",draw:function(a){a.threadSize>1&&this.append($("<div>").addClass("thread-size clear-title").text(a.threadPosition+" / "+a.threadSize))}}),a.point("io.ox/mail/detail"
).extend({index:125,id:"flag",draw:function(a){this.append($("<div>").addClass("flag flag_"+c.getFlag(a)+" clear-title").text(" "))}}),a.point("io.ox/mail/detail").extend({index:130,id:"subject",draw:function(a){this.append($("<div>").addClass("subject clear-title").text(_.prewrap(a.subject?$.trim(a.subject):" ")).append($("<span>").addClass("priority").append(c.getPriority(a))))}}),a.point("io.ox/mail/detail").extend({index:150,id:"tocopy",draw:function(a){var b=_(a.to).reduce(function(a,b){return a&&
b[1]===e.get("mail.defaultaddress")},!0),d=a.cc&&a.cc.length>0,f=a.to&&(a.to.length>1||!b),g=f||d;g&&this.append($("<div>").addClass("to-cc list").append($("<span>").addClass("io-ox-label").text(h("To")+"  "),c.serializeList(a.to,!0),$.txt("   "),d?$("<span>").addClass("io-ox-label").text(h("Copy")+"  "):[],c.serializeList(a.cc,!0)))}}),A=function(a,c,e){var f=(new b.DropdownLinks({label:c,classes:"attachment-link",ref:"io.ox/mail/attachment/links"})).draw.call(a,e),g=k(e.content_type),h,i;m.test
(g)&&f.find("a").on("click",e,function(a){var b=$(this),c=a.data,e=b.parent(),f,g;e.hasClass("open")&&e.find(".instant-preview").length===0&&(f=d.getUrl(c,"view"),g=f+"&scaleType=contain&width=190&height=190",e.find("ul").append($("<li>").append($("<a>",{href:f,target:"_blank"}).append($("<img>",{src:g,alt:""}).addClass("instant-preview")))))}),_.isArray(e)?(h=d.getUrl(e,"zip"),i=(e.subject||"mail")+".zip"):(h=d.getUrl(e,"download"),i=String(e.filename||"")),f.find("a").attr({title:e.title,draggable
:!0,"data-downloadurl":g+":"+i.replace(/:/g,"")+":"+ox.abs+h}).on("dragstart",function(a){$(this).css({display:"inline-block",backgroundColor:"white"}),a.originalEvent.dataTransfer.setData("DownloadURL",this.dataset.downloadurl)})},B=function(a){return!("filename"in a)&&a.attachments&&a.attachments.length===1&&a.attachments[0].content===null},a.point("io.ox/mail/detail").extend({index:160,id:"attachments",draw:function(a){var b,c,d,e,f,g=[],i=!1,j={id:a.id,folder_id:a.folder_id};for(b=0,c=(a.nested_msgs||
[]).length;b<c;b++)d=a.nested_msgs[b],B(d)?(e=d.attachments[0],g.push(_.extend({},e,{mail:j,title:d.filename||""}))):g.push({id:d.id,content_type:"message/rfc822",filename:d.filename||_.ellipsis((d.subject||"").replace(/\s+/g," "),50),title:d.filename||d.subject||"",mail:j,nested_message:_.extend({},d,{parent:j})}),i=!0;for(b=0,c=(a.attachments||[]).length;b<c;b++)d=a.attachments[b],d.disp==="attachment"&&(g.push(_.extend(d,{mail:j,title:d.filename||""})),i=!0);i&&(f=$("<div>").addClass("list attachment-list"
).append($("<span>").addClass("io-ox-label").text(h("Attachments")+"  ")),_(g).each(function(a,b){var c=(a.filename||"Attachment #"+b).replace(/\.(\w+)$/,function(a){return a.toLowerCase()});A(f,c,a)}),g.length>1&&(g.subject=a.subject,A(f,h("All"),g)),this.append(f))}}),a.point("io.ox/mail/detail").extend(new b.InlineLinks({index:170,id:"inline-links",ref:"io.ox/mail/links/inline"})),a.point("io.ox/mail/thread").extend(new b.InlineLinks({index:100,id:"inline-links",ref:"io.ox/mail/links/inline"})
),a.point("io.ox/mail/detail").extend({index:195,id:"externalresources-warning",draw:function(a){var b=this;a.modified===1&&this.append($("<div>").addClass("list").addClass("infoblock backstripes").append($("<a>").text(h("Show images")),$("<i>").text(" – "+h("External images have been blocked to protect you against potential spam!"))).on("click",function(c){c.preventDefault(),require(["io.ox/mail/api"],function(c){c.getUnmodified(a).done(function(a){var c=z.draw(a);b.empty().append(c.children())}
)})}))}}),a.point("io.ox/mail/detail").extend({index:200,id:"content",draw:function(a){this.addClass("view").attr("data-cid",a.folder_id+"."+a.id).append(z.getContent(a),$("<div>").addClass("mail-detail-clear-both"))}}),z})