
package com.openexchange.admin.soap.reseller.context.reseller.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T11:28:46.071+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "ContextExistsException", targetNamespace = "http://soap.reseller.admin.openexchange.com")
public class ContextExistsException_Exception extends java.lang.Exception {
    
    private com.openexchange.admin.soap.reseller.context.reseller.soap.ContextExistsException contextExistsException;

    public ContextExistsException_Exception() {
        super();
    }
    
    public ContextExistsException_Exception(String message) {
        super(message);
    }
    
    public ContextExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ContextExistsException_Exception(String message, com.openexchange.admin.soap.reseller.context.reseller.soap.ContextExistsException contextExistsException) {
        super(message);
        this.contextExistsException = contextExistsException;
    }

    public ContextExistsException_Exception(String message, com.openexchange.admin.soap.reseller.context.reseller.soap.ContextExistsException contextExistsException, Throwable cause) {
        super(message, cause);
        this.contextExistsException = contextExistsException;
    }

    public com.openexchange.admin.soap.reseller.context.reseller.soap.ContextExistsException getFaultInfo() {
        return this.contextExistsException;
    }
}
