
package com.openexchange.admin.soap.reseller.context.reseller.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T11:28:46.249+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXResellerContextServicePortType_OXResellerContextServiceHttpEndpoint_Server{

    protected OXResellerContextServicePortType_OXResellerContextServiceHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXResellerContextServicePortTypeImpl();
        String address = "http://192.168.32.167/servlet/axis2/services/OXResellerContextService.OXResellerContextServiceHttpEndpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXResellerContextServicePortType_OXResellerContextServiceHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
