define("io.ox/files/actions",["io.ox/files/api","io.ox/core/extensions","io.ox/core/extPatterns/links","gettext!io.ox/files/files"],function(a,b,c,d){var e=c.Action;"use strict",new e("io.ox/files/actions/upload",{id:"upload",requires:"create",action:function(a){require(["io.ox/files/views/create"],function(b){b.show(a,{uploadedFile:function(b){a.invalidateFolder(b)}})})}}),new e("io.ox/files/actions/share",{id:"share",action:function(a){require(["io.ox/publications/wizard"],function(b){b.oneClickAdd
(a.folder.get())})}}),new e("io.ox/files/actions/editor",{id:"editor",requires:function(a){return a.collection.has("one")&&/\.(txt|js|md)$/i.test(a.context.data.filename)},action:function(a){ox.launch("io.ox/editor/main").done(function(){this.load(a)})}}),new e("io.ox/files/actions/editor-new",{id:"editor-new",action:function(a){ox.launch("io.ox/editor/main").done(function(){this.create({folder:a.folder.get()})})}}),new e("io.ox/files/actions/download",{id:"download",requires:"some",action:function(
b){_(b).each(function(b){a.get(b).done(function(c){b.version&&(c=_.extend({},c,{version:b.version})),window.open(a.getUrl(c,"download"))})})}}),new e("io.ox/files/actions/edit",{id:"edit",requires:"one modify",action:function(a,b){b.view.edit()}}),new e("io.ox/files/actions/open",{id:"open",requires:"some",multiple:function(b){_(b).each(function(b){a.get(b).done(function(c){b.version&&(c=_.extend({},c,{version:b.version})),window.open(a.getUrl(c,"open"),c.title||"file")})})}}),new e("io.ox/files/actions/send"
,{id:"send",requires:"some",multiple:function(b){require(["io.ox/mail/write/main"],function(c){a.getList(b).done(function(a){c.getApp().launch().done(function(){this.compose({infostore_ids:a})})})})}}),new e("io.ox/files/actions/delete",{id:"delete",requires:"some",multiple:function(b){require(["io.ox/core/tk/dialogs"],function(c){(new c.ModalDialog).text(d("Are you really sure about your decision? Are you aware of all consequences you have to live with?")).addPrimaryButton("delete",d("Shut up and delete it!"
)).addButton("cancel",d("No, rather not")).show().done(function(c){c==="delete"&&a.remove(b)})})}}),b.point("io.ox/files/actions/edit/save").extend({id:"save",action:function(b,c){var d=c.view.getModifiedFile();a.update(d).done(),c.view.endEdit()}}),b.point("io.ox/files/actions/edit/cancel").extend({id:"cancel",action:function(a,b){b.view.endEdit()}}),new e("io.ox/files/versions/actions/makeCurrent",{id:"makeCurrent",action:function(b){a.update({id:b.id,last_modified:b.last_modified,version:b.version
})}}),new e("io.ox/files/versions/actions/delete",{id:"delete",action:function(b){require(["io.ox/core/tk/dialogs"],function(c){(new c.ModalDialog).text(d("Are you really sure about your decision? Are you aware of all consequences you have to live with?")).addPrimaryButton("delete",d("Shut up and delete it!")).addButton("cancel",d("No, rather not")).show().done(function(c){c==="delete"&&a.detach(b)})})}}),b.point("io.ox/files/links/toolbar").extend(new c.Link({index:100,id:"upload",label:d("Upload"
),ref:"io.ox/files/actions/upload"})),b.point("io.ox/files/links/toolbar").extend(new c.Link({index:200,id:"share",label:d("Share"),ref:"io.ox/files/actions/share"})),b.point("io.ox/files/links/toolbar").extend(new c.Link({index:300,id:"editor-new",label:d("Pad!"),ref:"io.ox/files/actions/editor-new"})),b.point("io.ox/files/links/inline").extend(new c.Link({id:"editor",index:40,prio:"hi",label:d("Edit document"),ref:"io.ox/files/actions/editor"})),b.point("io.ox/files/links/inline").extend(new c.
Link({id:"edit",index:50,label:d("Edit"),ref:"io.ox/files/actions/edit"})),b.point("io.ox/files/links/inline").extend(new c.Link({id:"open",index:100,prio:"hi",label:d("Open"),ref:"io.ox/files/actions/open"})),b.point("io.ox/files/links/inline").extend(new c.Link({id:"download",index:200,prio:"hi",label:d("Download"),ref:"io.ox/files/actions/download"})),b.point("io.ox/files/links/inline").extend(new c.Link({id:"send",index:300,label:d("Send by email"),ref:"io.ox/files/actions/send"})),b.point("io.ox/files/links/inline"
).extend(new c.Link({id:"delete",index:400,prio:"hi",label:d("Delete"),ref:"io.ox/files/actions/delete"})),b.point("io.ox/files/links/edit/inline").extend(new c.Button({id:"cancel",index:100,label:d("Cancel"),ref:"io.ox/files/actions/edit/cancel",cssClasses:"btn",tabIndex:40})),b.point("io.ox/files/links/edit/inline").extend(new c.Button({id:"save",index:1e5,label:d("Save"),ref:"io.ox/files/actions/edit/save",cssClasses:"btn btn-primary",tabIndex:30})),b.point("io.ox/files/versions/links/inline")
.extend(new c.Link({id:"open",index:100,label:d("Open"),ref:"io.ox/files/actions/open"})),b.point("io.ox/files/versions/links/inline").extend(new c.Link({id:"download",index:200,label:d("Download"),ref:"io.ox/files/actions/download"})),b.point("io.ox/files/versions/links/inline").extend(new c.Link({id:"makeCurrent",index:250,label:d("Make this the current version"),ref:"io.ox/files/versions/actions/makeCurrent",isEnabled:function(a){return!a.current_version}})),b.point("io.ox/files/versions/links/inline"
).extend(new c.Link({id:"delete",index:300,label:d("Delete version"),ref:"io.ox/files/versions/actions/delete",special:"danger"})),b.point("io.ox/files/dnd/actions").extend({id:"create",index:10,label:d("Drop here to upload a <b>new file</b>"),action:function(a,b){b.queues.create.offer(a)}}),b.point("io.ox/files/dnd/actions").extend({id:"newVersion",index:20,isEnabled:function(a){return!!a.currentFile},label:function(a){if(a.currentFile.title)return d('Drop here to upload a <b>new version</b> of "%1$s"'
,String(a.currentFile.title).replace(/</g,"&lt;"));else return d("Drop here to upload a <b>new version</b>")},action:function(a,b){b.queues.update.offer(a)}}),b.point("io.ox/files/shortcuts").extend({id:"cancel",shortcut:"esc",ref:"io.ox/files/actions/edit/cancel"}),b.point("io.ox/files/shortcuts").extend({id:"edit",shortcut:"ctrl+enter",ref:"io.ox/files/actions/edit"})})