define("io.ox/files/view-detail",["io.ox/core/extensions","io.ox/core/extPatterns/links","io.ox/core/extPatterns/layouts","io.ox/core/tk/keys","io.ox/core/date","io.ox/core/event","io.ox/files/actions","io.ox/files/api","io.ox/preview/main","io.ox/core/tk/upload","io.ox/core/api/user","gettext!io.ox/files/files"],function(a,b,c,d,e,f,g,h,i,j,k,l){var m,n,o=function(b){var d,e="display",f=$("<div>").addClass("file-details view"),g=new c.Sections({ref:"io.ox/files/details/sections"}),i={"refresh.list"
:!0};return d={element:f,file:b,trigger:function(a,c){if(i[a])return;var d=this;c&&c.id&&c.id===b.id&&a!=="delete"&&h.get({id:c.id,folder:c.folder}).done(function(b){d.file=b,g.trigger(f,a,b)})},toggleEdit:function(){e==="edit"?a.point("io.ox/files/actions/edit/save").invoke("action",d,d.getModifiedFile(),{view:d,data:d.getModifiedFile()}):d.edit()},edit:function(){if(e==="edit")return;e="edit",g.each(function(a,c){var e=!0;a.each(function(a,c){a.edit?(e=!1,a.edit.call(c,b,{data:b,view:d})):a.deactivate?
(e=!1,a.deactivate.call(c,b,{data:b,view:d})):c&&c.css({opacity:"0.5"})}),e&&(c.fadeOut(),c.data("io-ox-files-hidden",!0))})},endEdit:function(){if(e==="display")return;e="display",g.each(function(a,c){a.each(function(a,c){a.endEdit?a.endEdit.call(c,b,{data:b,view:d}):a.activate?a.activate.call(c,b,{data:b,view:d}):c&&c.css({opacity:""})}),c.data("io-ox-files-hidden")&&(c.fadeIn(),c.data("io-ox-files-hidde",!1))})},getModifiedFile:function(){return g.each(function(a,c){a.each(function(a,c){a.process&&
a.process.call(c,b,{data:b,view:d})})}),b},destroy:function(){g.destroy(),f.empty(),f=null}},g.draw.call(f,b,d),d};return"use strict",a.point("io.ox/files/details/sections").extend({id:"header",layout:"Grid",index:100}),a.point("io.ox/files/details/sections").extend({id:"content",layout:"Grid",index:200}),a.point("io.ox/files/details/sections").extend({id:"upload",title:l("Upload a new version"),layout:"Grid",index:300}),a.point("io.ox/files/details/sections").extend({id:"versions",title:l("Versions"
),layout:"Grid",index:400,isEnabled:function(a){return a.current_version&&a.version>1}}),a.point("io.ox/files/details/sections/header").extend({id:"title",index:10,draw:function(a){this.append($("<div>").addClass("title clear-title").text(a.title||a.filename||" "))},edit:function(a,b){var c=this.find(".title").height(),e=(new d(this)).include();c<30&&(c=30),this.find(".title").empty().append($("<input>",{type:"text",name:"title"}).addClass("editing").attr({placeholder:l("Title"),tabIndex:10}).val
(a.title)),this.find("input").focus(),e.on("enter",function(){b.view.toggleEdit()}),this.data("keyListener",e)},endEdit:function(a){this.find(".title").empty().text(a.title||a.filename||" "),this.data("keyListener").remove(),this.data("keyListener",null)},process:function(a){a.title=this.find("input").val()},on:{update:function(a){this.empty(),this.append($("<div>").addClass("title clear-title").text(a.title||a.filename||" "))}}}),a.point("io.ox/files/details/sections/header").extend({id:"basicInfo"
,index:20,draw:function(b){var c;this.addClass("basicInfo"),c=$("<div>"),this.append(c),a.point("io.ox/files/details/sections/header/basicInfo").each(function(a){var d=0;_.each(a.fields,function(e,f){var g=null;c.append($("<em>").text(a.label(f)+":"),g=$("<span>"),$.txt("  ")),a.draw(f,b,g),d++,d===5&&(d=0,c=$("<div>"),this.append(c))})})},on:{update:function(a,b){this.empty(),b.draw.call(this,a)}}}),m=function(a){var b=["Bytes","KB","MB","GB","TB"],c;if(a===0)return"n/a";else return c=parseInt(Math
.floor(Math.log(a)/Math.log(1024)),10),(a/Math.pow(1024,c)).toFixed(1)+" "+b[c]},a.point("io.ox/files/details/sections/header/basicInfo").extend({id:"filename",index:100,fields:["filename"],label:function(){return l("File name")},draw:function(a,b,c){c.text(b.filename||"N/A")}}),a.point("io.ox/files/details/sections/header/basicInfo").extend({id:"size",index:200,fields:["file_size"],label:function(){return l("Size")},draw:function(a,b,c){c.text(m(b.file_size))}}),a.point("io.ox/files/details/sections/header/basicInfo"
).extend({id:"last_modified",index:400,fields:["last_modified"],label:function(){return l("Last Modified")},draw:function(a,b,c){var d=new e.Local(e.Local.utc(b.last_modified));c.append(k.getLink(b.created_by),$.txt(" – "+d.format(e.FULL_DATE)))}}),function(){var c=new b.InlineLinks({ref:"io.ox/files/links/inline"}),d=new b.InlineLinks({ref:"io.ox/files/links/edit/inline"});a.point("io.ox/files/details/sections/header").extend({index:30,id:"inline-links",orientation:"right",draw:function(a,b){c.draw
.call(this,{data:a,view:b,folder_id:a.folder_id})},edit:function(a,b){this.empty(),d.draw.call(this,{data:a,view:b.view,folder_id:a.folder_id})},endEdit:function(a,b){this.empty(),c.draw.call(this,{data:a,view:b.view,folder_id:a.folder_id})}})}(),a.point("io.ox/files/details/sections/content").extend(new i.Extension({id:"preview",index:10,dim:{span:6},parseArguments:function(a){if(!a.filename)return null;return{name:a.filename,mimetype:a.file_mimetype,size:a.file_size,dataURL:h.getUrl(a,"bare")}}
,on:{update:function(a,b){this.empty(),b.draw.call(this,a,b)}}})),a.point("io.ox/files/details/sections/content").extend({id:"description",index:20,dim:{span:6},isEnabled:function(){return!0},draw:function(a){this.append($("<div>").css({fontFamily:"monospace, 'Courier new'",whiteSpace:"pre-wrap",paddingRight:"2em"}).addClass("description").text(a.description||""))},edit:function(a,b){var c=this.parent().innerHeight(),e=(new d(this)).include();c<220&&(c=220),this.empty().append($("<textarea>").css
({resize:"none",width:"100%",height:c+"px",boxSizing:"border-box"}).attr({placeholder:l("Description"),tabIndex:20}).val(a.description)),e.on("shift+enter",function(){b.view.toggleEdit()}),this.data("keyListener",e)},endEdit:function(a){this.empty().append($("<div>").css({fontFamily:"monospace, 'Courier new'",whiteSpace:"pre-wrap",paddingRight:"2em"}).addClass("description").text(a.description||"")),this.data("keyListener").remove(),this.data("keyListener",null)},process:function(a){a.description=
this.find("textarea").val()},on:{update:function(a,b){this.empty(),b.draw.call(this,a,b)}}}),a.point("io.ox/files/details/sections/upload").extend({id:"form",index:10,dim:{span:6},draw:function(a){var b,c,e=this,f=$("<form>").appendTo(this),g=$("<input>",{type:"file"}),i=$("<button/>").text("Upload").addClass("btn btn-primary pull-right").on("click",function(){return _(g[0].files).each(function(d){i.addClass("disabled").text(l("Uploading...")),c.addClass("disabled"),g.addClass("disabled"),h.uploadNewVersion
({file:d,id:a.id,folder:a.folder,timestamp:a.last_modified,json:{version_comment:c.val()}}).done(function(a){i.removeClass("disabled").text(l("Upload new version")),c.removeClass("disabled"),g.removeClass("disabled"),b.hide(),c.val("")})}),!1});$("<div>").addClass("row-fluid").append($("<div>").addClass("span6").append(g)).append($("<div>").addClass("span6 pull-right").append(i)).appendTo(f),b=$("<div>").addClass("row-fluid").hide().appendTo(f),b.append($("<label>").text(l("Version Comment:"))),c=
$("<textarea rows='5'></textarea>").css({resize:"none",width:"100%"}).appendTo(b),g.on("change",function(){b.show(),c.focus()}),(new d(b)).on("shift+enter",function(a){a.preventDefault(),a.stopImmediatePropagation(),i.click()}).include()}}),n=function(a,b){if(a.version===b.version)return 0;if(a.current_version)return-1;if(b.current_version)return 1;return b.version-a.version},a.point("io.ox/files/details/sections/versions").extend({id:"table",index:10,isEnabled:function(a){return a.current_version&&
a.version>1},draw:function(a,b,d){var e=this,f=$("<a>",{href:"#"}).appendTo(this),g=$("<div>").addClass("versions");function i(a){g.empty(),_.chain(a).sort(n).each(function(a){var b=$("<div>").addClass("row-fluid version "+(a.current_version?"current":"")).append($("<div>").addClass("span1").append($("<span>").text(a.version).addClass("versionLabel"))),d=$("<div>").addClass("span11").appendTo(b);(new c.Grid({ref:"io.ox/files/details/versions/details"})).draw.call(d,a),g.append(b)}),e.empty().append
(g)}d?i(d):h.versions({id:a.id}).done(i)},on:{update:function(a,b){var c=this;h.versions({id:a.id}).done(function(d){c.empty(),b.draw.call(c,a,null,d)})}}}),a.point("io.ox/files/details/versions/details").extend({index:10,id:"filename",dim:{span:4},draw:function(a){(new b.DropdownLinks({label:a.filename,ref:"io.ox/files/versions/links/inline"})).draw.call(this,a)}}),a.point("io.ox/files/details/versions/details").extend({index:20,id:"size",dim:{span:4},draw:function(a){this.text(m(a.file_size)).css
({textAlign:"right"})}}),a.point("io.ox/files/details/versions/details").extend({index:30,id:"created_by",dim:{span:4,orientation:"right"},draw:function(a){this.append($("<span>").append(k.getLink(a.created_by)).addClass("pull-right"))}}),a.point("io.ox/files/details/versions/details").extend({index:40,id:"comment",dim:{span:8},draw:function(a){this.addClass("version-comment").text(a.version_comment||" ")}}),a.point("io.ox/files/details/versions/details").extend({index:50,id:"creation_date",dim:{
span:4,orientation:"right"},draw:function(a){var b=new e.Local(e.Local.utc(a.creation_date));this.append($("<span>").text(b.format(e.DATE_TIME)).addClass("pull-right"))}}),{draw:o}})