package com.openexchange.admin.soap.context;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-05-31T10:53:55.276+02:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "OXContextService", 
                  wsdlLocation = "null",
                  targetNamespace = "http://soap.admin.openexchange.com") 
public class OXContextService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.admin.openexchange.com", "OXContextService");
    public final static QName OXContextServiceHttpsEndpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpsEndpoint");
    public final static QName OXContextServiceHttpsSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpsSoap11Endpoint");
    public final static QName OXContextServiceHttpSoap11Endpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpSoap11Endpoint");
    public final static QName OXContextServiceHttpEndpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpEndpoint");
    public final static QName OXContextServiceHttpSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpSoap12Endpoint");
    public final static QName OXContextServiceHttpsSoap12Endpoint = new QName("http://soap.admin.openexchange.com", "OXContextServiceHttpsSoap12Endpoint");
    static {
        WSDL_LOCATION = null;
    }

    public OXContextService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OXContextService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OXContextService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsEndpoint")
    public OXContextServicePortType getOXContextServiceHttpsEndpoint() {
        return super.getPort(OXContextServiceHttpsEndpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsEndpoint")
    public OXContextServicePortType getOXContextServiceHttpsEndpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpsEndpoint, OXContextServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsSoap11Endpoint")
    public OXContextServicePortType getOXContextServiceHttpsSoap11Endpoint() {
        return super.getPort(OXContextServiceHttpsSoap11Endpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsSoap11Endpoint")
    public OXContextServicePortType getOXContextServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpsSoap11Endpoint, OXContextServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpSoap11Endpoint")
    public OXContextServicePortType getOXContextServiceHttpSoap11Endpoint() {
        return super.getPort(OXContextServiceHttpSoap11Endpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpSoap11Endpoint")
    public OXContextServicePortType getOXContextServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpSoap11Endpoint, OXContextServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpEndpoint")
    public OXContextServicePortType getOXContextServiceHttpEndpoint() {
        return super.getPort(OXContextServiceHttpEndpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpEndpoint")
    public OXContextServicePortType getOXContextServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpEndpoint, OXContextServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpSoap12Endpoint")
    public OXContextServicePortType getOXContextServiceHttpSoap12Endpoint() {
        return super.getPort(OXContextServiceHttpSoap12Endpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpSoap12Endpoint")
    public OXContextServicePortType getOXContextServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpSoap12Endpoint, OXContextServicePortType.class, features);
    }
    /**
     *
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsSoap12Endpoint")
    public OXContextServicePortType getOXContextServiceHttpsSoap12Endpoint() {
        return super.getPort(OXContextServiceHttpsSoap12Endpoint, OXContextServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OXContextServicePortType
     */
    @WebEndpoint(name = "OXContextServiceHttpsSoap12Endpoint")
    public OXContextServicePortType getOXContextServiceHttpsSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(OXContextServiceHttpsSoap12Endpoint, OXContextServicePortType.class, features);
    }

}
