
package com.openexchange.admin.soap.usercopy.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T08:52:52.829+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "UserExistsException", targetNamespace = "http://soap.copy.user.admin.openexchange.com")
public class UserExistsException_Exception extends java.lang.Exception {

    private com.openexchange.admin.soap.usercopy.soap.UserExistsException userExistsException;

    public UserExistsException_Exception() {
        super();
    }

    public UserExistsException_Exception(String message) {
        super(message);
    }

    public UserExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserExistsException_Exception(String message, com.openexchange.admin.soap.usercopy.soap.UserExistsException userExistsException) {
        super(message);
        this.userExistsException = userExistsException;
    }

    public UserExistsException_Exception(String message, com.openexchange.admin.soap.usercopy.soap.UserExistsException userExistsException, Throwable cause) {
        super(message, cause);
        this.userExistsException = userExistsException;
    }

    public com.openexchange.admin.soap.usercopy.soap.UserExistsException getFaultInfo() {
        return this.userExistsException;
    }
}
