ALTER TABLE prg_attachment
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY creation_date INT8 NOT NULL,
    MODIFY created_by INT4 UNSIGNED NOT NULL,
	MODIFY attached INT4 UNSIGNED NOT NULL,
	MODIFY module INT4 UNSIGNED NOT NULL,
	MODIFY file_mimetype VARCHAR(255) NOT NULL,
	MODIFY filename VARCHAR(255) NOT NULL,
	MODIFY comment VARCHAR(255),
	MODIFY file_id VARCHAR(255) NOT NULL,
	MODIFY file_size INT4 UNSIGNED NOT NULL,
    ENGINE=InnoDB;


ALTER TABLE del_attachment
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
    MODIFY del_date INT8 NOT NULL,
	MODIFY attached INT4 UNSIGNED NOT NULL,
	MODIFY module INT4 UNSIGNED NOT NULL,
    ENGINE=InnoDB;
    