#@(#) mail.sql consistency


ALTER TABLE mail_domains
    MODIFY cid INT4 UNSIGNED NOT NULL,
    MODIFY id INT4 UNSIGNED NOT NULL,
	MODIFY domainName VARCHAR(128) UNIQUE NOT NULL,
	MODIFY smtpSenderRule VARCHAR(128) NOT NULL,
	MODIFY restriction VARCHAR(64) NOT NULL,
    ENGINE=InnoDB;

ALTER TABLE user_mail_restrictions
	MODIFY cid INT4 UNSIGNED NOT NULL,
	MODIFY id INT4 UNSIGNED NOT NULL,
	MODIFY className VARCHAR(64) NOT NULL,
	MODIFY address VARCHAR(255) UNIQUE NOT NULL,
    ADD FOREIGN KEY (cid, id) REFERENCES user(cid, id),
	ENGINE=InnoDB;

ALTER TABLE address_mappings
	MODIFY cid INT4 UNSIGNED NOT NULL,
	MODIFY id INT4 UNSIGNED NOT NULL,
	MODIFY address VARCHAR(255) UNIQUE NOT NULL,
	MODIFY destination VARCHAR(255) NOT NULL,
	ENGINE=InnoDB;

# amavis

ALTER TABLE policy
	ENGINE=InnoDB;
