define("io.ox/mail/write/test/text_send",["io.ox/mail/write/main","io.ox/mail/api","io.ox/core/api/user","io.ox/core/config","io.ox/core/extensions"],function(a,b,c,d,e){var f=ox.base+"/apps/io.ox/mail/write/test",g=5e3;"use strict";function h(){var a=function(){return a.value};return a.value=!1,a.yep=function(){a.value=!0},a}e.point("test/suite").extend({id:"mail-compose-text",index:100,test:function(e){e.describe("Compose email",function(){var f,i,k=null,l=null,m=null;e.it("opens compose dialog in TEXT mode"
,function(){var b=new h;e.waitsFor(b,"compose dialog",g),a.getApp().launch().done(function(){k=this,k.compose().done(function(){k.setFormat("text").done(function(){l=k.getEditor(),m=k.getWindow().nodes.main.find("form"),b.yep(),e.expect(l).toBeDefined(),e.expect(m).toBeDefined(),e.expect(l.getMode()).toEqual("text")})})})}),e.it("adds recipient",function(){var a;m.find("input[data-type=to]").val("otto.xentner@io.ox").focus().trigger($.Event("keyup",{which:13})),a=m.find(".recipient-list input[type=hidden][name=to]"
),e.expect(a.val()).toEqual('"otto.xentner" <otto.xentner@io.ox>')}),e.it("adds recipient with display name",function(){var a;m.find("input[data-type=to]").val('"Otto X." <otto.xentner@io.ox>').focus().trigger($.Event("keyup",{which:13})),a=m.find(".recipient-list input[type=hidden][name=to]").last(),e.expect(a.val()).toEqual('"Otto X." <otto.xentner@io.ox>')}),e.it("adds recipient by focussing another element",function(){var a;m.find("input[data-type=to]").val('"Otto;must escape,this" <otto.xentner@io.ox>'
).focus().blur(),a=m.find(".recipient-list input[type=hidden][name=to]").last(),e.expect(a.val()).toEqual('"Otto;must escape,this" <otto.xentner@io.ox>')}),e.it("adds multiple recipients at once",function(){var a;m.find("input[data-type=to]").val(' "Otto;must escape,this" <otto.xentner@io.ox>; "Hannes" <hannes@ox.io>, '+"Horst <horst@ox.io>;, ").focus().blur(),a=m.find(".recipient-list input[type=hidden][name=to]").slice(-3),e.expect(!0).toEqual(a.eq(0).val()==='"Otto;must escape,this" <otto.xentner@io.ox>'&&
a.eq(1).val()==='"Hannes" <hannes@ox.io>'&&a.eq(2).val()==='"Horst" <horst@ox.io>')}),e.it("opens CC section",function(){var a;m.find("[data-section-link=cc]").trigger("click"),a=m.find("[data-section=cc]:visible"),e.expect(a.length).toEqual(1)}),e.it("adds recipient to CC",function(){var a;m.find("input[data-type=cc]").val("otto.xentner@io.ox").focus().trigger($.Event("keyup",{which:13})),a=m.find(".recipient-list input[type=hidden][name=cc]"),e.expect(a.val()).toEqual('"otto.xentner" <otto.xentner@io.ox>'
)}),e.it("opens BCC section",function(){var a;m.find("[data-section-link=bcc]").trigger("click"),a=m.find("[data-section=bcc]:visible"),e.expect(a.length).toEqual(1)}),e.it("adds recipient to BCC",function(){var a;m.find("input[data-type=bcc]").val("hannes@io.ox").focus().trigger($.Event("keyup",{which:13})),a=m.find(".recipient-list input[type=hidden][name=bcc]"),e.expect(a.val()).toEqual('"hannes" <hannes@io.ox>')}),e.it("removes recipient from BCC",function(){var a,b=m.find(".recipient-list input[type=hidden][name=bcc]"
);b.parent().find("a.remove").trigger("click"),a=m.find(".recipient-list input[type=hidden][name=bcc]"),e.expect(!0).toEqual(b.length===1&&a.length===0)}),e.it("closes BCC section",function(){var a;m.find("[data-section-label=bcc]").trigger("click"),a=m.find("[data-section=bcc]:visible"),e.expect(a.length).toEqual(0)}),e.it("sets high priority",function(){var a;m.find("input[name=priority]").eq(0).focus().prop("checked",!0).trigger("change").blur(),a=m.find(".priority-overlay"),e.expect(a.hasClass
("high")).toEqual(!0)}),e.it("sets subject",function(){m.find("input.subject").val("TEST: Hello World"),e.expect(m.find("input[name=subject]").val()).toEqual("TEST: Hello World")}),e.it("sets editor content",function(){l.setContent("Lorem ipsum"),e.expect(l.getContent()).toEqual("Lorem ipsum")}),e.it("has correct mail body",function(){var a=k.getMail().data;e.expect(a.attachments&&a.attachments.length&&a.attachments[0].content_type==="text/plain").toEqual(!0),e.expect(a.attachments[0].content).toEqual
("Lorem ipsum")}),e.it("has correct mail props (bcc)",function(){var a=k.getMail().data;e.expect(_.isArray(a.bcc)&&a.bcc.length===0).toEqual(!0)}),e.it("has correct mail props (cc)",function(){var a=k.getMail().data;e.expect(_.isArray(a.cc)&&a.cc.length===1&&a.cc[0][0]==='"otto.xentner"'&&a.cc[0][1]==="otto.xentner@io.ox").toEqual(!0)}),e.it("has correct mail props (delivery receipt)",function(){var a=k.getMail().data;e.expect(a.disp_notification_to===0).toEqual(!0)}),e.it("has correct mail props (from)"
,function(){var a=k.getMail().data;e.expect(_.isArray(a.from)&&a.from.length===1).toEqual(!0)}),e.it("has correct mail props (priority)",function(){var a=k.getMail().data;e.expect(a.priority===1).toEqual(!0)}),e.it("has correct mail props (subject)",function(){var a=k.getMail().data;e.expect(a.subject==="TEST: Hello World").toEqual(!0)}),e.it("has correct mail props (to)",function(){var a=k.getMail().data;e.expect(_.isArray(a.to)&&a.to.length===6&&a.to[4][0]==='"Hannes"'&&a.to[4][1]==="hannes@ox.io"
).toEqual(!0)}),e.it("has correct mail props (vcard)",function(){var a=k.getMail().data;e.expect(a.vcard===0).toEqual(!0)}),f={},_.browser.IE||(e.it("sends mail successfully",function(){var a=k.getMail().data,l=new h,m=d.get("identifier");e.waitsFor(l,"mail being send",g),c.get({id:m}).done(function(c){a.to=[['"'+c.display_name+'"',c.email1]],a.cc=[],a.bcc=[],i=a,b.send(a).always(function(a){l.yep(),f=String(a.data),e.expect(a.error).toBeUndefined()})})}),e.it("verifies that sent mail is ok",function(
){var a=new h,c=i,d=f.split(/\/(\d+$)/);e.waitsFor(a,"mail being fetched",g),b.get({folder:d[0],id:d[1]}).done(function(b){b.from[0][0]='"'+b.from[0][0]+'"',b.to[0][0]='"'+b.to[0][0]+'"',a.yep(),e.expect(_.isEqual(b.subject,c.subject)&&_.isEqual(b.from,c.from)&&_.isEqual(b.to,c.to)&&_.isEqual(b.cc,c.cc)&&_.isEqual(b.bcc,c.bcc)&&_.isEqual(b.priority,c.priority)&&_.isEqual(b.disp_notification_to||0,c.disp_notification_to||0)&&_.isEqual(b.vcard||0,c.vcard||0)).toEqual(!0)})})),e.it("closes compose dialog"
,function(){k.markClean(),k.quit(),e.expect(k.getEditor).toBeUndefined(),k=l=m=null})})}})})