define("io.ox/settings/accounts/email/settings",["io.ox/core/extensions","io.ox/settings/utils","io.ox/core/api/account","io.ox/settings/accounts/email/model","io.ox/settings/accounts/email/view-form","io.ox/core/tk/dialogs","gettext!io.ox/settings/settings"],function(a,b,c,d,e,f,g){var h,i,j,k,l,m,n,o,p,q,r,s,t,u;return"use strict",a.point("io.ox/settings/accounts/email/settings/detail").extend({index:200,id:"emailaccountssettings",draw:function(a){var b,g,h,i,j;if(a.data.id)c.get(a.data.id).done
(function(c){return b=c,j=$("<div>").addClass("accountDetail"),h=new d(b),g=new e({model:h,node:j}),g.dialog=(new f.SidePopup("800")).show(a,function(a){a.append(g.render().el)}),g.node});else return j=$("<div>").addClass("accountDetail"),i=a.data.autoconfig,h=new d(i),g=new e({model:h,node:j}),g.dialog=(new f.SidePopup("800")).show(a,function(a){a.append(g.render().el)}),g.node}}),j=function(b){var c="email",d=$("<div>");require(["io.ox/settings/accounts/"+c+"/settings"],function(e){a.point("io.ox/settings/accounts/"+
c+"/settings/detail").invoke("draw",d,b)})},k=function(a,b){a.find(".alert").remove(),a.find(".busynotice").remove(),a.append($("<div>").addClass("alert alert-block fade in").append($("<a>").attr({href:"#","data-dismiss":"alert"}).addClass("close").html("&times;"),$("<p>").text(b)))},l=function(a){a.find(".notice").remove(),a.find(".alert").remove(),a.append($("<div>").addClass("busynotice").text(g("Trying to auto-configure your mail account")).addClass("notice").append($("<div>").addClass("busy_pic"
)))},m=function(a,b){a.find(".notice").remove(),a.find(".alert").remove(),a.append($("<div>").addClass("alert alert-success").text(b))},n=function(a,b){a.name=a.primary_address,a.personal=a.primary_address,a.unified_inbox_enabled=!1,a.mail_secure=!0,a.transport_secure=!0,a.transport_credentials=!1,a.spam_handler="NoSpamHandler",p(a,b)},o=function(a,b){var c=$("<div>"),d=$(".listbox"),e=d.find($('[data-item-id="email/'+a+'"]'));e[0]||(c.addClass("deletable-item"),c.attr("data-item-id","email/"+a),
c.append($("<a>").html("&times;").addClass("close")),c.append($("<div>").html(b)),c.on("click",function(){console.log("click"),c.parent().find('div[selected="selected"]').attr("selected",null),c.attr("selected","selected")}),d.append(c))},p=function(a,b){c.on("account_created",function(a,b){o(b.id,b.email),i.close(),u()}),c.validate(a).done(function(c){if(c===!1){var e=g("Failed to connect. Please check your password and try again");k(b,e),i.idle()}else{var f=new d({});f.save(a)}}).fail(function(
){var a=g("Failed to connect.");k(b,a),i.idle()})},q=function(a,b){c.autoconfig({email:b,password:"test"}).done(function(c){a.data||(a.data={}),a.data.autoconfig=c,a.data.autoconfig.primary_address=b,h.close(),t(a)}).fail(function(){console.log("no configdata recived"),a.data||(a.data={},a.data.autoconfig={}),a.data.autoconfig={},a.data.autoconfig.primary_address=b,j(a),h.close()})},r=function(a){var b=/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;if(b.test(a))return!0},s=function(
a){var b=$("<label>").text(g("Your mail address")),c=$("<input>",{value:""}).addClass("input-large"),d=$("<div>");c.keyup(function(a){if(a.keyCode===13){var b=h.getFooter().find(".btn-primary");b.trigger("click")}}),a.preventDefault(),require(["io.ox/core/tk/dialogs"],function(e){var f=this;h=new e.ModalDialog({width:400,easyOut:!0,async:!0}),h.header($("<h4>").text(g("Add mail account"))).append(b.append(c)).append(d).addButton("cancel","Cancel").addPrimaryButton("add","Add").show(function(){c.focus
()}),h.on("add",function(){var b=c.val();if(r(b))l(d),q(a,b);else{var e=g("This is not an valid mail address");k(d,e),c.focus(),h.idle()}})})},t=function(a){var b=$("<label>").text(g("Your password")),c=$("<input>",{value:""}).attr("type","password").addClass("input-large"),d=$("<div>");c.keyup(function(a){if(a.keyCode===13){var b=i.getFooter().find(".btn-primary");b.trigger("click")}}),a.preventDefault(),require(["io.ox/core/tk/dialogs"],function(e){var f=this;i=new e.ModalDialog({width:400,easyOut
:!0,async:!0}),i.header($("<h4>").text(g("Add password for mail account"))).append(b.append(c)).append(d).addButton("cancel",g("Cancel")).addPrimaryButton("add",g("Submit")).show(function(){c.focus()});var h=g("We now need your password to complete the setup process");m(d,h),i.on("add",function(b){var e=c.val(),f;if(e!=="")a.data.autoconfig.password=e,f=a.data.autoconfig,l(d),n(f,d);else{var h=g("Please fill the password");k(d,h),c.focus(),i.idle()}})})},u=function(){var a=$("<div>");require(["io.ox/core/tk/dialogs"
],function(b){var c=this,d=new b.ModalDialog({width:400,easyOut:!0,async:!0});d.header().append(a).addButton("cancel",g("Close")).show(function(){d.getFooter().find(".btn").addClass("closebutton");var b=g("Account added successfully");m(a,b)})})},{mailAutoconfigDialog:s}})