
package com.openexchange.admin.soap.context.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:39:08.185+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXContextServicePortType_OXContextServiceHttpEndpoint_Server{

    protected OXContextServicePortType_OXContextServiceHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXContextServicePortTypeImpl();
        String address = "http://ox6-dev.open-xchange.com/servlet/axis2/services/OXContextService.OXContextServiceHttpEndpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXContextServicePortType_OXContextServiceHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
