define.async("io.ox/core/date",["io.ox/core/gettext","io.ox/core/config"],function(a,b){var c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v=["","E","yMd","yMEd","Hm","yMEdHm","yMdHm","yMEdHm","v","yMEdHmv","yMdHmv","yMEdHmv","Hmv","yMEdHmv","yMdHmv","yMEdHmv"],w=31556952e3,x={SECOND:1e3,MINUTE:6e4,HOUR:36e5,DAY:864e5,WEEK:6048e5,DAYOFWEEK:1,DATE:2,TIME:4,TIMEZONE:8,DAYOFWEEK_DATE:3,DATE_TIME:6,DAYOFWEEK_DATE_TIME:7,TIME_TIMEZONE:12,DATE_TIME_TIMEZONE:14,FULL_DATE:15,getFormat:function(a){return a=a||x.DATE_TIME
,typeof a=="number"&&(a=v[a],x.locale.h12&&(a=a.replace("H","h")),a=x.locale.formats[a]),a}};"use strict",x.locale={daysInFirstWeek:null,days:["1","2","3","4","5","6","7"],daysShort:["1","2","3","4","5","6","7"],daysStandalone:["1","2","3","4","5","6","7"],months:["1","2","3","4","5","6","7","8","9","10","11","12"],monthsShort:["1","2","3","4","5","6","7","8","9","10","11","12"],formats:{E:"E",yMd:"y-M-d",yMEd:"E, y-M-d",yMMMd:"y MMM d",yMMMEd:"E, y MMM d",hm:"h:mm a",Hm:"HH:mm",v:"v",Hmv:"HH:mm v"
,hmv:"h:mm a v",yMdHm:"y-M-d HH:mm",yMdHmv:"y-M-d HH:mm v",yMdhm:"y-M-d h:mm a",yMdhmv:"y-M-d h:mm a v",yMEdHm:"E, y-M-d HH:mm",yMEdHmv:"E, y-M-d HH:mm v",yMEdhm:"E, y-M-d h:mm a",yMEdhmv:"E, y-M-d h:mm a v"},date:"y MMM d",time:"HH:mm",dateTimeFormat:"%2$s %1$s",intervals:{fallback:"%1$s – %2$s",hm:{a:"h:mm a – h:mm a",h:"h:mm–h:mm a",m:"h:mm–h:mm a"},Hm:{a:"HH:mm–HH:mm",h:"HH:mm–HH:mm",m:"HH:mm–HH:mm"},hmv:{a:"h:mm a – h:mm a v",h:"h:mm–h:mm a v",m:"h:mm–h:mm a v"},Hmv:{a:"HH:mm–HH:mm v",h:"HH:mm–HH:mm v"
,m:"HH:mm–HH:mm v"},yMMMd:{d:"yyyy-MM-d – d",m:"yyyy-MM-dd – MM-d",y:"yyyy-MM-dd – yyyy-MM-dd"},yMMMEd:{d:"E, yyyy-MM-dd – E, yyyy-MM-dd",m:"E, yyyy-MM-dd – E, yyyy-MM-dd",y:"E, yyyy-MM-dd – E, yyyy-MM-dd"}},dayPeriods:{am:"AM",pm:"PM"},eras:["BCE","CE"],dateTime:"y MMM d HH:mm",h12:!1},c=0;function y(a){return a.getDays()-(a.getDay()-x.locale.weekStart+7)%7}function z(a){return y(a)+7-x.locale.daysInFirstWeek}function A(a,b){var c=z(a),d=a.constructor,e=new d(c*x.DAY),f=new d(e.getYear(),b?e.getMonth
():0);return Math.floor((c-f.getDays())/7)+1}function B(a){var b=a.getYear(),c=a.getMonth(),d=A(a);return c===0&&d>26&&b--,c===11&&d<26&&b++,b}function C(a){return a%4===0&&(a%100!==0||a%400===0)}d="GyYMwWDdFEuaHkKhmsSzZvV".split("").join("+|")+"+",e=new RegExp("("+d+")|'((?:[^']|'')+)'|('')","g");function D(a,b){var c,d,e=b.toString();a-=e.length;if(a<=0)return e;c=new Array(a+1);for(d=0;d<a;d++)c[d]="0";return c[a]=e,c.join("")}function E(a,b,c){return a>=4?b:c}f={a:function(a,b){return x.locale
.dayPeriods[b.getHours()<12?"am":"pm"]},D:function(a,b){return D(a,b.getDays()-(new b.constructor(b.getYear(),0)).getDays()+1)},d:function(a,b){return D(a,b.getDate())},E:function(a,b){var c=b.getDay();return E(a,x.locale.days[c],x.locale.daysShort[c])},F:function(a,b){return D(a,Math.floor(b.getDate()/7)+1)},G:function(a,b){return x.locale.eras[b.getYear()<1?0:1]},H:function(a,b){return D(a,b.getHours())},h:function(a,b){return D(a,b.getHours()%12||12)},K:function(a,b){return D(a,b.getHours()%12
)},k:function(a,b){return D(a,b.getHours()||24)},M:function(a,b){var c=b.getMonth();if(a>=3)return E(a,x.locale.months[c],x.locale.monthsShort[c]);else return D(a,c+1)},m:function(a,b){return D(a,b.getMinutes())},S:function(a,b){return D(a,b.getMilliseconds())},s:function(a,b){return D(a,b.getSeconds())},u:function(a,b){return D(a,(b.getDay()+6)%7+1)},W:function(a,b){return D(a,A(b,!0))},w:function(a,b){return D(a,A(b))},Y:function(a,b){var c=b.getYear(),d=b.getMonth(),e=A(b);return d===0&&e>26&&
c--,d===11&&e<26&&c++,c<1&&(c=1-c),D(a,a===2?c%100:c)},y:function(a,b){var c=b.getYear();return c<1&&(c=1-c),D(a,a===2?c%100:c)},z:function(a,b){},Z:function(a,b){},v:function(a,b){return b.getTimeZone()},V:function(a,b){}};function F(a,b){return String(a).replace(e,function(a,c,d,e){if(c)return f[c.charAt(0)](c.length,b);else if(d)return d.replace(/''/g,"'");else if(e)return"'"})}g="("+d+")(?!"+d+")|("+d+")(?="+d+")|'((?:[^']|'')+)'|('')|([$^\\\\.*+?()[\\]{}|])",h=new RegExp(g,"g");function G(a)
{return String(a).replace(/[$\^\\.*+?()\[\]{}|]/g,"\\$&")}function H(a,b){return"("+_.map(a.concat(b),G).join("|")+")"}function I(a,b){var c,d={};for(c=0;c<a.length;c++)d[a[c]]=c,d[b[c]]=c;return d}m="([+-]?\\d+)";function J(){return m}n={a:function(a){return"("+G(x.locale.dayPeriods.am)+"|"+G(x.locale.dayPeriods.pm)+")"},E:function(a){return j},G:function(a){return"("+G(x.locale.eras[0])+"|"+G(x.locale.eras[1])+")"},M:function(a){return a>=3?i:m},D:J,d:J,F:J,H:J,h:J,K:J,k:J,m:J,S:J,s:J,u:J,W:J,w
:J,Y:J,y:J};function K(a){return a>1?"([-+\\d]\\d{1,"+(a-1)+"})":"(\\d{1,"+a+"})"}o={M:function(a){return a>=3?i:K(a)},a:n.a,D:K,d:K,E:n.E,F:K,G:n.G,H:K,h:K,K:K,k:K,m:K,S:K,s:K,u:K,W:K,w:K,Y:K,y:K};function L(a){return function(){return function(b,c){c[a]=Number(b)}}}p={a:function(a){return function(a,b){b.pm=a===x.locale.dayPeriods.pm}},E:function(a){return function(a,b){}},G:function(a){return function(a,b){b.bc=a===x.locale.eras[0]}},h:function(a){return function(a,b){b.h2=a==="12"?0:Number(a)
}},k:function(a){return function(a,b){b.h=a==="24"?0:Number(a)}},M:function(a){return a>=3?function(a,b){b.m=k[a]}:function(a,b){b.m=a-1}},Y:function(a){return function(b,c){c.wcentury=a===2&&b.match(/^\d\d$/),c.wy=Number(b)}},y:function(a){return function(b,c){c.century=a===2&&b.match(/^\d\d$/),c.y=Number(b)}},D:L("yd"),d:L("d"),F:$.noop,H:L("h"),K:L("h2"),m:L("min"),S:L("ms"),s:L("s"),u:$.noop,W:$.noop,w:L("w")},q=new Date,r=Math.floor((q.getUTCFullYear()+20)/100)*100;function M(a,b,c){var d,e,
f,g,i,j=[],k=a.replace(h,function(a,b,c,d,e,f){if(b)return j.push(p[b.charAt(0)](b.length)),n[b.charAt(0)](b.length);else if(c)return j.push(p[c.charAt(0)](c.length)),o[c.charAt(0)](c.length);else if(d)return d;else if(e)return"'";else if(f)return"\\"+f}),l=b.match(new RegExp("^\\s*"+k+"\\s*$","i"));if(!l)return null;d={bc:!1,century:!1,pm:!1,y:1970,m:0,d:1,h:0,h2:0,min:0,s:0,ms:0,w:1,wd:0};for(e=0;e<j.length;e++)j[e](l[e+1],d);d.h||(d.h=Number(d.h2)+(d.pm?12:0));if(d.h<0||d.h>=24||d.min<0||d.min>=60||
d.s<0||d.s>=60||d.ms<0||d.ms>=1e3)return null;function m(a,b){var e;return b&&(a=Number(a)+r,e=new c(a-20,d.m,d.d,d.h,d.min,d.s,d.ms),e.getTime()>q.getTime()&&(a-=100)),d.bc&&(a=1-a),a}d.y=m(d.y),f=new c(0);if("wy"in d){d.wy=m(d.wy),f.setYear(d.wy),g=f.getDays(),i=y(f),7-(g-i)<x.locale.daysInFirstWeek&&(i+=7),f.setTime(c.utc(x.DAY*(i+7*d.w-7+(d.wd-x.locale.weekStart+7)%7)));if(B(f)!==Number(d.wy)||A(f)!==Number(d.w)||f.getDay()!==Number(d.wd))return null}else if("yd"in d){if(d.yd<0||d.yd>(C(d.y)?366
:365))return null;f.setYear(d.y),f.add(x.DAY*(d.yd-1))}else{f.setYear(d.y,d.m,d.d);if(f.getYear()!==Number(d.y)||f.getMonth()!==Number(d.m)||f.getDate()!==Number(d.d))return null}return f.setHours(d.h,d.min,d.s,d.ms),f}s=function(){function a(a){return"(?:"+a+")?"}var b="([^\\d,+-]{3,})",c="(\\d+)(?::(\\d+)(?::(\\d+))?)?",d="([+-])?"+c,e=",(?:J(\\d+)|(\\d+)|M(\\d+)\\.(\\d+)\\.(\\d+))(?:\\/"+c+")?";return new RegExp("^"+b+d+a(b+a(d)+e+e)+"$")}();function N(a,b){var c=(a-1)*x.DAY+b,d=a>31+28?x.DAY:0
;return function(a){return Date.UTC(a,0)+c+(C(a)?d:0)}}function O(a,b){var c=a*x.DAY+b;return function(a){return Date.UTC(a,0)+c}}function P(a,b,c,d){var e;if(Number(b)===5)return function(b){var e=Date.UTC(b,a)-x.DAY,f=(new Date(e)).getUTCDay();return e-(f-c+7)%7*x.DAY+d};else return a--,e=b*7*x.DAY+d,function(b){var d=Date.UTC(b,a),f=(new Date(d)).getUTCDay();return d+(c-f+7)%7*x.DAY+e}}function Q(a){var b,c,d,e,f=s.exec(a);function g(a){return f[a++]*x.HOUR+(f[a++]||0)*x.MINUTE+(f[a]||0)*x.SECOND
}function h(a){return f[a]==="-"?g(a+1):-g(a+1)}function i(a){var b=f[a+5]?g(a+5):72e5;return f[a]?N(f[a],b):f[a+1]?O(f[a+1],b):P(f[a+2],f[a+3],f[a+4],b)}if(f){b={abbr:f[1],isdst:!1,gmtoff:h(2)};if(f[6])return c={abbr:f[6],isdst:!0,gmtoff:f[8]?h(7):b.gmtoff+x.HOUR},d=i(11),e=i(19),function(a,f){var g=(new Date(a)).getUTCFullYear(),h=d(g)-(f?0:b.gmtoff),i=e(g)-(f?0:c.gmtoff),j=h<i?a>=h&&a<i:a>=h||a<i;return j?c:b};else return function(){return b}}}function R(a){var b,d,e,f,g,h,i,j,k,l,m,n,o;if(a.slice
(0,4)!=="TZif")throw new Error("Not a zoneinfo file.");b={8364:128,8218:130,402:131,8222:132,8230:133,8224:134,8225:135,710:136,8240:137,352:138,8249:139,338:140,381:142,8216:145,8217:146,8220:147,8221:148,8226:149,8211:150,8212:151,732:152,8482:153,353:154,8250:155,339:156,382:158,376:159},d=0;function p(){var c=a.charCodeAt(d++);return c<256?c:b[c]}function q(){return p()*16777216+p()*65536+p()*256+p()}function r(){var a=q();return a<2147483648?a:a-4294967296}function s(){return r()*4294967296+
q()}function u(){if(a.slice(d,d+4)!=="TZif")throw new Error("Invalid zoneinfo header.");return d+=20,{ttisgmtcnt:r(),ttisstdcnt:r(),leapcnt:r(),timecnt:r(),typecnt:r(),charcnt:r()}}f=u(),h=a.charAt(4)>="2",h?(g=s,d+=f.timecnt*5+f.typecnt*6+f.charcnt+f.leapcnt*8+f.ttisstdcnt+f.ttisgmtcnt,f=u()):g=r,i=[];for(e=0;e<f.timecnt;e++)i.push({start:g()*1e3});for(e=0;e<f.timecnt;e++)i[e].index=p();j=[];for(e=0;e<f.typecnt;e++)j.push({gmtoff:r()*x.SECOND,isdst:p(),abbr:p()});i=_.map(i,function(a){return{start
:a.start,ttinfo:j[a.index]}});for(e=0;e<f.typecnt;e++)k=d+j[e].abbr,j[e].abbr=a.slice(k,a.indexOf("\0",k));d+=f.charcnt,d+=f.leapcnt*(h?12:8)+f.ttisstdcnt+f.ttisgmtcnt,l=_.find(j,function(a){return!a.isdst})||_.first(j),m=h&&p()===10?Q(a.slice(d,a.indexOf("\n",d))):function(){return _.last(i).ttinfo},n=w/2;function v(a,b){var c,d,e,f,g,h=Infinity,i=-Infinity;function j(a){return Math.floor((a-c)/n)}d=[];if(a.length){h=_.first(a).start,i=_.last(a).start,c=h+w/4,e=-1;for(f=0;f<a.length;f++){g=j(a[f
].start);while(e<g)d[++e]=f;d[e]=f}}return function(c){var e;if(c<h)return l;else if(c>=i)return m(c,b);else{for(e=d[j(c)];a[e].start>c;--e);return a[e].ttinfo}}}function y(a){switch(arguments.length){case 0:this.t=(new Date).getTime()+c,this.local=y.localTime(this.t);break;case 1:this.t=(new Date(a)).getTime(),this.local=y.localTime(this.t);break;default:this.local=Date.UTC.apply(Date,arguments),this.t=y.utc(this.local)}}$.extend(y.prototype,t);if(Object.defineProperty)for(e in t)Object.defineProperty
(y.prototype,e,{enumerable:!1});return y.getTTInfo=v(i),y.localTime=function(a){return a+y.getTTInfo(a).gmtoff},o=l,y.getTTInfoLocal=v(_.map(i,function(a){return{start:a.start+o.gmtoff,ttinfo:o=a.ttinfo}}),!0),y.utc=function(a){return a-y.getTTInfoLocal(a).gmtoff},y.parse=function(a,b){return M(x.getFormat(b),a,y)},0,y}return t={getDays:function(){return Math.floor(this.local/x.DAY)},getTimeZone:function(){return this.constructor.getTTInfo(this.t).abbr},valueOf:function(){return this.t},toString:
function(){return this.format(x.FULL_DATE)},add:function(a){return this.t=this.constructor.utc(this.local+=a),this},addUTC:function(a){return this.local=this.constructor.localTime(this.t+=a),this},addMonths:function(a){var b=new Date(this.local);return b.setUTCMonth(b.getUTCMonth()+a),this.t=this.constructor.utc(this.local=b.getTime()),this},addYears:function(a){var b=new Date(this.local);return b.setUTCFullYear(b.getUTCFullYear()+a),this.t=this.constructor.utc(this.local=b.getTime()),this},setStartOfWeek
:function(){return this.local=x.DAY*y(this),this.t=this.constructor.utc(this.local),this},getTime:function(){return this.t},setTime:function(a){return this.local=this.constructor.localTime(this.t=a),this},getYear:function(){return(new Date(this.local)).getUTCFullYear()},setYear:function(a,b,c){var d=new Date(this.local);return d.setUTCFullYear.apply(d,arguments),this.t=this.constructor.utc(this.local=d.getTime()),this},getMonth:function(){return(new Date(this.local)).getUTCMonth()},setMonth:function(
a,b){var c=new Date(this.local);return c.setUTCMonth.apply(c,arguments),this.t=this.constructor.utc(this.local=c.getTime()),this},getDate:function(){return(new Date(this.local)).getUTCDate()},setDate:function(a){var b=new Date(this.local);return b.setUTCDate(a),this.t=this.constructor.utc(this.local=b.getTime()),this},getDay:function(){return(new Date(this.local)).getUTCDay()},getHours:function(){return(new Date(this.local)).getUTCHours()},setHours:function(a,b,c,d){var e=new Date(this.local);return e
.setUTCHours.apply(e,arguments),this.t=this.constructor.utc(this.local=e.getTime()),this},getMinutes:function(){return(new Date(this.local)).getUTCMinutes()},setMinutes:function(a,b,c){var d=new Date(this.local);return d.setUTCMinutes.apply(d,arguments),this.t=this.constructor.utc(this.local=d.getTime()),this},getSeconds:function(){return(new Date(this.local)).getUTCSeconds()},setSeconds:function(a,b){var c=new Date(this.local);return c.setUTCSeconds.apply(c,arguments),this.t=this.constructor.utc
(this.local=c.getTime()),this},getMilliseconds:function(){return(new Date(this.local)).getUTCMilliseconds()},setMilliseconds:function(a){var b=new Date(this.local);return b.setUTCMilliseconds(a),this.t=this.constructor.utc(this.local=b.getTime()),this},format:function(a){return F(x.getFormat(a),this)},getIntervalFormat:function(a,b){var c=x.locale;if(b&x.TIME)if(this.getDays()===a.getDays()){var d=c.intervals[(c.h12?"hm":"Hm")+(b&x.TIMEZONE?"v":"")];if(this.getHours()<12!=a.getHours()<12)return d
.a;else if(this.getHours()!==a.getHours())return d.h;else if(this.getMinutes()!==a.getMinutes())return d.m;else if(this.getTimeZone()===a.getTimeZone())return x.getFormat(b)}else b|=x.DATE;else{var d=b&x.DAYOFWEEK?c.intervals.yMMMEd:c.intervals.yMMMd;if(this.getYear()!==a.getYear())return d.y;else if(this.getMonth()!==a.getMonth())return d.m;else if(this.getDate()!==a.getDate())return d.d;else return x.getFormat(b)}return b=x.getFormat(b),_.printf(c.intervals.fallback,b,b)},formatInterval:function(
a,b){typeof b=="number"&&(b=this.getIntervalFormat(a,b));var c={},d;e.lastIndex=0;while(d=e.exec(b)){var f=d[1].charAt(0);if(c[f])break;c[f]=!0}if(e.lastIndex)return this.format(b.slice(0,d.index))+a.format(b.slice(d.index));else return this.format(b)}},x.getTimeZone=_.memoize(function(a){return require(["text!io.ox/core/date/tz/zoneinfo/"+a]).pipe(R).pipe(function(c){return c.id=a,c.displayName=b.get(["availableTimeZones",a],a),c})}),u=a.language.pipe(function(a){return require(["text!io.ox/core/date/date."+
a+".json"])}).done(function(a){x.locale=JSON.parse(a),i=H(x.locale.months,x.locale.monthsShort),j=H(x.locale.days,x.locale.daysShort),k=I(x.locale.months,x.locale.monthsShort),l=I(x.locale.days,x.locale.daysShort)}),$.when(x.getTimeZone("Europe/Berlin"),u).pipe(function(a){return x.Local=a,x})})