define("io.ox/core/http",["io.ox/core/event"],function(a){var b,c,d,e,f,g,h,i,j,k,l,m={common:{1:"id",2:"created_by",3:"modified_by",4:"creation_date",5:"last_modified",20:"folder_id",100:"categories",101:"private_flag",102:"color_label",104:"number_of_attachments"},mail:{102:"color_label",600:"id",601:"folder_id",602:"attachment",603:"from",604:"to",605:"cc",606:"bcc",607:"subject",608:"size",609:"sent_date",610:"received_date",611:"flags",612:"level",613:"disp_notification_to",614:"priority",615
:"msgref",651:"flag_seen",652:"account_name"},contacts:{500:"display_name",501:"first_name",502:"last_name",503:"second_name",504:"suffix",505:"title",506:"street_home",507:"postal_code_home",508:"city_home",509:"state_home",510:"country_home",511:"birthday",512:"marital_status",513:"number_of_children",514:"profession",515:"nickname",516:"spouse_name",517:"anniversary",518:"note",519:"department",520:"position",521:"employee_type",522:"room_number",523:"street_business",525:"postal_code_business"
,526:"city_business",527:"state_business",528:"country_business",529:"number_of_employees",530:"sales_volume",531:"tax_id",532:"commercial_register",533:"branches",534:"business_category",535:"info",536:"manager_name",537:"assistant_name",538:"street_other",539:"city_other",540:"postal_code_other",541:"country_other",542:"telephone_business1",543:"telephone_business2",544:"fax_business",545:"telephone_callback",546:"telephone_car",547:"telephone_company",548:"telephone_home1",549:"telephone_home2"
,550:"fax_home",551:"cellular_telephone1",552:"cellular_telephone2",553:"telephone_other",554:"fax_other",555:"email1",556:"email2",557:"email3",558:"url",559:"telephone_isdn",560:"telephone_pager",561:"telephone_primary",562:"telephone_radio",563:"telephone_telex",564:"telephone_ttytdd",565:"instant_messenger1",566:"instant_messenger2",567:"telephone_ip",568:"telephone_assistant",569:"company",571:"userfield01",572:"userfield02",573:"userfield03",574:"userfield04",575:"userfield05",576:"userfield06"
,577:"userfield07",578:"userfield08",579:"userfield09",580:"userfield10",581:"userfield11",582:"userfield12",583:"userfield13",584:"userfield14",585:"userfield15",586:"userfield16",587:"userfield17",588:"userfield18",589:"userfield19",590:"userfield20",592:"distribution_list",594:"number_of_distribution_list",596:"contains_image1",597:"image_last_modified",598:"state_other",599:"file_as",104:"number_of_attachments",601:"image1_content_type",602:"mark_as_distributionlist",605:"default_address",524
:"internal_userid",606:"image1_url"},calendar:{200:"title",201:"start_date",202:"end_date",203:"note",204:"alarm",207:"recurrence_position",208:"recurrence_date_position",209:"recurrence_type",212:"days",213:"day_in_month",214:"month",215:"interval",216:"until",220:"participants",221:"users",400:"location",401:"full_time",402:"shown_as"},infostore:{700:"title",701:"url",702:"filename",703:"file_mimetype",704:"file_size",705:"version",706:"description",707:"locked_until",708:"file_md5sum",709:"version_comment"
,710:"current_version",711:"number_of_versions"},tasks:{200:"title",201:"start_date",202:"end_date",203:"note",204:"alarm",209:"recurrence_type",212:"days",213:"day_in_month",214:"month",215:"internal",216:"until",220:"participants",221:"users",300:"status",301:"percent_completed",302:"actual_costs",303:"actual_duration",305:"billing_information",307:"target_costs",308:"target_duration",309:"priority",312:"currency",313:"trip_meter",314:"companies",315:"date_completed"},folders:{1:"id",2:"created_by"
,3:"modified_by",4:"creation_date",5:"last_modified",6:"last_modified_utc",20:"folder_id",300:"title",301:"module",302:"type",304:"subfolders",305:"own_rights",306:"permissions",307:"summary",308:"standard_folder",309:"total",310:"new",311:"unread",312:"deleted",313:"capabilities",314:"subscribed",315:"subscr_subflds",316:"standard_folder_type",3010:"com.openexchange.publish.publicationFlag",3020:"com.openexchange.subscribe.subscriptionFlag",3030:"com.openexchange.folderstorage.displayName"},user
:{610:"aliases",611:"timezone",612:"locale",613:"groups",614:"contact_id",615:"login_info"},group:{},resource:{},account:{1001:"id",1002:"login",1003:"password",1004:"mail_url",1005:"transport_url",1006:"name",1007:"primary_address",1008:"spam_handler",1009:"trash",1010:"sent",1011:"drafts",1012:"spam",1013:"confirmed_spam",1014:"confirmed_ham",1015:"mail_server",1016:"mail_port",1017:"mail_protocol",1018:"mail_secure",1019:"transport_server",1020:"transport_port",1021:"transport_protocol",1022:"transport_secure"
,1023:"transport_login",1024:"transport_passord",1025:"unified_inbox_enabled",1026:"trash_fullname",1027:"sent_fullname",1028:"drafts_fullname",1029:"spam_fullname",1030:"confirmed_spam_fullname",1031:"confirmed_ham_fullname",1032:"pop3_refresh_rate",1033:"pop3_expunge_on_quit",1034:"pop3_delete_write_through",1035:"pop3_storage ",1036:"pop3_path",1037:"personal"}};return"use strict",$.extend(m.contacts,m.common),$.extend(m.calendar,m.common),$.extend(m.infostore,m.common),delete m.infostore[101]
,delete m.infostore[104],$.extend(m.tasks,m.common),$.extend(m.user,m.contacts,m.common),b={},c=function(a,b){var c=m[a]||{},d=[],e="";for(e in c)d.push(e);return d.sort(function(a,b){return a-b}),b===!0?d.join(","):d},d=function(a,b,d){if(typeof a!="object")return a;d=d!==undefined?d:c(b);var e=m[b]||{},f={},g=0,h=a.length;for(;g<h;g++){var i=e[d[g]];f[i]=a[g]}return f},e=function(a,b){var d=$.extend({module:"",params:{},data:{},dataType:"json",appendColumns:b==="GET"||b==="UPLOAD"?!1:!0,columnModule
:a.module||"",appendSession:!0,processData:!0,processResponse:!0,cursor:!0},a||{}),e;return d.type=b,d.url=ox.apiRoot+"/"+d.module,d.appendSession===!0&&(d.params.session=ox.session),d.appendColumns===!0&&d.params.columns===undefined&&(e=c(d.columnModule),e.length&&(d.params.columns=e.join(","))),d.params.columns&&d.params.columns.replace(/\s/g,""),b==="GET"||b==="POST"?d.data=d.params:b==="PUT"||b==="DELETE"?(d.url+="?"+_.serialize(d.params),d.original=d.data,d.data=typeof d.data!="string"?JSON.
stringify(d.data):d.data,d.contentType="text/javascript; charset=UTF-8"):b==="UPLOAD"&&(d.url+="?"+_.serialize(d.params),d.contentType=!1,d.processData=!1,d.processResponse=!1),d},f=function(a,b,c){if(!_.isArray(a)||!c)return a;else{var e=0,f=a.length,g=[],h,i=c.split(",");for(;e<f;e++)h=a[e],g.push(_.isArray(h)?d(h,b,i):h);return g}},g=function(a,b,d){if(b&&b.error!==undefined&&!b.data){var e=/^SES\-/i.test(b.code),g=d.module==="login"&&d.data&&d.data.action==="autologin";e&&!g?(ox.session="",ox
.relogin(d,a)):a.reject(b)}else{b&&b.error!==undefined&&console.warn("TODO: warning");if(d.dataType==="json"&&d.processResponse===!0){var h=[],i;if(b)if(d.module==="multiple"){var j=0,k=b.length,l;for(;j<k;j++)i=b[j].timestamp!==undefined?b[j].timestamp:_.now(),b[j].data!==undefined?(l=f(b[j].data,d.data[j].columnModule,d.data[j].columns),h.push({data:l,timestamp:i}),b[j].error!==undefined&&console.warn("TODO: warning")):h.push({error:b[j],timestamp:i});a.resolve(h)}else{var m=d.params.columns||(
d.processResponse===!0?c(d.columnModule,!0):"");h=f(b.data,d.columnModule,m),i=b.timestamp!==undefined?b.timestamp:_.now(),a.resolve(h,i)}else a.resolve({},_.now())}else a.resolve(b||"")}},h=!1,i=[],j=_.url.hash("slow"),k=_.url.hash("fail"),l=function(){function c(a){var c=a.o.fixPost&&a.xhr.type==="POST",d=_.extend({},a.xhr,{dataType:c?"text":a.xhr.dataType});$.ajax(d).pipe(function(a){if(c){var b=/\((\{.*?\})\)/.exec(a);return b&&b[1]?JSON.parse(b[1]):JSON.parse(a)}else return a}).done(function(
c){a.o.processData?g(a.def,c,a.o,a.o.type):a.xhr.dataType==="json"&&c.error!==undefined?a.def.reject(c):a.def.resolve(c),b.trigger("stop done",a.xhr),a=null}).fail(function(c,d,e){a.def.reject({error:c.status+" "+(e||"general")},c),b.trigger("stop fail",a.xhr),a=null})}function d(d){var e;d.o.type==="GET"?(e=JSON.stringify(d.xhr),a[e]!==undefined?(a[e].then(d.def.resolve,d.def.reject).then(function(){b.trigger("stop done",d.xhr),d=null},function(){b.trigger("stop fail",d.xhr),d=null}),e=null):(a[
e]=d.def.always(function(){delete a[e],e=null}),c(d),d=null)):(c(d),d=null)}var a={};return function(a,c){a=e(a,c);var f,g=$.Deferred();if(h===!0)return i.push({deferred:g,options:a}),g;f={def:g,o:a,xhr:{type:c==="UPLOAD"?"POST":c,url:a.url,data:a.data,dataType:a.dataType,processData:a.processData,contentType:a.contentType!==undefined?a.contentType:"application/x-www-form-urlencoded"}},typeof a.timeout=="number"&&(f.xhr.timeout=a.timeout);function l(){k&&a.module!=="login"&&Math.random()<Number(k
)?(console.error("HTTP fail",f.o.url,f.xhr),f.def.reject({error:"0 simulated fail"}),b.trigger("stop fail",f.xhr)):d(f),f=a=null}return b.trigger("start",f.xhr),Number(j)?setTimeout(l,250*Number(j)+(Math.random()*500>>0)):l(),g}}(),b={GET:function(a){return l(a,"GET")},POST:function(a){return l(a,"POST")},PUT:function(a){return l(a,"PUT")},DELETE:function(a){return l(a,"DELETE")},UPLOAD:function(a){return l(a,"UPLOAD")},getAllColumns:c,makeObject:d,simplify:function(a){var b=0,c=null,d=new Array(
a.length);for(;c=a[b];b++)if(typeof c=="object"){d[b]={id:c.id};if(c.folder||c.folder_id)d[b].folder=c.folder||c.folder_id;c.recurrence_position&&(d[b].recurrence_position=c.recurrence_position)}else d[b]=c;return d},fixList:function(a,c){return c.pipe(function(c){var d,e,f,g,h;a=b.simplify(a),f={},g=new Array(c.length);for(d=0;e=c[d];d++)h=String(e.internal_userid?e.internal_userid:(e.folder_id||0)+"."+(e.internal_userid||e.id)+"."+(e.recurrence_position||0)),f[h]=e;for(d=0;e=a[d];d++)h=String(typeof 
e=="object"?(e.folder||0)+"."+(e.internal_userid||e.id)+"."+(e.recurrence_position||0):e),g[d]=f[h];return f=e=a=null,g})},retry:function(a){var b=(a.type||"GET").toUpperCase();return this[b](a)},pause:function(){h=!0,this.trigger("paused")},resume:function(){var a,b,c,d,e,f=$.Deferred(),g=i.slice();if(h===!0){a=0,b=g.length,e=[];for(;a<b;a++)c=g[a].options,delete c.params.session,d=$.extend(c.params,{module:c.module,data:c.original}),c.params.action!==undefined&&(d.action=c.params.action),e.push
(d);i=[],h=!1,this.trigger("resumed"),e.length>0?this.PUT({module:"multiple","continue":!0,data:e,appendColumns:!1}).done(function(c){for(a=0,b=g.length;a<b;a++)g[a].deferred.resolve(c[a]);f.resolve(c)}).fail(f.reject):f.resolve([])}else f.resolve([]);return f}},a.extend(b),b})