
package com.openexchange.admin.soap.user.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:24:58.903+02:00
 * Generated source version: 2.6.0
 */

@WebFault(name = "MissingServiceException", targetNamespace = "http://soap.admin.openexchange.com")
public class MissingServiceException_Exception extends java.lang.Exception {

    private com.openexchange.admin.soap.user.soap.MissingServiceException missingServiceException;

    public MissingServiceException_Exception() {
        super();
    }

    public MissingServiceException_Exception(String message) {
        super(message);
    }

    public MissingServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MissingServiceException_Exception(String message, com.openexchange.admin.soap.user.soap.MissingServiceException missingServiceException) {
        super(message);
        this.missingServiceException = missingServiceException;
    }

    public MissingServiceException_Exception(String message, com.openexchange.admin.soap.user.soap.MissingServiceException missingServiceException, Throwable cause) {
        super(message, cause);
        this.missingServiceException = missingServiceException;
    }

    public com.openexchange.admin.soap.user.soap.MissingServiceException getFaultInfo() {
        return this.missingServiceException;
    }
}
