package com.openexchange.admin.soap.user.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:24:59.078+02:00
 * Generated source version: 2.6.0
 *
 */
@WebService(targetNamespace = "http://soap.admin.openexchange.com", name = "OXPublicationServicePortType")
@XmlSeeAlso({com.openexchange.admin.soap.user.io.ObjectFactory.class, ObjectFactory.class, com.openexchange.admin.soap.user.rmi.ObjectFactory.class, com.openexchange.admin.soap.user.exceptions.ObjectFactory.class, com.openexchange.admin.soap.user.dataobjects.ObjectFactory.class})
public interface OXPublicationServicePortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:getPublication", output = "urn:getPublicationResponse", fault = {@FaultAction(className = MissingServiceException_Exception.class, value = "urn:getPublicationMissingServiceException"), @FaultAction(className = NoSuchPublicationException_Exception.class, value = "urn:getPublicationNoSuchPublicationException")})
    @WebMethod(action = "urn:getPublication")
    public void getPublication(
        @WebParam(partName = "parameters", name = "getPublication", targetNamespace = "http://soap.admin.openexchange.com")
        GetPublication parameters
    ) throws MissingServiceException_Exception, NoSuchPublicationException_Exception;

}
