
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.openexchange.admin.soap.user.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-01T18:24:58.986+02:00
 * Generated source version: 2.6.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "OXUserService",
                      portName = "OXUserServiceHttpSoap11Endpoint",
                      targetNamespace = "http://soap.admin.openexchange.com",
                      // wsdlLocation = "null",
                      endpointInterface = "com.openexchange.admin.soap.user.soap.OXUserServicePortType")
                      
public class OXUserServicePortTypeImpl2 implements OXUserServicePortType {

    private static final Logger LOG = Logger.getLogger(OXUserServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#createByModuleAccess(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  usrdata ,)com.openexchange.admin.soap.user.dataobjects.UserModuleAccess  access ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.User createByModuleAccess(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User usrdata,com.openexchange.admin.soap.user.dataobjects.UserModuleAccess access,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation createByModuleAccess");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(access);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#change(com.openexchange.admin.soap.user.soap.Change  parameters )*
     */
    @Override
    public void change(Change parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation change");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#createByModuleAccessName(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  usrdata ,)java.lang.String  accessCombinationName ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.User createByModuleAccessName(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User usrdata,java.lang.String accessCombinationName,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation createByModuleAccessName");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(accessCombinationName);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#getModuleAccess(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  user ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.UserModuleAccess getModuleAccess(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User user,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getModuleAccess");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.UserModuleAccess _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#listAll(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.util.List<com.openexchange.admin.soap.user.dataobjects.User> listAll(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation listAll");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.user.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#getContextAdmin(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.User getContextAdmin(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , DuplicateExtensionException_Exception , RemoteException_Exception    { 
        LOG.info("Executing operation getContextAdmin");
        System.out.println(ctx);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new DuplicateExtensionException_Exception("DuplicateExtensionException...");
        //throw new RemoteException_Exception("RemoteException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#changeByModuleAccessName(com.openexchange.admin.soap.user.soap.ChangeByModuleAccessName  parameters )*
     */
    @Override
    public void changeByModuleAccessName(ChangeByModuleAccessName parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation changeByModuleAccessName");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#delete(com.openexchange.admin.soap.user.soap.Delete  parameters )*
     */
    @Override
    public void delete(Delete parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation delete");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#deleteMultiple(com.openexchange.admin.soap.user.soap.DeleteMultiple  parameters )*
     */
    @Override
    public void deleteMultiple(DeleteMultiple parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation deleteMultiple");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#changeByModuleAccess(com.openexchange.admin.soap.user.soap.ChangeByModuleAccess  parameters )*
     */
    @Override
    public void changeByModuleAccess(ChangeByModuleAccess parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation changeByModuleAccess");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#getMultipleData(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)java.util.List<com.openexchange.admin.soap.user.dataobjects.User>  users ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.util.List<com.openexchange.admin.soap.user.dataobjects.User> getMultipleData(com.openexchange.admin.soap.user.dataobjects.Context ctx,java.util.List<com.openexchange.admin.soap.user.dataobjects.User> users,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getMultipleData");
        System.out.println(ctx);
        System.out.println(users);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.user.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#getAccessCombinationName(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  user ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.lang.String getAccessCombinationName(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User user,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getAccessCombinationName");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#create(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  usrdata ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.User create(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User usrdata,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation create");
        System.out.println(ctx);
        System.out.println(usrdata);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#list(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)java.lang.String  searchPattern ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.util.List<com.openexchange.admin.soap.user.dataobjects.User> list(com.openexchange.admin.soap.user.dataobjects.Context ctx,java.lang.String searchPattern,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation list");
        System.out.println(ctx);
        System.out.println(searchPattern);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.user.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#listCaseInsensitive(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)java.lang.String  searchPattern ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.util.List<com.openexchange.admin.soap.user.dataobjects.User> listCaseInsensitive(com.openexchange.admin.soap.user.dataobjects.Context ctx,java.lang.String searchPattern,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation listCaseInsensitive");
        System.out.println(ctx);
        System.out.println(searchPattern);
        System.out.println(auth);
        try {
            java.util.List<com.openexchange.admin.soap.user.dataobjects.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#changeModuleAccessGlobal(com.openexchange.admin.soap.user.soap.ChangeModuleAccessGlobal  parameters )*
     */
    @Override
    public void changeModuleAccessGlobal(ChangeModuleAccessGlobal parameters) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , RemoteException_Exception    { 
        LOG.info("Executing operation changeModuleAccessGlobal");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new RemoteException_Exception("RemoteException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#exists(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  user ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public java.lang.Boolean exists(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User user,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation exists");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

    /* (non-Javadoc)
     * @see com.openexchange.admin.soap.user.soap.OXUserServicePortType#getData(com.openexchange.admin.soap.user.dataobjects.Context  ctx ,)com.openexchange.admin.soap.user.dataobjects.User  user ,)com.openexchange.admin.soap.user.dataobjects.Credentials  auth )*
     */
    @Override
    public com.openexchange.admin.soap.user.dataobjects.User getData(com.openexchange.admin.soap.user.dataobjects.Context ctx,com.openexchange.admin.soap.user.dataobjects.User user,com.openexchange.admin.soap.user.dataobjects.Credentials auth) throws StorageException_Exception , InvalidCredentialsException_Exception , InvalidDataException_Exception , NoSuchContextException_Exception , RemoteException_Exception , NoSuchUserException_Exception , DatabaseUpdateException_Exception    { 
        LOG.info("Executing operation getData");
        System.out.println(ctx);
        System.out.println(user);
        System.out.println(auth);
        try {
            com.openexchange.admin.soap.user.dataobjects.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StorageException_Exception("StorageException...");
        //throw new InvalidCredentialsException_Exception("InvalidCredentialsException...");
        //throw new InvalidDataException_Exception("InvalidDataException...");
        //throw new NoSuchContextException_Exception("NoSuchContextException...");
        //throw new RemoteException_Exception("RemoteException...");
        //throw new NoSuchUserException_Exception("NoSuchUserException...");
        //throw new DatabaseUpdateException_Exception("DatabaseUpdateException...");
    }

}
