
package com.openexchange.admin.soap.reseller.user.soap;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T09:43:16.718+02:00
 * Generated source version: 2.6.0
 * 
 */
 
public class OXResellerUserServicePortType_OXResellerUserServiceHttpEndpoint_Server{

    protected OXResellerUserServicePortType_OXResellerUserServiceHttpEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OXResellerUserServicePortTypeImpl();
        String address = "http://192.168.32.167/servlet/axis2/services/OXResellerUserService.OXResellerUserServiceHttpEndpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OXResellerUserServicePortType_OXResellerUserServiceHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
